### ISSUE TITLE
Establish and publish a code of conduct

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1]
See, for example, https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md

**Comment by xml-project** [comment]
Do we still need this, since we are now an W3C community group.
Same for #2 and #3.

Proposal: Add link to community group page in readme.org, then close #1, #2 and #3.

**Comment by ndw** [comment]
Fine by me.

**Comment by xml-project** [comment]
Fixed with pr #212
