### ISSUE TITLE
Support importing function libraries

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#10]
Implementations should allow users to import libraries of functions to be used in the pipeline. Obvious candidates for function libraries include XQuery and XSLT modules.

**Comment by xml-project** [comment]
See also https://github.com/xproc/3.0-specification/issues/42

**Comment by ndw** [comment]
Reopened at Feb, 2018 workshop because we can't find the proposal on which consensus was apparently achieved.

**Comment by xml-project** [comment]
Closes this, because it is basically the same as #42 , but there is a longer discussion.
