### ISSUE TITLE
Specify function names/signatures and default result representations for invocations from XDM-compliant environments

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#100]
Although it might not be in the core focus of the XProc spec, it will be useful to be able to specify the representation of pipeline results, particularly if the pipeline is invoked through an XQuery function. It will also be useful to specify a default function name, namespace, and signature for invocation of XProc pipelines via functions from external, XDM-3.1-compliant environments.

Possible result representations include 

- a sequence of wrapper elements like [cx:document](http://xmlcalabash.com/docs/reference/cx-eval.html), where each wrapper element contains a sequence of documents that appear on that port
- an XDM map in which each output port name is mapped to a sequence of documents that appears on that port
- some kind of implementation-defined iterator, handle, function item, … that allows to access individual output ports

Non-XML documents that appear on output ports need be represented by appropriate stub documents (`<c:document port="scaled-images"><c:file href="…"/><c:file href="…"/></c:document>` or XDM values such as `map {'scaled-images': ({'href': …}, {'href': …})}`. They may also contain serialized binary or text representations of the content as per other parts of the spec. Example: `map {'scaled-images': ({'href': …, 'base64': …}, {'href': …, 'base64': …})}`. 

The default function could probably be named xproc:execute-pipeline($pipeline, $inputs, $options, $params, $serialization-options), where xmlns:xproc="http://www.w3.org/ns/xproc", $pipeline can be either a string representing a URI, a QName representing a step name, or an XProc pipeline document, $input is either a map or a multiplexed c:document as for cx:eval, and the other function arguments are maps.
$serialization-options should be a map from output port name to another map with this port’s serialization options. The serialization options should be extended so that one can specify whether the output should be represented as a stub XML document, as a map, or as c:document documents.
 
If $pipeline is a string that represents the URI of a XProc library, it needs to specify which pipeline inside the library should be executed, maybe by giving the step declaration’s XML ID after a pound sign in the URI. 
If steps are to be executed by their type (QName), then there must be a standardized mechanism for making available XProc steps and libraries to the XQuery environment.

**Comment by gimsieke** [comment]
This probably belongs to EXPath, but I don't see what's keeping us from recommending a uniform XProc invocation interface across XDM-3.1-compliant XPathm implementations.
(Open question: Should this XPath interface for running pipelines also be made available in XProc pipelines?)

**Comment by ndw** [comment]
I'm inclined to think that returning a map is the way to go.

The non-XML documents case is trickier. A "p:file" element that either has a `content-type` attribute and has either content or an `href` attribute might be a useful way forward. The spec should allow things that are known to be text (`text/plain`, `text/csv` (or `application/csv`?), `application/json`) to be serlialized as text. I suppose inline content of other sorts should be base64 encoded with an `encoding` attribute.

**Comment by Conal-Tuohy** [comment]
Could this interface correspond to that required by the proposed dynamic evaluation XProc step?

**Comment by gimsieke** [comment]
The dynamic evaluation step, in particular its most recent manifestation (#97), is exposing input and output port declarations to the XProc processor so that there can be some static dependency graph analysis. This analysis cannot be performed when calling a pipeline from XPath within another XProc pipeline. I think if we want to have dynamic pipeline execution by calling XPath functions, we need to think about an alternative XQuery implementation of XProc 3.0 where inputs and outputs are represented as maps and the XQuery-implemented XProc processor can do dependency analysis by looking into these maps. Example: 
```
declare namespace xproc = "http://www.w3.org/ns/xproc";
let $doc := <doc>input</doc>,
    $xslt-result as map(*) := xproc:xslt(map{'source': $doc}, map {'initial-mode':'test'})
return 
  for $secondary in $xslt-result('secondary')
  return xproc:store(map{'source':$secondary}, map{'href':base-uri($secondary)})
```
I’m not sure whether there is a natural XQuery representation for everything that will be in XProc 3.0. If there is, then we can think about an equivalent XQuery syntax in separate issues. People who were involved in the non-XML XProc 2.0 effort or in XQuery-based XProc implementations might want to weigh in on this matter. Nudging @xquery…

One fundamental question is whether we want to pursue alternative XQuery representations of XProc at all. As much as I’m invested in the XML syntax of XProc, I’d like to be able to seamlessly call pipelines from within eXist, BaseX, MarkLogic, etc., too.

Writing an XProc pipeline in XQuery will probably amount to writing an (annotated) function:
```
module namespace mylib = "http://my.xproc.lib/namespace";
declare namespace xproc = "http://www.w3.org/ns/xproc";
declare 
  %xproc:step 
  function
  mylib:some-step (
    $inputs as map(*), 
    $options as map(*), 
    $params as map(*), 
    $serialization as map(*)
  ) as map(*) {
    …
};
```
where by convention—established by the `xproc:step` annotation—the first argument contains a map that associates input port names with input documents and the result contains a map that associates output port names with output documents.

**Comment by gimsieke** [comment]
The dynamic evaluation step, in particular its most recent manifestation (#97), is exposing input and output port declarations to the XProc processor so that there can be some static dependency graph analysis. This analysis cannot be performed when calling a pipeline from XPath within another XProc pipeline. I think if we want to have dynamic pipeline execution by calling XPath functions, we need to think about an alternative XQuery implementation of XProc 3.0 where inputs and outputs are represented as maps and the XQuery-implemented XProc processor can do dependency analysis by looking into these maps. Example: 
```
declare namespace xproc = "http://www.w3.org/ns/xproc";
let $doc := <doc>input</doc>,
    $xslt-result as map(*) := xproc:xslt(map{'source': $doc}, map {'initial-mode':'test'})
return 
  for $secondary in $xslt-result('secondary')
  return xproc:store(map{'source':$secondary}, map{'href':base-uri($secondary)})
```
I’m not sure whether there is a natural XQuery representation for everything that will be in XProc 3.0. If there is, then we can think about an equivalent XQuery syntax in separate issues. People who were involved in the non-XML XProc 2.0 effort or in XQuery-based XProc implementations might want to weigh in on this matter. Nudging @xquery…

One fundamental question is whether we want to pursue alternative XQuery representations of XProc at all. As much as I’m invested in the XML syntax of XProc, I’d like to be able to seamlessly call pipelines from within eXist, BaseX, MarkLogic, etc., too.

Writing an XProc pipeline in XQuery will probably amount to writing an (annotated) function:
```
module namespace mylib = "http://my.xproc.lib/namespace";
declare namespace xproc = "http://www.w3.org/ns/xproc";
declare 
  %xproc:step 
  function
  mylib:some-step (
    $inputs as map(*), 
    $options as map(*), 
    $params as map(*), 
    $serialization as map(*)
  ) as map(*) {
    …
};
```
where by convention—established by the `xproc:step` annotation—the first argument contains a map that associates input port names with input documents and the result contains a map that associates output port names with output documents.

**Comment by ndw** [comment]
Not in the core spec

**Comment by gimsieke** [comment]
Should probably be discussed in EXPath, once XProc 3.0 is a standard.
