### ISSUE TITLE
Question about loading empty text documents

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1003]
Consider:
````
<p:load content-type="text/plain" href="some-text.txt" />
````
What is a processor expected to do, if 'some-text.txt' is an empty document? Looking at the specs this might be an error because it can't be a text document: 

> Representations of text documents are XDM documents that contain a single text node.

Since XDM does not know empty text nodes, an empty text file can't be represented as text document in XProc, right?

On the other hand dealing with empty text documents is something normal for which it seems unusual to me, that it is an error case. What do you think?

If I did not completely misunderstand the case, I would suggest do define the concept of a text document via text media type and then say, that the document node may contain zero or one text node(s).

Did I miss something?

**Comment by gimsieke** [comment]
I agree with your analysis and with the proposed solution (text documents may contain zero nodes in order to represent empty text files)

**Comment by ndw** [comment]
👍

**Comment by xml-project** [comment]
Fixed with pr #1004
