### ISSUE TITLE
What is the context for evaluating the expression in the collection attribute?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1005]
Several elements have a `collection` attribute to resolve the question of what context should be used for evaluating an expression (`p:when`, `p:variable`, etc.)

The attribute is defined as an AVT, but that raises the question, what is the context for evaluating that AVT?

1. It is undefined and the default collection is empty. You have to make the choice about whether or not collections are allowed without examining the collection. 
2. It is undefined and the default collection contains the collection that the *other* expression will see if the `collection` expression evaluates to true.
3. Something else, for example, an integer atomic value containing the number of documents that would be in the collection.

I expect the 99% case is that the AVT will be "`true()`" and the answer to this question is irrelevant. But we still have to answer it. I lean towards 1 for it's simplicity, but I don't feel strongly about it.

If you're tempted to say the answer should be 2, I'd be very interested to hear a use case for when the answer depends on the collection because:

1. If the other expression doesn't refer to the context item, the `collection` answer is irrelevant
2. If the other expression *does* refer to the context, an exception will be thrown if `collection` is false.

**Comment by xatapult** [comment]
Can't we say that what collection does kicks in *after* all AVTs are evaluated. That would mean that the context for an AVT for `@collection` is the DRP, like for all other AVT situations?

**Comment by ndw** [comment]
The value of the `collection` attribute **is** an AVT. You can't get to _after_ all the AVTs until that one's been evaluated!

I guess if we do nothing at all, the status quo is that the `collection` AVT will be evaluated with the DRP. If the DRP is a sequence and the AVT refers to the context item, that'll throw an exception.

That seems a little bit odd, but I guess it's fine.

**Comment by xatapult** [comment]
> I guess if we do nothing at all, the status quo is that the collection AVT will be evaluated with the DRP. If the DRP is a sequence and the AVT refers to the context item, that'll throw an exception.

Yes, I can live with that.

But it raises the question: Why is `@collection` an AVT at all? But maybe we should not go there in this stage.

**Comment by ndw** [comment]
15 July 2021, editor's are tempted to make `@collection` an `xs:boolean` that *isn't* an AVT. Norm will ask Achim if his implementation would be impacted.

**Comment by ndw** [comment]
The `collection` attribute is no longer an AVT (the change is actually in the grammar repository).
