### ISSUE TITLE
Missleading prefix in a code box?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1011]
In section [Extension step](https://spec.xproc.org/lastcall-2020-08/head/xproc/#p.extension) the code box says `p:atomic-step'. In the para right after, it says:

> Extension steps must not be in the XProc namespace 

I think using the prefix "p" (bound to the XProc namespace) is at least missleading, if not wrong.

**Comment by ndw** [comment]
Yes. That looks like a copy-and-paste error from the preceding section or something. It should be in a different namespace.
