### ISSUE TITLE
Check text for p:for-each, p:viewport, p:choose (p:when)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#103]
The syntax box and the text of [p:for-each](http://spec.xproc.org/master/head/xproc30/#p.for-each) are not consistent with the example given: The example uses "p:iteration-source" but in the syntax box and the text a p:input is mentioned.

**Comment by gimsieke** [comment]
related to #21

**Comment by xml-project** [comment]
Thanks! I was still searching the related issue.

**Comment by xml-project** [comment]
Check prose and examples for replacement of p:iteration-source, p:viewport-source and p:xpath-context with p:input

**Comment by gimsieke** [comment]
In particular, the first sentence of [p:choose](http://spec.xproc.org/master/head/xproc30/#p.choose), "A p:choose has no inputs.", is misleading if p:choose may have a child named p:input.
