### ISSUE TITLE
Inconsistent use of “atomic step”

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#1030]
As described in https://github.com/xproc/3.0-specification/issues/1029#issuecomment-920186913, there are two different definitions of “atomic step“ in the 1.0 spec. 

The first definition is “step without subpipeline in its definition”, the second is “step without subpipeline in its invocation”.

In 3.0, we have mostly adopted the second definition.

However, there are remnants of the first, namely in:

---

### [§ 16.5. p:declare-step](https://spec.xproc.org/master/head/xproc/#p.declare-step)

> A p:declare-step provides the type and signature of a pipeline or an atomic step. Pipelines contain a subpipeline which defines what the declared step does. Atomic steps have an implementation defined elsewhere in some other way.

and

#### [§ 16.5.2. Declaring atomic steps](https://spec.xproc.org/master/head/xproc/#declare-atomic-steps)

> The distinction between an atomic step declaration and a pipeline declaration hinges on the presence or absence of a subpipeline. An atomic step declaration does not have a subpipeline. 

> Atomic step declarations may not import other pipelines or functions, may not declare static options, and may not declare additional steps. In other words, the content of an atomic step declaration consists exclusively of p:input, p:output, and p:option elements.

In addition, the two static errors [`err:XS0042`](https://spec.xproc.org/master/head/xproc/#err.inline.S0042) and [`err:XS0029`](https://spec.xproc.org/master/head/xproc/#err.inline.S0029) also use “atomic step” in its first sense.

---

This is not how we defined atomic steps in

### [§ 15.8. Atomic Steps](https://spec.xproc.org/master/head/xproc/#p.atomic)

> [Definition: An atomic step is a step that does not contain a subpipline when it is invoked.]

I propose that we use a different term than “atomic step” for the first meaning, “step without subpipeline in its declaration,” and replace it in § 16.5 and in both error messages (in case they survive #1029).

**Comment by gimsieke** [comment]
We can try to call them “atomic step declarations” throughout in 16.5 and in the surviving error(s) and add a note about the difference between an “atomic step” and an “atomic step declaration.” 

This double meaning of “atomic step”, together with the double meaning of `p:input`, were the two things that confused me most in the 1.0 spec. We disambiguated `p:input`, let’s also disambiguate “atomic step.”

Suggestion for such a note, to be placed in a rephrased § 16.5:

---

#### Note

As per its definition, an atomic step doesn’t have a subpipeline _when it is invoked_. On the other hand, an atomic step declaration (read: a step declaration that is atomic, not: a declaration of an atomic step) is a step _declaration_ that lacks a subpipeline. 

The declarations of the standard library steps, for instance, are atomic. A user-defined step’s declaration is never atomic because the declaration always has a subpipeline. Both kinds of steps are atomic _at the point of use_, but the declarations aren’t atomic in the case of user-defined steps. If there were standard steps implemented in XProc, their declarations would not be atomic, either.

---

Not sure whether we need a formal definition for “atomic step declaration“ that goes into the glossary then, and glossterms marked up in the text.

**Comment by ndw** [comment]
Consider:

```
<p:declare-step type="ex:my-step">
  <p:input port="source"/>
  <p:output port="result"/>
</p:declare-step>
```

Is that (a) a declaration for an atomic step or (b) an attempt to define a pipeline that doesn't contain at least one step and is therefore an error.

I assert that you can't tell. Only the implementation knows. It hinges on whether or not the type `ex:my-step` is something the implementation knows how to do or not.

If the processor doesn't know how to do `ex:my-step` then it's an error and I think we need a new static error code for it.

**Comment by gimsieke** [comment]
I agree.

Calabash 1.1.22 says: „err:XS0100:Declared step has no subpipeline, but is not known.“

[`err:XS0100`](https://spec.xproc.org/master/head/xproc/#err.S0100) has a different definition in 3.0. In 1.0 I was unable to spot any `err:XS0100`.
