### ISSUE TITLE
Are default input bindings resolve statically or dynamically?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1031]
Consider:
```
<p:declare-step type="ex:step">
  <p:input port="source">
    <p:document href="doc.xml"/>
  </p:input>
  ...
</p:declare-step>
```
Is `doc.xml` resolved and retrieved at "compile time", meaning the default will be the same for every use of the pipeline, or is the default the document reference itself which must be resolved at "run time" when the pipeline is being prepared for execution?

I think it should probably be resolved statically, but the spec doesn't say.

**Comment by gimsieke** [comment]
It can be checked at compile time, but I don’t think it should be read and cached then. 

With `p:http-request` (that can be used to access local file resources), we accept that resources can change during runtime.

I’m leaning a bit more towards retrieving resources at runtime.

**Comment by gimsieke** [comment]
Ok, default resources may be a special case. In the interest of interoperability, we should specify whether they should be read and cached at compile time. Contrary to what I said before, I’ll leave the decision to the current implementers. Whatever fits better into their architecture(s).

**Comment by ndw** [comment]
I'm trying not to make the decision based on my implementation. Default inputs have been (and continue to be) such an incredible PITA that I'm not sure my implementor brain could say anything that wasn't apoplectic raging.

It seems to me that the pipeline author is saying "the default is that" and it makes more sense if "that" is something the author has control over. It seems less likely to me to think "if no input is provided, then the default can be whatever is randomly in that file at runtime."

There are other ways you could write the pipeline to load a file at runtime if input wasn't provided.

But it isn't an issue I want to lie down in the road over.
