### ISSUE TITLE
Clarify 6.1, connections to the default readable port

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1033]
Recently, we amended 6.1 to admit the possibility that a clever implementation could avoid making connections where they could not be used (that is, where providing them was pointless because the expressions involved made no reference to the context item). 

Consider a step that has one input, one output (both primary) and one option, `option`:

```
<ex:step name="first" option="1"/>
<ex:step name="second" option="{1 + 1}">
  <p:with-input>
    <p:empty/>
  </p:with-input>
</ex:step>
```

Neither the input nor option of the second step can read the output of the first, so by the rules of 6.1 an implementation is free to run these in parallel.

Now consider this example:

```
<ex:step name="first" option="1" depends="second"/>
<ex:step name="second" option="{1 + 1}">
  <p:with-input>
    <p:empty/>
  </p:with-input>
</ex:step>
```

Now a clever implementation that has determined that the second step doesn't depend on the first will be fine. But if an implementation doesn't implement that checking, it will appear that these steps form a loop and the pipeline will be rejected.

I think we have to tighten up the wording in 6.1 to say that implementations are not just allowed to forgo connections where they cannot be read, but that they must. There's no requirement that the steps be run in parallel or anything like that, just that statically, there are no connections between steps where no connection could have any bearing on the outcome.

I don't think it's much of a hardship for implementors. It's already necessary to analyze the expressions used to initialize options in a step to determine what variables they reference and whether or not they refer to the context item.

**Comment by gimsieke** [comment]
Ok
