### ISSUE TITLE
Is the value of p:inline-expand-text an AVT?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1035]
When parsing the XML descendants of `p:inline` where `expand-text` is true, is the value of the `p:inline-expand-text` attribute an AVT?

```
<p:inline expand-text="true">
  <doc>
    <p p:inline-expand-text="{3+4 gt 5}">{Don't expand me!}</p>
  </doc>
</p:inline>
```

**Comment by gimsieke** [comment]
It need not be an AVT, I’d say. If it facilitates implementation.

**Comment by ndw** [comment]
Apparently I failed to mention this issue explicitly in the PR so it didn't get closed.
