### ISSUE TITLE
Does expand-text apply when the content-type of p:inline is not XML?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1036]
We say that the value of `expand-text` is ignored when an encoding is present. I think that means it isn't ignored (i.e., `expand-text` applies) regardless of the content-type when the content *isn't* encoded.

I wonder if we should say that more explicitly.

**Comment by gimsieke** [comment]
It can be a bit challenging to author a `text/json` inline document with `expand-text=true`, but I think it is sensible to clarify that `expand-text` applies regardless of the `content-type` when `encoding` isn’t specified.
