### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1039]
Apparently, the links to the schemas are 404 from the 2020-08 last call draft.

**Comment by xatapult** [comment]
@ndw Not sure what you're referring to. I checked the links in the latest version of the spec, https://spec.xproc.org/master/head/xproc/#ancillary-files

These are all ok as far as I can see. I suppose you refer to an older version but do we need to fix this?

Can we close this issue?

**Comment by ndw** [comment]
Yep, that must have been a transient issue. Maybe the grammars repo had to be rebuilt or something. :-/
