### ISSUE TITLE
Think about more implicit connections

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#104]
This is a reminder of a [discussion](https://github.com/xproc/Workshop-2017-02/wiki/Minutes-for-day-two:-8-February-2017#important-workflows-for-publishing-use-cases) we had at XProc Workshop Prague 2017:
@rdeltour proposed to have more implicit connections between steps, for example if the previous step has n output ports and the current step has n input ports: They are connected in order.

But this would lead to abandon the concept of the "default readable port" in favour of something like a default readable set of ports. Difficult to explain and possibly much more confusing in use?

But there was also the idea of having different default readable ports for different content types, so when a step has an output port with an xml-document and one with a jpeg and the next step has two input port with matching content-types, they are auto connected.

Related to #93

**Comment by ndw** [comment]
What does "connected in order" mean? Declaration order? That's awfully far removed from the point of use.

Maybe it makes sense to match them up by producing/consuming content type, but it seems like that could get awfully messy.

1/2 :-1:

**Comment by ndw** [comment]
The group declines to add this feature.
