### ISSUE TITLE
What happens if `select` on `p:with-input` isn't a string?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1040]
Martin Honnen [asks](https://xmlcom.slack.com/archives/C011NLXE4DU/p1636454612094200) on Slack:

> Trying to play a bit more with XProc 3 I wrote a pipeline with an empty sequence for the source port but then a p:identity step that tries to output a variable e.g.
```
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="3.0">
    <p:input port="source" sequence="true">
        <p:empty/>
    </p:input>
    <p:output port="result" sequence="true" serialization="map{ 'method' : 'json', 'indent' : false() }"/>
    <p:variable name="array-of-strings" as="array(xs:string)" select="['foo', 'bar']" xmlns:xs="http://www.w3.org/2001/XMLSchema"/>
    <p:identity>
        <p:with-input port="source" select="$array-of-strings"/>
    </p:identity>
</p:declare-step>
```
> Morgana XProcIII (latest beta) doesn't output anything as the result, XML Calabash 3 (latest preview) does output some kind of odd serialization of that JSON array. 

What do we think the right answer is? I started out thinking that an empty sequence was the right answer, but I've talked myself around to thinking that if `select` selects a variable, the actual document isn't relevant and what you get back is the selected variable.

But does that make sense?

**Comment by xml-project** [comment]
To correct Martin's observation: MorganaXProc returns an empty sequence as a result of this pipeline. ("doesn't output anything" is not a correct result of any XProc pipeline).
To my understanding the select-expression on p:identity is never used in this case, because the specs [says](https://spec.xproc.org/master/head/xproc/#p.with-input):

> A select expression may also be provided with a connection. The select expression, if specified, applies the specified XPath select expression to the document(s) that are read.

So my reading: No document, no application of the select-expression. The empty document just passes true.

But I agree that it might be confusing, that for any other input than the empty sequence the result is `['foo', 'bar']`.

It seems like a strange use case, but we could say, that the select-expression is evaluated with the document(s) on port `source` as context item, or with no context item in the case of the empty sequence. This is, I asume, what XMLCalabash does and what Martin expects.

**Comment by ndw** [comment]
I assume that in the case of a sequence of documents, the `select` expression is applied to each document in turn with that document as the context item. That is, the case of "the context item would have to be more than one document" never applies.

I think we could justify either of these positions:

1. The select expression is evaluated with no context item if the sequence is empty, or
2. The select expression is ignored if the sequence is empty.

I'm not sure which makes more sense.

**Comment by martin-honnen** [comment]
I agree with your comments that is simply a question of deciding whether the `select` is evaluated without a context item for an empty sequence of whether it is ignored.

I threw some similar example at Morgana, using a JSON document with `null`:
```
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="3.0">
    <p:input port="source" sequence="true">
        <p:document content-type="application/json" href="null.json"/>
    </p:input>
    <p:output port="result" sequence="true" serialization="map{ 'method' : 'json', 'indent' : false() }"/>
    <p:variable name="array-of-strings" as="array(xs:string)" select="['foo', 'bar']" xmlns:xs="http://www.w3.org/2001/XMLSchema"/>
    <p:identity>
        <p:with-input port="source" select="$array-of-strings"/>
    </p:identity>
</p:declare-step>
```

Output I get is not empty but `["foo","bar"]`.

The reference JSON file has just `null`.

**Comment by xml-project** [comment]
I would like to add two observations:

1. In the current version of the test suite are 7 tests (both written by @ndw and me), suggesting that option (1) is right.
2. In my implementation you get the results expected by @martin-honnen , if the empty sequence does not arrive from another step, but the `p:with-input select="…"` is directly bound to p:empty.

**Comment by ndw** [comment]
Okay. I think based on that evidence and on the comments from @martin-honnen that option 1 is what we should do.
