### ISSUE TITLE
Cut-and-paste error?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1044]
The last sentence in 16.10 before the note about text value templates reads:

> The interpretation of the (possibly decoded) content depends on the document’s content type.

I think that should say "the inline's content type" instead. Or something like that. I assume (but haven't checked) that this text was copied from `p:document` or something.

**Comment by gimsieke** [comment]
I don’t think this is an error. Throughout the inline section, we speak of “the document” (that is provided inline). The document provided inline does have document properties, including a content type.

**Comment by ndw** [comment]
👍 

I was looking at that line in isolation.
