### ISSUE TITLE
Default inputs for atomic steps and `err:XS0042`

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1045]
I believe that we decided to allow default inputs for atomic steps to support `p:archive`:

```xml
<p:declare-step type="p:archive">
     <p:input port="source" primary="true" content-types="any" sequence="true"/>
     <p:input port="manifest" content-types="xml" sequence="true">
          <p:empty/>
     </p:input>
     <p:input port="archive" content-types="any" sequence="true">
          <p:empty/>
     </p:input>
     <p:output port="result" primary="true" content-types="any" sequence="false"/>
     <p:output port="report" content-types="application/xml" sequence="false"/>
     <p:option name="format" as="xs:QName" select="'zip'"/>        
     <p:option name="relative-to" as="xs:anyURI?"/>                
     <p:option name="parameters" as="map(xs:QName, item()*)?"/>    
</p:declare-step>
```

So it seems **wildly** inconsistent that we explicitly exclude this case in the language specification:

> On a p:declare-step for an atomic step, the p:input can only declare the input port. It is a static error (err:XS0042) to attempt to provide a connection for an input port on the declaration of an atomic step. 

Did we just change our minds about default inputs on atomic steps and forget to remove `err:XS0042`? Or is there something more subtle going on here?

**Comment by xml-project** [comment]
> Am 26.11.2021 um 13:03 schrieb Norman Walsh ***@***.***>:
> 
> So it seems wildly inconsistent that we explicitly exclude this case in the language specification:
> 
> On a p:declare-step for an atomic step, the p:input can only declare the input port. It is a static error (err:XS0042) to attempt to provide a connection for an input port on the declaration of an atomic step.
> 
> Did we just change our minds about default inputs on atomic steps and forget to remove err:XS0042? Or is there something more subtle going on here?
> 
> 
How is this different from issue #1029, which, to my reading, is still unsolved?

------------------------------------------------
Achim Berndzen
***@***.***

<xml-project /> Achim Berndzen
Kleine Breite 26a
38302 Wolfenbüttel, Germany

https://www.xml-project.com

**Comment by ndw** [comment]
Nevermind. This is #1029
