### ISSUE TITLE
Order in p:library

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1050]
In p:declare-step the spec defines as order:
(1) Imports
(2) Prolog (=inputs, outputs, options)
(3) step declarations.

In p:library step declarations and static options can be mixed at will.
May be there should be a defined order (option, step declarations) in p:library too, so confusions could be avoided.

**Comment by ndw** [comment]
This seems reasonable to me.

**Comment by gimsieke** [comment]
No objections
