### ISSUE TITLE
Deadlock conditions in `use-when` aren't discussed

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1051]
Consider:

```xml
<p:declare-step type="cx:lib2d1" use-when="not(p:step-available('cx:lib2d2'))">
  <p:output port="result"/>
  <p:identity>
    <p:with-input><doc>lib1s1</doc></p:with-input>
  </p:identity>
</p:declare-step>

<p:declare-step type="cx:lib2d2" use-when="not(p:step-available('cx:lib2d1'))">
  <p:output port="result"/>
  <p:identity>
    <p:with-input><doc>lib1s1</doc></p:with-input>
  </p:identity>
</p:declare-step>
```

It's relatively difficult to create such a deadlock. You have to put the `use-when` expression on a `p:declare-step` and it has to include a call to `p:step-available`. There are a number of options for resolving them, but I think the simplest thing to do for 3.0 is make this a static error.

**Comment by gimsieke** [comment]
agree

**Comment by ndw** [comment]
It may be worth noting that deadlock conditions can also arise on `p:import` which is sort of like `p:declare-step` in that regard. Consider:

Consider:

```xml
<p:import href="library.xpl" use-when="p:step-available('cx:foo')"/>
```

If `cx:foo` is already available, this is fine. But if `cx:foo` is not currently available,  it cannot be determined that `cx:foo` is unavailable because it would be available if it was defined in `library.xpl`, but `library.xpl` cannot be loaded unless it can be determined that `cx:foo` is available.
