### ISSUE TITLE
Clarify XD0019

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1052]
At present `err:XD0019` and `err:XD0036` aren't clearly distinguished. Both refer to the type of a value being incorrect.

I believe the intent was that `err:XD0036` is for type errors ("Spoon!" is not an `xs:integer`) and `err:XD0019` is for errors where the option gives a list of values and the value specified is not in the list. For example, a `position` option of "Spoon!" on `p:insert`.

We have tests that support this position and it seems like a useful distinction.

**Comment by gimsieke** [comment]
ok
