### ISSUE TITLE
The spec is contradictory about the content of p:option

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1056]
In 7.1, we have an example of a static option that contains a `p:document`. But in 16.4.2, we define the content model of `p:option` as empty. 

My guess is that we intended to allow `p:document` and `p:inline` (and implicit inlines) in *static* `p:option` elements.

But we haven't written it that way yet.

**Comment by xatapult** [comment]
I agree. We should fix this inconsistency in the standard.

**Comment by ndw** [comment]
On reflection: the example is wrong. `p:option` doesn't have content. And if we allowed it for static options but not dynamic options then `select` would have totally different semantics. If we think we got this wrong, we should fix it in v.next.
