### ISSUE TITLE
Don't allow p:step-available() to test the step currently being declared

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1057]
Allowing `p:step-available` to test the step currently being defined leads to paradoxical results. Consider:

```
<p:declare-step type="test:test" use-when="not(p:step-available('test:test'))"> ... </p:declare-step>
```

If `p:step-available()` returns true, then `test:test` won't be defined, so it should have returned false. But if it returns false, then `test:test` will be defined, so it should have returned true.

Or consider:

```
<p:declare-step type="test:test">
  <p:output port="result"/>
  <p:input use-when="p:step-available('test:test')" />
</p:declare-step>
```

where the step is-or-isn't an undefined atomic step depending on what `p:step-available()` returns.

I propose:

> [It is a static-error (S0116) if the argument to `p:step-available()` refers to a step that is currently being defined.] In practice this only occurs if `p:step-available()` is used in a `use-when` expression on or within the `p:declare-step` that defines the step to which it refers.

Suggestions for better wording most welcome. 

Hat tip to @xml-project for finding and documenting the paradoxical behavior.

**Comment by gimsieke** [comment]
Isn’t `use-when="not(p:step-available('test:test'))"` also problematic on a `p:library` that contains the declaration for `test:test`?

**Comment by xml-project** [comment]
@gimsieke Yes, this is problematic too. But an import of
```
<p:library use-when="false()">...</p:library>
```
already results in XS0052 because a p:import does not point to a p:library. At least I would argue that there is a similarity between pointing to an empty doc in `p:import` or to the discussed case.

Do you think we need a special error code saying that `p:library use-when="false()"` is nonsense?

**Comment by gimsieke** [comment]
CG thinks that `false` is the right answer

**Comment by xatapult** [comment]
Tried to address the outcome of the discussions in #1068
