### ISSUE TITLE
namespace rules on [p:]use-when not clear from the spec

### ISSUE THREAD

**Issue by Gertone** [xproc/3.0-specification#1058]
unless I am missing the obvious, it seems that the namespace rules for use-when are not explained in the spec

on a custom step I use p:use-when (having the attribute in the xproc namespace)
`<cma:process-doc p:use-when="$process-content">...`

in an equivalent example I use use-when (having the attribute in the null namespace)
```
<p:if test="true()" use-when="$process-content">
   <cma:process-doc/>
</p:if>
```
I am not arguing this is not the right approach, 
But it seems the spec does not explain clearly why this attribute needs to be in the null namespace in one case and in the xproc namespace in another case

**Comment by ndw** [comment]
Well, [Section 14.9 Common Attributes](https://spec.xproc.org/master/head/xproc/#common-attr) attempts to describe this behavior. And [the description](https://spec.xproc.org/master/head/xproc/#use-when) of `[p:]use-when` is consistent with it, I believe.

Is that unclear, or is it poorly placed in the specification?

**Comment by Gertone** [comment]
Thanks for the reference.
Seems consistent and clear enough.
Was working my way up starting from a text search for "use-when"
My apologies for overlooking it

**Comment by ndw** [comment]
No worries. Keep on reporting the things that trip you up!
