### ISSUE TITLE
p:with-input with empty binding, but select attribute

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#1059]
In a discussion yesterday with @Gertone the following question came up: What is the result of
````
<p:with-input select="(1, 2, 3)">
  <p:empty />
</p:with-input>
````
Given the current specs, my answer would be: An empty sequence of document. Prove: In [p:with-input](https://spec.xproc.org/master/head/xproc/#p.with-input) the "select" attribute is explained as:

> The expression will be evaluated once for each document that appears on the port, using that document as the context item. The result of evaluating the expression (on each document that appears, in the order they arrive) will be the sequence of items that the step receives on the port.

Now in the example, no document appears on the port and therefor the "select" expression is never applied.
Is this right?

What makes me doubt is:
````
<p:with-input select="(1,2,3)"><doc></p:with-input>
````
Here the select expression is executed (because there is a document), so the result is three JSON documents. 
But obviously the document does not contribute to the result, it does just trigger the mechanism in XProc. Wouldn't one expect, that the first examples produces the same result?
What did I miss?

**Comment by xml-project** [comment]
Thanks for reminding me, Norm!

> I agree that there are odd consequences for static expression that don't involve the context. But using one of those to filter the context is, in itself, a little odd.

Ok, I have to confess, that I am a little odd, because I use this sometimes.

**Comment by Gertone** [comment]
My apologies for adding to a closed comment.
But just to be clear....
I have a number of cases where I bind the input port of a p:for-each to an empty sequence because I want to p:for-each a sequence of strings from a variable
If I understand the above well (which is in line with the spec)
Achim's example
```
<p:with-input select="(1, 2, 3)">
  <p:empty />
</p:with-input>
```
should not evaluate the three integers but just do nothing
```
<p:with-input select="(1, 2, 3)">
  <doc/>
</p:with-input>
```
however would evaluate the three integers?

**Comment by ndw** [comment]
Yes, @Gertone I believe that is the case.

**Comment by Gertone** [comment]
thanks for confirming @ndw.
