### ISSUE TITLE
Think about renaming input connections to "p:with-input"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#106]
From a conversation with @gimsieke (hope to remember right) a while ago:
In XProc 1.0 "p:input" is used for port declaration as well as to provide an input connection to a declared port. 
This could be a potential source of confusion to XProc learners.

For options we have the distinction between "p:option" (declaration) and "p:with-option" (providing a value). By reserving "p:input" for declaration and "p:with-input" for providing a connection, XProc 3.0 might be more consistent and (hopefully) easier to learn.

**Proposal:**

1. Change "p:input" to "p:with-input" in http://spec.xproc.org/master/head/xproc30/#input-connections.

1. Apply the new term accordingly in the rest of the specs.

**Comment by xml-project** [comment]
@ndw @gimsieke  Any comments on this?

**Comment by gimsieke** [comment]
Let’s discuss it in [Aachen](https://github.com/xproc/Workshop-2017-09/wiki/Agenda-and-Minutes) and maybe have a straw poll then. I personally can live with both. I do, however, think that naming these two usages of `p:input` differently can indeed help novices realize faster that there’s a difference.

**Comment by ndw** [comment]
I'm willing to give it a try. It's even more verbose, but we could certainly publish a few pipelines with this format and see what the users think in Aachen.

**Comment by xml-project** [comment]
I will prepare some of the examples in the specs with "p:with-input" and put them on a new wiki page for [Aachen](https://github.com/xproc/Workshop-2017-09/wiki/Agenda-and-Minutes).

**Comment by xml-project** [comment]
Added a page to the Aachen wiki with comments. I will add another example or two in the next days.

**Comment by eriksiegel** [comment]
IMHO using <with-input> simply makes the whole language a lot clearer and less ambiguous, especially for novices. And whatever lowers the entrance barrier to XProc is to beseriousy considered. I'm in favor because ot this.

**Comment by xml-project** [comment]
Solved with pull request #144
