### ISSUE TITLE
Scoping of step names

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1104]
The spec says:

> The scope of the names of the steps (the values of the step’s name attributes) is determined by the [environment](https://spec.xproc.org/3.0/xproc/#dt-environment) of each step. In general, the name of a step, the names of its sibling steps, the names of any steps that it contains directly, the names of its ancestors, and the names of the siblings of its ancestors are all in a common scope. All steps in the same scope must have unique names: it is a [static error](https://spec.xproc.org/3.0/xproc/#dt-static-error) ([err:XS0002](https://spec.xproc.org/3.0/xproc/#err.S0002)) if two steps with the same name appear in the same scope.

But I don't think the *environment* section actually says anything useful about step names.

I **think** this is editorial, but I'm not sure exactly how to remedy it. We could try to add step names to the environment, or we could change this paragraph in the spec to read:

> The scope of the names of the steps (the values of the step’s name attributes) is the step on which the name appears, the names of its sibling steps, the names of any steps that it contains directly, the names of its ancestors, and the names of the siblings of its ancestors. All steps in the same scope must have unique names: it is a [static error](https://spec.xproc.org/3.0/xproc/#dt-static-error) ([err:XS0002](https://spec.xproc.org/3.0/xproc/#err.S0002)) if two steps with the same name appear in the same scope.

**Comment by xml-project** [comment]
I think the proposed wording is much better than the previous one.
