### ISSUE TITLE
Document the difference between step-evaluated and pipeline-evaluated expressions

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#111]
I haven’t found a piece of non-normative prose in the 1.0 spec or in the current draft where the distinction between step-evaluated and pipeline-evaluated expressions is explained, and that variable bindings/options of the surrounding pipeline are not available when, for example, `p:string-replace` evaluates its `@match` or `@replace` attributes. Maybe we should link to such a note from every attribute that is _XSLTMatchPattern_ or _XPathExpression_.
I’d think that all `@select`, the `p:viewport/@match`, the `p:when/@test` and the `p:namespaces/@element` attributes (these are all occurrences of _XSLTMatchPattern_ or _XPathExpression_ in the 3.0 language spec) are supposed to be processor-evaluated while all patterns/expressions in the 3.0 step library (and any other step) are step-evaluated. A note should clarify that any bindings and XProc-specific functions are only available in processor-evaluated expressions / matching patterns.
By the way, Calabash doesn’t know bindings in `p:viewport/@match` and maybe other attributes of which I thought they should fall into the “processor-evaluated” category.

**Comment by gimsieke** [comment]
related to #101 and #66

**Comment by ndw** [comment]
The answers to these questions are in 2.7.2, but that section is fairly techncial. Add a note to the spec (somewhere, TBD) that describes this in less technical terms for the benefit of pipeline authors. Point out, for example, that the XPath extension functions (p:iteration-size, etc.) are not available inside steps (in an XSLT stylesheet, for example).

**Comment by ndw** [comment]
I propose that the current §7.2.2 XPath in XProc is sufficient.

Objections?

**Comment by xml-project** [comment]
No objections. For a technical document it pretty clear. As a pipeline author I am sure I will continue to make the mistake every once in a while.
