### ISSUE TITLE
Clarify p:import-functions

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1110]
When are functions loaded? Are they accessible in `[p:]use-when` expressions during static analysis?

**Comment by gimsieke** [comment]
I think it can possibly be useful if imported functions are available in `use-when` expressions (that lexically follow the `p:import-functions`, maybe). If implementers think that static analysis will become easier without access to imported functions in `use-when`, then it is acceptable though to declare imported functions out of context during static analysis.

**Comment by ndw** [comment]
Achim and I have both implemented it so that they're available in `use-when` expressions, so I think we can document it that way. But it should be documented! :-)
