### ISSUE TITLE
What are match attributes?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#1118]
Some steps have attributes with the special type `XSLTSelectionPattern`. These are typically named `match`.

Are they expressions, like `select` attributes on `p:with-input`? Are they AVTs like most step options? Are they both?

We have a test, `nw-viewport-003` which can only succeed if they are expressions. Unfortunately, it has the awful description "Test that the match attribute can be an AVT with a variable reference." I think that's incoherent and I can say that because I wrote it. 😄 

 The same test can be written with a simple, atomic step, so let's consider that case so we don't have to question whether the rules are special on compound steps:

```xml
         <p:variable name="gi"
                     select="xs:QName('ex:p')"/>

         <p:add-attribute match="*[node-name(.) = $gi]"
                          attribute-value="true"
                          attribute-name="found"/>
```

In order to pass this test, you have to analyze the value of the `match` attribute as an XPath expression, observe that it relies on the value of `$gi`, and make sure the runtime value of `$gi` is delivered to the step. Observe that although the variable is statically known here, it could be a user supplied option.

You could also write this: `match="*[node-name(.) = {$gi}]"`. It's not (if we allow XSLTSelectionPattern attributes to be AVTs) syntactically invalid, but it won't work. AVT rules on attributes collapse that to a string: `"*[node-name(.) = ex:p]"` which I guess looks for an element named `ex:p` to match against the node name and almost certainly goes horribly sideways.

If we allow XSLTSelectionPatterns to be both expressions and AVTs, I think we end up in a place where the processor cannot determine statically which in-scope variables are needed. Consider: `match="*[node-name(.) = ${$optname}]"`. At runtime, if the user passes in `abc` as the value of `$optname`, when the AVT is resolved, this becomes `match="*[node-name(.) = $abc]"`. That's a valid expression, but it's impossible for the processor to have worked out that `$abc` was going to be required. 

I think the right answer is: options of type XSLTSelectionPattern are expressions, **not** AVTs.

We should clarify that in the spec and, at some point, we should consider if/how a user-defined pipeline step could assert that an option was an XSLTSelectionPattern. I don't think there's any useful purpose in asserting that about a user defined step, it's only relevant for steps that are going to be implemented as atomic steps, so I don't think it's a crisis that in the current state of affairs that might require implementation-level API magic.

**Comment by xml-project** [comment]
May be it is just a side note, but I am a little confused by your "p:add-attribute" example. The spec says:

> The XProc processor evaluates all of the XPath expressions in select attributes on variables, options, and inputs, in match attributes on [p:viewport](https://spec.xproc.org/lastcall-2024-08/head/xproc/#p.viewport), and in test attributes on [p:when](https://spec.xproc.org/lastcall-2024-08/head/xproc/#p.when) and [p:if](https://spec.xproc.org/lastcall-2024-08/head/xproc/#p.if) steps.

From this I would says, that `$gi` is not visible in the match expression because it is evaluated in step context with no global variables visible. The match in `p:viewport` is the only XSLTSelectionPattern were variable/options are visible.
Did I miss something?

**Comment by ndw** [comment]
Oh. Interesting. We made `match` on `p:viewport` explicitly magic. That seems really unsatisfying.

**Comment by xml-project** [comment]
I think it ever was. The basic idea was, that a atomic step(s) logic could be performed by some external service, implementors have no control over.
If the service does XSLTMatchpattern right, it can be used. But there has to be no way to set variable values to be used in evaluating the XSLTMatchPattern.
Am I confused?

**Comment by ndw** [comment]
No. It was probably something like that. Anyway, it would clearly be wildly incompatible to change the semantics of `XSLTSelectionPattern` options on atomic steps now. Bah, say it with me, humbug.
