### ISSUE TITLE
What is an XSLTMatchPattern in 3.0?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#112]
If we try to align the spec with [XSLT 3.0](https://www.w3.org/TR/xslt-30/#patterns), should match patterns also be allowed to match any item? Does this have far-reaching consequences, or is this irrelevant because there are only documents arriving at input ports anyway, and an XSLT 3.0 pattern that matches, for example, a string or an xs:base64binary value may not occur in practice? 
Should we restrict XSLTMatchPatterns to node-matching patterns, as per the [XSLT 2.0 spec](https://www.w3.org/TR/xslt20/#patterns)?

**Comment by gimsieke** [comment]
related to #35

**Comment by Conal-Tuohy** [comment]
I think there is a lot of value in being able to pass non-documents through the pipeline. For instance, if we could pass an XDM map from the output port of one step to the input port of the next, then we could process JSON just as easily as XML documents.

**Comment by ndw** [comment]
My understanding is that we're planning to allow any XDM value to pass through the pipeline. Not sure how that plays out against select expressions and such.

**Comment by gimsieke** [comment]
Romain proposed this a while ago, too. But IIRC we decided to keep the distinction between ports (documents) and options (any XDM item) though. Since the XSLTMatchPattern attributes in question only relate to ports, matching nodes is the only meaningful way to go here. 
Regarding JSON: The current proposal is to represent non-XML documents as empty document nodes (and maybe text documents as a document node with a text node in it). A map cannot be a node; therefore you’d have to convert the JSON string to an XML representation before accessing it by XPath.

**Comment by gimsieke** [comment]
(off-topic wrt this issues original topic)

At [yesterday’s workshop](https://github.com/xproc/Workshop-2017-06/wiki/Minutes), the sentiment among us was to allow only documents between ports and to represent non-XML documents with a `/c:document-properties` proxy document. If you pass a JSON document to a step that consumes JSON documents, you don’t have to convert it. If you need to access its contents in XPath expressions or if a step only understands an XML representation of it, you’d convert it by means of two XProc functions that act as an interface between the proxy document and the corresponding XPath 3.1 conversion functions:
```xml
<p:load href="some.json"/>
  <!-- ⇒ <c:document-properties base-uri="…" content-type="application/json"/> -->
<p:group>
  <!-- A newly introduced function p:parse-json() processes proxy documents 
with an application/json content type. It retrieves the file’s content (using the 
processor’s resource manager) and calls fn:parse-json() to convert it to a map 
or to an array. -->
  <p:variable name="json-as-map-or-array" select="p:parse-json(/)" as="item()*"/>
  <!-- Same thing for calling fn:json-to-xml() on the proxy document: -->
  <p:variable name="json-as-xml" select="p:json-to-xml(/)" as="document-node()?"/>
  …
</p:group>
```
Note that the proxy document, in its attributes, only mirrors the map that you can retrieve with `p:document-properties()`. It remains to be determined whether a processor can be bothered (by the spec) to make this proxy document read-only and also to dynamically manipulate the attributes synchronously with the document properties. Ideally these attributes and the map that `p:document-properties()` returns are just two views on the same metadata.

**Comment by gimsieke** [comment]
(Technically one can argue that any XML document is read-only since it is immutable, and that each `p:add-attribute`, `p:insert` etc. will create a new document. The processor needs to have some notion of document identity though that goes beyond node identity and maybe also beyond base-uri identity, and the processor should probably prevent any step from manipulating the proxy documents, except steps for setting document properties.)

**Comment by ndw** [comment]
Patterns are described in Section 5.5 of the XSLT 3.0 spec.
