### ISSUE TITLE
Attribute "depends"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#116]
The explanation of "depends" in 2.5.1 Additional dependent connections needs, at least from my point of view, two clarifications:
a) We have to mention, that the attribute needs to be in XProc's namespace, so it does not mingle with other attributes defined by a user declared step.
b) The specs say that the value of the attribute has to be a list of step names. I propose to clarify this by saying, it is a list of step names separated by blanks.

**Comment by ndw** [comment]
I'm happy with the clarification that the names are space separated, but I think the proposal is for an attribute called "depends" in no namespace. Yes, that steps on any option value named "depends" but I think that's ok. We step on "name" as well.

**Comment by xml-project** [comment]
I agree with you to do have "depends" in no namespace like "name". My idea was to align "depends" with section "3.8 Extension attributes", because "depends" was an extension attribute with XMLCalabash and MorganaXProc. 
May be we should add a short appendix, listing attributes names not allowed in no namespace in "Extension Steps" and user defined steps.

**Comment by ndw** [comment]
I think it's simpler than that. In XProc 3.0 cx:depends is an extension attribute just like it is in 1.0; it has whatever semantics the implementor says it has, including none. I think my inclination as an implementor will be to make it behave like 'depends' but warn that it's deprecated. And eventually raise an error for it.

**Comment by xml-project** [comment]
I will make the PR concerning space separation of names this weekend (have to rebuild my fork of the repo first) and then close this issue.

**Comment by xml-project** [comment]
Fixed with with pr #123 per 17-08-13.
