### ISSUE TITLE
Error code for defect p:try

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#125]
We currently have no error code for a p:try without a p:catch (or without a p:group).
Processors behave differently: XMLCalabash XS0027, MorganaXProc XS0044.
Both do not really fit. 

Proposal:
(a) Introduce a new static error XS1012, stating that a p:group and a p:catch is required for a p:try.
(b) Introduce a generic static error message XS1011 stating that it is a static error, if a non-step multi-container step has not the child steps required. This error could be used for p:try and also for an empty p:choose

**Comment by ndw** [comment]
I have a mild preference for (b).

I'm surprised we don't already have a general, "you got the syntax wrong" error, but we don't seem to.

**Comment by xml-project** [comment]
Yes, that was my preference too. But after thinking a while about it:
- some of our error are very specific, so reading the error code usually tells what is wrong as an experienced XProc developer. Having a generic error might seem like a break in the system approach.
- errors are cheap, so having an extra error code does not bother us but has a potential benefit for users.

So: My preference is somewhat for (a), but I could life with (b) too.

**Comment by ndw** [comment]
Ok. Go for (a). Like you say, the codes are cheap.

**Comment by xml-project** [comment]
Addressed with PR #126
