### ISSUE TITLE
What about @p:expand-text

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#129]
Suppose you want to disable expand-text inside an inline? Should we allow @p:expand-text on non-XProc elements? Should it be removed from the generated inline?

**Comment by xml-project** [comment]
I would say: yes and yes!
Having this attribute is not a big burden on the implementation side, but makes node construction a lot easier (even if it is a very special case).
In a typical use case the @p:expand-text is not wanted on the produced node, so it should be removed for the generated node. If we copy it to the inline, a p:delete would be required to remove the attribute. So it is easier for users not to copy the attribute.

Can anyone think of a use case, where you want @p:expand-text to be copied? If there is a use case, obviously the answer to the second question must be "no".

**Comment by gimsieke** [comment]
I see potential issues in two cases: 

1. When someone binds [another namespace URI to the `p` prefix](https://github.com/jpcs/transform.xq/blob/master/lib/patterns.xq#L9) and happens to use an attribute `p:expand-text` in that namespace in their documents. 
1. When someone wants to supply an XProc pipeline, by means of `p:inline`, to, for example, `p:run`, and this pipeline contains another `p:inline` where `@p:expand-text` should be passed verbatim.

The first case can be checked for by looking at the actual namespace URI that is associated with the `p` prefix in the inline document. For text expansion, the processor should only consider (and later remove) `@p:expand-text` if `p` is bound to `http://www.w3.org/ns/xproc`. 

For the (improbable?) second case, we can require the processor to pass `@p:expand-text` verbatim when it has an ancestor `p:inline` (with `p` bound to `http://www.w3.org/ns/xproc`) within the inline document.

**Comment by ndw** [comment]
1. Indeed, the prefix is irrelevant, p:expand-text is just a shorthand for the expand-text attribute in the p: namespace.

2. I suggest we ignore this case in the short term. In the *very* rare case that someone wants to do this, they can always use an add-attribute step and a little complexity to put it back.
