### ISSUE TITLE
Standardize cx:depends attribute

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#13]

**Comment by xml-project** [comment]
Sure to close this?

**Comment by ndw** [comment]
I don't see it in the 1.1 spec yet. Am I missing something?

**Comment by xml-project** [comment]
No, its not in the specs but I think it should be in. So to standardize is an issue, which should be open and not closed. Where is my mistake?

**Comment by ndw** [comment]
Sorry. I must have closed it by mistake and then when I read your comment, I thought *you* had closed it. Yes. It should be open. We're good. Sorry about that.

**Comment by xml-project** [comment]
See section "2.5.1 Additional dependent connections" in Editor's Draft 21 March 2017 (build 10).
Done!
