### ISSUE TITLE
Remove XS0024

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#130]
I propose we remove XS0024. In the XPath data model, the constraint that a document have a single XML root is not enforced, so we shouldn't enforce it in p:inline.

Perhaps we should on p:store, however...

**Comment by gimsieke** [comment]
What will p:count return for an inlined source with two top-level elements?

**Comment by xml-project** [comment]
@gimsieke I think p:inline with two top-level elements should be treated as one document with to element children as in XQuery "document{<a />,<b/>}". So p:count is 1.
To make this clear, we should say, whatever appeared in a p:inline is wrapped in/by a document-node.

In general I think we need to say, that it is an error if p:store with @method='xml' (etc.) is called and the document on port "source" is not an XML-document. For p:http-request we already have err:XC0022 saying, that a proper XML document is needed if an xml content-type is selected.

**Comment by xml-project** [comment]
fixed with pr #346
