### ISSUE TITLE
Do we want to bring p:data back?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#132]
For discussion, see: http://markmail.org/message/suqboygye2h62mhh?q=xproc-dev

**Comment by ndw** [comment]
"No."

If the system determines that the content type should be XML, it is an error if it's not well-formed XML. The p:document element should have an override-content-type attribute for specifying the content type explicitly.

**Comment by ndw** [comment]
It is implementation-defined what level of validation is performed on documents loaded. XML documents must be well-formed.  Implementations may also perform syntactic checks on non-XML documents, for example, that JSON or CSV documents are syntactically correct.

**Comment by ndw** [comment]
This issue doesn't propose any changes to the spec and it's been marked as consensus for several weeks. I'm closing it.
