### ISSUE TITLE
User-defined functions per p:variable?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#135]
Aren’t function items permitted as variable values? Consider this example:
```xml
  <p:variable name="count" as="xs:integer" select="4"/>
  <p:variable name="foo" 
              select="function($i as xs:integer) as xs:string+ {
                        for $j in (1 to $i) return 'a'
                      }" 
              as="function(xs:integer) as xs:string+"/>
  <p:message message="{$foo($count)}"/><!-- ('a', 'a', 'a', 'a') -->
```
I don’t know how hard this is to implement. In principle, implementations might just translate `$foo($count)` to an XPath 3.1 expression by looking up the declarations, put them after a `let` statement and have the expression evaluated:
```xquery
  let $count := 4,
      $foo := function($i as xs:integer) as xs:string+ {
                for $j in (1 to $i) return 'a'
              } 
  return $foo($count)
```
If they use an XQuery processor to evaluate expressions, they can also add the type constraints:
```xquery
  let $count as xs:integer := 4,
      $foo as function(xs:integer) as xs:string+ := function($i as xs:integer) as xs:string+ {
                for $j in (1 to $i) return 'a'
              } 
  return $foo($count)
```

**Comment by gimsieke** [comment]
Maybe this is [supposed to work out of the box](http://spec.xproc.org/master/head/xproc30/#xpath-context)?

**Comment by xml-project** [comment]
Yes, it would. But please mind that higher order functions are an optional feature for an XPath/XQuery processor. Saxon HE 9.8.x does not support it (Saxon PE is required), BaseX 8.6.6 does.
I have not yet decided whether the upcoming 3.1 version of MorganaXQuery will, but I guess it will not.
------------------------------------------------
Achim Berndzen
achim.berndzen@xml-project.com

<xml-project /> Achim Berndzen
Kleine Breite 26a
38302 Wolfenbüttel, Germany

http://www.xml-project.com

**Comment by ndw** [comment]
I don't know how hard that's going to be to implement. Well, As Achim says, it's going to be impossible with Saxon HE, but even with Saxon PE or  EE, it requires getting the declared function into the dynamic context somehow. I haven't investigated how difficult that is. And it's not near the top of my list :-)

**Comment by xml-project** [comment]
But we should provide a way to import functions (either xquery or xslt) into XProc's context. I think both XMLCalabash and MorganaXProc have a way to do this.
My proposal is to find a common standard for import for both processors at the lowest possible level of dependency to Saxon.
