### ISSUE TITLE
Remove p:pipeline (Was: Change implicit primary port behavior for p:pipeline)

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#136]
Gioele Barabucci suggested that in order to make it easier for newbies who start with `p:pipeline` and then add ports, they sometimes want to rename the primary input or output ports. Instead of forcing them to switch to `p:declare-step`, maybe we can change p:pipeline that you can declare other ports primary (with other names that 'source' and 'result', but maybe even providing a different declaration for a primary input port called 'source', maybe with a default connection). Declaring primary ports explicitly in `p:pipeline` should override the implicit default ports.

**Comment by gimsieke** [comment]
Consensus to drop `p:pipeline` altogether (and rename `p:declare-step` `pipeline`?)

**Comment by ndw** [comment]
Consensus: get rid of the defaulting version, have only one way to do it. No consensus on what to call it.

Possibilities: declare-pipeline, declare-step, pipeline, step ...

**Comment by gimsieke** [comment]
I created a [doodle poll](http://doodle.com/poll/zicuz2tps5ax246f). We must not miss out on this bikeshedding opportunity!

**Comment by gimsieke** [comment]
An overwhelming majority for keeping `p:declare-step`: 
![poll](https://user-images.githubusercontent.com/122601/30556907-c20f60fa-9cac-11e7-8832-3a24cdd9edc5.png)
