### ISSUE TITLE
Clarify @select at input declarations (sec 5.1.1)

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#137]
@select is metioned but not explained

**Comment by gimsieke** [comment]
There is this paragraph in Sect 5.1.1: 
> If a connection is provided in the declaration, then `select` may be used to select a portion of the input identified by the `p:empty`, `p:document`, or `p:inline` elements in the `p:input`. This select expression applies only if the default connection is used. If an explicit connection is provided by the caller, then the default select expression is ignored.

I propose to insert: "… may be used to select, **in the sense and with the restriction of the input connection `select` that is described in Sect. 5.1.2**, a portion …" (or to make this parenthesis a second sentence in the original paragraph).

**Comment by xml-project** [comment]
May be we should also remove p:empty from the quotes paragraph, because only speaking in a very strict sense, you can select portions from a p:empty.

**Comment by xml-project** [comment]
@ndw close #137?

**Comment by ndw** [comment]
Fixed by #158, I must have lost the magic incantation that closes the issue automatically.
