### ISSUE TITLE
Add 'static' to variable declarations

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#138]
Only at the top level, presumably.

**Comment by ndw** [comment]
Should use-when also have access to pipeline-declared options; they must be static, right?

**Comment by ndw** [comment]
On balance, I think we shouldn't do this (at least in 3.0).

On first glance, it seems like a good idea:

    <p:declare-step ...
      <p:option name="output-directory" static="true" ...

Now `$output-directory` is known to be known statically. It could, in principle, be referenced in `use-when` expressions, for example.

But what happens if this step is called dynamically from another pipeline? Is the caller forbidden from providing a value for the `output-directory` option? If so, it's not static. If not, then how is it initialized? It's effectlvely "hidden" inside the outer-most pipeline or library that contains it.

Ugh. It's complex and appears to add very little value.

"No."

**Comment by xml-project** [comment]
I with you Norm, but I would not  close it now, because I see the value.
Proposal: Let the issue open, I will look into the XSLT 3.0 specs to see whether we can take their concept. 
If someone comes up with a clever way to do it, we will implement. Otherwise: Lets defer it to a later XProc version

**Comment by eriksiegel** [comment]
Since this is now implemented (#452), can be closed.
