### ISSUE TITLE
Standardize cx:message step

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#14]

**Comment by xml-project** [comment]
See also: https://github.com/xproc/3.0-specification/issues/41

**Comment by xml-project** [comment]
See for proposed resolution: http://markmail.org/search/?q=xproc%20kraetke#query:xproc%20kraetke%20from%3A%22Kraetke%2C%20Martin%2C%20le-tex%22+page:1+mid:4r3afri7lusg64uk+state:results

**Comment by xml-project** [comment]
See https://github.com/xproc/steps/issues/2

**Comment by ndw** [comment]
Overtaken by #29
