### ISSUE TITLE
Serialisation parameters as map?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#147]
We have serialisation parameters in p:store, p:http-request etc. 
Would it not be a good idea change the step signature of these steps, so that we have an option "serialisation" which expects a map?
One important reason is have one variable with the map and not having to write them down over and over. The second reason is that we could use fn:json-doc() to load serialisation parameters from a resource.

**Comment by ndw** [comment]
I like it. In my experience, setting the output method is the most common thing, often with no other serialization parameters. I wonder if it makes sense to keep 'method'. Or maybe say that the name of the option is method and it contains either a string or a map:

```
  <p:store method="html">...
```
or
```
  <p:store method="map { 'method': 'xml', 'indent': true() }">...
```

I dunno. Maybe that's too complicated. But

```
  <p:store serialization="map { 'method': 'xml' }">...
```
is a bit tedious too.

**Comment by gimsieke** [comment]
I’m favoring a `@serialization` attribute that holds a map. 

We can use the same attribute on `<p:output>` and discard `<p:serialization>`. 

By allowing variables or options in the map construction expressions and in the `@serialization` attribute (via AVTs), we can save a lot of typing, and we become quite flexible because we can pass serialization settings as options to steps (either whole maps or just some values). 

It don’t think it will bother you too much if you occasionally have to construct a map for serialization instead of using the conventional serialization attributes.

Example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" 
  xmlns:my="http://acme.com/step-library"
  type="my:html-renderer" version="3.0">
  <p:documentation>A step that outputs a complete HTML document 
  on the primary output port and snippets on the port called 
  'sections'. A calling pipeline can specify 'html' or 'xhtml'
  for the method and also an HTML version.</p:documentation>
  <p:option name="method" as="xs:string" select="'html'"/>
  <p:option name="html-version" as="xs:string" select="'5.0'"/>
  <p:option name="default-serialization" as="map(xs:string,xs:anyAtomicType)" 
    select="map {'method': $html, 'version': $html-version"></p:option>
  <p:output port="result" serialization="{$default-serialization}" primary="true">
    <p:documentation>The idea is to drop 'p:serialization' in favor of this
    'serialization' option on 'p:output'. Attribute value templates should be 
    possible in this attribute.</p:documentation>
  </p:output>
  <p:output port="sections" serialization="{$default-serialization}" 
    as="document-node(element(*))+"/>
  …  
</p:declare-step>
```

**Comment by gimsieke** [comment]
(The example is a bit contrived – passing serialization options dynamically to a step, to be used on its output ports, is pointless. But you can think of a variable that holds a serialization map that is used repeatedly on individual `<p:store>` steps in the pipeline. Using a variable to hold the map will save you some typing.)

**Comment by ndw** [comment]
The fact that they can go on p:output pushes it over the top for me. Yes.

Now, what do you think of my idea that the attribute is called method and can either be the name of an output method (xml, html, etc.) or a map of serialization parameters?

**Comment by gimsieke** [comment]
Too much magic!

No, seriously I’d say that if the esteemed implementors feel comfortable with this polymorphism, then I’m not against it.
