### ISSUE TITLE
"@select" on p:output for compound steps?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#151]
We do have @select for p:input and p:with-input, but we do not have it for p:output, e.g.

<p:output port="result">
   <p:pipe step="some-step" port="some-port" />
</p:output>

The fact that I just discovered this is a hint that I did not miss it before or it is often used. But I do not see, why we do not have it. For symmetry reasons with p:input I would argue that we should have it: Easier to learn, easier to teach and perhaps even sometimes useful.

**Comment by ndw** [comment]
Primarily because you don't need it. You can always run the documents through a filtering step (p:identity with a select, for example).

It's definitely extra complexity and I'm not convinced it's worth the effort.

**Comment by xml-project** [comment]
As you said: You actually do not need it (very often). Having it would be for symmetry reasons only, so that the default binding on p:input and p:output are handled the same way.
I think it is easier for teaching/learning, to have a @select and I think the complexity on implementation side is manageable.
So: I would like to have it, but it is ok, if we decide to renounce it.

**Comment by ndw** [comment]
You want to weigh in Gerrit? Or if anyone else is following along at home, feel free to chime in.

**Comment by gimsieke** [comment]
I’m a bit out of the loop due to holidays and book fair preparations. All I can offer is a superficial “I have never missed `@select` on `p:output`.”

**Comment by xml-project** [comment]
I have never missed it too. Just by reading specs I missed @select on p:output and then found out, that @select was not allowed in XProc 1.0 either.
**Proposal**: Wait a week for some to want this feature. If no one asks for it, lets close this issue.

**Comment by xml-project** [comment]
The week is over, so close?

**Comment by ndw** [comment]
/me closes the door quietly and locks it from the inside.
