### ISSUE TITLE
Remove proxy documents section

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#154]
Following the decisions we made in Aachen, the proxy document section needs to be updated/remove.

**Comment by gimsieke** [comment]
Do we state instead that XPath expressions see non-XML documents as empty document nodes (with properties)? Previously it was completely implementation-dependent IIRC, which we thought, at the London workshop, to be unwieldy for pipeline authors and bad for interoperability.

**Comment by ndw** [comment]
Done
