### ISSUE TITLE
Rationalize error codes

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#162]
In order to make editing more practical, we've been inventing error codes haphazardly. I propose to clean that up by renumbering all of the ones currently larger than the largest 1.0 error so that they're sequential again.

I then propose to create a wiki page listing the error codes. Everytime an editor needs to invent a new error code, he or she should add it to the wiki page, thereby getting a sequential list.

**Comment by xml-project** [comment]
Good proposal. As I obviously implement other aspects than you do, I have the same problem.

**Comment by ndw** [comment]
See https://github.com/xproc/3.0-specification/wiki/Error-Codes

I'm going to wait until #165 is merged to avoid any merge conflicts.
