### ISSUE TITLE
Rethink implicit inlines

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#167]
I think the concept of implicit inline documents is to narrow at the moment. According to our current concept, 
<p:with-input port="port">&lt;element /></p:with-input> 
is allowed, but having two top level elements as children of p:with-input, p:input or p:output is not allowed. 
As we say "An explicit p:inline is required if the author wants to include top level comments, processing instructions, or whitespace, or if the document element is in the XProc namespace." I do not see that this restriction is necessary.
We could imho therefor say in 5.9.3:
"As an authoring convenience, **any element node**, optionally preceded and/or followed by whitespace, in any namespace other than the XProc namespace, occurs where a p:inline is allowed, it is treated as if it was enclosed within a p:inline element (with no attributes)."

**Comment by ndw** [comment]
The problem is here:

```
<p:with-input port="source">
  <?pi?>
  <doc/>
  <!-- this is a test -->
  <doc/>
  <?pi target?>
  <doc/>
  <!-- another comment-->
</p:with-input>
```

Which documents do the PIs and comments go in?

We could have a rule, but it would have to be a complicated rule: with the preceding/following document unless there isn't one in which case with the following/preceding document. Or, I suppose, we could say that you need a p:inline in this case.

I don't feel strongly about it. I expect that the 80% case is just elements.

But that's why the rule is the way it is today.

**Comment by xml-project** [comment]
Yes, I see your point. But the specs (http://spec.xproc.org/master/head/xproc30/#implicit-inlines) do not allow PI, comments and text but ask for ** a single element node**. 
And I think <doc /><doc /> is not ambiguous.
So: Either we allow trailing and following comments, text and PIs, then we need to have one document. Or we ask for an element node, then we could allow more than more.

**Comment by ndw** [comment]
The schema fragments aren't capable of constraining comments and PIs. I believe the intent is that this:

    <p:inline>
      
      <?pi?>
      <doc/>
    </p:inline>

is a document consisting of whitespace, a comment, whitespace, a PI, whitespace an element, and whitespace.

**Comment by xml-project** [comment]
Sorry to reopen, but there is still a problem with p:with-input because inline elements in (http://spec.xproc.org/master/head/xproc30/#p.with-input) are a non repeatable and exclusive. To my reading it has to be:

```
 (p:empty | 
    ((p:pipe | 
        p:document | 
        p:inline | 
        anyElement)+)?
```

**Comment by ndw** [comment]
Damn it. I swear I fixed that. And I checked my local bulid. I must have borked something. Will fix later today or this weekend.

**Comment by xml-project** [comment]
Yes, I am pretty sure I saw it in some version, but it is not in the current build.
