### ISSUE TITLE
Clarify content of p:inline

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#168]
As per syntax box (http://spec.xproc.org/master/head/xproc30/#p.inline) the content of a p:inline needs to be _anyElement_. I think it has to be _anyNode_, to allow:
&lt;p:inline content-type="text/plain">Some text</p:inline> and also (as we construct Documents per XDM) &lt;p:inline><?PI target?></p:inline>.

**Comment by ndw** [comment]
The p:inline wrapper is now optional. Do we have consensus that it's only optional for XML documents. That is, you can say:

    <p:with-input><doc/></p:with-input>

but you can't say

    <p:with-input>this is text/plain</p:with-input>

If you want to insert text/plain, you need to provide the content type. And that's done in the p:inline document properties:

    <p:with-input><p:inline document-properties="map{'content-type':'text/plain'}">this is text/plain</p:inline></p:with-input>
