### ISSUE TITLE
Static checking of serialization parameters

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#170]
Current version of specs (http://spec.xproc.org/master/head/xproc30/#serialization) says:
"It is a static error (err:XS1201) if the map contains any property name not recognized as a serialization parameter."

I would like to argue to change this to a _dynamic error_, so we could use variables and construct the map at runtime.

**Comment by ndw** [comment]
Yes, absolutely.

**Comment by xml-project** [comment]
Addressed with pr #171

**Comment by xml-project** [comment]
Fixed with pr #173
