### ISSUE TITLE
Clarification on p:document necessary

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#175]
In the XProc 3.0 we explain p:document via reference to p:load. But as I recall, dynamic evaluation like
&lt;p:with-input>
   &lt;p:document href="{$a}" document-properties="map{'content-type',$c}" />
&lt;p:with-input>
is not possible, because p:document is not a step and @href and @document-properties are no options of that (non-) step.

If this is right, it might be useful to add a line to the prose of p:document saying that the values of 'href', 'document-properties' and 'override-content-type' are evaluated statically and that p:load should be used for dynamic value evaluation.

**Comment by ndw** [comment]
I think we **want** to allow dynamic evaluation as you've shown. The only reason you need `p:load` in XProc 3.0, I think, is if you need DTD validation. We could almost remove `p:load`, but I don't think we should.

**Comment by xml-project** [comment]
No objection! The specs say: "In an attribute that is designated as an attribute value template ...", but we have not marked them yet. For some, like @name and @depends it is clear, that we need static evaluation. 
We should discuss, how far we want to go here and I do not have a clear option on this yet. Making (almost all) dynamic will clearly enhance expressibility, but it (since we loose static checking) it will lead to more pipelines failing.
