### ISSUE TITLE
Double use of xs0004

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#177]
Currently we use XS0004 for:

- It is a static error to declare two or more options on the same step with the same name.
- It is a static error to include more than one p:with-option with the same option name as part of the same step invocation.

I propose to split the two up, so it is easier for pipeline authors to find the error. For the second type I propose a new error XS0080.

**Comment by xml-project** [comment]
Addressed with pr #178

**Comment by ndw** [comment]
Ok. I've tended, I think, to try to group similar errors under a single code. But I'm ok with more codes I guess. There's probably room to split several.

**Comment by xml-project** [comment]
Fixed with pr #178
