### ISSUE TITLE
Better/more valuable debugging output

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#18]
Extend the error vocabulary?

**Comment by josteinaj** [comment]
For debugging, I often find it difficult, based on the logs, to figure out:

- which step is referred to (it might indicate p:xslt, but which one?)
- why was that step invoked (was it through the first or second p:when? etc.)

Maybe it would make sense to have some sort of "XProc stacktrace". Something like this:

```
Error XD0001 : It is a dynamic error if a non-XML resource is produced on a step output or arrives on a step input.
    at p:xslt (src/steps/convert.xpl:11 - /*[1]/*[5]/*[2])
    at p:group (src/steps/convert.xpl:8 - /*[1]/*[5])
    at p:declare-step (src/steps/convert.xpl:2 - /*[1])
    at my:step (src/pipeline.xpl:50 - /*[1]/*[8]/*[1]/*[3])
    at p:when (src/pipeline.xpl:30 - /*[1]/*[8]/*[1])
    at p:choose (src/pipeline.xpl:25 - /*[1]/*[8])
    at p:declare-step (src/pipeline.xpl:2 - /*[1])
```

And while debugging it might be useful to have a way of triggering a stacktrace. Maybe through a function like this:

```xml
<p:xslt cx:message="{p:stacktrace()}">...</p:xslt>
```

**Comment by ndw** [comment]
That is a good idea. I'll see if I can add that kind of stack trace to errors reported by XML Calabash.

**Comment by xml-project** [comment]
for cx:message see also: https://github.com/xproc/3.0-specification/issues/29

**Comment by ndw** [comment]
No further spec action required (consensus, 10 Jan 2019)

**Comment by bertfrees** [comment]
Back in 2017 I have implemented a stack trace in our Pipeline version or calabash1, similar to how Jostein described it, and I've also extended the error vocabulary.
