### ISSUE TITLE
Explain use of "exclude-inline-prefixes"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#180]
The attribute "exclude-inline-prefixes" is defined on p:declare-step, p:with-input and p:inline.

I think we have to explain, how the hierarchy has to be understood: Is it 
a) "cascading" or "additive" like in css
b) "default", so that the nearest ancestor of the inlined documents (and only this) determines which namespaces must be excludes.

**Comment by ndw** [comment]
I think "nearest ancestor" is the right semantic.

**Comment by xml-project** [comment]
Yes, I think so, but its not defined in the current version and it wasn't for XProc 1.0 either.

Reaming problem: Does a <p:declare-step /> inside a <p:declare-step /> inherit the values or does it open up a new scope. I think you could argue for both.

**Comment by ndw** [comment]
In fact, I was mistaken. The spec clearly says they're cumulative: see 5.9.2.

I could go either way no declare step.

**Comment by xml-project** [comment]
Do we really still need this cascading mechanism? 
I could image an @exclude-inline-prefix directly stated on the relevant element taking a string variable or an array of strings.

**Comment by ndw** [comment]
I would (strongly) prefer not to make the exclude-inline-prefixes attribute an AVT. This is something that's done statically and I think it should remain that way. If there's a use case for doing this dynamically, I think we should add a p:remove-namespaces step.

I think the question this issue asks is answered unambiguously in 5.9.2. I propose that we close it.

Achim, if you're strongly opposed to static inheritance, please make a counter proposal.

**Comment by xml-project** [comment]
It is ok for me to keep it like it is. 
I rarely use the inheritance because I have to look into to many places to see what will actually happen at a special p:inline. But if others like this feature, its ok with me.

My idea to make "exclude-inline-prefixes" an AVT came from the fact that thanks to TVT in XProc 3.0 now the actual document in most cases has to be created dynamically anyway.

**Comment by ndw** [comment]
You're right about dynamic creation, but the point of `exclude-inline-prefixes` was to prevent other, static prefixes in your pipeline from leaking into your inline. If you put the document in a file and use `p:document` to load it, you have complete control. If you use `p:inline`, all of the namespaces in-scope on the `p:with-input` that contains it are also in-scope for your inline. You can keep them out with `exclude-inline-prefixes`.
