### ISSUE TITLE
@select and document-properties

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#193]
The example @ndw provided in his [mail](http://markmail.org/search/?q=list%3Axproc-dev#query:list%3Axproc-dev+page:2+mid:exbrvizz3bbplrjb+state:results) to me raises another point with @select on p:with-input etc.:
Suppose I have a step which accepts say "text/plain" and I have an XML document containing a text node as child of a "section" element. Can I use
`<p:with-input select="//section/text">`
with the XML document as default readable port or context node (if you prefer)?

The problem is at which point we will say, that the document to arrive on the text step does not match the expected content type "text/plain". If we do it before the evaluation @select an error has to be raised because there its "application/xml". If we consider the result of @select (as we do to assess whether its a sequence or not), no error should be raised.

I think you can make up the same kind of example for any XDM defined type as value of @select.

I hope, I made my point clear. If not, please tell me so and I try to provide an elaborated example.

**Comment by ndw** [comment]
I think, practically, the input to the step has to be considered the result of evaulating the `@select` expression. We may need to say what conversions are allowed/required/standardized.

**Comment by xml-project** [comment]
Can we close this or do we have to add some prose to the specs explicitly saying, that checking for the right content type has to be done after the "select" phrase is applied to the incoming document?

**Comment by ndw** [comment]
I've been leaving it open because it feels like the spec needs to be clear. I'll take a look at fixing it.
