### ISSUE TITLE
Allow parameters on p:document / p:load

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#196]
Given that we've extended p:document and p:load to support non-XML data, I think we should allow `parameters` on each. The allowed parameters are implementation-defined and vary according to the content type being loaded. For example, XPath 3.1 defines several parameters to control various aspects of loading JSON content.

If we make this change, I think that 'dtd-validate' should be a boolean property, not an explicit option on p:load.

**Comment by xml-project** [comment]
Yes, we should have a map option on p:document and p:load. For some content-type we should define standard behaviour (e.g. the JSON-load/parse behaviour should be identical the XPath 3.1), for text/* we might come up with some parameters and probably for RDFs.

dtd-validate -> boolean property in a map: Yes!

**Comment by ndw** [comment]
I agree about standardizing parameters for some media types.
