### ISSUE TITLE
Callout HTML as a special case

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#201]
We describe four general classes of media type: XML, text, JSON, and "other binary". We should probably call out HTML as well! :-)

**Comment by gimsieke** [comment]
These four types are currently only described in [`p:load`](http://spec.xproc.org/master/head/steps30/#c.load), while there are just three types (XML, text, other non-XML) in the [core spec](http://spec.xproc.org/master/head/xproc30/#document-types). Maybe we should mention in the core spec that while they fall into the “text” category, extra parsing and serialization rules exist for the content types `text/json` and `text/html`.

Do we define HTML documents as the non-XML serialization form and identified by its media type `text/html`?

What should `p:load` and `p:http-request` do if the resources are delivered (according to an HTTP header)  as `text/html`, but have an XML declaration and can be parsed as XML? Load the doc as HTML or as XML?

For file: URIs that do not come with HTTP headers: Should there be some rules that include file name analysis (`.xhtml` → `application/xhtml+xml`, `.html` → `text/html`) and/or content sniffing and/or a fallback cascade (first try to parse as XML → `application/xhtml+xml`, then as HTML → `text/html`, then as text → `text/plain`, then as binary → `application/octet-stream`)?

Do we say that the parsing rules for the HTML version that the DOCTYPE declaration purports should apply, and [HTML5 parsing rules](https://www.w3.org/TR/html5/syntax.html#syntax) if there is no DOCTYPE?

Should HTML5 parsing rules be applied as meticulously as [inserting `tbody` elements](https://www.w3.org/TR/html5/syntax.html#element-restrictions) where they are missing in the source HTML?

What should be the effect of loading/parsing a `text/html` resource? Should it be presented as an XDM document, with named character entities resolved, or should this only happen by means of an explicit `p:cast-content-type`? 

Do we need an option for [`p:cast-content-type`](http://spec.xproc.org/master/head/steps30/#c.cast-content-type) that specifies whether we want a `c:data` result or an XDM representation? Maybe an entry of a cast-pair-specific map that is passed to `p:cast-content-type` as a `parameters` option?

Should HTML, SVG, and MathML namespaces be added if they are not present in the source HTML?

Should every XProc processor implementation support HTML parsing, or is this ability _implentation-defined_?

**Comment by xml-project** [comment]
Could you two please give a hint, why we should handle html as a special case. 
In XProc 1.0 we handled html as xhtml via tidy or tagsoup. Where a the pros of handling it as a separate case? Will there be steps specialised on content-type "text/html"?

**Comment by gimsieke** [comment]
I understood Norm’s proposal as an analogy to the special case of [loading `text/json`](http://spec.xproc.org/master/head/steps30/#c.load.json), where an implementation must be able to apply `fn:parse-json()` to the string value of a text document.
Similarly, we might stipulate that an implementation must be able to parse HTML (that comes in with an HTML serialization) into an XDM document. Technically, implementations will perform this using tagsoup, validator.nu or similar, but this wasn’t standardized. You could not _expect_ an implementation to be able to handle HTML-serialized input.
And we can stipulate that an implementation must be able to serialize a document as HTML5, with appropriate doctype, charset meta, empty element handling, character entities, etc.

**Comment by ndw** [comment]
Yes, just what @gimsieke said. Should we say that processors are required to be able to load XML, HTML, and JSON documents? That's perhaps more than we say now, actually, wrt to JSON, but is there any reason not to require it for interoperability.

**Comment by xml-project** [comment]
Yes, I agree with both of you: The processor should be able to deal with XML, HTML, JSON, and text.
Currently binary data is optional, we may think about a required rudimentary processing for binary data as well, so that a processor is required at least to be able to load and save uninterpreted binary data, put it into a zip file etc.

By the way: In [loading text data](http://spec.xproc.org/master/head/steps30/#c.load.text) we talk about a "text document". I think we should either say, that the representation of text is implementation defined, or do we mean an XDM-document that has one text-node as its child? The last decision would make text documents available for XPath's string functions.

**Comment by ndw** [comment]
Overtaken by #400.
