### ISSUE TITLE
Describe context node for p:inline

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#204]
Now that `p:inline` can contain AVTs and TVTs, we have to decide what the context node is for evaluating those expressions. There seem to be two options:

1. The context node is undefined.
2. The context node is the default readable port at the point where `p:inline` occurs.

Option 1 is simpler, but option 2 is probably more useful. Note, however, that there's no place to put a p:pipe to change the context node, it can *only* be the default readable port.

**Comment by xml-project** [comment]
I tend to opt for (1), because finding a notation and understanding (2) tends to be very difficult and might lead to unexpected results when writing pipelines.
Since we now allow nodes to be inserted into the document via variables, we have the mechanism (2) would be useful for.

**Comment by gimsieke** [comment]
I was tempted to come out in favor of (2) but Achim’s remarks, particularly the one about variables, make me lean towards (1).

**Comment by ndw** [comment]
Section 5.9.2 already says that. Thank you. :-)
