### ISSUE TITLE
XPath errors in TVT and AVT

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#208]
I propose a special dynamic error to be raised if the XPath expression in a TVT or AVT can not be evaluated (because of a syntax error, a reference to the context node -which is empty-, a reference to an undeclared variable/option etc. 

Otherwise we have to use XD0030: "It is a dynamic error if a step is unable or incapable of performing its function." which is far to generic to be informative for pipeline authors.

**Comment by ndw** [comment]
Sure. I've been adding errors as I encounter implementation scenarios where I need them. This seems like a good place.

**Comment by xml-project** [comment]
Yes, this is exactly the situation I was in need for the error. I will reserve XD0050 for this and write the prose in the specs later.
