### ISSUE TITLE
Can p:for-each/p:iteration-source and p:viewport/p:viewport-source be simplified?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#21]
Remove redundancy

**Comment by ndw** [comment]
The current draft has replaced each of p:iteration-source and p:viewport-source with an anonymous p:input. (Though some of the prose and examples still need to be updated.)

Is this sufficient?

**Comment by xml-project** [comment]
Aside from the prose, I think you did a very good job here. Think we can close this.

**Comment by ndw** [comment]
Agreed to close as completed, 4 May 2017

**Comment by xml-project** [comment]
Just removed "proposed resolution" label from a closed issue. Right?

**Comment by gimsieke** [comment]
sure
