### ISSUE TITLE
Scope of variables

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#219]
Just to be sure:
As I understand our new approach with p:variable anywhere, this does not change the concept of variables in comparison to XProc 1.0, does it? It is just a convenience that I do not have to open a p:group to declare a variable. 
The variable is visible to all step from &lt;p:variable/> to the end of compound step it contains **in lexical order**.

The question comes from the new paragraph at the end of http://spec.xproc.org/master/head/xproc30/#p.variable. This paragraph could be read as given up the concept of lexical scope in the sense of Java etc. at all and saying: The variable is visible to all steps that can connect to it without a loop, which may include steps appearing before p:variable in lexical order.

**Comment by ndw** [comment]
I think it's more than a convenience that the `p:group` is no longer required, but yes, the variable is only visible to those steps which follow it in document order. It's possible, with an explicit `p:pipe` to make *it* depend on something that follows it, and consequently, it's possible to introduce loops with variables, but scoping remains lexical.

I hope that's a, uh, clarification. :-)

**Comment by xml-project** [comment]
Thank you, indeed for me it was a clarification. So I think we can close this until some else comes up and says that the cited paragraph might be misleading.
