### ISSUE TITLE
allow p:compare to support multiple comparison methods

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#221]
We’ve been discussing this at the [London workshop](https://github.com/xproc/Workshop-2017-06/wiki/Minutes): `p:compare` should accept a map option (maybe called 'parameters', maybe as a map from xs:string to xs:string) that specifies the comparison method and further implementation-defined parameters to the selected method. In the absence of such a map, or if the map contains the key 'method' with an associated value of 'deep-equal', it should work in the same way as the XProc 1.0 step `c:compare`. It should then raise a dynamic error if one of the documents to be compared is not an XML document.

**Comment by gimsieke** [comment]
Or a parameters option just like every other parameters option in the library: `<p:option name="parameters" as="map(xs:QName,item())"/>` 
This way, we can pass entire XML structures or maps as configuration options, even in the namespace of the selected implementation. 
Example: `map {'method':'deltaxml', 'deltaxml:conf': map {'opt1': 'val1', 'opt2', 'val2'}}`

**Comment by ndw** [comment]
Yes, I think it should take a normal parameters option.

However, I'd be inclined to make the selection of the comparison method a separate option. Something like:

````
<p:declare-step type="p:compare">
   <p:input port="source" primary="true" content-types="*/*"/>
   <p:input port="alternate" content-types="*/*"/>
   <p:output port="result" content-types="application/xml"/>
   <p:option name="method" as="xs:QName"/>
   <p:option name="fail-if-not-equal" select="false" as="xs:boolean"/>
   <p:option name="parameters" as="map(xs:QName,item())"/>
</p:declare-step>
````

Where we say that an unspecified `$method` or a `$method` of `deep-equal` does the same comparison as today.

I wonder if moving `fail-if-not-equal` into`$parameters` makes sense though...

**Comment by gimsieke** [comment]
I’d stipulate that the criterion for what is an option or a `parameters` entry is its independence of an actual method. I’d also stipulate that `fail-if-not-equal` needs to be supported by each and every method. Therefore `fail-if-not-equal` should be an option proper.

Two more things: 

According to the 1.0 spec, if `fail-if-not-equal` is `false`, a `c:result` document whose content is either 'true' or 'false' will be produced. Users might be interested in actual diffs in an XML, a text, or another non-XML representation. 
Therefore I propose that we introduce an additional port `<p:output port="diff" content-types="*/*" as="document-node()*"/>` (or `<p:output port="diff" content-types="*/*" sequence="true"/>`). The documents that appear on this port will be _implementation-defined_ (and method/parameters-dependent), for example a single text file with a line line-based diff representation that contains `<<<<<<<`, `=======`, and `>>>>>>>` markers.

Maybe we should also support three-way diff by providing an additional input port called `common-base`. If present and if the method supports three-way diff, again an _implementation-defined_ (and method/parameters-dependent) set of diff documents will appear on the `diff` port, for example, a text file with a line line-based diff representation that contains `<<<<<<<`, `=======`, `>>>>>>>`, and `|||||||` markers.

**Comment by ndw** [comment]
Ok, I'm persuaded on `method` and `fail-if-not-equal`. And I'm happy to add a `diff` port, though I think I'll propose the name `differences`.

However, I think three-way diff is a different beast. It's easy to ignore an output port, but it's much harder to ignore an input port. By default, it's going to get connected to the default-readable-port.

I encourage you to propose a three-way diff step :-)
