### ISSUE TITLE
Invalid XInclude refs

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#238]
In using this repo to try to auto-generate step descriptions for the XProc 3 book, I stumbled upon errors in some XInclude refs in the step descriptions in src/main/xml/steps/

- In exec.xml: exec-as1.txt is referenced but the file is called exec-as1.xml. Same for *-as2
- In xquery.xml: examples/xquery.xml is referenced but this file is called xquery.txt

**Comment by ndw** [comment]
There's are build steps (xproc30_examples and steps30_examples) in build.gradle that transform the .xml files into .txt files. If you build the spec, you should then have all the ancillary files. (Ideally the .txt files would be in build/ but I haven't worked that out yet.

**Comment by eriksiegel** [comment]
Got the build system working, solved
