### ISSUE TITLE
@href and @pipe on p:with-input and p:output

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#246]
I think we need some further clarification on the use of  these attribute:

1. What does &lt;p:with-input pipe="step@port" href="some-uri" /> mean?
Given the current specification it is a short cut for a p:with-input with a pipe-element **and** a document element. But is it &lt;p:pipe /> followed by &lt;p:document /> or the other way around?
I am not sure whether it makes sense to allow both short cuts on p:with-input/p:output because we will have to impose an order which will be hard to remember. First idea was, that order of the attributes matters, but [XML specs](https://www.w3.org/TR/REC-xml/#sec-starttags) says, attribute order does not matter. Next idea would be alphabetical order, so href always comes before pipe if both appear (on a port marked as sequence).

2. What does &lt;p:with-input pipe="step@port">&lt;p:empty/>&lt;/p:with-input /> mean?
In the current version of the specs no p:document, p:inline or p:pipe is allowed, but p:empty is not explicitly excluded. May be I miss a point, but I think we should exclude p:empty too.

3. Why is p:inline explicitly excludes, but implicit inlines are allowed? I think they should be forbidden too. 

Proposal:
- On p:with-input and p:output either a "@pipe" or a "@href" can occur, but not both. (Solves the problem in which order the documents will appear on the port = problem 1)
- If a "@pipe" or a "@href" occurs on p:with-input or p:output, then the only elements allowed as children of p:with-input or p:output are p:documentation and p:pipeinfo. (solves problem 2 and 3).

**Comment by gimsieke** [comment]
I concur with your proposal to make `@pipe` and `@href` mutually exclusive (to raise XS0082 or a new error code if both occur simultaneously), and also with your second proposal.

**Comment by xml-project** [comment]
As the problem also occurs with p:option, p:variable and p:with-option I think the proposed solutions would also work there.

**Comment by xml-project** [comment]
Fixed with PR #253 and PR #257
