### ISSUE TITLE
Variables/options in the document-properties map with p:inline

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#255]
Do we anywhere say something about the use of variables in constructing the map for document-properties? 
I think we should, because at least the label "content-type" and its value must be determined during static analysis to know whether the content should be treated as XML-document, text, JSON etc.

I am not sure whether we need to know base-uri statically, but any other entry might depend on a variable / option. 

Any opinion, any solution?

**Comment by ndw** [comment]
Overtaken by events.
