### ISSUE TITLE
Edit section @select on p:with-input

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#256]
In [section 17.2](http://spec.xproc.org/master/head/xproc/#p.with-input) (select) is some editing required:

- It is not stated what happens when the select expression select an attribute. Other node types are wrapped into a document node, but this is not possible for attributes. Possibilities: (a) error or  (b) the value of the attribute is wrapped into a text node.
- It is not defined what happens when the result is an atomic value. Possibilities: (a) error or (b) the value of the attribute is wrapped into a text node.
- It is not said, that an error is raised, if the result is a map or an array.
- It is unclear how to set property "base-uri" when the selected node is not a document or an element.

**Comment by ndw** [comment]
12 June 2018 f2f:
1. attribute -> error
2. atomic value -> wrap in text node
3. maps/arrays -> error
4. An atomic value has no base URI

**Comment by ndw** [comment]
For an atomic value, the type is lost. The content type of an atomic value is text/plain

**Comment by xml-project** [comment]
Fixed with #668
