### ISSUE TITLE
p:until

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#26]
Repeat a subpipeline until a stable point is reached.

**Comment by Conal-Tuohy** [comment]
This is interesting to me. One of the "pain points" I've offered encountered in XProc has been in iteratively processing pages of data received from a foreign source (i.e. datasets organised as linked lists). Having to use recursion to access and process the data brings some memory management problems along with it.

At first glance, `p:until` looked like a way to deal with this problem. Is that the idea?

Off the top of my head, it seems to me that `p:until` would have to be an oddity in terms of XProc's scoping rules. If the loop termination is to be effected by something that happens inside the loop, then values in the loop's internal scope would need to be in the scope of the expression that controls the loop termination, too. 

Apologies if I've got the wrong end of the stick about `p:until`.

**Comment by eriksiegel** [comment]
Closed because deferred to 4.0
