### ISSUE TITLE
Add expand-text to more places

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#270]
It's only allowed on p:inline today, surely we meant it to be inheritable from, for example, p:declare-step?
On p:group? On all compound steps? On all steps (consider a p:input inside an atomic step).

**Comment by ndw** [comment]
Consider adding to 3.10?

**Comment by eriksiegel** [comment]
I would like to propose to be able to add it (for now?) to p:declare-step *only*. That would provide you with a way to set a default for your step. Consistent with how xslt does this.

**Comment by xml-project** [comment]
I agree with Erik to make it p:declare-step _only_. Allowing it in other places might be useful when writing pipelines but definitely will lead to a lot of trouble when next steps are inserted into the pipeline or one tries to debug it.

**Comment by ndw** [comment]
Section 3.4 of the XSLT 3.0 spec, expand-text and a number of other attributes are allowed on any XSLT element.

I'm reasonably strongly in favor of consistency with XSLT on this point.

**Comment by eriksiegel** [comment]
We could do that, but it feels to me like making the @expand-text setting overly important. This is *not* XSLT where you're usually creating text nodes all over the place. This is XProc where it  applies only to p:inline's.

Staying consistent with XSLT is good, but IMHO we're overdoing it here. 

I can live with both options. Anybody else has an opinion about this?

**Comment by eriksiegel** [comment]
This discussion still runs but I noticed that there is currently no `expand-text` attribute mentioned explicitly on `<p:declare-step>`. I think it should (including mentioning its default value `true`).

**Comment by xml-project** [comment]
If I get @ndw 's argument right, he proposes to add it to section 3.10, so it can appear on any element (like in XSLT), so we do not need to mention it in p:declare-step.
I am not sure whether the analogy to XSLT holds because in XProc we decided that its default is true (in XSLT it is false) and we want it to be an xs:boolean (in XSLT its "yes", "1", "no" or "no").

**Comment by eriksiegel** [comment]
Yes, but I'm still not in favor of adding it to any element. See my comment of Feb 15.

**Comment by xml-project** [comment]
So where do we allow it:
- p:declare-step
- p:inline
seems to be clear. What about:
- p:library?
- p:input /p:with-input?
- any step element?

**Comment by eriksiegel** [comment]
p:library: yes, as it is the root of an XProc document. 

IMHO: Given the rather limited nature where you can use TVT-s, only on p:inline and not anywhere else.

**Comment by xml-project** [comment]
Consensus?

**Comment by ndw** [comment]
12 June f2f, we'll allow it everywhere. It defaults to the value on your nearest ancestor or true.
