### ISSUE TITLE
Are there things that can be added to the spec to help implementations become streaming?

### ISSUE THREAD

**Issue by bertfrees** [xproc/3.0-specification#275]
I don't know if this question makes sense or if it has been discussed before. I just saw that XSLT 3.0 does this and wondered if it's something XProc could do. I'm not very familiar with the XSLT streaming features yet, so I don't have a clear idea of how it would look. The vague idea I had is to add a generic `streamable` attribute on steps which puts additional restrictions on the inputs/options. What the exact restrictions are probably needs to be specified per step.

**Comment by gimsieke** [comment]
We discussed streaming briefly in [London](https://github.com/xproc/Workshop-2017-06/wiki/Minutes) (look for “streaming” on the Wiki page) and, half jokingly, postponed it to XProc 4.0. My gut feeling tells me that everything has to be re-thought and re-implemented from the ground up, like in XSLT 3.0.

**Comment by bertfrees** [comment]
OK I missed that. Thanks for the pointer.

**Comment by bertfrees** [comment]
@gimsieke You say that everything might need to be re-thought from the ground . But my naïve understanding is that if all steps in a pipeline are streamable the pipeline is streamable. Is it more complicated than that?

**Comment by ndw** [comment]
We aren't going to attempt to address streamability at the level of detail that XSLT 3.0 does in this version.
We'll continue to try to avoid adding features that would inhibit streaming.

**Comment by eriksiegel** [comment]
Closed because deferred to 4.0
