### ISSUE TITLE
Reverse syntax @pipe

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#281]
Turn the order of the @pipe values around.
NOT: step@port
BUT: port@step

More logical and consistent with how the @ sign is normally used (like in emails)

**Comment by Gertone** [comment]
thinking about this, is the @ not a little bit confusing? (at least it was for me at first)
we might use a # instead which also makes sense from the url point of view

**Comment by eriksiegel** [comment]
Well, I think port@step is not confusing at all. On the contrary: You pronounce @ as 'at' and the resulting 'port at step' sounds fine to me. It's also a nice analogue with an e-mail address, first the 'child' (the email name) and then the'parent' (the server name).

If we would like to use the # sign, then I think we'll have to reverse it again to stay consistent with how an url uses it. The port after the # is an anchor inside an encompassing document. So: step#port

My preference stays: port@step

**Comment by Gertone** [comment]
I understand about the "at" meaning, so reversing when using @ would be the way to go.

At first I was thinking inline xpath, so this is referring to an attribute, when just using "@step",
that is why I was confused the very first time I saw that

I agree (and that is what I implied) that if we would use # it would indeed have to be step#port

**Comment by gimsieke** [comment]
I slightly lean towards keeping `@`. Any other ASCII-range character candidates for a delimiter? Maybe a pipe symbol, `|`, like `port|step` or `|step`? Doesn’t look right because it looks like piping into `step` while you are actually reading from `step`.

**Comment by xml-project** [comment]
To me its a matter of taster, of usability and limitation of character sets.
First I like "port@step" as explicit form much better than the original order "step@port". But turning it around means that we have to write "@step" if the port is missing, which is not nice but ok for me.

Also see the beauty in @Gertone approach using "#" base on the "page#fragment" concept, so it goes to "step#port", "step" and "#port". My only reservation would be, that I am not sure all parsers support "#" in text as we want it (and I would have to escape it with "&").

Short story: I think "@" is perfectly explainable as "mail@server" - lets stay with this if one one really objects.
