### ISSUE TITLE
p:compare and isomorphic

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#282]
Could we use the concept of isomorphic compare, Jim presented at Prague as a method in p:compare or do we need a unique step to do this.
Having this type of comparison is imho more interesting than deep-equal

**Comment by ndw** [comment]
I think that it could be a 'method' on the existing p:compare step.

**Comment by ndw** [comment]
Can we close this as resolved: if you implement it, make a method name for it.
