### ISSUE TITLE
Text value templates for NON-xml documents

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#284]
In Prague we seemed to have reached a silent consensus, that tvt's are not only for xml documents but for all documents constructed. (Remember the discussion about '{' and JSON inlines on day 1).
I like that idea and think it will be very useful, but the current prose of [2.10.2 Text Value Templates](http://spec.xproc.org/master/head/xproc30/#text-value-templates) does not reflect that consensus in talking e.g. about nodes inserted into a document.

For constructed text documents it seems to be pretty clear that the tvt-section evaluates to a string (not a text node), but what about constructing a JSON with {$a} and $a holds a map?
Any proposal?

**Comment by ndw** [comment]
The context in which TVTs are expanded really only applies to XDM nodes. This inline constructs a text node that has the form of a JSON object:

````
<p:inline>{{ "a": 3+4 }}</p:inline>
````
but I'm not convinced we actually worked out what you have to do next to make that into an actual JSON object. Maybe a document-properties setting is enough, but that needs some detailed spec work to assure that it's sensible.

**Comment by xml-project** [comment]
My first though was to limit TVTs to XDM nodes only, which would include also "text documents" because they are a document node wrapped around a text node. So this
`<p:inline document-properties="map{Q{}content-type:"text/plain"}">
  Some text with {$a} a variable
  </p:inline>`
should work. JSON-documents are surely different.
Do you see many fundamental problems here or are you just stating the fact, that the current version of the specs does not cover this case?

**Comment by ndw** [comment]
I am concerned that there will be hard problems in the details, so I'm observing that we don't have any of the details specified yet.

**Comment by ndw** [comment]
Overtaken by #398
