### ISSUE TITLE
p:inline construction of JSON documents

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#286]
In Prague 2018 we decided that JSON documents can be constructed via p:inline like so:
`<p:inline document-properties="map {xs:QName('content-type'): 'application/json' }" expand-text="false"> {"test": "foo"} </p:inline>`

This decision must be inserted into [specs](http://spec.xproc.org/master/head/xproc30/#document-types) with a hint, that the expand-text-feature is true by default, so "{" has to be written as "{{".

The representation part of a JSON document is constructed by calling [fn:parse-json()](https://www.w3.org/TR/xpath-functions-31/#func-parse-json) with the string value of the text node constructed.

Open questions:

- Is it possible to access the JSON object with an XPath expression and e.g. assign it to a variable? How to do this?

- How are text value templates evaluated for JSON documents?

See: see [Document model for non-XML documents](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-6-Feb)

**Comment by ndw** [comment]
12 June f2f, we resolved the question of how JSON documents work. The TVT question is clear in the spec.
