### ISSUE TITLE
Introduce attribute "tunnel" (xs:boolean) for options

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#291]
Consensus: We’ll attempt to spec and implement a 'tunnel' option on p:option. If a called step has declared an option as 'tunnel' and the calling step does not specify a value for that option, the in-scope value is inherited.

Consensus: If a tunnelled option has a declared type that differs from the declared type in the outer scope, it is an error. Working definition of "that differs" the normalized-space string-comparison of the two values of the 'as' attribute are different.

A tunneled option does not satisfy the constraint required=true on a declared option.

See: [minutes, day 1](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-6-Feb#default-values-for-options-on-steps)

**Comment by eriksiegel** [comment]
Added a first text proposal to the spec with PR #360

**Comment by ndw** [comment]
After much discussion, we've concluded that using an option that is a map is not significantly more difficult to use and avoids having to implement (and explain) a quite complex feature. Deferred.

**Comment by eriksiegel** [comment]
This one can be closed for now
