### ISSUE TITLE
Think about import of variables from xslt- and xquery packages

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#292]
At Prague 2018 we decided to have `p:import-functions` for functions defined in xslt- and xquery packages. (see #42).

It would be nice if variables defined in those packages could be imported to.

See [minutes, day 2](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-7-Feb#revisit-importing-function-libraries)

**Comment by eriksiegel** [comment]
To clarify: Only *global* variables and only variables in the *namespace* as specified in the import-functions/@namespace attribute

**Comment by ndw** [comment]
11 June f2f, we said "no" again. :-)
