### ISSUE TITLE
Introduce new step p:tee

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#293]
See [minutes, day 2](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-7-Feb#ptee)

**Comment by eriksiegel** [comment]
Proposal for a p:tee step:

A p:tee step acts exactly like a p:identity step with the additional functionality of being able to writing the contents "flowing through" to a file.


```
<p:declare-step type="p:tee">
   <p:input port="source" content-types="*/*" sequence="true"/>
   <p:output port="result" sequence="true" content-types="*/*"/>
   <p:option name="href" required="true" as="xs:anyURI"/>        
   <p:option name="serialization" as="map(xs:string,xs:anyAtomicValue)"/>
   <p:option name="enable" as="xs:boolean" required="false" select="true()"/>   
</p:tee>
```

When @enable is false() the step acts exactly as a p:identity step.

When @enable is true() every document flowing through is written to the URI as specified by @href using the same semantics as p:store. Existing content on @href is overwritten if possible (for files).

An implementation in XProc could be written as:
```
<p:identity name="tee-in"/>
<p:if collection="true" test="$enable">
 <p:store>
    <p:with-option name="href" select="$href"/>
    <p:with-option name="serialization" select="$serialization"/>    
 </p:store>
</p:if>
<p:sink/> 
<p:identity>
  <p:with-input pipe="@tee-in"/>
</p:identity>
```

(NOT SURE: Can the above XProc fragment be done differently (shorter maybe?) using ports on the p:if?)

**Comment by ndw** [comment]
I think the `enable` option is a little odd. If it's for debugging, we have other mechanisms for that. If it's not for debugging, why do you want a dynamic enable condition? And, obviously, you can implement this yourself in XProc if you want precisely these semantics.

**Comment by eriksiegel** [comment]
The enable option is there because I use it for... debugging. I usually have a $debug parameter in my stylesheets that turns tee operations on. 
Yes, you're right, implementation in XProc is easily done (and that's exactly what I have done in the 1.0 case). The request for a p:tee was more out of convenience reasons, I think its a nice lightweight debugging tool, useful for more than just me. But if I'm the only one that does things this way, no problem to skip it.

**Comment by xml-project** [comment]
One reason for having p:tee as a step in the standard library (as opposed to implementing it with XProc in a p:library) might be the debug flag itself. We could think about introducing the notion of a XProc processor running in debug-mode which switches steps as p:tee on.
The advantage here is, that the pipeline/stylesheet/query itself does not need a switch to turn debugging on or off and the processors could do some interesting things with the output of debugging.

**Comment by eriksiegel** [comment]
Sounds interesting and would shorten things. But be aware: A p:tee is useful for more than debugging alone and it would be a pity if it only worked when you fire off your processor with a debug flag. So I'm not sure whether this is a good idea...

**Comment by eriksiegel** [comment]
I'm making up the proposal for the `p:tee` step. 

There was some debate about introducing an `enable ` option. I still think, given the main use-case for a `p:tee` (debugging) that an `enable` option is useful. However I also agree that it deviates from what we do in other steps, so its odd. 

I personally would like to introduce a `p:tee` `enable` option, it makes the step much more useful to _me_ and hopefully lots of others. But before I do that: Any more thoughts, strong opposition or support?

**Comment by gimsieke** [comment]
I also like to have an option that I can set at each invocation of a macroscopic pipeline (and maybe without the need to explicitly pass this option to each invoked step). 
So something like the tunneled options, but without the need for general tunneled options. 
Maybe like `<p:tee enable="{contains(/*, 'trigger string') and p:system-property('p:debug-level') gt 2}" …>` (anticipating that there might be a `debug-level` system property that users can set when invoking the processor). 
This option would also be useful for a generalized [`p:message`](https://github.com/xproc/steps/issues/2) step.
It is not necessary to have this `debug-level` system property. We can pass the option/parameter explicitly if need be.
