### ISSUE TITLE
Attribute value templates on extension attributes

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#30]
The specs currently says nothing about AVTs on extension attributes.
Some of these attributes are evaluated while compiling the pipeline (e.g. cx:depends-on), some other may be evaluated while running the pipeline (e.g. cx:message).
AVTs are possible on the latter, but not on the former. To ban uses of AVTs in all cases would be to restrictive.
How do we make the difference?

**Comment by ndw** [comment]
I propose that we allow AVTs in extension attributes. We're going to move cx:depends-on into the language proper where we can forbid AVTs.

If an implementor adds an extension attribute that's used at "compile" time, they have the option of saying that AVTs are forbidden in that attribute. I propose that we don't have to worry about whether or not that's a "conformant" implementation.
