### ISSUE TITLE
Publish specification for "Optional validation steps"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#300]
At Prague 2018 we decided to publish a spec called "Optional validation steps" containing all steps "p:validate-with-*".

See [minutes, day 2](https://github.com/xproc/Workshop-2018-02/wiki/Raw-Minutes,-7-Feb#step-library-questions)

**Comment by ndw** [comment]
We also decided that we'd make optional steps into separate specs. I decided when editing that putting all three validation steps in one spec was counter to the spirit of that decision. Suppose I only want to implement XSD validation? Or RNG? Or Schematron. Separate specs make more sense, I think.

**Comment by xml-project** [comment]
If I remember right, the main reason for separation was not to give the implementer a reference to say "I implement this spec, but not that.", but to have more stability in editing.
Putting the three validation steps into one spec was motivated by the idea of a common validation result document which applies to all three steps.
If we split it up, we will have to repeat some part of the specifications in all three. And: If we modify the description of the validation result document, all three documents need republishing.
However: I will not insist on having one document.

**Comment by eriksiegel** [comment]
Can't we make a single document consisting of all steps that are optional? And then I mean individually optional, so every implementer is free to implement zero, one or more of the optional steps, as he/she sees fit.

**Comment by ndw** [comment]
This is fixed. I must have mentioned the wrong issue number in the commit msg. :-(
