### ISSUE TITLE
Schema missing in repo?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#301]
Opening the `src\main\schema\xproc.rnc` schema, it complained about not finding the `src\main\schema\steps.rnc` schema.

Sounds like something is wrong. Who can fix this? @ndw ?

**Comment by ndw** [comment]
Actually, `steps.rnc` is generated from the spec sources. You probably need to grab the version(s) from the `build/schemas` directory. I'm most of the way through the build refactor, I'll make sure this is sorted.

**Comment by xml-project** [comment]
Is this still open?

**Comment by eriksiegel** [comment]
Nope
