### ISSUE TITLE
make p:catch optional

### ISSUE THREAD

**Issue by mkraetke** [xproc/3.0-specification#305]
I would like to propose to make `p:catch` optional for `p:try`. If `p:catch` is left out and the subpipeline within `p:try` fails, `p:try` should just provide the error as primary output.

Background: Frequently, the only reason you write a `p:catch` is to forward errors and take care of it later, e.g. for printing them in a status report. The pipeline below shows a simple concept of forwarding errors.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
  xmlns:c="http://www.w3.org/ns/xproc-step" 
  version="1.0">
  
  <p:output port="result"/>
  
  <p:try>
    <p:group>
      
      <p:error code="err">
        <p:input port="source">
          <p:inline>
            <err>Shhht</err>
          </p:inline>
        </p:input>
      </p:error>
      
    </p:group>
    <p:catch name="catch">
      
      <p:identity>
        <p:input port="source">
          <p:pipe port="error" step="catch"/>
        </p:input>
      </p:identity>
      
    </p:catch>
  </p:try>
  
</p:declare-step>
```
The pipeline produces this output:
```xml
<c:errors xmlns:c="http://www.w3.org/ns/xproc-step">
  <c:error name="!1.2.1.1" type="p:error" code="err">
    <err>Shhht</err>
  </c:error>
</c:errors>
```
In my proposal, this much more concise try-statement should provide the same output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
  xmlns:c="http://www.w3.org/ns/xproc-step" 
  version="3.0">
  
  <p:output port="result"/>
  
  <p:try>
      
    <p:error code="err">
      <p:input port="source">
        <p:inline>
          <err>Shhht</err>
        </p:inline>
      </p:input>
    </p:error>
      
  </p:try>
  
</p:declare-step>
```

**Comment by xml-project** [comment]
@mkraetke @gimsieke 
Could you please check the current version of the specs. p:catch is optional so the error could be catched by a higher (surrounding) p:catch or by the system.
To implement the requested behavior I think a new construct would be necessary because we need to make a difference between an error handled by p:try/p:finally and then bubbling up (as in Java and other programming languages) and your idea of converting the error implicitly into a document which then flows on a port.

**Comment by mkraetke** [comment]
OK, then I would withdraw that proposal as I see that a shortened `p:try` is not congruent with the concept of bubbling up errors to other `p:try` statements. Perhaps we could give this step another name. Personally, I like the concept of easily converting errors to documents that float through the pipeline and Java introduced with version 1.7 a [try-with-resources Statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html]). However the difference is that this shortened `try` is used to implicitely close resources, so you're not forced to write every time a `finally` statement.

**Comment by mkraetke** [comment]
@xml-project: Even though this ticket is closed, we can proceed with the discussion here. Achim asked for a more distinct step name and I think `p:force` would be appropriate: The step forces the pipeline to proceed, even if errors occurred.

@gimsieke  came up with another idea: We could add a `fail-on-error` option to `ptry` (defaults to `true`). If `fail-on-error` is set to `false`, then the error could be provided as document either at the primary output port or another secondary port named `report` or something else.
