### ISSUE TITLE
Clarify semantics of p:try (without p:catch)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#306]
After reading the specs on p:try again I think we need to clarify the semantics of a p:try which has no p:catch but a p:finally. 
Two interpretations of behaviour in an error case:
(1) Since no p:catch is specified here but there is a p:try, the error is discarded and p:finally is executed. The output port of p:try are the output ports of the p:group (or of the subpipeline since p:group is not required anymore), but all output ports are empty.
(2) Since no p:catch is stated here, the error has to bubble up to an outer p:catch or the processor. But since there is a p:finally, this subpipeline is executed before the error bubbles up.

I am in favour of interpretation (2) which would be _my_ natural reading of the pipeline, but I am certainly open to arguments.

However we decide: Since we made p:catch optional we need to explain, what p:try-p:finally means.
Any thoughts?

**Comment by ndw** [comment]
I think it has to be option (2). Consider:

    <p:try>
      <my:step/>
      <p:catch code="err:XD0011">
        <my:whatever/>
      </p:catch>
      <p:finally>
        <my:finish/>
      </p:finally>
    </p:try>

I assume it's unambiguous that if `my:step` raises some error other than `err:XD0011` then `p:finally` is executed and then the error bubbles up because there was no catch for it. A `p:try` with no `p:catch` children trivially fails to catch any errors and they all bubble up.

**Comment by xml-project** [comment]
I think the following para from p:try second to the syntax box was accidentally deleted:
<para><error code="S0075">It is a <glossterm>static error</glossterm>		
 -if a <tag>p:try</tag> does not have exactly one <tag>p:group</tag> and		
 -at least one <tag>p:catch</tag> or exactly one <tag>p:finally</tag>.</error></para>

**Comment by ndw** [comment]
That just repeats what the content model says so I didn't think it was adding anything.

**Comment by xml-project** [comment]
Oh, I see. But if I remember right, I introduced this para to introduce the error code, because we do not have any error code for this situation.

**Comment by ndw** [comment]
Ok. But we have an error code for "your pipeline doesn't conform to the grammar of pipelines". Do you think there's significant value in a separate, distinct error code for this case? If you do, I don't object to putting the paragraph back.

I have a small preference, in specs, for not repeating things. Having a structure that's erroneous in two distinct ways just introduces variability in the way implementations report the error. If it's both a violation of the grammar (err:XXX) and specifically a distinct error (err:YYY), I assume implementations are correct regardless of which one they report.

**Comment by xml-project** [comment]
I am not sure we have an error for "your pipeline doesn't conform to the grammar of pipelines", but we have specific error for a compound step without a subpipeline, a choose without a when or an otherwise and so on.

I would not object to have such a generic error code for static errors and leave it to the processor to give an error message which hints what is wrong. But then I would expect this error to be always used when a pipeline does not conform to the grammar of pipelines. All other XS???? should be errors are not expressible in the grammar.

But I think this decision is not special to this case.

**Comment by ndw** [comment]
Fair enough. I'll put it back. But I'd like to get #300 sorted first.

**Comment by xml-project** [comment]
Thanks! I will open a new issue concerning the error code for "your pipeline doesn't conform to the grammar of pipelines".
