### ISSUE TITLE
Attribute href on p:document within p:input

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#310]
The specs [say](http://spec.xproc.org/master/head/xproc/#p.document):

> The attribute href can be an attribute value template in all use cases except when the p:document appears as a child of p:input, because a static binding is required there. It is a static error (err:XS0084) if the attribute href on a p:document within a p:input is an attribute value template.

I have two questions:

1. Does it really make sense to have this error message which requires the processor to parse the attribute value as AVT and if it is an AVT to raise an error. We could as an alternative say, that the attribute value of href is _not treated as an AVT_ in the given case, so it will most probably result in a dynamic error ("resource not found") to write an AVT.

2. Since it is treated as an AVT (to raise the error) but not allowed to be an AVT, do I have to write "{{" if I want "{"? Very unlikely to be used in an URI, but might happen.

**Comment by ndw** [comment]
Is a static binding really required here?

**Comment by xml-project** [comment]
Hhm? Good question. Having dynamic binding would open up some interesting use cases.
`<p:input><p:inline>` TVTs are allowed, so this default binding has to be developed dynamically. 
I guess there was a reason for forbidding dynamic binding of URI. Do you remember what it was?
I am currently implementing this part, so I might try to implement dynamic binding on p:document in p:input and see, if any problems come up.
@gimsieke @eriksiegel Any idea?

**Comment by gimsieke** [comment]
I’m inclined to proceed as not interpreting the attribute as an AVT and then to wait for whatever error to emerge from that.

**Comment by eriksiegel** [comment]
I agree with @gimsieke

**Comment by ndw** [comment]
I don't think any errors will emerge from not having an AVT. I also can't think of any reason why the processor needs to know the URI statically. But I'll go with the flow.

**Comment by xml-project** [comment]
I think it will be difficult to explain, why I can have dynamic evaluation with TVTs in p:inline as a child of p:input, but not dynamic binding for p:document. But ok, if you all agree on this, ...
@ndw I think the errors will appear in the very rear cases where someone writes <p:document href="{$a}" />, because there probably will be no resource named "{$a}". But it is up to good error messages telling the pipeline author were the problem comes from.

**Comment by xml-project** [comment]
Proposed resolution then:
Remove the last sentence of:
> The attribute href can be an attribute value template in all use cases except when the p:document appears as a child of p:input, because a static binding is required there. It is a static error (err:XS0084) if the attribute href on a p:document within a p:input is an attribute value template.

**Comment by eriksiegel** [comment]
Wait a minute. In Prague we decided on allowing variables in the prologue part of a step as well. This is also the part where these damned @href attributes appear. Right? 
So why shouldn't we allow AVT's? The same rules apply to setting the values of variables in that section of the step. Sorry for the change of heart, but it makes sense to me to allow them... So you can declare (or staticly compute) a variable with the name of a file and later on use that in the p:document/@href

**Comment by xml-project** [comment]
Now: Taking Eric's comment, Norm's (?) and my preference for dynamic binding, the proposed resolution is to remove the whole paragraph (=AVT in all use cases) and mark attribute href on p:input as an AVT too.

Consensus?

**Comment by gimsieke** [comment]
Yes
