### ISSUE TITLE
Binding for p:with-option and p:variable 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#315]
Opposed to XProc 1.0 the current syntax of [p:with-option](http://spec.xproc.org/master/head/xproc/#p.with-option) and [p:variable](http://spec.xproc.org/master/head/xproc/#p.variable) allow multiple documents to appear as context node for the select-expression. This results in a dynamic error (XD0008), but is no syntax error anymore.
Is this intentional or a mistake, so we need to replace "*" with "?" in the syntax?

**Comment by xml-project** [comment]
@ndw @gimsieke @eriksiegel Nobody any idea?

**Comment by gimsieke** [comment]
I vaguely remember that we wanted to use the first document for evaluation if multiple documents are present.

**Comment by xml-project** [comment]
@gimsieke 
Thanks Gerrit, that was the hint I needed: It's a sequence because of the collection attribute. And the error has to be dynamic (and not static anymore) because collection is an AVT.
