### ISSUE TITLE
Defining p:document via p:load

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#319]
We define [p:document](http://spec.xproc.org/master/head/xproc/#p.document) via [p:load](http://spec.xproc.org/master/head/steps/#c.load).
Questions:

1. Since p:load supports "URI globbing"  does this mean, p:document supports it too and is able to load more than one document? (Specs say: "A p:document reads a document...")

1. p:load enables dtd-validation via entry in map "parameters". Does this mean, p:document supports dtd-validation too?

I suggest the answer to both questions is "NO", so we have to add these restrictions to the prose of p:document.

**Comment by ndw** [comment]
We apparently added document-properties and parameters to `p:document`, why not support globbing and dtd validation there?

**Comment by xml-project** [comment]
I am not opposed to support globbing and dtd validation on p:document. But we then have to change the prose, because p:document no longer reads **a** document, but might read a sequence of documents. Additionally p:document should be marked to raise XD0043 and an error marking an invalid document.

May be we could get rid of p:load then, because p:load and
````
<p:identity>
  <p:with-input>
    <p:document href='something' />
  </p:with-input>
</p:identity>
````
seems to be exactly the same.
Did I miss something?

**Comment by eriksiegel** [comment]
@xml-project : That makes sense. Why keep p:load when we can do this; +1

**Comment by eriksiegel** [comment]
Sorry, closed the issue accidentally

**Comment by ndw** [comment]
At the moment, there's no way in `p:document` to control the context node for the expression in `href`. It's presumably the default readable port. I suppose we need to change that regardless.

I suppose allowing `p:with-option` inside `p:document` (see also #325) would fix this.

Rather than remove `p:load`, I think I'd rather define it as Achim suggested and leave it in the spec, perhaps in an appendix.

**Comment by xml-project** [comment]
@ndw Could you please elaborate on the last sentence of your comment because I did not get your point.

**Comment by ndw** [comment]
Rather than removing `p:load` we could leave it in the spec, implemented in XProc:

```xml
<p:declare-step name="p:load">
   <p:identity> ...
```

That's all. No reason to make people change all p:loads to p:identitys.

**Comment by xml-project** [comment]
Now I got it. Thanks and agreed.

**Comment by xml-project** [comment]
I think we could close this because we agreed that p:load will have some features that p:document does not have (e.g. globbing), so we have to keep p:load as a step.

**Comment by xml-project** [comment]
But see issue #325

**Comment by ndw** [comment]
12 June f2f, we've removed globbing so nevermind. See #325.
