### ISSUE TITLE
Relative uris in p:load 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#320]
The current version of [specs](http://spec.xproc.org/master/head/steps/#c.load) does not say what happens, if the uri provided for href is relative. XProc 1.0 specs said:

> If it is relative, it is made absolute against the base URI of the element on which it is specified (p:with-option or p:load in the case of a syntactic shortcut value).

I think we need to add this sentence to the specification of p:load.

**Comment by ndw** [comment]
Yes.
