### ISSUE TITLE
Problems in URI globbing

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#325]
While I like the idea of having globs in XProc 3.0, I have to admit, that I do not think our current approach is right:
1. Although we use the term URI globbing, a string like "file:///users/*[0-9].*" is no valid URI ('[' and ']' are not allowed in a URI).
1. Using "?" as the glob mark for any single character conflicts with "?" as character indicating the query string of a URI: Is "http://www.xml-project.com/?0" a URI glob or a URI with a query string?
1. Implementing globs in the way currently defined is very inefficient because almost no (Java) standard library can be used (URISyntaxException) and so for a lot of standard things new code has to be written.

I would therefor like to propose another approach to globbing which is clearly inspirited by ANT:
1. Attributes "href" (on p:load, p:document and c:request) or "path" (on p:directory-list) are proper URIs.
1. Each of these elements get a new optional parameter which contains a globbing-expression. This expression is a whitespace separated list of globs which are used to match children etc. of the directory (file) or collection (webdav) named by the URI. 
1. A child is included in the result, if it matches any of the globs.

I hope, I was able to sketch my idea. I not, please feel free to ask.

**Comment by eriksiegel** [comment]
I agree with Achim that allowing globs in @href would be a step too far. It would IMHO deviate too much from what is the usual contents of a @href and therefore it would be both hard to explain and error-prone to use.

A seperate @glob (or something like that) would solve that problem. We could also go for the ant <fileset> approach (with child elements).

If we go for @glob, would *space* separated be ok? A space is a valid character in a filename...

**Comment by xml-project** [comment]
@eriksiegel Yes, space separation may be wrong because you would have to use %20 to escape spaces in filenames.
The other option is an XDM sequence (xs:string*), so one could write
glob="('*.xml', '*.xsl', '*.xpl')"

**Comment by ndw** [comment]
If we're going to take it out of the URI string, then I don't think it should be called a glob anymore, nor is there any compelling reason for it to follow the globbing rules. It would more easily be described and implemented as a regular expression over the URI string(s). But it introduces additional problems.

First, "/d/**/*.txt" matches "/d/" followed by any number of path segments followed by any filename that ends in ".txt". How can that be expressed as a literal URI and an additional set of match strings? How is the base URI going to be construed as something which matches more than one thing? I guess it could
be the root: `file:///d/` and the match `**/*.txt`. Maybe.

Second, there needs to be some way to associate the matching rules with the URI (consider a step that takes two URI parameters, how are matches associated with them both?)

Finally, there will be immediate pressure to provide more control, "include" vs "exclude" patterns, for example.

Maybe we need to do this with a function.

    p:uriset(baseURI: xs:anyURI, include-patterns: xs:string+)
    p:uriset(baseURI: xs:anyURI, include-patterns: xs:string*, exclude-patterns: xs:string*)

That means the href parameters on steps would have to take sequences, though. Which maybe they should anyway.

Or maybe Erik is right and this should be done with more syntax:

    <p:document>
      <p:with-option name="href">
        <p:uriset baseURI="file:///d/">
          <p:include name=".*\.txt$"/>
          <p:exclude name=".*/.*test.*"/>
        </p:uriset>
      </p:with-option>
    </p:document>

(Bearing in mind that `p:with-option` isn't allowed on `p:document` at the moment.

**Comment by xml-project** [comment]
I will not argue for globs or for regular expressions, but if there is something, you can not express with regular expressions but with the glob syntax, that seems to be an argument to keep glob syntax. May be we can have both, either with different option/attribute-names or with a syntax prefix like in Java 7 with FileSystem.getPathMatcher().

Concerning the syntax I like the function variant, because it (a) is shorter and (b) fits into our current syntax framework. The <p:uriset> construct look very familiar from ANT, so it should not be difficult to explain. But what does it means to bind the value of "@href" with this?

BTW: If we decide to use the construct variant, we have a reason the keep p:document AND p:load, because as you said, this will not work easily with p:document.

**Comment by ndw** [comment]
I presume we could allow the constructor in `p:document` if we wanted to.

**Comment by eriksiegel** [comment]
If we go for the function approach, it would mean that the datatype of an href would become xs:string+ ?

But href is now defined as a value which can be filled in using an AVT.... So if we go for the function approach we also need to change that href can be filled using a child p:with-option (which you cannot do now). And a p:with-option can potentially become complicated with nested p:document-s inside...

So why not like this: We keep href as an AVT attribute. But *instead* of a href you can also do this:

```
<p:document>
    <p:uriset baseURI="file:///d/">
      <p:include name=".*\.txt$"/>
      <p:exclude name=".*/.*test.*"/>
    </p:uriset>
</p:document>```

Drop the idea of a  p:with-option on a p:document.

**Comment by xml-project** [comment]
1. I think @eriksiegel is right on dismissing the functional approach because it does not work with AVTs and I want "href" to be an AVT too.
1. The approach to have either "href" or p:uri-set as proposed by @eriksiegel is very elegant and takes away the problem to explain what it means to binding "href".

1. What I was thinking about is the relation between p:document (in our new approach) and p:directory-list. I would like the two to be as similar as possible saying that the latter delivers the names of URIs while the p:document delivers the resources named by the URIs. As a consequence we could use p:uri-set on p:directory-list as well, or we take the options "include-filter" and "exclude-filter" (as xs:string+) from p:directory-list to p:document. As it is easier to write and needs no new construct to be introduced, I would clearly opt for the later. So it could be:
````
<p:document 
   href = {anyURI+}  <!-- required -->
   include-filters ={xs:string+} <!-- optional, regex or glob-syntax -->
   exclude-filters = {xs:string+} <!-- optional, regex or glob-syntax -->
   <!-- ... -->
/>
````
If there is no include-filters or exclude-filters it works as in XProc 1.0 (with the difference of now having xs:anyURI+), if one of the attributes (or both) are present, with respect to uri resolving it behave like p:directory-list.

4. As @ndw pointed out, the glob-syntax can express restrictions, regex can't. So it would propose that "include-filters" (and exclude-filters) can use both and we use a prefix in the respective expression string ("glob:" and "regex:") to distinguish them. (This would of course also work with @eriksiegel's proposal of uri-set.) If the prefix is missing, we might say regex is default.

1. Then, from my point of view, the only remaining problem is that the href-expression in p:document does not have access to a context-node, while the href-expression in p:load has. I do not think we should invent a new construct to tackle this problem. From my memory this is a rare use-case and I would suggest to use a combination of p:variable and p:document for this.

Lastly, I wonder what @gimsieke has to say, because from their large collection of pipelines there should be some benefit for this topic.

**Comment by ndw** [comment]
Random thoughts:
1. I'm not sure why the function is seen as incompatible with an AVT.
```xml
<p:document href="mydoc.xml"/>
<p:document href="{$mydoc}"/>
<p:document href="{p:uriset('file:///d/', '**/*.xml')}"/>
```
It does mean that href becomes URI+, but that's ok if we declare that it's a sequence. That makes `href="{('a.xml','b.xml')}"` legal, but I can live with that, I think.

2. If we're going to do `<p:uriset>`, I think it needs to be inside a with-option so that it can be a general purpose mechanism, not a special bit of syntax inside `<p:document>`.

3. I'm not hugely fond of adding include/exclude directly to `p:document`. Again, that looks like a bit of magic syntax where a general feature would be better.

4. We need to be finished so there's starting to feel like pressure not to add stuff. We have to balance between getting it right and getting it finished.

**Comment by xml-project** [comment]
> We need to be finished so there's starting to feel like pressure not to add stuff. We have to balance between getting it right and getting it finished.

Totally agree. Since p:document/p:load is a central feature of a processor, I am somewhat delayed by this standoff.

**Comment by eriksiegel** [comment]
Not against the function in AVT approach but it goes against *my* understanding of what an AVT does... so maybe I'm wrong?

As far as I understand, an AVT is away to create the *contents* of an attribute, as a *string*, using XPath expressions in between curly braces. It doesn't magically create some XPath data thing, it creates a string. And then this string is interpreted by whatever that reads the value of the attribute.

**Comment by xml-project** [comment]
I think @eriksiegel is right. The specs say:

> The string value of the attribute is the result of the attribute value template as an xs:untypedAtomic.

So
````
<p:document href="{p:uriset('file:///d/', '**/*.xml')}"/>
````
(even if p:uriset returns xs:anyURI* and href is declared as xs:anyURI+) will not work, because the result of the AVT it is a sequence of characters which could be converted to xs:anyURI (possibly), but not to a sequence of xs:anyURI, at least if we do not add any magic here.

**Comment by gimsieke** [comment]
Since whitespace must be escaped in URIs, I think we can assume that `p:uriset()` may produce `xs:anyURI*` and that this sequence will be flattened to a string that consists of space-separated URIs. (This should probably be a general rule for AVTs, just like in [XSLT](https://www.w3.org/TR/xslt/#d7e20028).)

**Comment by xml-project** [comment]
Exactly. And this, to my reading, makes the functional approach impossible, because we can not make a space-separated list in to a sequence of xs:anyURI which we want to load.

**Comment by xml-project** [comment]
The only way I can think of if we follow the function approach is to say, that href on p:document and p:load is a single xs:string. This string is then taken as a space-separated list of URIs.
Is this to much magic?

I personally still would prefer to align p:document and p:load with p:directory-list and use attributes/options "include-filter" and "exclude-filter" (interpreted as a glob or a regex).

**Comment by gimsieke** [comment]
As an aside, people often want to pass OS file names (that may contain whitespace or be relative to the current working directory from which the pipeline was invoked) to pipelines. It would be super convenient if OS file names were also accepted where proper URIs are expected. We solve this by a step [tr:file-uri](https://github.com/transpect/xproc-util/blob/master/file-uri/xpl/file-uri.xpl) that accepts a single `filename` argument that can be a URL or an OS file name. It will then be analyzed and transformed to a `c:result` document with attributes `@os-path`, `@local-href`, `@href` and some others. The step is further complicated by optionally downloading resources via HTTP to local files in a temporary location, and to use an XML catalog for resolving URIs also for non-XML resources.
This step is extremely useful, and something like this would also be good for 3.0. I’m thinking about a function `p:resource()` that will accept a file name or a URI and return a map with the keys `os-name` and `href` with the normalized versions. 
Example: `p:resource('\\some\path\file.txt') ⇒ {"os-name": "\\some\path\file.txt", "href": "file://///some/path/file.txt"}`
If the poor `@href` attribute of `p:document` were to accept also OS names, it cannot deal with multiple space-separated values.
This is a new dimension in the problem space that now consists of:

- wildcard vs. plain names
- wildcard style (regex vs. glob)
- single values vs. multiple values
- OS paths vs. URIs
- different inclusion/exclusion expressions for subdirectories and for files

And for all of these dimensions we want to have a solution that is simple for simple cases but that also supports more complicated cases and that is the same for `p:directory-list`, `p:load`, and `p:document`.

**Comment by xml-project** [comment]
Thanks @gimsieke 
I have two questions:

1. Do I understand you right, that you propose to pass the map generated by p:resource() to p:document etc. Why does "get(p:resource(...),'href')" which is a string/uri not work?
1. Can we take your last paragraph as a sarcastic hint that what we try to achieve will not work?

**Comment by gimsieke** [comment]
No, I just wanted to say that accepting file names in many places where URIs are expected will be beneficial to users and pipeline authors. The function that would be most appropriate for `@href` options is probably something like `p:urify(xs:anyAtomicType) → xs:anyURI` that will accept a file name as a string or a URI (as xs:anyURI or as `xs:string`) and return a URI (or throw a dynamic error). 
Fictitious AVT example: `href="{p:glob('C:/Users/*/Desktop/*.jpg', {{"file-exclude-regex": "^\d{8}_\d{6}"}} ! p:urify(.)}"` will return a sequence of `xs:anyURI`s that then will be flattened to a space-separated string that the processor then will tokenize (the processor can probably choose to optimize the flattening and the tokenization away) in order to obtain a sequence of file: URIs to read. We don’t have this flattening/serialization problem when we pass multiple resource locations using `<p:with-option/>`. Since both passing methods may look the same to a processor so that it doesn’t know whether to read a space-separated string as a list of URIs or a file name with spaces in it, we can stipulate this rule: If the href value is a single `xs:string`, the processor must first tokenize it at whitespace and check whether each token is castable as `xs:anyURI`. If it is castable, it should process it as a sequence of URIs, otherwise as a single OS path.
The `p:glob()` function may accept an OS file/dir name or a URI as the first argument and an optional map with different include/exclude options and a base URI or OS path as the second argument. It may apply `p:urify()` on its own in order to always return URIs, or it may return whatever the first argument was, OS name or URI. 
`p:urify()` will be idempotent when applied to URIs.
This example does not need additional globbing/inclusion/exclusion attributes. It relies on XSLT-like AVT behavior (turn sequences into space-separated strings) and is a bit more flexible than approaches that only provide a single inclusion/exclusion/globbing attribute, since you can invoke `p:glob()` as often as you want within the AVT or within, for ex., `<p:with-option name="href" select="('foo.png', p:glob('*.jpg', {'base-uri': static-base-uri()} ))"/>`.
A last note on relative paths: I propose that the default base dir should be the one that `pos:info` reports as `cwd`, not the current pipeline’s base URI. This is more in line with user expectations.

**Comment by ndw** [comment]
Ok, I now see the AVT/attribute/string issue. At the end of the day, the href attribute will be a string. Attributes are strings. I don't think it would be too much magic to say that the attribute's value is interpreted as a space-separated list of strings (there's precedent: `cdata-elements`, `use-character-maps`, etc.). Lists get flattened by putting spaces between the items, so I think that would work. Consider:
```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:f="http://example.com/functions"
		exclude-result-prefixes="f" version="2.0">

<xsl:output method="xml" omit-xml-declaration="yes"/>

<xsl:template match="/">
  <doc href="{f:list()}"/>
</xsl:template>

<xsl:function name="f:list">
  <xsl:sequence select="('a','b','c')"/>
</xsl:function>

</xsl:stylesheet>
```
which produces
```xml
<doc href="a b c"/>
```
I'm personally unmoved by the plight of people who put spaces in filenames and then wish to pretend that those strings are URIs. They aren't. Escape them or don't put [expletive deleted] spaces in your filenames!

But Gerrit's observation that there's a huge problem space here is relevant. Maybe we should go back to "a `p:document` takes a single URI and loads a single document". If you want to do complicated things, use `p:load`. We can more easily put features on a step than we can on a language construct.

**Comment by xml-project** [comment]
Is it consensus we keep p:document simple (no multiple uris, no globbing, no regex) and do the smarter stuff with p:load?

**Comment by xml-project** [comment]
See related issue #319

**Comment by eriksiegel** [comment]
As of 12/7: No more globbing, anywhere

**Comment by eriksiegel** [comment]
include and exclude filters will become xs:string*

Means you cant set multiple filters using an AVT, you need p:with-option then

**Comment by ndw** [comment]
https://github.com/xproc/3.0-specification/wiki/XProc-3.0-editorial-team-minutes,-12-July-2018
