### ISSUE TITLE
Clarify syntax of p:library

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#34]
Clarify, that p:library always needs @version.

**Comment by ndw** [comment]
I thought we discussed this and concluded that the current rule was ok.

**Comment by xml-project** [comment]
I still find it irritating because
"If the p:library has no ancestors in the XProc namespace, then it must have a version attribute."
make me think about the case where it might have an ancestor in the XProc namespace.
But we really need this rule as opposed to library always needs a version attribute.
Can you please remind me again, what the argument is.

**Comment by ndw** [comment]
Consider `mycontrivedexample.xpl`:
```
<p:pipeline xmlns:p="..." version="3.0">
  <p:pipelinfo>
     <p:library xml:id="fred"> ... </p:library>
  </p:pipeinfo>
  ...
</p:pipeline>
```

And `<p;import href="mycontrivedexample.xpl#fred"/>`

Or, for that matter:

```
<p:i-made-up-my-own-non-standard-container version="4.0">
  <p:library xml:id="fred">...</p:library>
  ...
</p:i-made-up-my-own-non-standard-container>
```

**Comment by xml-project** [comment]
Ah yes, I remember. This is a very, very special case. Never thought of doing this.
The second one is more interesting, but poses at lot of pressure on the XProc-Prozessor. This would mean that a processor has do dig deep into non-XProc stuff (in the XProc namespace) to find the library.
It does not work with MorganaXProc but you are right: There is no reason (except simplicity) to restrict the way a processor finds the library to be imported. And fragment identifiers are surely a way to do this.

I try to learn the example by heart and promise to never ask you again about this.
Proposal: Close!

**Comment by ndw** [comment]
:-)

Getting documents with fragment identifiers is uncommon, but not *that* uncommon.
