### ISSUE TITLE
Formalize "injecting" trace information into a pipeline

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#340]
Back in October, I made a proposal in email for a mechanism that allows the person running an XProc pipeline to inject "inspectors" into a pipeline. It's archived [here](https://lists.w3.org/Archives/Public/xproc-dev/2017Oct/0000.html), though I see the archiver borked the markup.

Here's what I proposed:

```xml
<p:injectable xmlns:p="http://www.w3.org/ns/xproc"
              xmlns:c="http://www.w3.org/ns/xproc-step">

  <p:input step="/p:declare-step/p:identity[1]" port="source"
           message="Document sent to identity[1] on source"/>

  <p:input step="//p:identity" port="source"
           base-uri="pipe.xpl"
           message="Document sent to identity on source for pipe"/>

  <p:output step="/*/p:wrap-sequence" condition="$opt-class = 'b'">
    <doc class="{$opt-class}">{.}</doc>
  </p:output>

  <!-- also p:step for when a step runs -->
</p:injectable>
```

>The idea is that you can put an “inspector” on a particular input port
>or on a particular output port. (The comment at the bottom aludes to a
>p:step injectables as well, for when a step executes; I’m less
>confident about that one, purely on implementation grounds.)
>
>In order to insert something, you have to be able to point to it.
>Pointing with step names doesn’t work because you need to have
>something that’s unique across the whole pipeline, not just in a
>particular scope. Rather than inventing a new kind of step addressing
>language, I just went with XPath.
>
>If you don’t specify a base URI, the injector applies to all pipelines
>(which is fine because usually there’s only one anyway).
>
>The message can be either an attribute or content. If it’s an
>attribute, it’s an AVT so you can inspect the in-scope variables at
>the point of insertion. It’s an error if you refer to variables that
>aren’t in scope at that point.
>
>If the message is content, it’s like p:inline, it expands the TVT.
>
>Condition let’s you specify when you’d like the injectable to “fire”.
>
>There’s still lots of unanswered questions, like where does the output
>go?
>
>I’m implementing this by literally inserting steps into the graph.
>That complicates the graph, which could change behavior, but it means
>the injectables can refer to different variables than the steps.

Vojtech made some observations and there's a little bit of follow-on discussion on the list.

Is there any support for formalizing this in a spec? In the XProc spec or a separate spec?

I'd like to get it down somewhere because I think it's a superior solution to hand crafted `p:message`
statements or debug flags on steps. (I really don't like the debug flag on `p:tee`, architecturally.)

**Comment by gimsieke** [comment]
Just some random thoughts:

1. The pointer should also be able to take the call stack into account. You might want to log the output of an HTTP request in `lib:do-something` that in turn was called by `otherlib:some-pipeline` but not if `lib:do-something` was invoked from `thirdlib:boring-stuff`. 
1. Even if the output of the HTTP request in `lib:do-something` were to be logged in both cases, the output file names and serialization parameters need to be configurable in a different way, dependent on the call stack, the iteration position, etc. This means the call stack and the matching pipeline element (its XPath location, its name, its ID if there is one, …) must be available to the output file name calculation.
1. Logging is not the only thing that injection is good for. The greatest flexibility might be achievable if the action is specified in a subpipeline that is applied to the documents on the selected ports. For the debug/logging scenario, this could be a `p:store` or a `p:http-request` that posts the documents to some other storage facility.
1. One conceivable way of passing all the relevant information to a subpipeline that handles the interception is to wrap it in a compound step (for ex. `p:handle-injection`, as a child of `p:injectable/p:input` and `p:injectable/p:output`). `p:handle-injection` will make available to the subpipeline a variable called `stack`. This variable is an array (one item for each stack position) of maps with keys `base-uri`, `xpath-location`, `pipeline-document`, 'iteration-position', `type`, `name`, `id`, … Alternatively, the call stack could be passed as a sequence of pipeline documents with the aforementioned keys as document properties. Apart from the `stack` variable or input port, `p:handle-injection` has a primary input port on which the document appears (or the documents appear) that match the input or output port specification.
1. Matching should be performed against the call stack as sketched in the previous item. Suppose the stack is a sequence of pipeline/library documents with properties like `xpath-location` and `iteration-position`. Then it will be hard to express with XPath: If the calling pipeline’s type is `otherlib:some-pipeline` and the current pipeline’s execution path satisfies `id(do-something1)` (or `/p:declare-step/lib:do-something[1]`), then call the subpipeline that is specified for an input port of `lib:do-something`. Maybe it is easier with arrays? Suppose that the innermost item on the stack is at position `1` in the array. Then you can specify the matching condition `map:find($stack, 'type')(2) = 'otherlib:some-pipeline' and map:find($stack, 'id')(1) = 'do-something1'` if $stack is an array variable that automatically springs into existence at each possible injection point, when matching the `p:injectable` conditions against the execution location. Matching atomic map items such as `type`, `id`, `iteration-position` will be easier than matching arbitrary `xpath-location`s. An `xpath-location` is given as a string that needs to be evaluated against the step that is currently executed. It should make no difference if it is specified as `(//lib:do-something)[1]`, as `/Q{http://www.w3.org/ns/xproc}declare-step/Q{http://acme.com/ns/lib}do-something[1]`, as `id(do-something1)`,  as `//*[@xml:id='do-something1']` or as `//*[@name='ds1']` if that’s the name of the step within the pipeline. 
Is your XProc processor capable of evaluating XPath expressions against XProc documents? If not, one probably needs to specify that the XPath strings will be compared to what [`fn:path`](https://www.w3.org/TR/xpath-functions-31/#func-path) returns.
1. If injection targets are located by XPath, does this rule out injection for alternative pipeline syntaxes?

**Comment by eriksiegel** [comment]
Whew...  Tough stuff. Do we really have to get into this for 3.0 (since the workload is already big enough). How about deferring this to a later version (as we've already done for much more easy things).

**Comment by gimsieke** [comment]
It was meant to be in a separate spec anyway so it can develop at its own speed.

**Comment by eriksiegel** [comment]
Closed for now
