### ISSUE TITLE
Invalid documents on p:document

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#341]
Using parameter 'dtd-validation" we can perform a dtd-validation with p:document now, but we do not have an error to be raised, if the validation fails. Taking the current specs, which defines p:document via p:load it would be XC0027, but it seems strange to me using a C-error (from p:load) on a p:document which usually a child of some other step (e.g. p:xslt).
The alternative would be to overload XD0011, but this is already very general, so I would argue for a new XD-error for invalid p:document and use this also on p:load instead of xc:0027.

**Comment by ndw** [comment]
Yes, I agree.
