### ISSUE TITLE
Parameters on p:document/p:load

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#343]
In [p:load](http://spec.xproc.org/master/head/steps/#c.load) we like the use of parameters to XPath's parse-json, but map we define in XProc `(map(xs:QName,item()))` is not compatible with the map in XPath, which is `map(*)`.
I do not think, we should deviate from what XPath defines, so I propose to change the signature of parameters to `map(*)`.

**Comment by ndw** [comment]
Sigh. I have no idea why the map is defined that way, but I concede that it is.
