### ISSUE TITLE
Document-properties as map

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#344]
Why do we restrict document-properties to be `map(xs:QName, item())`?
Currently we do not have a document-property which is a QName, so why 'xs:QName'?
Since we allow the document-properties to have user defined items, why do we restrict the values to `item()` and not use `item()*`?

To my current understanding, we should say that document-properties are represented by a map(*).
What did I miss?

**Comment by eriksiegel** [comment]
@xml-project Do you propose that all maps we use for parameter passing etc as map(*). I hav no objections, as long as the rules how to interpret them are clear.

**Comment by xml-project** [comment]
@eriksiegel exactly: They should be map(*). To interpret them, we could use the table-approach of XPath 3.1.

**Comment by ndw** [comment]
Logically, I think document properties are a map from names to item(s). We define several names that I assume are "in no namespace". We might reasonable assert that we control all names that are in no namespace, which is consistent with what we do in other places.
If an author wants to invent a property, they can put it in their own namespace or put it in no namespace and risk that we'll walk on it.
I see no value in allowing arbitrary non-name keys to the document properties map. I think keys have to be atomic, so all you're allowing with `map(*)` is keys with values like "5" and "true()" and I don't see the value.

**Comment by ndw** [comment]
Per #343, I concede that the simplest thing to do is make the properties map `map(*)`.

**Comment by xml-project** [comment]
See discussion and solution on #371
