### ISSUE TITLE
Change XS0070 and XS0071 to dynamic errors

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#345]
I fail to understand, why XS0070 and XS0071 on [p:inline](http://spec.xproc.org/master/head/xproc/#p.inline) are marked as **static errors**. Both errors depend on the value of content-type, which as a value in document-properties{} which is a value only to be determined during pipeline execution.

Consider:
````
<p:option name="content-type" required="true" />
<p:identity>
  <p:with-input>
    <p:inline document-properties="map{'content-type':$content-type}">
````

Where is my mistake?

**Comment by ndw** [comment]
I think you're right. Since we moved content type into the properties map, those have to be dynamic errors.
