### ISSUE TITLE
Implicit inlines and TVTs

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#347]
Currently we [say](http://spec.xproc.org/master/head/xproc/#text-value-templates):

> All text nodes that are the descendants of a p:inline element are text value templates unless the p:inline has an expand-text attribute with the value “false”. Text nodes that are not the descendants of a p:inline are never text value templates.

Taking this literally implicit inlines could never contain TVTs because there is no p:inline. I think this is not what we want.

**Comment by eriksiegel** [comment]
I agree. Implicit inlines should also do TVT processing.

**Comment by xml-project** [comment]
Fixed with pr #348
