### ISSUE TITLE
Signature of p:document-properties etc.

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#353]
I think we should change the signature of p:document-properties etc., so it does not take any parameter but implicitly refers to the context node. This is necessary because only documents appearing on ports do have document-properties, while "normal" documents don't.
So
`p:document-properties(doc('some-uri'))` will either be an error or return an empty map. The same holds for

````
<p:variable name="doc" select=".">
  <p:document href="some-uri" />
</p:variable>

.... select="p:document-properties($doc)" />
````

Removing the parameter will clear this up.

**Comment by xml-project** [comment]
Yes, we might say that any document node has properties. But I do not see how the map can have any values for "p:document-properties(doc('some-uri'))".
"doc('some-uri')" will be resolved by the underlying XPath processor which does not know anything about XProc's concept of document-properties.

**Comment by eriksiegel** [comment]
If it doesn't know anything it can simply return an empty map?

But it does know several things in case of `p:document-properties(doc('some-uri'))`:
- The base-uri
- That its XML

So it could return this?

**Comment by gimsieke** [comment]
agree

**Comment by xml-project** [comment]
I am not opposed to @eriksiegel 's proposal, but it might place a burden on implementers which use 3rd parts XPath implementations. So the question is, whether it is worth it.

**Comment by eriksiegel** [comment]
True. You *can* return something but why the heck should you...

**Comment by xml-project** [comment]
@eriksiegel
If you mean "you can" as "implementation defined", I think this is wrong, because we run into interoperability problems if one processor return an empty map and another returns something else.

**Comment by eriksiegel** [comment]
Yes. So maybe the question is: Do we have a use case for p:document-properties not referring to the context node? I cant think of one.

**Comment by ndw** [comment]
As @eriksiegel suggests, the base URI and the content-type are always available from the context node, so that at least is possible. I also think it's possible that more information may be available to the implementation.

**Comment by xml-project** [comment]
Consider this:
´´´´
<p:variable name="var" select=".">
  <p:inline document-properties="{'key':'avalue'}">...</p:inline>
</p:variable>
´´´´
No I do: `p:document-property($var, 'key')`  Is a processor required to return 'avalue'? 

I do not think we should say, this is implementation defined. If we keep the current signature, the answer should be 'yes'. But that might be a burden, this is why I suggested to chance the signature.

**Comment by xml-project** [comment]
@ndw @eriksiegel @gimsieke 
I think we should decide this: Thump up means change signature, thump down: keep it like it is.
