### ISSUE TITLE
Base-uri of documents created with p:inline

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#359]
What is the base-uri of documents created with p:inline and where do we say this?

**Comment by eriksiegel** [comment]
Good question... `static-base-uri()` ??? And/or should we allow a `base-uri` attribute on p:inline ???

**Comment by ndw** [comment]
The answer is the base URI of the p:inline element. It appears that that prose has been lost in the conversion to "document-properties". It needs to be put back.

**Comment by eriksiegel** [comment]
Ehh, and what would that be? The p:inline element is in the pipeline document, so `static-base-uri()`?

**Comment by xml-project** [comment]
What @ndw said is, that there is no change to XProc 1.0, just the text has been lost.
Since `<p:inline>` is an XML element it has a URI (either that of the pipeline itself or some URI set by xml:base).

**Comment by xml-project** [comment]
Fixed with pr #370
