### ISSUE TITLE
Legacy from 1.0: # 2.7.2 Syntax: allow <p:pipe port="secondary"/> 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#37]
# 2.7.2 Syntax: allow <p:pipe port="secondary"/> 

>This is an aggregation of the discussion on "2.7.2 Syntax: allow <p:pipe port="secondary"/>" ([Issue 35 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/35))

**Opened by: ndw on 2014-08-22, 18:31h**

## ndw said on 2014-08-22, 18:31h:

XProc 1.0 offers relatively few default behaviors, requiring instead that pipelines specify every construct fully. User experience has demonstrated that this leads to very verbose pipelines and has been a constant source of complaint. XProc 2.0 will introduce a variety of syntactic simplifications as an aid to readability and usability, including but not limited to: 

`<p:pipe port="secondary"/>`binds to the “secondary” port of the step on which the default readable port occurs. 

	On 2014-08-22, 18:31h: ndw added the requirement label.

	On 2014-08-22, 18:36h: xproc added the must label.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

	On 2014-10-01, 15:37h: xquery self-assigned this.

	On 2014-10-06, 08:19h: vojtechtoman referenced this issue.

	On 2014-10-28, 16:22h: xquery was unassigned by ndw.

**Comment by ndw** [comment]
Make step and port optional; if step is missing, it refers to the step from which the default readable port would be read (its an error if there's no default readable port). If port is missing, it refers to the primary output port of the step (its an error if there's no primary output port).

**Comment by ndw** [comment]
Done.
