### ISSUE TITLE
Signature of p:document-property()

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#372]
The signature is:
````
p:document-property($doc as document-node(), $key as xs:QName) as item()
````
But the prose says:

> An empty sequence is returned if no such key exists.

So it should be:
````
p:document-property($doc as document-node(), $key as xs:QName) as item()?
````
Right?

**Comment by xml-project** [comment]
if we move to understand map(*) it has to be as item()*

**Comment by eriksiegel** [comment]
I agree about the item()? but I dont understand your last remark.

**Comment by xml-project** [comment]
Sorry, I did not check the markup. If we use `map(*)` the result of p:document-properties() has to be `item()*`, because `map(*)` is short for `map(xs:anyAtomicType, item()*)`.

**Comment by xml-project** [comment]
See discussion and solution on #371
