### ISSUE TITLE
Legacy from 1.0: # 2.8 Document backwards-incompatibilities 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#38]
# 2.8 Document backwards-incompatibilities 

>This is an aggregation of the discussion on "2.8 Document backwards-incompatibilities" ([Issue 44 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/44))

**Opened by: ndw on 2014-08-22, 18:35h**

## ndw said on 2014-08-22, 18:35h:

Backwards incompatiblity is painful for users and will be avoided wherever possible. However, XProc 2.0 will introduce language features that are not backwards compatible with 1.0. The specification must document these incompatibilities. 

	On 2014-08-22, 18:35h: ndw added the requirement label.

	On 2014-08-22, 18:36h: xproc added the must label.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
The new language is so different, we no longer believe that this would be useful.
