### ISSUE TITLE
Update specs to XSLT 3 match pattern

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#384]
from a comment by @gimsieke 

In #112 (comment), @ndw said that XSLT matching pattern are “are described in Section 5.5 of the XSLT 3.0 spec”. Our current draft still refers to XSLT 2.0 matching patterns though. If we really want to have XSLT 3.0 matching patterns, we need to a) refer to the XSLT 3.0 spec and b) clarify that we only refer to what XSLT 3.0 calls “selection patterns”, as they only match nodes.

**Comment by gimsieke** [comment]
You could also have reopened #112…

**Comment by xml-project** [comment]
I could, but there is a lot of legacy in issue #112, so I thought a new issue stating the point would be good.

**Comment by xml-project** [comment]
After reading the XSLT 3.0 specs again, I am not sure we should restrict XSLTPattern to "selection pattern" in general, because the "predicate pattern" could be very useful for (future) steps that deal with non-XML documents, especially json-documents. (See: Michael Kay's [Transforming JSON](http://dev.saxonica.com/blog/mike/2017/11/transforming-json.html))
Proposal:
(1) Update the core specs to XSLT 3.0 with an emphasis on the distinction between "selection pattern" and "predicate pattern".
(2) Update the step library for all existing (xml)-steps so the comment for "match" makes clear, that they have to be selection pattern by marking them with `<!-- XSLTSelectionPattern -->`.

**Comment by ndw** [comment]
:+1:
