### ISSUE TITLE
Do we really need p:character-map?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#391]
May be this is a stupid question, if so, please enlighten me.

After our workshop in Prague we introduced p:character-map, but actually I fail to understand why we need it as a construct in XProc.
The background is, that I am tend to understand serialization in XProc as a call of `fn:serialize()` were the document appearing on the output port is the first parameter and the map `serialization` defined on p:output is the second parameter of this function.
[XPath](https://www.w3.org/TR/xpath-functions-31/#func-serialize) now defines a key-value-relation for the map, saying that the key "use-character-maps" must refer to a `map(xs:string, xs:string)` where any occurrence of the value in key is replaced by the string as value.

This seems to be a pretty good way to do it because I can have all my serialization parameters in one variable or even (for continuous use) in a json-file.
So: What is the advance of having it as an XProc construct?

**Comment by xml-project** [comment]
Sorry, I did not make my point clear. Here is "my version" of your example:
````
<p:declare-step>
  <p:output port="result"
   serialization = "map{'use-character-maps':map{'[':'<'}}"/>
  <p:identity />
</p:declare-step>
````
I do not propose to use a serialization step, but talking about the option `serialization`on p:output. This option is a map and I just propose to use the same key-value conventions XPath uses for the map supplied to `fn:serialize()`. And since XPath defines a way to define character maps, I do not think that we have to invent  our own.

**Comment by gimsieke** [comment]
Since we ought to be able to use variables within the `@serialization` attribute, the question of avoiding redundancy (a potential reason for declaring a character map with `p:character-map`) shouldn’t arise. On the other hand, there is currently no way, neither `p:library` nor XSLT/XQuery import, for centralizing variable assignments. Maybe we should allow `p:variable` in `p:library`?

**Comment by ndw** [comment]
Per 11 June f2f, we don't need a character map element because it's part of the map of serialization parameters already.
