### ISSUE TITLE
Finesse the discussion of creating nodes with TVTs

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#398]
In 2.10.2 Text Value Templates, we say that TVTs can produce nodes. Make sure that the prose is coherent when the content type of the `p:inline` is, for example, "application/json".

**Comment by ndw** [comment]
Suppose that `$name` is bound to

```xml
 <name><f>Mary</f> <l>smith</l></name>
```
Are any of the following allowed? Are any an error?

1. The value is quoted:
```xml
<p:inline content-type="application/json">
  {{ "name": "{$name/node()}" }}
</p:inline>
```   
2. The value isn't quoted:
```xml
<p:inline content-type="application/json">
  {{ "name": {$name/node()} }}
</p:inline>
```
3. The value is quoted and the expression returns quotes:
```xml
<p:inline content-type="application/json">
  {{ "name": "{concat('"', $name/node(), '"')}" }}
</p:inline>
```

**Comment by xml-project** [comment]
After checking definition of p:parse-json() I would tend to think, that (2) and (3) will result in errors, because {"key" : "value"} is expected.

**Comment by ndw** [comment]
Ok. I'm going to try to make that more explicit in my PR for this issue.

**Comment by ndw** [comment]
See #426
