### ISSUE TITLE
Document the various flavors of cast-content-type

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#399]
We've discussed using it for
1. Making canonical `application/xml+rdf` documents
2. Casting HTML to XML via some parameterized mechanism (tidy, validator.nu, etc.)
etc.

**Comment by ndw** [comment]
Casting from JSON to XML

**Comment by ndw** [comment]
Now that p:load automatically makes XML out of HTML, is casting from HTML to XML still useful?
Is there a spec that describes "canonical" `application/xml+rdf` documents?

**Comment by ndw** [comment]
See also #373

**Comment by ndw** [comment]
I propose that this is overtaken as well.

**Comment by xml-project** [comment]
@ndw Since you are in charge for this issue: Close it in favour of #373 ?

**Comment by ndw** [comment]
Sure.
