### ISSUE TITLE
Legacy from 1.0: 3.3 Support steps with a dynamic number of ports 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#40]
# 3.3 Support steps with a dynamic number of ports 

>This is an aggregation of the discussion on "3.3 Support steps with a dynamic number of ports" ([Issue 47 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/47))

**Opened by: ndw on 2014-08-22, 18:38h**

## ndw said on 2014-08-22, 18:38h:

While most steps have a predetermined and static number of inputs and outputs, this is not universally the case. In XProc 1.0, a putative p:eval step which could run a dynamically constructed pipeline, for example, suffers from the limitation that the signature of the p:eval step usually differs from the signature of the evaluated pipeline. 

XProc 2.0 should provide a facility for supporting steps with a variable number of inputs and outputs. 

	On 2014-08-22, 18:38h: ndw added requirement should labels.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

**Comment by xml-project** [comment]
See https://github.com/xproc/3.0-specification/issues/46

**Comment by gimsieke** [comment]
see #97 (make dynamic evaluation a compound step)
We might consider closing this issue in favor of discussing `p:run`

**Comment by xml-project** [comment]
Yes, I think we can close this because #97 proposes a viable solution

**Comment by xml-project** [comment]
I think with #97 we have a viable proposal how to solve this. So I think we can close this.
