### ISSUE TITLE
The xpath-version attribute is no longer required

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#408]
Right?

**Comment by gimsieke** [comment]
Thank you for reporting this issue.
You will receive an answer within 48 hours. 
Do not reply to this comment.

**Comment by ndw** [comment]
WAT?

**Comment by gimsieke** [comment]
DO NOT ANSWER THE BOT SAID!!!1!

**Comment by gimsieke** [comment]
Yes, let’s remove it. It’s always 3.1 (unless we want to enable people to roll and declare their own versions, but I don’t think we want to let them)

**Comment by gimsieke** [comment]
(I was just trying to implement the new “react within 48 hours group policy”)

**Comment by eriksiegel** [comment]
NO, wrong. What if (ever) XPath 4.0 comes out and some implementer implements it and you want to switch to it. The fact that there is an xpath-version attribute now in XProc 1 means you can pop up the version to 2.0, othersie that wouldn't have been possible...
So I don't think we should remove it. Optional, default value 3.1.

**Comment by gimsieke** [comment]
I’d argue that if XPath 4.0 came out and were incompatible with XPath 3.1, the XProc version number itself needs to be increased.
If, on the other hand, XPath 4.0 was compatible with 3.1, it would suffice to let pipeline authors use `p:xpath-version-available('4.0')` in order to include conditional code that requires specific XPath 4.0 features.

**Comment by eriksiegel** [comment]
I think that choosing an XPath version must be a "conscious" decision. And when 4.0 cam out I would like to deliberately choose whether I want to use/enable features of it, not leave this to the processor.

Agreed, it will probably stay 3.1 for a loooong time, but I see no reason at all to change the choosing mechanism already present in XProc 1.0. Just leave /*/@xpath-version as it is now, default value 3.1, all processors *must* support this version. Whether a processor wants to support any other version is implementation dependent.

Simple mechanism, understood well, works well, why change?

**Comment by gimsieke** [comment]
I don’t know whether it works well. I doubt that any XProc 1.0 user has ever used it. 
On “why change”: Because the spec will be more compact and the implementers have less work determining the required version before raising an error. 
Btw, [`err:XD0027`](https://www.w3.org/TR/xproc/#err.D0027) seems to have vanished in the current spec. And: Can’t it be a static error?

**Comment by eriksiegel** [comment]
? I put an xpath-version="2.0" on *every* XProc stylesheet I write. As far as I'm aware, XPath 1.0 is still the prescribed default for XProc 1.0 and I need 2.0. But maybe that was unnecessary? (@ndw, @xml-project : What is the default XPath version of your processors?) 
Anyway, I think there must be mechanism to go to a newer XPath spec when (whenever) this arrives in a *controlled* fashion, not at the whim of the processor implementers. /*/@xpath-version is fine for that.

**Comment by gimsieke** [comment]
I was able to use XPath 2 functions without declaring the required XPath version both in Morgana and Calabash.

**Comment by xml-project** [comment]
This is because XPath 2.0 is default in XProc 1.0. If you want 1.0 or 3.0 you have to select it.
It would tend to agree with Eric: If there is an XPath 3.x or 4.x we run into a problem, so let us keep the attribute and say explicitly that XPath 3.1 is default.

**Comment by ndw** [comment]
Ok by me. Implementation wise, we don’t have a good story about varying the
expression language. But that can wait for 4.0 IMHO.

**Comment by xml-project** [comment]
Do we have a consensus on this? Keeping the attribute and saying explicitly, that XPath 3.1 is default.

**Comment by gimsieke** [comment]
I bet we won't ever need it in XProc 3.0 but I won't oppose keeping it.

**Comment by ndw** [comment]
I concur with @gimsieke

**Comment by xml-project** [comment]
@gimsieke I will not accept the bet, because I think you are probably right.

**Comment by xml-project** [comment]
@ndw Help needed: Which file used to generate the syntax after your revisions?

**Comment by ndw** [comment]
Sorry, @xml-project I'm not sure I understand the question. Which syntax?
1. The step declarations are generated from the markup in the spec.
2. The Relax NG grammars are generated from `src/main/schema/core30.rnc`

**Comment by xml-project** [comment]
@ndw Sorry, for being not clear enough: I was asking for answer (2).

**Comment by xml-project** [comment]
Fixed with pr #421
