### ISSUE TITLE
Legacy from 1.0: 3.4 Provide improved status information 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#41]
# 3.4 Provide improved status information 

>This is an aggregation of the discussion on "3.4 Provide improved status information" ([Issue 48 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/48))

**Opened by: ndw on 2014-08-22, 18:39h**

## ndw said on 2014-08-22, 18:39h:

XProc 1.0 provides scant support for reporting the status of a pipeline and providing aid to users attempt to debug pipelines. Implementation-defined extensions have demonstrated that some additional facilities, such as a p:message step, would be an aid to users. 

XProc 2.0 will add some mechanism for reporting status messages and will consider adding additional steps and/or language features to aid in analysing the behavior of a running pipeline. 

	On 2014-08-22, 18:39h: ndw added requirement should labels.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

	On 2015-06-11, 11:13h: ndw added the proposed-resolution label.

## ndw said on 2015-06-11, 11:13h:

Add a p:message step; absent concrete suggestions for other improvements, we'll leave it to implementors.

**Comment by xml-project** [comment]
See for proposed resolution: http://markmail.org/search/?q=xproc%20kraetke#query:xproc%20kraetke%20from%3A%22Kraetke%2C%20Martin%2C%20le-tex%22+page:1+mid:4r3afri7lusg64uk+state:results

**Comment by ndw** [comment]
Overtaken by #340
