### ISSUE TITLE
Option "serialization" on p:output is not inline with current discussion

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#427]
Since we agreed to be in line with fn:serialize(), it has to be map(*)

**Comment by ndw** [comment]
I don’t think we’ve applied our recent decisions about maps to the spec yet. I had some doubts about the current declaration of `document-properties` when I was working on `p:inline`, but I didn’t want to mix that discussion into the already complicated discussion of TVTs and inline.

**Comment by gimsieke** [comment]
Needs to be `map(xs:QName, item()*)`

**Comment by ndw** [comment]
Closed by PR #525
