### ISSUE TITLE
Are default pipeline inputs really worthwhile?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#438]
Consider:

```xml
<p:declare-step version="3.0" xmlns:p="http://www.w3.org/ns/xproc">
  <p:input port="source">
    <p:inline><doc/></p:inline>
  </p:input>
  <p:output port="result"/>
  <p:identity />
</p:declare-step>
```

That inline `<doc/>` only applies if there's no input provided for the `source` port. Does anyone actually do this? Would any kittens be harmed if we removed this feature?

It's really quite different from everything else. It’s weirdly challenging to implement, though I don’t consider that a motivation for removing a useful language feature. I’m just not sure this feature is very useful.

Consider also what you'd have to do if you wanted to save a "compiled pipeline". You'd have to carry the XML source and all its namespace contexts around in the compiled form.

I’m on the verge of proposing that we remove this dubious “feature”.

**Comment by xml-project** [comment]
> I’m on the verge of proposing that we remove this dubious “feature”.

What 'feature' are you talking about precisely? Is it just default connection with p:inline and implicit inline document or are you arguing against any default connection (also no p:empty and no p:document)?

**Comment by ndw** [comment]
I'm on the verge of arguing that default connections in p:input in p:declare-step are not worth the trouble. But I'm prepared to be persuaded that I'm mistaken. :smile:

**Comment by xml-project** [comment]
Proposal: Topic 2 for Thursday, unless someone has a nice knock-down argument.

**Comment by ndw** [comment]
Sounds like a plan.

**Comment by gimsieke** [comment]
We use it sometimes. In a larger transpect project, I found 15 `p:declare-step/p:input/p:inline`. Most of the occurrences seem to be sample pipelines, such as [this one](https://github.com/transpect/calabash-frontend/blob/master/xpl/xsd-sch-xsl.xpl).


[This one](https://github.com/transpect/calabash-frontend/blob/master/xpl/svrl2txt.xpl) contains an XSLT and a default Schematron document. 

Or [here](https://github.com/transpect/xproc-util/blob/master/store-zip/xpl/store-zip.xpl#L13)’s an empty Zip manifest.

If you consider not throwing away `p:inline` specifically in these declarations, but default connections on input ports in general:  We frequently use `p:document` to point to default, overrideable XSLTs or Schematrons. Example: https://github.com/transpect/docx2hub/blob/master/xpl/single-tree.xpl#L22

**Comment by ndw** [comment]
Nevermind. The particular case I was looking at came from the test suite. It was a pipeline with a single input that was defaulted. That seemed pointless. But as soon as you consider pipelines with more than one input, being able to default some of them makes perfect sense.
