### ISSUE TITLE
Non empty text nodes as siblings of implicit inlines

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#439]
Currently the [specs](http://spec.xproc.org/master/head/xproc/#err.S0079) says:

> It is a static error if comments or processing instructions occur as siblings of an element node that would be treated as an implicit inline.

According to the RNG-syntax text nodes are not allowed either, but we do not have an error for this.

Proposal: Change XS0079 to:

 It is a static error if comments, **non whitespace text nodes** or processing instructions occur as siblings of an element node that would be treated as an implicit inline.

**Comment by ndw** [comment]
:+1:

**Comment by eriksiegel** [comment]
Sorry, I don't get this. You mean that this is an error?
'<p:inline> <blah/></p:inline>`

Why?

**Comment by xml-project** [comment]
@eriksiegel No, your example is not an error. You have an explicit inline, while I was talking about **implicit** inlines, like
````
<p:with-input>
  <doc />
  <!-- comment -->
  <doc />
</p:with-input>
````
This has to be an error, because it is not clear, whether the comment is the last node of the first document or the first of the second. Therefore comment, processing-instructions and non-empty text nodes are not allowed as siblings of implicit inlines.
If you want comments, processing instructions before or after the root element, you have to use `p:inline`.

**Comment by eriksiegel** [comment]
Ok, get it. +1
