### ISSUE TITLE
Where do we say that processing-instructions are ignored

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#445]
In  err:XS0079 we say, that processing instructions are not allowed as siblings of implicit inlines.

But: Where do we say, that they have to be ignored in all other places? Both XMLCalabash and MorganaXProc do this, but I can not find this rule in the specs (neither 1.0 nor 3.0).

**Comment by eriksiegel** [comment]
I agree with Norm.

**Comment by xml-project** [comment]
I agree with Norm to, but I wonder whether we should state this rule somewhere in the specs, to prevent a processor from following another rule like:
I will raise an error for every processing instruction I do not understand.

**Comment by eriksiegel** [comment]
We don't have to. Its a basic XML thing. 

Analogy: We also don't specify that processors have to ignore XML comments...

**Comment by xml-project** [comment]
> Its a basic XML thing.

This is exactly my problem: I was not able to find this rule in the XML specification. Where to find it?

**Comment by eriksiegel** [comment]
Hmmn, you're right. https://www.w3.org/TR/xml/#sec-pi does not *explicitly* say "Ignore unless you recognize the PI" (and that's how I've always understood a PI, I suppose everybody?)

So yes, maybe a little reminder in the spec about this (although probably superfluous)?
