### ISSUE TITLE
Confusion about connecting inputs

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#446]
I think `err:XS0003` and `err:XS0032` are redundant.

* err:XS0003: It is a static error if any declared input is not connected.
* err:XS0032: It is a static error if no connection is provided and the default readable port is undefined.

The only way that a declared input _can_ be unconnected is if _both_ no connection is provided _and_ no default readable port exists.

I propose we remove one of them. Or someone explain how I’m supposed to tell them apart.

**Comment by xml-project** [comment]
Not looking at the error text, but on the position in the specs, where the errors are introduced, I concluded for XProc 1.0, that XS0032 is for _primary_ input ports, while XS0003 is for "normal" input ports. This interpretation is enforced by the tests in the XProc 1.0 test suite.

I think that the text of both messages are badly written: XS0003 mentions missing connections on an _input_ port, while XS0032 does only mention missing connects (which does also apply to options/variables).

For debugging purposes to me it makes sense to have different errors for primary input ports, which get auto-connected and other input ports, for which I have to supply a connection.

Proposal: Keep both errors, but change text of XS0032 to:

It is a static error if any primary input is not connected.

**Comment by ndw** [comment]
I'd like to leave the bit about the DRP in there because it's what distinguishes this case from the XS0003 case. How about

> It is a static error (err:XS0032) if no connection is provided for a primary input port and the default readable port is undefined.

Given that a primary input port *is* an input port, XS0003 would also apply, so if we want to keep them, we need to make the distinction as clear as possible. I think.

**Comment by xml-project** [comment]
> Given that a primary input port is an input port, XS0003 would also apply, so if we want to keep them, we need to make the distinction as clear as possible.

Yes, but in the 1.0 test suite you made a strong distinction between the two errors: A test that returns XS0003 for a secondary input for is marked as wrong, because XS0032 is explicitly required.

I remember that well, because it took me a day or so to figure out the problem. Solving it was easy.

**Comment by ndw** [comment]
Fair enough.

**Comment by ndw** [comment]
I don't think there's any more to do here.
