### ISSUE TITLE
Legacy from 1.0: 3.10.1 Additional steps and enhancements: p:zip and p:unzip 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#45]
# 3.10.1 Additional steps and enhancements: p:zip and p:unzip 

>This is an aggregation of the discussion on "3.10.1 Additional steps and enhancements: p:zip and p:unzip" ([Issue 54 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/54))

**Opened by: ndw on 2014-08-22, 18:42h**

## ndw said on 2014-08-22, 18:42h:

The vocabulary of steps available in XProc is extensible. Users and implementors have developed additional steps. For example, to support pipelines that produce EPUB documents or manipulate files on disk. It is worth considering which, if any, new steps should be elevated to the XProc namespace. The candidates include, but are not limited to: 

p:zip and p:unzip 

	On 2014-08-22, 18:42h: ndw added requirement should labels.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

	On 2015-06-11, 13:01h: xquery added the steps label.

**Comment by gimsieke** [comment]
Also extend the [current EXproc specs for pxp:zip and pxp:unzip](http://exproc.org/proposed/steps/other.html) with the ability to extract a whole archive to disk (plus an option whether existing files should be overwritten / the extract directory be removed beforehand) and to create an archive from a URI of a file or directory.

**Comment by gimsieke** [comment]
See https://github.com/xproc/steps/issues/3 and https://github.com/xproc/steps/issues/4 for generic archive/unarchive step requests

**Comment by ndw** [comment]
Closing 45, over taken by 3 and 4 above.
