### ISSUE TITLE
XS0037 vs. xs0044

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#450]
Currently XS0037 says:

> It is a static error (err:XS0037) if any step directly contains text nodes that do not consist entirely of whitespace.

Is there a reason for the restriction to _step directly_? Consider
````
<p:identity>
  whitespace1
  <p:input port="source">whitespace2 
````
'whitespace1' raises XS0037, while 'whitespace2' has to be XS0044 (in lack of a bettet one).

I think this makes lexing difficult and adds no value to authors.

**Comment by ndw** [comment]
I'd accept a PR that made XS0037 broader. Maybe something like "It is a static error if any element in the XProc namespace contains non-whitespace characters where they are not allowed." But better. :-)

**Comment by xml-project** [comment]
What about:

> It is a static error if any element in the XProc namespace (other than p:inline) or any user defined extension step directly contains text nodes that do not consist entirely of whitespace.

**Comment by xml-project** [comment]
Or (perhaps better):

It is a static error if any user extension step or any element in the XProc namespace other than p:inline directly contains text nodes that do not consist entirely of whitespace.

**Comment by ndw** [comment]
:+1:
