### ISSUE TITLE
Introduce a file system path → URI normalization function?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#451]
In the light of the discussions in #325 and #449, I’d like to propose a function `p:urify()` as described in https://github.com/xproc/3.0-specification/issues/325#issuecomment-374000201.

It should basically convert file system paths to `file:` URIs.

This function is useful because users often like to submit file system paths instead of URIs as options, while most steps with an `href` or similar option only accept URIs.
The issue has become more pressing because with #449 we introduced space-separated `href` values. When heuristically accepting file system paths instead of proper URIs, a processor must not interpret spaces in the argument as part of the (file system) name. Instead, each space must be regarded as separating (possibly relative) URIs. 
We should exonerate users from the burden of percent-escaping, `file:`-prepending, … file system paths.

`p:urify()` should by and large be idempotent if the argument is already recognized as an absolute URI. It could, however, perform additional normalizations on URIs such as eliminating consecutive duplicate slashes or, if the argument is determined to represent a directory, append a trailing slash.

When passing user-supplied paths to a step that accepts space-separated URIs, a pipeline author could just apply `p:urify` to the paths:

```xml
  <p:document href="{$paths ! p:urify()}"/>
```

(assuming that a sequence of URIs will be flattened to a space-separated string that is then tokenized and each token is cast as a URI). 

Relative paths should be resolved to the current working directory (as currently returned by [`pos:info`](http://exproc.org/proposed/steps/os.html), not to the pipeline’s base URI. 

Path separators should be interpreted as per the system property reported by `pos:info`, with the exception that if the separator is reported as `\`, `/` should also be interpreted as a separator.

We have implemented a similar function as a step, [`tr:file-uri`](https://github.com/transpect/xproc-util/tree/master/file-uri/xpl/file-uri.xpl). It does a bit more than the suggested function, namely optional catalog resolution and optional retrieval of HTTP resources (stored in a temporary directory). It returns an XML structure with the local URI, the current working directory, the last path component, etc. 

I see some value in having a function though because it can be used in AVTs and XPath expressions in general, without the need to insert another step into the subpipeline. 

It would still be nice to be able to use a catalog resolver even for URIs that don’t refer to XML resources. Maybe `p:urify()` can accept an optional parameter map that provides implementation-defined functionality, such as `{ 'use-xml-catalogs': true(), 'fetch-http': true() }`.

**Comment by eriksiegel** [comment]
Like Gerrit, I've written these kinds of functions many times in my XSLT and XQuery programs. So yes, good idea.

**Comment by ndw** [comment]
:+1:

The name `p:urify()` doesn't fill my heart with joy, but we can fuss about that later.

**Comment by gimsieke** [comment]
It's a bit of a p:un, but we can certainly agree on a different name, such as p:file-uri

**Comment by ndw** [comment]
🤦‍♂️ I totally didn’t see ‘p:urify’. That is good. 😆

**Comment by ndw** [comment]
Some examples:
* c:\path\to\file => file:/c:/path/to/file
* \\hostname\path\to\file => file://///hostname/path/to/file
* probably others

**Comment by eriksiegel** [comment]
a b ==> a%20b

**Comment by gimsieke** [comment]
Spec this out (as an operation from a string to a string)

**Comment by dmj** [comment]
Documents to consider:
- [RFC8090 "file" Scheme](https://tools.ietf.org/html/rfc8089), include Appendix D
- [File URIs in Windows](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/)

**Comment by gimsieke** [comment]
A draft is at https://github.com/xproc/Workshop-2018-09/blob/master/p_urify/p_urify.xml
Here’s an [HTML rendering](https://htmlpreview.github.io/?https://github.com/xproc/Workshop-2018-09/blob/master/p_urify/out/xhtml/p_urify.xhtml)

**Comment by gimsieke** [comment]
Will add examples and an XSLT implementation soon.

**Comment by gimsieke** [comment]
Since Java 1.7, there is the `java.nio.file.Path` interface with really convenient normalization and URIfication methods. Therefore I think I will make the spec less detailed just in case it stipulates things that the library functions do differently. Maybe I’ll make it implementation-dependent, with just some basic stipulations that non-file: URIs be passed unchanged, and that a literal space character in purported-yet-invalid file: URIs should not raise an error, but should be escaped instead.
I created [this sample implementation](https://github.com/xproc/Workshop-2018-09/blob/master/p_urify/test.java) that I think does the job already sufficiently well. I will add some test cases later today.

**Comment by gimsieke** [comment]
A note on Windows: Creating files and directories with UTF-8 multi-byte chars on Windows is easy, but passing them to Java on the command line (processing command line arguments is the primary use case for `p:urify()`) turned out to be pretty hard. Luckily, there is a solution with recent Windows 10 releases.
https://stackoverflow.com/questions/7660651/passing-command-line-unicode-argument-to-java-code/53995490#answer-53995490
Please do also note the `-Dsun.jnu.encoding=UTF-8` setting that I needed to supply to XML Calabash in addition to changing the Windows locale to UTF-8. I have looked at Calabash’s code but did not see a place where this additional mojibake might be introduced.
