### ISSUE TITLE
Re-instate static variables as solution for the "variable in prolog" problems?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#452]
I was going over the use cases I had for wanting variables in the prolog. And most of them (if not all) were relatively simple cases of wanting to declare/define things only once and/or use a descriptive name for something. Computation using run-time-available-only values (like options) are, for me, *not* in scope.

So my thoughts went to: Why don't we re-instate the idea of static variables (like XSLT has, see also https://github.com/xproc/3.0-specification/issues/138) with the following semantics:

- Static variables *must* (of course) be compile-time computable (whether an implementation really does this at compile time or by lazy evaluation at run-time is of course implementation defined). So no references to options, ports, etc. Only to other static variables.
- Variables in a step prolog and as global library variables are allowed to be static *only*. You *must* specify `static="true"` (or whatever syntax). 
- Because of the static nature of the variables we might (not sure) redo the content model of a p:declare-step back to "mix everything"?

Yes, this a p:constant in disguise. But I don't mind, it solves what I want these prolog variables for. As a nice side effect it makes the `@use-when`  much more useful. And it sounds more easy to implement???

Very interested whether this would solve @gimsieke 's use-cases.

**Comment by xml-project** [comment]
Sounds reasonable to me, but I am not sure, I understood all problems involved.
Let's see, what @ndw thinks about this.

**Comment by ndw** [comment]
Yes, I think that would solve the problems as I understand them. I was thinking about this use case last night:

```xml
<p:declare-step …
   <p:variable name="foo" …

   <p:declare-step …
      <p:variable name="bar" select="$foo"/>
```

And I was going to try to convince y’all that we absolutely *had* to require `foo` to be static in this case. 

I think the content model [we described](https://github.com/xproc/3.0-specification/wiki/XProc-3.0-editorial-team-minutes,-12-July-2018) is fine.

We add the rule that only variables declared as static may be referenced in `p:input`,
`p:output`, `p:declare-step`, and other variables declared as static.

I’m spending the rest of the day on an airplane, I’ll try to think it through more carefully.

BTW, I don’t know if we discussed it, but I am assuming we all agree that variable declarations in a `p:library` have to be static. Whether they’re declared as static or not, you can’t _see outside_ the `p:library`.

**Comment by ndw** [comment]
I'm pleased to report it only took me an hour or so to support this pipeline:

```xml
<p:declare-step version="3.0" xmlns:p="http://www.w3.org/ns/xproc" name="main">
  <p:variable name="p1" static="true" select="'x'"/>
  <p:variable name="p2" static="true" select="'ml'"/>
  <p:variable name="method" static="true" select="concat($p1,$p2)"/>
  <p:input port="source">
    <p:inline><doc>this is my doc</doc></p:inline>
  </p:input>
  <p:output port="result" serialization="map { 'method': $method }"/>
  <p:identity/>
</p:declare-step>
```
I'll work on writing up the spec changes to introduce static and the restriction that only static variables may occur in the prologue.

**Comment by xml-project** [comment]
@eriksiegel I see your point with XSLT and I think it is important. 
But the signature of static and (dynamic) variables are quite different in XProc. Most of the option on p:variable do not make sense on static variables. And they do not have a document binding.
So preventing authors from mistakes may be another argument.

**Comment by ndw** [comment]
Well...RELAX NG can distinguish between them by the presence of static=true. In fact, I was noodling with the schema last night while waiting for my bags to arrive. (Hello from cooler up state New York, btw.)

And I think most of the options are possible on a static variable. Consider:

```xml 
<p:variable name=“foo” 
   as=“document(element(things))+”
   static=“true”
   collection=“true” expand-text=“false”
   exclude-result-prefixes=“a b c”>
     <p:inline><things/></p:inline>
     <p:document href=“thing1.xml”/>
     <p:document href=“thing2.xml”/>
</p:variable>
```

I haven’t used `@select` but clearly we need that. I think the only thing you can’t do from a static variable is use `@pipe` and `p:pipe`. I’m not sure a different element for that small exclusion is really going to be easier to understand/explain. And we can forbid it with RELAX NG for syntax directed editors.

If we *do* need two names, I’d opt for something short like `p:static` or `p:constant` over `p:static-variable`.

**Comment by xml-project** [comment]
Sorry, my comment was a bit premature without what you will actually come up with. If static variables can have bindings (I was not aware of that).
