### ISSUE TITLE
Revert multiple URIs in @href on p:document?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#453]
Multiple URIs on p:document was a workaround for dynamic variables in @href on p:input.

Now that we don't have that, I propose that we make the @href attribute on p:document a single URI again.

That will avoid the complication of multiple URIs which have to share the same properties.

**Comment by ndw** [comment]
Any objections?

**Comment by gimsieke** [comment]
I don’t object to it

**Comment by ndw** [comment]
Done.
