### ISSUE TITLE
Evaluation of default inputs

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#454]
Consider this pipeline:
```xml
<p:declare-step version="3.0" xmlns:p="http://www.w3.org/ns/xproc" name="main">
  <p:input port="source">
    <p:document href="/this/uri/does/not/exist"/>
  </p:input>
  <p:output/>
  <p:identity/>
</p:declare-step>
```
If a document is provided at runtime for the source port, there are several possibilities:
1. The default value is not evaluated (the implementation is forbidden from doing so).
2. The default value is evaluated, but the error is suppressed
3. The default value may be evaluated (implementation dependent), but if it is, the error is suppressed
4. The default value is evaluated and the error is thrown

I propose that the spec should mandate option 1.

**Comment by xml-project** [comment]
I think (1) is plausible for p:document, because resource's existence may change from run to run.

But what about:
````
<p:declare-step>
  <p:input port="source">
    <doc>{$i-am-no-declared}</doc>
  </p:input>
  ...
</p:declare-step>
````
Here I would opt for (3), so the implementation _can_ give the author a hint, that this pipeline will never run without a document provided at runtime.

So may be the rule should be: A processor is free to evaluate (unused) default connections, but it is not allowed to raise an error, unless it is used.
I think the same rule may hold for default values on p:option.

**Comment by eriksiegel** [comment]
??? As a user, Looking at the first (Norm's) example: 

- When the source port is not connected and the processor is forced to fallback to the default provided by p:document, and this document does not exist, I surely would expect an error... 
- But when the source port *is* connected I couldn't care less whether the document referenced by p:document actually exists, I would expect no error.

So, @ndw, Is your list of options in the first comment applicable to the static analysis phase only? In that case +1

**Comment by ndw** [comment]
@xml-project : At “compile time”, the processor has no idea whether or not an input will be provided. I think absence of a static declaration for `$i-am-no-declared` should always be a static error.

@eriksiegel : If the default input is used, then yes, you’d get an error. My point is that in your second bullet, I think you *do* care: you don’t want dynamic errors in the default input to interrupt your pipeline.

Mostly, I’m just observing that we need to make this explicit in the spec.

**Comment by xml-project** [comment]
@ndw:

> At “compile time”, the processor has no idea whether or not an input will be provided. 

Obviously I know that.

> I think absence of a static declaration for $i-am-no-declared should always be a static error.

In an other conversation you argued, that an error is only to be raised, if the respective construct is used. So my example wouldn't be an error, if a connection for the input port is provided.

Since this point comes up over and over again and I fail to understand your general line of thought regarding errors, I think we should try to have a general rule on dynamic errors in the specs.

> The default value is not evaluated (the implementation is forbidden from doing so).

I do not agree with this as a general rule because (1) I have no idea how you want to test compliant behaviour for this rule and (2) I think a processor should be free to gather as much information as it like to inform authors on request.

**Comment by ndw** [comment]
Let’s have a discussion about errors on the next call. I don’t think a missing variable declaration is a dynamic error. I think it’s a static error and I think I’ve consistently argued for reporting all of them.

Re: (1) the test for compliant behavior would be to have a 404 in p:document but pass an input to the pipeline. Re: (2) there’s nothing that says the processor is forbidden from issuing warnings or having a switch that enables some non-conformant mode that reports anything you like. Heck, you can print warnings even in a conformant mode, what you can’t do is report the 404 and abort the pipeline execution or raise an exception.

Apologies if that’s not clear.

**Comment by xml-project** [comment]
Sorry, I was not to find the static error for undeclared variable you mentioned in the specs for TVTs:
Currently we only have

> It is a dynamic error (err:XD0050) if the XPath expression in an AVT or TVT can not be evaluated.

I like the your idea of having the general problem as a topic on next call. Given your (re: 2) in your last comment, I am not sure I still understand the differences between alternatives (1)-(3) in your initial post.

**Comment by ndw** [comment]
Let's take a slightly different example, since the error is just one kind of side effect.

```xml
<p:declare-step version="3.0" xmlns:p="http://www.w3.org/ns/xproc" name="main">
  <p:input port="source">
    <p:document href="https://example.com/hitcounter"/>
  </p:input>
  <p:output/>
  <p:identity/>
</p:declare-step>
```
Imagine that "example.com/hitcounter" keeps track of how many GET requests have been made on that URI and has some out-of-band way of reporting that information. Assume that when I run the pipeline, I pass in a document for the `source` port. Because I've passed in a binding for `source`, its that binding that will flow through the pipeline *not* the results of the hitcounter.

* Option 1 says default value must not be evaluated by the processor. The hit counter will not be advanced. If the service is down, no one will know because the URI will never be accessed.
* Option 2 says the default value will be evaluated. The hit counter will be incremented. But if the service is down, the error that arises must be suppressed. No exception will be raised in the pipeline.
* Option 3 says that it's implementation dependent whether or not the default value gets evaluated. Maybe the hit counter goes up, maybe it doesn't. But if the service is down, the error is suppressed.
* Option 4 says the default value is always evaluated and raises an exception if it fails.

Option 4 is silly. It's there for logical completeness.

I really think option 1 is the only sensible answer, but it does put a burden on implementations to evaluate default inputs lazily and not, for example, at compile time.

**Comment by ndw** [comment]
Consensus on 26 July 2018: option 1. (Achim, Gerrit, Norm.)
