### ISSUE TITLE
Require select on p:option

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#461]
A while back we decided that the default value for `p:option` values would be `()` if no default was provided. This allowed us to get rid of a fair bit of complexity and at least one extension function.

I propose that if we are going to say every option has a default value, we make the `select` attribute required and force users to specify it rather than defaulting silently to `()`

**Comment by xml-project** [comment]
+1
I do not remember what was the reason behind making "@select" optional.

In the current specs "@select" is required and I agree with you to keep it required.

**Comment by ndw** [comment]
It isn't currently required on option declarations (because it used to be possible to have options that had no value).

I'm going to post a big PR later this morning, I'll add this change to it.

**Comment by eriksiegel** [comment]
@ndw, why the requiredness of `@select`?  I think silently defaulting to `()` is perfectly acceptable *and* the XSLT way also.

**Comment by eriksiegel** [comment]
And anyway, a default value for a required option makes no sense, or do I miss something?

**Comment by ndw** [comment]
Required and defaulted is a static error.
I'm not going to lie down in the road over whether or not `()` should silently be the default. I'll leave it that way as it's the status quo.

**Comment by ndw** [comment]
I suppose, btw, there's no reason to require a `select` attribute on static options either, the default can be the empty sequence too.
