### ISSUE TITLE
Edit section "Extension Steps"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#468]
The first sentence of section "[Extension step](http://spec.xproc.org/master/head/xproc/#p.extension)" currently is:

> Pipeline authors may also have access to additional steps not defined or described by this specification. Atomic extension steps are invoked just like standard steps ...

I wonder if it makes sense to be a bit more elaborate here because this section not only applies to the minor case of build-in processor extensions but also to the IMHO much larger use case of calling steps declared by pipeline authors with `p:declare-step`.

**Comment by ndw** [comment]
Sure. Go ahead and propose something more complete.

**Comment by xml-project** [comment]
Will do!

**Comment by gimsieke** [comment]
Also consider the comments in #635 about regrouping the current “atomic steps” and “extension steps” sections and adapting the prose in Sect. [17.5](http://spec.xproc.org/master/head/xproc/#p.declare-step). In 17.5, there is currently a distinction between “atomic steps” (in the sense of processor-implemented standard steps) and “pipelines” (user-defined steps written in XProc). The distinction should follow the proposed new distinction in 16.8.

Proposal for regrouping 16.8 and 16.9. (thereby eliminating 16.9):

**16.8 Atomic Steps**
**16.8.1 Processor-Implemented Standard Atomic Steps**
All atomic steps whose type is in the XProc namespace and whose declarations don’t have a subpipeline

**16.8.2 Standard Atomic Steps Written in XProc**
There aren’t any yet. This section will only be included if we decide to pursue this way.

**16.8.3 User-Defined Atomic Extension Steps**
Declaration with subpipeline, namespace not XProc, need to be imported.

**16.8.4 Atomic Processor Extension Steps**
Declaration without subpipeline, namespace not XProc. Whether they need to be imported (or which need not be imported, like the EXProc steps in 1.0 for certain processor versions, I believe) is implementation-defined.

**16.8.5 Atomic Step Errors**
XS0010, XS0044, XS0048, XD0010

**Comment by ndw** [comment]
Clarify: steps in the XProc namespace do not have to be imported, everything else does.
