### ISSUE TITLE
Legacy from 1.0: 3.10.4 Additional steps and enhancements: semweb steps 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#47]
# 3.10.4 Additional steps and enhancements: semweb steps 

>This is an aggregation of the discussion on "3.10.4 Additional steps and enhancements: semweb steps" ([Issue 57 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/57))

**Opened by: ndw on 2014-08-22, 18:43h**

## ndw said on 2014-08-22, 18:43h:

The vocabulary of steps available in XProc is extensible. Users and implementors have developed additional steps. For example, to support pipelines that produce EPUB documents or manipulate files on disk. It is worth considering which, if any, new steps should be elevated to the XProc namespace. The candidates include, but are not limited to: 

Semantic web steps (p:sparql, p:rdfa, ...)? 

	On 2014-08-22, 18:46h: ndw added requirement should labels.

	On 2014-08-25, 22:28h: ndw added this to the XProc 2.0 LC milestone.

	On 2015-06-11, 13:01h: xquery added the steps label.

**Comment by ndw** [comment]
Replaced by https://github.com/xproc/steps/issues/10 and https://github.com/xproc/steps/issues/11
