### ISSUE TITLE
Scoping of static variables and options

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#473]
On yesterdays call we agreed to the following rule, proposed by @ndw:

> [...] a simple rule: only static references
within the attributes and descendants of p:input, p:output, and other
variables and options declared to be static.

I think thats a clear story to tell, however we need to add some further explanation:

Consider:
````
<p:declare-step>
  <p:option static="true" name="uri" select="'http://some-uri'" />
  <p:input port="source" href="{$uri}" /> <!-- it is clear, that this should work -->

  <p:declare-step type="foo:bar">
    <p:input port="source" href="{$uri}" />  <!-- (2) -->
</p:declare-step>
````
Does `foo:bar`inherit the static scope (variables and options) of the outer step, viz. is (2) valid? 
I think it should be and I see no obstacles to it. IMHO we should says something about the scope of static variables/options. [Currently](http://spec.xproc.org/master/head/xproc/#initiating) we just say

> The in-scope bindings are limited to the lexically preceding, statically declared options and variables.

**Comment by ndw** [comment]
I agree, (2) should be valid. There's no reason that *static* bindings can't be visible inside child `p:declare-step` elements. The same is true of static preceding `p:variable`s in a `p:library`, one assumes.

**Comment by xml-project** [comment]
> The same is true of static preceding p:variables in a p:library, one assumes.

I would expect this too.

**Comment by xml-project** [comment]
see issue #454

**Comment by xml-project** [comment]
Could somebody please remind me what to do here (and/or a why this issue was assigned to me).

**Comment by xml-project** [comment]
Since no one seem to remember what to do here. Close it and see, if it pops up again?

**Comment by ndw** [comment]
Sure.
