### ISSUE TITLE
Lazy evaluation of variables and options (how far do we go?)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#478]
There seems to be a silent consensus, that the specs should not restrain lazy evaluation of variables and options (static as well as dynamic). This means that a processor is not required to evaluate an XPath expression of any variable/option and check whether its type is correct unless the value is actually *used*. 
It does also imply, that a dynamic error associated with the `@select` or `@as` is not raised, before the variable/option is actually used. Having a clear rule on this is important, because the pipeline author needs to know, where to put `p:try`- `p:catch` if she wants to catch the error.

Now I wonder *how* lazy we are or what actually constitutes the *use* of a variable. Consider: (1)
````
<p:declare-step>
  <p:option name="option" select="$undeclared-ref" />
  <p:output port="result" />
  <p:identity>
    <p:with-input><doc /></p:with-input>
  </p:identity>
</p:declare-step>
````
Since `$option` is never used, the processor is not required to evaluate the value of `$option`. Therefor  this pipeline will not raise an error, but produce `<doc />`.
Now let us look at (2):
````
<p:declare-step>
  <p:option name="option" select="$undeclared-ref" />
  <p:option name="option1" select="$option" />
  <p:output port="result" />
  <p:identity>
    <p:with-input><doc /></p:with-input>
  </p:identity>
</p:declare-step>
````
One might argue, that in `@select` of `p:option1`  the value of `$option` is used, so a dynamic error should be raised. **But:** Since `$option1` is not used, the processor is not required to evaluate the XPath expression and therefor might never discover, that `$option1` refers via `$option`do an undeclared variable. So given lazy evaluation, what hold for one option/variable holds for all. Pipeline (2) will also produce `<doc />`. Now (3)
````
<p:declare-step>
  <p:option name="option" select="$undeclared" />
  <p:option name="option1" select="$option" />
  <p:output port="result" />
  <p:add-attribute match="/doc" attribute-name="att" attribute-value="$option1">
    <p:with-input><doc /></p:with-input>
  </p:p:add-attribute>
</p:declare-step>
````
has to raise an error, because it is required to evaluate `$option1`: When the processor tries to execute `p:add-attribute` it has to evaluate `$option1` and as a consequence `$option`. (BTW: It will be a quality of implementation feature to give the right hint to the user, where to find the error cause. "$option1 can not be evaluated because it refers to an undeclared variable/option $undeclared" would almost certainly result in some debugging problems.)

Is this something we can agree on?

**Comment by ndw** [comment]
I don't think lazy evaluation should defer static analysis. I think all of those pipelines have a static error because of the undeclared variable.

I agree that you can't determine if an expression returns the right type, and if you don't need the variable you might never detect the type error. I also think a processor should be allowed to raise the invalid type error statically if you put

    <p:variable name="whatever" as="xs:double" select="concat('a','b'')"/>

in your pipeline.

**Comment by xml-project** [comment]
(1) So if you talk about lazy evaluation it does not include static analysis of the expression, right? I would agree with this.
(2) Currently we have no static XProc error saying: The XPath expression s has a static error. We need to introduce one.
(3) I am not sure concerning the invalid type as a *static error* in your example: Static typing in XPath is an [optional feature](https://www.w3.org/TR/xpath-31/#id-xpath-static-typing), so depending an the used (version of) the XPath processor, you get either a static or (a catchable) dynamic error. I would argue for interoperability reason, it has to be a dynamic error.

**Comment by xml-project** [comment]
BTW: It is a dynamic error (err:XD0049) if the sequence type is not syntactically valid.
Shouldn't we make this error static?

**Comment by ndw** [comment]
Created PR #502 to resolve points (1) and (2).

I'm not saying it's a static error in (3); I'm saying that it's among the classes of dynamic errors that a processor may report statically if it determines that it will always occur.

**Comment by xml-project** [comment]
Referring to variables not in-scope is just one case of a statically invalid XPath-expression. (e.g. containing statically unknown functions/namespaces apart from general syntactic muddle.
I think having a special error code for variables is right, but I still think we need another error for the other cases, don't we.
