### ISSUE TITLE
Context item on Syntactic shortcuts for option values

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#480]
While explaining syntactic shortcuts for option values, we [say](http://spec.xproc.org/master/head/xproc/#option-shortcut):

> If the option value includes curly braces, it is treated as an attribute value template. The context node for attribute value templates in an option shortcut value comes from the default readable port for the step on which they occur.

But in explaining attribute value templates, we [say](http://spec.xproc.org/master/head/xproc/#dt-attribute-value-template.):

> Each expression is evaluated with an undefined context node.

Although there might be use cases for option shortcuts which rely on the context item, I think the general rule "AVTs are evaluated with an undefined context node" is easy to memorise. Binding options with reference to the context item therefor needs to be done with `p:with-options`.

Proposed resolution: Remove "The context ... occur." from the quoted section on option shortcuts.

**Comment by xml-project** [comment]
It is not that easy, because we also use AVT on XProc elements, like `@href` on `p:input` where we do not have a default readable port. 
If we want to have a context item on syntactic shortcuts, we need to say in which cases there is a context item and in which cases the context item is undefined. This would be hard to memorise.
This is why I am arguing for a simple rule.

**Comment by gimsieke** [comment]
I suspect that instead of memorizing simple rules, people expect that they may set `foo="{.}"`, given the previous step’s  primary output, `<c:result>bar</c:result>`, instead of being forced to use `<p:with-option name="foo" select="."/>`. 
The default readable port [is already allowed to be undefined](http://spec.xproc.org/master/head/xproc/#dt-default-readable-port), so referring to context in an AVT where the DRP is undefined should raise a dynamic error. Therefore a reference to [err:XD0026](http://spec.xproc.org/master/head/xproc/#err.D0026) should be added to the AVT section, in order to make the raised error more specific than [err:XD0050](http://spec.xproc.org/master/head/xproc/#err.D0050).

If we change this for AVTs, we should also change it for TVTs.

**Comment by xml-project** [comment]
I do not want to speculate about what people might expect. I am just saying, that we have to come up for those cases of AVTs where the notion of a DRP, you used in your suggestion, is not even defined.

**Comment by xml-project** [comment]
Here is a (possibly not complete list of use cases of AVT in the current syntax, where the context item is undefined according to the current specs. The once where the notion of a DRP is not defined, are marked as bold.

- match on p:viewport (DRP possibly present)
- collection on p:when (DRP possibly present)
- collection on p:if (DRP possibly present)
- **href on p:input (DRP not defined)**
- href on p:with-input (DRP possibly present)
- **href on p:output (DRP not defined)**
- collection on p:variable (DRP possibly present)
- **href on p:variable (DRP possibly present for non-static variables, not defined for static variables)**
- href on p:with-option (DRP possibly present)
- **href on p:document (DRP not defined if it is a child of p:input, p:output and p:variable [static], possibly present if it is a child of p:with-input, p:with-output or p:variable [non-static]**

Do we want to allow reference to the context item whenever the DRP is possibly present?

**Comment by xml-project** [comment]
For text value templates I think the rule is pretty easy, since they can occur as a child of p:inline only: "The XPath expression in the TVT is evaluated with the DRP as context item if the p:inline is not a child of p:input, p:output or a p:variable marked as static."
But I am not able to figure out an easy rule for AVTs. Perhaps we should say:
"The variable parts of the AVT are evaluated with the DRP as context item unless the AVT appears on elements where no DRP is defined." And we could then having a static error for those cases, where no DRP is defined and reserve XD0026 (which was proposed by @gimsieke ) for those cases, where a DRP is defined, but not present.
XS???? It is a static error if the XPath expression in a variable part of an attribute value template or in a text value template makes reference to the context item when the default readable port is not defined.

**Comment by xml-project** [comment]
For resolution see #482 . If leave this open because the contradiction in the current specs noted in my first comment still needs to be resolved.

**Comment by ndw** [comment]
👍

**Comment by ndw** [comment]
I added your observation to #482 so that we can close this issue.
