### ISSUE TITLE
Describe context node for p:document and p:inline

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#482]
Per discussion on 9 Aug:

The p:inline and p:document elements establish a context node from the default readable port (if there is one). This context node is used for descendant AVTs and TVTs. It is not a static error if there is no DRP, it simply establishes that there's no binding for the context (and it will be a dynamic error to refer to it).

It is a static error to refer to the context in expressions that appear where no default readable port is possible (for example, on p:declare-step, p:library, p:input, and p:output).

**Comment by xml-project** [comment]
Just to be sure, I know what to do:

In a number of place we say, that a connection to the drp is made only if no explicit document connection is provided. This has changed now, because the connection is now also made, if a document connection is provided with p:document and p:inline, but not for p:pipe and p:empty. Right?

So this:
````
<p:identity name="a">
   <p:with-input><doc /></p:with-input>
</p:identity>

<p:identity name="b">
  <p:with-input><p:document href="something" /></p:with-input>
</p:identity>
````
is not a static error, because the output port of step `a` is connected to step `b`, but changing `b` to
````
<p:identity name="b" pipe="x@y" />
````
is an error, because output port "result" of step `a` is unbound. Right?

What about:
````
<p:identity name="a">
   <p:with-input><doc /></p:with-input>
</p:identity>

<p:count limit="1">
  <p:with-input><p:empty /></p:with-input>
</p:identity>
````
It is again NO static error because the primary output port of `a` is bound to p:count to provide the context item for the XPath expression in p:option. Right?

**Comment by ndw** [comment]
Output ports don't have to be bound. In your second example, where `pipe="x@y"`, the output port of "a" simply pours onto the floor. It's only an error for *input* ports to be unbound.

**Comment by xml-project** [comment]
Sorry, wrong word: It's not "bound", but "connected". I tried to figure out the consequences of our decision for 

> The primary output port of a step must be connected to some consumer. It is a static error (err:XS0005) if the primary output port of any step is not connected.

The examples were to demonstrate, that now a p:inline, a p:document, an attribute value short cut and a p:option count as connection for the primary output port of a previous step.

Sorry for being not so precise that my examples are understandable.

**Comment by ndw** [comment]
No, my fault, not yours. I forgot about err:XS0005.

So the question is, does a connection to a p:inline or p:document count as a binding for the purposes of XS0005? I don't know what I think the right answer to that question is, off the top of my head.

**Comment by xml-project** [comment]
I think it might be a consequence of saying that a p:inline or a p:document get their context item from the default readable port (which is in most of the cases the primary output port of the previous step).

And probably it is the one which aligns yesterdays decision about TVTs and the AVT on p:document with the current terminology of the specs.

**Comment by ndw** [comment]
I agree. But we *could* (I'm not advocating for, just saying we could) write the spec such that connections to p:inline/p:document didn't count as connections for the purpose of deciding if the primary output port was connected.

Pro: my guess is that users won't really be thinking about the connections to p:inline/p:document. Most often, there won't be any AVTs or TVTs so there will be no reason to think about it. When there are AVTs/TVTs, they will "just get" the behavior they expect and again won't really be thinking about it. So by ignoring those connections for the purpose of XS0005, we'll have more consistent behavior. Changing a p:document to a p:pipe won't suddenly raise a static error, instead the static error will always be present so they'll have to fix it with a p:sink or something.

Con: it's another rule, it's possibly a little more complicated to explain.

**Comment by xml-project** [comment]
I completely agree with your analysis of the Pro's. This is why I was against a context item for TVTs.

Additional argument for counting it as a connection: To my reading it is the only (plausible) way to make @gimsieke 's request work. Consider: (yes, the example is silly, but its the easiest way to make my point).

````
<p:identity step="a">
  <p:with-input><doc a="some-url" /></p:with-input>
</p:identity>

<p:identity step="b">
   <p:with-input>
      <p:document href="{./doc/@a}" />
   </p:with-input>
</p:identity>
````
So the primary output port of (a) is the default readable port and is takes as context item for the AVT on p:document (or of a possible p:inline). 

If this does not count as connection for the primary output port of a, this example would result in XS0005, right?

The only possibility to avoid this error would be a p:sink between (a) and (b), right?

But then the default readable port for (b) is never present because it is consumed by p:sink, so we will never ever will have a default readable port (or context item) for TVTs or the AVT on p:document.

**Comment by xml-project** [comment]
Random thought:
TVTs and the AVT on p:document do not have a context item, but can use a function `p:name-to-be-invented(step-name, port-name)` to establish a connection to any readable port.

BTW: If we follow yesterdays decision we have to consider creating a new dynamic error when the DRP has more than one document which is used as context item.

**Comment by ndw** [comment]
If we introduce a function to establish bindings, we'll find users wanting to do that all over the place. I think it complicates static analysis horribly and would prefer not to do it. (You'd have to have special rules about only constant values, etc.)

If we need a new dynamic error, I'm ok with that. I thought there was one already, but I could be wrong.

**Comment by xml-project** [comment]
Yes, you are right. The function is probably not a good idea. (Actually it is a pretty bad one.)

Any other idea, how to make the context item for TVTs work?

**Comment by gimsieke** [comment]
Isn’t this:
> BTW: If we follow yesterdays decision we have to consider creating a new dynamic error when the DRP has more than one document which is used as context item.

already covered by [err:D0008](http://spec.xproc.org/master/head/xproc/#err.inline.D0008)?

Did we already discuss changing this into “the first item of a sequence will be used as context”?

**Comment by xml-project** [comment]
Yes, may be we should D0008, but may be its getting to generic then. Don't know.
My main point was that we need to mention the error condition (if it is one) when talking explaining how a TVT is evaluated using a context item.

**Comment by ndw** [comment]
I'm going to put this on the agenda for Leipzig.

**Comment by ndw** [comment]
In #480, @xml-project notes:

While explaining syntactic shortcuts for option values, we say:

>    If the option value includes curly braces, it is treated as an attribute value template. The context node for attribute value templates in an option shortcut value comes from the default readable port for the step on which they occur.

But in explaining attribute value templates, we say:

>    Each expression is evaluated with an undefined context node.

This is a contraction we need to make sure is resolved in the spec.

**Comment by ndw** [comment]
From the 5 Sep workshop:

Proposal: remove the restriction that primary output ports must
be connected. Simultaneously say that AVTs and TVTs get their
context item from the default readable port.

Achim suggests a pipe attribute on p:document and p:inline to specify
a different port. It did not garner support.

Proposal accepted as worded.

**Comment by xml-project** [comment]
> Proposal: remove the restriction that primary output ports must
be connected. 

Done with pr #541 

> Simultaneously say that AVTs and TVTs get their
context item from the default readable port.

TBD.
