### ISSUE TITLE
Static evaluation of @select at p:option raises dynamic error

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#484]
In [p:option](http://spec.xproc.org/master/head/xproc/#p.option) we say:

> The select expression is evaluated during static analysis.

But then we also say:

> It is a dynamic error (err:XD0026) if the select expression makes reference to the context node, size, or position.

I think the error has to be raised static.

**Comment by ndw** [comment]
Not sure why this got reopened. I think it can be closed now.
