### ISSUE TITLE
Options without a value

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#496]
In "[7.2.2 XPath in XProc](http://spec.xproc.org/master/head/xproc/#xpath-context)" in the section "In-scope variables" there is a note saying

> An option that has neither a specified value nor a default value will not appear as an in-scope variable. Consequently, an attempt to refer to that variable will raise an error.

I think, this note is outdated now, because an option without a specified value and no default value is now automatically set to an [empty-sequence](http://spec.xproc.org/master/head/xproc/#p.option):

> If no default value is explicitly provided, the default value of an option is the empty sequence.

**Comment by ndw** [comment]
Yes.

**Comment by xml-project** [comment]
Fixed with pr #497
