### ISSUE TITLE
Legacy from 1.0: Register application/xproc+xml media type 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#50]
# Register application/xproc+xml media type 

>This is an aggregation of the discussion on "Register application/xproc+xml media type" ([Issue 74 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/74))

**Opened by: ndw on 2014-09-03, 00:57h**

## ndw said on 2014-09-03, 00:57h:

How: 

When doing the W3C Last Call announcement: Send an email to the mailing list[ietf-types@iana.org](mailto:ietf-types@iana.org)asking for comments on the Media Type section of your specification: 

* Include a pointer to and a plaintext copy (not just an attachment) of the Media Type registration section in your email to[ietf-types@iana.org](mailto:ietf-types@iana.org). 
* Make sure you address and reply to comments and questions on[ietf-types@iana.org](mailto:ietf-types@iana.org). If you change the registration in your specification as a result of comments on ietf-type (or for any other reason), send the revised version to[ietf-types@iana.org](mailto:ietf-types@iana.org). 
* If you are registering an XML-based format, you may want to cc:[ietf-xml-mime@imc.org](mailto:ietf-xml-mime@imc.org). 
* Note that you need to be subscribed to the list to post to it. 
* To make it easier for your WG to track comments on the Media Type section, you may cross-post the comments list for your specification. 

## ndw said on 2015-06-11, 13:14h:

Assigned to Henry at the 11 June 2015 WG meeting. 

	On 2015-06-11, 14:19h: htInEdin was assigned by ndw.

	On 2015-10-07, 14:55h: ndw added this to the XProc 2.0 LC milestone.

**Comment by eriksiegel** [comment]
W3C appears to have failed this. We close it for now.
The registration is already in the 1.0 spec, but didn't come through for some reason.
