### ISSUE TITLE
Scoping of (non-static) options

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#505]
In XProc 1.0 the following pipeline has a static error, because `$option` is not visible in the XPath-expression:
````
<p:declare-step version="1.0" 
  xmlns:p="http://www.w3.org/ns/xproc"
  xmlns:mox="http://www.xml-project.com/morganaxproc">
  <p:output port="result" />
	<p:option name="option" select="'name'" />	
	<p:declare-step type="mox:test" >
		<p:output port="result" />
		<p:option name="inner" select="$option" />
		<p:add-attribute match="/*">
			<p:input port="source">
				<p:inline><doc /></p:inline>
			</p:input>
			<p:with-option name="attribute-name" select="$inner" />
                        <!-- HERE IS THE PROBLEM -->
			<p:with-option name="attribute-value" select="$option" />
		</p:add-attribute>
	</p:declare-step>
	<mox:test />
</p:declare-step>		
````
Now in the [XProc 3.0](http://spec.xproc.org/master/head/xproc/#environment) specs, we say:

> The environment of a step also includes the in-scope bindings for all of the variables and options “visible” from its lexical position.

I can't find any explanation of "visible" except the "shadowing" rule. But as `$option` in the marked position is not shadowed, one could assume it to be visible.
What did I miss? 
Should we be a little bit more explicit about visibility (or scoping) of options and variables?

**Comment by gimsieke** [comment]
I, too, understand lexical scoping in such a way that embedded step declarations see options and static variables that are declared in the surrounding step declaration.

In https://github.com/xproc/3.0-specification/issues/826#issuecomment-507718221, @ndw asserts the following:

> […] Pipelines are self-contained. If I pick one up and drop it into a larger pipeline, it shouldn't suddenly break because of the static variables in the surrounding pipeline.

and in https://github.com/xproc/3.0-specification/issues/826#issuecomment-507343180, he argues

> I don't think we should make nested pipelines different from imported pipelines […]

So if we treat nested pipelines as if they are imported, we need to define “lexical scoping in XProc documents“ more precisely, because IMHO this contradicts everyone’s conception of lexical scope when they simply look at the XML document and its element nesting & order.

**Comment by xml-project** [comment]
Sorry, could you give us (at least me) a hint, why you reopened this issue. 
As far as I understood our consensus "lexical scoping" means "lexical scoping inside the (embedded) step". 
This seems to be inline with the cited comments. Do you see this principle at risk?

**Comment by gimsieke** [comment]
It isn’t reflected anywhere in the spec. At least I didn’t see it. Maybe you can point me to the section in the spec where we explain what lexical scope means for XProc documents. If not, we need to say something about it. This is why I reopened the issue.

**Comment by xml-project** [comment]
Ah, ok. Thanks. 
Last time we thought it was clear enough from the concept of a step, but I agree that to say a bit more about it can't be wrong.

**Comment by gimsieke** [comment]
@xml-project pointed out to me that there is this in [§ 16.5.1](http://spec.xproc.org/master/head/xproc/#declare-pipelines):

> The in-scope bindings at the beginning of a p:declare-step are limited to the lexically preceding, statically declared options and variables.

I think it doesn’t do harm if we add notes in [§ 11](http://spec.xproc.org/master/head/xproc/#variables-options-background) (Variables and Options), [§ 16.4](http://spec.xproc.org/master/head/xproc/#variables-options) (Variables and Options) and/or [§ 7.2.1](http://spec.xproc.org/master/head/xproc/#environment) (Environment, in-scope bindings) that point to this restriction wrt lexical scope.

**Comment by ndw** [comment]
I believe we have consensus that `p:declare-step`starts a new context and non-static variables declared in an outer scope are not visible in the declare step.

The open assertion in this issue, as I understand it, is that the spec isn't clear on this point.

**Comment by eriksiegel** [comment]
Can I assume that we have consensus about this and that it is OK if I attempt to resolve this issue?

**Comment by xml-project** [comment]
If the consensus is what ndw said 22 days ago, I would agree.

**Comment by eriksiegel** [comment]
Anybody *dis*agrees with Norm's last comment?

**Comment by gimsieke** [comment]
No.
