### ISSUE TITLE
@expand-text of descendants of (implicit) inlines

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#508]
Currently we [say](http://spec.xproc.org/master/head/xproc/#expand-text-attribute):

> If a p:inline occurs as a descendant of another p:inline, any expand-text within the inner p:inline is treated like an ordinary attribute; that is, neither will its value influence text expansion nor will it be removed from the descendant.

Since we have now `@expand-text` everywhere, I am not sure this special treatment of `p:inline` is a legacy (and should be expanded to all occurrences of `@expand-text`) or we keep its special role.

**Comment by gimsieke** [comment]
Suggestion:

Any expand-text attribute on a descendant of `p:inline` or within an implicit inline is treated like an ordinary attribute; that is, neither will its value influence text expansion nor will it be removed.

**Comment by gimsieke** [comment]
The use case would be to turn off (and possibly on again) expansion down the inlined document. 
The downside of acting on the instruction and removing `@p:expand-text` is that you cannot create `@p:expand-text` in inlined documents.
Documents in which `@expand-text` or `@p:expand-text` occur a probably XProc documents. 
Authors can always use explicit `<p:inline expand-text="…">` instead of `@p:expand-text` in the inlined pipelines.
Therefore I agree with you.

Suggestion:

Any `p:expand-text` attribute on a descendant of p:inline or within an implicit inline, however, will influence expansion and will be removed in the resulting document.

**Comment by xml-project** [comment]
> Any p:expand-text attribute on a descendant of p:inline or within an implicit inline, however, will influence expansion and will be removed in the resulting document.

This is the current rule, as I understand it. Isn't it?

I wasn't sure, whether "Any expand-text attribute" in your first suggestion included `p:expand-text`, so I asked.

**Comment by gimsieke** [comment]
I didn’t think of `@p:expand-text` in the first answer. I think it’s prudent to state (maybe in a note) that `p:expand-text` retains its specified behavior even if it occurs in already-inlined contexts.

**Comment by ndw** [comment]
I always thought the point of `p:inline` was to quote some markup. My feeling is that no attributes should have any special meaning inside p:inline.

**Comment by gimsieke** [comment]
It’s a fringe case anyway and we should probably pursue what implementers think is easiest to implement for them.

**Comment by ndw** [comment]
I think @gimsieke is saying that an expand text attribute among the descendants of a `p:inline` is a fringe case.

**Comment by gimsieke** [comment]
Yes

**Comment by xml-project** [comment]
Sorry, I do not understand it: To me, it looks like the two of you changed your mind about this feature. 
I would appreciate to understand, why you want me to un-implement this feature.

**Comment by ndw** [comment]
Now that we have TVTs, I'm not sure what the right answer is. What have you implemented? :-)

**Comment by xml-project** [comment]
We talked about p:expand-text in an inline controlling expansion last year and if I remember right, we agreed to do it:

````
<p:inline expand-text="true">
  <doc att="{3+4}">
    <element p:expand-text="false">{3+4}</element>
  </doc>
</p:inline>
````
create the following document:
````
<doc att="7">
  <element>{3+4}</element>
</doc>
````
This feature was requested (in my memory) to make it easier to create XProc pipelines in `p:inline`. And this was why we introduced `p:expand-text`. Did I completely misunderstand it?

**Comment by gimsieke** [comment]
You are right. `@p:expand-text` doesn’t make any sense a) outside of inlines or b) if it doesn’t control text expansion. Therefore: If we say it’s worth the while to keep it, then it needs to control TVT expansion in the inlined document.
I’d still say that if it is expensive to implement, we can do without. It is not an essential feature.

**Comment by ndw** [comment]
I concur. p:inline used to be about quoting but now that it has TVTs it's not about quoting.

**Comment by eriksiegel** [comment]
If you want to toggle text expansion inside a p:inline, use @p:inline-expand-text

**Comment by eriksiegel** [comment]
@ndw I think this issue must be handled together with #526, so I'm going to write some prose about it that will also handle the `p:inline-expand-text` attribute and by that will hopefully also cover this issue. Ok?
