### ISSUE TITLE
Legacy from 1.0: Should XProc adopt shadow attributes? 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#51]
# Should XProc adopt shadow attributes? 

>This is an aggregation of the discussion on "Should XProc adopt shadow attributes?" ([Issue 78 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/78))

**Opened by: ndw on 2014-10-06, 14:13h**

## ndw said on 2014-10-06, 14:13h:

XSLT 3.0 introduces [shadow attributes](http://www.w3.org/TR/xslt-30/#shadow-attributes). These allow for (some|all) attributes that would otherwise have to be entirely static to have values that are computed at compile time. So: 

```
  <p:pipe step="{$step}" port="result"/>
```

would be allowed provided that`$step`is known statically. 

It would not be allowed dynamically. I don't think we want to introduce the possibility that pipeline analysis depends on the runtime inputs, that seems unnecessarily confusing and just possibly unimplementable. 

	On 2014-10-06, 14:13h: ndw referenced this issue.

## ndw said on 2014-10-06, 14:14h:

c.f. issue[#33](https://github.com/xproc/1.0-specification/issues/33) 

## ndw said on 2015-02-04, 16:03h:

Still exploring, see [http://www.w3.org/XML/XProc/2015/02/04-minutes](http://www.w3.org/XML/XProc/2015/02/04-minutes) 

	On 2015-06-10, 16:00h: ndw added this to the XProc 3.0 milestone.

## ndw said on 2015-06-10, 16:00h:

Defer to 3.0 

## ndw said on 2015-06-10, 16:03h:

Some discomfort about introducing the notion of compilation in the spec; some concern that it makes the spec more complex and runs counter to our goals for 2.0. 

We could come back to it if there's time... 

	On 2015-06-11, 12:58h: ndw added the defer label.

**Comment by xml-project** [comment]
I agree with Norm's reservation about shadow attributes. Although they may be useful in some cases (e.g. importing libraries and/or steps from urls with version number), I do not think they will be used very often.
The burden of adopting them is very high in relation to the specs, because they need the distinction between static and dynamic pipeline analysis, a concept we do not have currently.

**Proposal:**
Defer!

**Comment by eriksiegel** [comment]
If we do, we should probably do it in the same way as XSLT does it: use the name of the originla attribute with an underscore in front.

**Comment by eriksiegel** [comment]
Closed because deferred to 4.0
