### ISSUE TITLE
We need to say more about p:document-properties (and friends)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#511]
By implementing `p:document-properties()` and friends, some questions and problems came up to me. As it is a rather long story to tell, I created [a wiki-page](https://github.com/xproc/3.0-specification/wiki/We-need-to-say-more-about-p:document-properties()-and-it's-friends). I hope you don't mind.

**Comment by ndw** [comment]
Thank you for the thoughtful analysis. I'm sure we'll talk about this over the next couple of days, but just a passing observation: with respect to having functions that only operate on the context node, you say that this means the `$variable` case will go away. I don't think that's true:

```xml
<p:variable name="properties" select="$variable/p:document-properties()" />
```

I don't think we gain anything by removing the argument. I think the answer is that the implementation is required to keep some sparkle around. If you pass (explicitly or via the context item) an item that has as it's ancestor a node that was an XProc document with properties, you get those properties.

I don't feel strongly, at the moment, about non-XProc documents. I think users will be least surprised if properties are manufactured for content type and (where applicable) base URI.

We probably also need to think about what happens to non-XProc documents that go through XProc steps:

```xml
<p:identity>
   <p:with-input select="doc('some-uri')" />
</p:identy>
<p:identity>
  <p:with-input select="p:document-properties-document(.)" />
</p:identity>
```

**Comment by ndw** [comment]
The 'base-uri' and 'content-type' properties will always return a value; for a node, the base URI property will be returned if it has one and the content type will be appropriate for that node type; for maps, arrays, and other atomic values, the base-uri and content-type are ().
