### ISSUE TITLE
DTD-Validation with no designated grammar

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#512]
We now have DTD-validation on p:document and p:load, but we do not say what happens, if the document to be validated designates no grammar.
In the XProc 1.0 specs (p:load) there was no rule for this case, but both processors raise an error. I propose to formalise this behaviour in XProc 3.0 by changing error message for XD0023. Currently it is:

> It is a dynamic error if a DTD validation is performed and the document is not valid.

I propose:

> It is a dynamic error if a DTD validation is performed and either the document is not valid or no DTD is found.

**Comment by xml-project** [comment]
@ndw Yes, you are right: I overlooked this. So I propose:
1. Change XD0023 to

> It is a dynamic error if a DTD validation is performed and either the document is not valid or no DTD is found.


2. Remove "and the document has a doctype declaration" from

> If the dtd-validate parameter is true and the document has a doctype declaration, then DTD validation must be performed when parsing the document."

**Comment by ndw** [comment]
:+1

**Comment by eriksiegel** [comment]
dtd-validate =true means using a validting parser

Consequence is that documents without a DTD ref fail

**Comment by xml-project** [comment]
fixed with pr #591
