### ISSUE TITLE
Is @href on p:input, p:with-input, p:variable, and p:option XML only now?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#514]
I realised today, when I went through the test suite, that shortcut `href` on these elements can now only be used for XML documents. 
Not sure, when this came in, whether I am right and whether this was indented.
I came to this conclusion because attribute `href` is a short cut for a `p:document`and the specification of p:document now [says](http://spec.xproc.org/master/head/xproc/#p.document):

> The document's content type is determined statically. If a content-type is specified, that is the content type. Otherwise, the content type is “application/xml”.

As no content-type can be defined using the shortcut, it is "application/xml". So using the `href`-shortcut on anything else then an xml document will raise a parsing error. 

What did I miss?

In a previous version of the specs -at least as far as I understood it- we had no special rule for missing content-type in p:document, so the default rule of p:load applied. And this meant, that the content-type is either taken from the URI protocol, otherwise it is implementation defined (guessed).

Why did we changed this? Was this intentional? 

If not, I would like to go back to the previous ruling, because it makes pipelines shorter. Do not know, whether this counts as argument this time, but I would like to remind all of you, that "being shorter" was a crucial argument the other week.

**Comment by xml-project** [comment]
May be this is meant, do not know. If I only look at the names (extensions), the processor could figure out that "x.json" is a JSON document. But what about the `content-type`response? As far as I understand it, this is dynamic, so can not be done.

I think the general question is, why we need the document's content type to be determined statically. My guess is, that we have overdone some things. There might be a reason for p:document on p:input (evaluated during static analysis) and other places, but on a `p:with-input` binding, I fail to see, why we need a static content-type.
Let's wait for someone to tell me, why I am wrong.

**Comment by ndw** [comment]
I'm confused about what the question is. I believe this is perfectly valid:

```xml
<p:document content-type="application/json" href="doc.json"/>
```

**Comment by ndw** [comment]
Ah, now I've seen the test suite pull-request, perhaps I have a better understanding of the problem. Perhaps we should say that the content type is implementation defined if it isn't specified with a note that implementations might use the operating system or filename extension to determine the type.

**Comment by xml-project** [comment]
@ndw Yes, that would be an idea. We event could take the "content-type" phrase completely away, because then the rules for p:load would apply and they say: Its implementation defined.

But do you remember why we said "The document's content type is determined statically."? Looking at file names and extension might count as statically, but does looking at the content-type header returned by an http-server count as static?
I am not sure, we need static here at all. What do I miss?

**Comment by ndw** [comment]
I don't want to take away content type, I should be able to say:
```xml
<p:document content-type="application/xml" href="the-extension-lies.json"/>
```
We say statically in order to avoid having to deal with dynamic values inside `<p:input>` I think. But maybe we could enforce that a different way.

**Comment by xml-project** [comment]
Sorry: Not taking away attribute "content-type", but the phrase having the _the special rules_ for content-type on p:document in opposition to the rules in p:load:
(1) Statically determined.
(2) application/xml is default.

**Comment by ndw** [comment]
Yes, I think you’re right.
