### ISSUE TITLE
Small improvements to p:load

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#515]
I'd like to propose two small improvements to p:load.
1. I'd like to extend err:XD0011 to say that it's an error if the document is invalid with respect to its content type (so invalid JSON is invalid just like invalid XML is invalid)
2. I'd like to relax err:XD0062 to say that, if the content type is specified in both places, it's an error if they are different.

**Comment by xml-project** [comment]
Completely agree with (2), but not sure about (1). 
Currently we have XD0057-XD0059 for invalid JSON. Do you want to raise XD0011 in these cases too? With respect to error catching in p:try I would tend to have more specific errors, i.e. keep XD0057-XD0059. Or did I miss your point?

**Comment by ndw** [comment]
Ah. I see now. No, let's make XD0011 for "not found" and add a new one in the XML section for XML errors.

**Comment by xml-project** [comment]
👍

**Comment by ndw** [comment]
Closed by merge.
