### ISSUE TITLE
Current expand-text attribute refers to TVTs but not AVTs

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#526]
It needs to say it applies to AVTs as well.

**Comment by ndw** [comment]
And it only applies within p:inline elements!

**Comment by ndw** [comment]
For the sake of clarity, also note that it doesn't apply "through" p:import

**Comment by dmj** [comment]
I think it should be renamed to e.g. expand-value-templates -- expand-text has a defined meaning in XSLT *and* our notion of text value templates is different from XSLT.

See Note in 10.2:

> Unlike XSLT, in XProc, text value templates are not atomized and converted to single text nodes. It is possible to insert nodes with text value templates in XProc, for example, if the XPath expressions refer to variables that have node content.
