### ISSUE TITLE
Step options of type QName need to be finessed

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#528]
Making the option type 'xs:QName' is going to be inconvenient for users:
```
<p:add-attribute attribute-name="xs:QName('p:foo')"/>
```
We probably need to say that it's value is anyAtomicType. If it's a string, then we apply the rules for converting it to a qname (including the rule about colons), if it's lexically an EQName then make it into a QName that way.

Introduce new dynamic errors for attempts to use non-string values (5, 3.4, etc.) or strings that aren't lexically QNames.

**Comment by xml-project** [comment]
Alternative idea: Introduce generic steps, so we have two step (p:add-attribute etc.) with different signature, like:
````
<p:input port="source" content-types="application/xml text/xml */*+xml"/>
   <p:input port="source" content-types="application/xml text/xml */*+xml"/>   
   <p:output port="result" content-types="application/xml"/>
   <p:option name="match" select="'/*'" as="xs:string"/>         <!-- XSLTSelectionPattern -->
   <p:option name="attribute-name" required="true" as="xs:QName"/>
   <p:option name="attribute-value" required="true" as="xs:string" />
````
and:
````
<p:declare-step type="p:add-attribute">
     <p:input port="source" content-types="application/xml text/xml */*+xml"/>
     <p:output port="result" content-types="application/xml"/>
     <p:option name="match" select="'/*'" as="xs:string"/>         <!-- XSLTSelectionPattern -->
     <p:option name="attribute-name" required="true" as="xs:string"/>
     <p:option name="attribute-prefix" as="xs:NCName"/>            
     <p:option name="attribute-namespace" as="xs:anyURI"/>         
     <p:option name="attribute-value" required="true" as="xs:string"/>
</p:declare-step>
````

The processor has then dynamically to determine, which of the two signatures fit by analysis the dynamic value of "attribute-name".

**Comment by ndw** [comment]
Maybe. But if the analysis has to be done dynamically, that's going to mean you can't (in principle) choose a step implementation statically and I think that's going to be a big change.

We already have `p:force-qname-keys()` which does for maps just about what we need to do here. I think it'll be easier to say something like what we say for forcing keys to QNames. Except that it's an error if you can't make a QName out of it.
