### ISSUE TITLE
What happens if a step produces an atomic type on an output port?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#529]
Proposal: take the string value and construct a document containing a text node with that value.

**Comment by ndw** [comment]
Is this still an issue? Haven't we basically agreed that anything you can represent in XDM (and even things you can't) can flow through the pipeline?

**Comment by xml-project** [comment]
I think it is still relevant for p:xslt / p:xquery what `content-type` as part of the document-properties is attached to the result. IMHO this should be part of the step's signature to be declared.
Treating this as a case of "[other documents](http://spec.xproc.org/master/head/xproc/#other-documents)" and working with implementation-defined content-types seems to break interoperability completely, doesn't it? What did I miss?
But we could move this to the step issues.

**Comment by ndw** [comment]
I think this is a language issue, I don't think we can push it off to the step library. On further reflection, I propose:

1. An XDM document that contains a single text node => text/plain
2. An XDM document containing something else => application/xml
3. An atomic value => application/json
4. A map or array => attempt to convert it to JSON, application/json or error
5. A function => error

The atomic value case is the one that troubles me.

**Comment by ndw** [comment]
Point of reference, however, what Saxon produces if you output a "5" is a document node containing a text node "5" so maybe my first proposal is better.

**Comment by xml-project** [comment]
> Point of reference, however, what Saxon produces if you output a "5" is a document node containing a text node "5" so maybe my first proposal is better.

Depends on what you do. Using 
````
<xsl:template name="eins">
  <xsl:sequence select="4+5" />
</xsl:template>
	
<xsl:template name="zwei">
  <xsl:map>
    <xsl:map-entry key="'eins'" select="13" />
  </xsl:map>
</xsl:template> 
	
<xsl:template name="drei">
  <xsl:sequence select="[1,2,3,4]" />
</xsl:template>
````
I get an XdmAtomicValue (xs:integer) for calling 'eins', an XdmMap for 'zwei' and an XdmArray for 'drei'.

**Comment by xml-project** [comment]
Fixed with pr #744

**Comment by Conal-Tuohy** [comment]
Like @xml-project I am curious about the nature of the possible "error" in case 4; where a step returns a map or array. It seems to me that a map or array can always be converted to JSON OK. 

What about a step that returns a sequence of atomic values, or a sequence of maps or arrays? Would they need to be treated as separate documents?

**Comment by eriksiegel** [comment]
> What about a step that returns a sequence of atomic values, or a sequence of maps or arrays? Would they need to be treated as separate documents?

We haven't specifically talked about this, but I think the answer is yes. If, for instance, an XSLT produces a *sequence* of somethings, the result will be a sequence of documents (for which the types depend on what these somethings are).

**Comment by Conal-Tuohy** [comment]
OK so a document containing a sequence of XDM items would be coerced into a sequence of documents, each containing one item? Effectively you could implement something like a`for-each` using an XSLT that produced a document containing multiple root nodes? e.g.

```xslt
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
   <xsl:template match="/">
      <xsl:sequence select="*/*"/>
   </xsl:template>
</xsl:stylesheet>
```

Presumably an empty document node would need to be quashed altogether?

**Comment by ndw** [comment]
I don't think that's quite right. I think a document that contains a sequence of nodes is just a single document. An empty document is just an empty document.

**Comment by xml-project** [comment]
I think we should discuss *this* problem with the step and not as a general aspect of the language. The question is whether the result port is a sequence port or not. If it is, I would tend to think that the result is a sequence of binary document/json documents.

But if it is a non sequence port, the step may try construct one document (by joining text nodes together to a text document and other nodes to an xml document). But then a sequence of maps or a sequence of atomics or any type mix definitely is a step error.
Did I miss something?

**Comment by eriksiegel** [comment]
Agree with @xml-project . 

BTW: The output port of `p:xslt` is defined as `sequence="true"`

**Comment by ndw** [comment]
I don't understand. If you specified sequence=false on the result port and then produced a sequence, no one would try to join the sequence together, you'd just get an error that the step produced a sequence when it wasn't supposed to.

**Comment by eriksiegel** [comment]
Sure. I was just trying to say that the situation we're discussing is not only theoretical. `p:xslt` *can* and *is allowed* to produce a sequence.

**Comment by Conal-Tuohy** [comment]
I realize now that my question about what would happen if the XSLT produces a document containing a sequence of atomic items was bogus; Any such sequence would be normalized by the XSLT processor, according to the stylesheet's serialization method, to produce a document node containing either a single text node, an XML document tree, or a JSON object (map, array, node or atomic value).

**Comment by Conal-Tuohy** [comment]
The `p:xslt` step can use `xsl:result-document` to emit a sequence (of *documents*) to appear on the `result` step of `p:xslt`; it's worth noting that documents in this sequence can be generated by different `xsl:result-document` statements, each with its own serialization parameters, where they can specify a serialization `method` (`json`, `text`, `xml` ...) and a `media-type`. If you don't specify a serialization method (with `xsl:output` or `xsl:result-document`) you get `xml` (or `xhtml` if the root element is `<html:html>`). The `media-type` is by default `text/xml` when `method="xml"`. So the XSLT author can be 100% explicit about the type of document they are producing, which should be sufficient for the XProc processor. If you want to write an XSLT to produce JSON, you should be required to be explicit, by including `<xsl:output method="json"/>`. Is that too much to ask of an XSLT programmer?

**Comment by ndw** [comment]
In an XProc implementation, it's unlikely that serialization comes into play. The values that the stylesheet produces are passed back to the XProc processor without ever being serialized. It's a real shame that there's no way (in the current APIs, that I'm aware of) to capture the stylesheet author's intended serialization options.

**Comment by gimsieke** [comment]
The stylesheet’s serialization settings won’t apply since the results on the `result` and `secondary` ports are not serialized. You need to specify the serialization parameters in XProc when using `p:store` to actually serialize the results. 
We might specify that a processor may attach the XSLT-supplied serialization maps to each output document so that they can be used when serializing the documents. But I’m not sure whether the XSLT processor is able to provide this information when it returns the results.

**Comment by Conal-Tuohy** [comment]
It would indeed be a shame if these serialization options aren't accessible, because in an environment in which serialization *does* take place, this is exactly the mechanism that XSLT authors would use. It would be nice to be able to stick with that and not be forced to ignore those XSLT instructions and duplicate their function with additional XProc markup and/or processing rules.

I'm just looking at Saxon's API docs, though, and it seems at first blush like these serialization properties might actually be passed by Saxon to a hypothetical XProc processor here:
http://www.saxonica.com/documentation/index.html#!javadoc/net.sf.saxon.s9api/XdmDestination@getReceiver

> Saxon calls this method to obtain a Receiver, to which it then sends a sequence of events representing the content of an XML document.
... and it passes a [SerializationProperties](http://www.saxonica.com/documentation/index.html#!javadoc/net.sf.saxon.serialize/SerializationProperties
) parameter, which if I am reading it correctly, should include `method` and `media-type`.

**Comment by ndw** [comment]
Interesting. That must be new in Saxon 9.9. I will investigate.

**Comment by ndw** [comment]
YES! In Saxon 9.9, it's possible to get the serialization options that the stylesheet requested. We'll be able to pass those along in document properties and do the right thing at serialization time!

**Comment by xml-project** [comment]
The original issue I think was fixed with PR #744 , wasn't it?
So I propose to close this here and move the issue to the step library issue because the discussion is now p:xslt only.
Agree?

**Comment by Conal-Tuohy** [comment]
For me, there's still the issue about exactly how an XSLT stylesheet's output declarations can over-ride the content-coercion rules as listed in that PR. For instance, an XDM document gets labelled as `application/xml`, though the stylesheet itself might have labelled it `application/rdf+xml` or `text/xml` (which I _believe_ the XSLT standard says is the default, for stylesheets that don't explicitly specify a media type). 

Of course this applies equally to `p:xquery`.

**Comment by Conal-Tuohy** [comment]
Incidentally, it seems to me also that it would be more useful to convert a single atomic value into a JSON document (i.e. to treat them the same as XDM maps and arrays).

**Comment by Conal-Tuohy** [comment]
On a different matter, I was wondering if there was a need to coin the new media type `application/vnd.xproc+atomic`, or if `application/json` could be used instead (i.e. XDM atomic types would be treated the same as maps and arrays, as instances of a JSON document. Initially I thought this would be kosher, but then I read the registration document for `application/json` and I realised that a JSON document would need to be either a JSON object or JSON array (=XDM map or XDM array) and that literal types were not allowed. So I deleted my original comment.

But since then, I read https://tools.ietf.org/html/rfc8259#page-5 and realise that this restriction has been relaxed. 

> A JSON text is a serialized value.  Note that certain previous specifications of JSON constrained a JSON text to be an object or an array.

So I'd like to suggest dropping `application/vnd.xproc+atomic`, and instead treating atomic values the same as XDM maps and arrays.

**Comment by xml-project** [comment]
Gentleman please, some discipline. I agree that this issue might also occur for p:query, but the solution won't surely be the same for p:query. 
I close this issue and file the relevant issues next week in the p:xslt step issue (with a note for p:query)

**Comment by Conal-Tuohy** [comment]
My [earlier comment about `application/vnd.xproc-atomic` and `application/json`](#issuecomment-462016620) is not about the `p:xslt` step in particular; it's a comment on the text which describes the rules for converting atomic types to documents of a particular type; the text from #744. Was this issue not the correct place to comment on it? Should I open another issue to revisit #744?

**Comment by xml-project** [comment]
@Conal-Tuohy We are currently on a conference, so it's difficult for me to sort the different things out on this resolved issue. So I beg you for time until Monday afternoon (GMT).
I will then try to sort your comments in the different channel, we currently discussing. Ok?

**Comment by Conal-Tuohy** [comment]
Sure ... take all the time you need. I just didn't want my comment to be lost when this ticket was closed.
