### ISSUE TITLE
Non-required options and @as

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#534]
In XProc 3.0 we say, that an option that is declared without an explicit `@select` has the empty sequence as default value.
In the step library (almost) all non required options are declared without occurrence modifier, e.g. "xs:string". But `() instance of xs:string` is false, so the processor must raise an error.

Best way to fix this seems to change occurrence modifier in  `@as` in the step library to something like `xs:string?`.

Did I miss something? Better proposals?

**Comment by gimsieke** [comment]
Agree

**Comment by ndw** [comment]
:+1:

**Comment by ndw** [comment]
We can get rid of the `required` altogether then, can't we?

**Comment by gimsieke** [comment]
I think so

**Comment by eriksiegel** [comment]
Rid of the `required`? What do you mean?

**Comment by gimsieke** [comment]
`as="xs:string"` says it is required, `as="xs:string?"` says it’s optional

**Comment by ndw** [comment]
required=true is equivalent to `as="sometype"`; required=false is equivalent to `as="sometype?"`. If we're going to require the `as` to allow `()` on non-required options (which I think we should) then there's no reason to separately specify that an option is required or not.

The one exception, I suppose is untyped options. But those are equivalent required=false and if youw ant required=true, you can say `as="xs:string"` (without a ?).

**Comment by eriksiegel** [comment]
I'm sorry but i disagree. `required="true"` means you *have* to **specify** the option on the step invocation, either as a `with-option` or as an attribute. You cannot not mention it.

This is as how it works in XSLT as well with required parameters for named templates.

**Comment by eriksiegel** [comment]
`required="false"` means you can leave it out and then the default (from the `@select`) kicks in

**Comment by eriksiegel** [comment]
So `as="xs:string?" ` does *not* mean its optional, it only means it accepts the empty sequence as value.

**Comment by ndw** [comment]
Ooookaaaayyyy...but
```xml
<p:option name="foo" required="true" as="xs:string?"/>
```
Means you must specify a value for `foo` but that value can be the empty string.
```xml
<p:option name="bar" required="false" as="xs:string?"/>
```
Means you don't have to specify the value, and if you don't it will be the empty string.

There's not a whole lot of difference between those two in practice.
```xml
<p:option name="baz" required="false" as="xs:string"/>
```
In principle means that you don't have to specify the option, but if you don't it will get the value `()` and that's not allowed so you'll get an error. So it is required, even though required=false. I think that's a serious usability problem.

**Comment by eriksiegel** [comment]
No, its not. I've done some playing around in XSLT and when this happens on a named template you get a runtime error...

```xml
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xsl:template match="/">
    <xsl:call-template name="xxx"/>
  </xsl:template>

  <xsl:template name="xxx">
    <xsl:param name="x" as="xs:string" required="no"/>
    <x>
      <xsl:value-of select="$x"/>
    </x>
  </xsl:template>

</xsl:stylesheet>
```

> A value must be supplied for parameter $x because the default value            is not a valid instance of the required type

So in XSLT `@required` is only about having to mention a parameter. Being consistent with XSLT was  always a strong argument and I think that is the case for this as well.

**Comment by ndw** [comment]
Okay.

**Comment by gimsieke** [comment]
This whole `@required` attribute in XSLT is quite uncommon to me and my colleagues, I must confess. I searched a larger transpect project. It has 247 XSLT files. There are 2 occurrences of `@required`:

https://github.com/transpect/epubtools/blame/master/modules/zip-package/xsl/generate-zip-manifest.xsl#L9
I think @mkraetke could have used `as="xs:string"` instead.

https://github.com/transpect/mathtype-extension/blame/master/xsl/transform/matrix.xsl#L76
I think @sbulka could have just omitted `@required`.

The XSLT 2 spec also says in https://www.w3.org/TR/xslt20/#parameters: 

> By contrast, <xsl:param name="p" as="xs:date"/> is treated as if required="yes" had been specified: the empty sequence is not a valid instance of xs:date, so in effect there is no default value and the parameter is therefore treated as being mandatory.

If you ask me, `@required` isn’t required at all in XSLT, either.

**Comment by gimsieke** [comment]
Something for Friday, I’d say

**Comment by ndw** [comment]
No, it isn't required in XSLT 2.0 or beyond, but it was in 1.0. I think it's only there for legacy and backwards-compatibility. I'm not lying down in the road for this one.

**Comment by eriksiegel** [comment]
Then I'm probably totally outdated and old-fashioned, but I happen to use it a lot. I like warnings when I forget to specify something I should.

**Comment by ndw** [comment]
I absolutely agree that it must be possible to have required attributes and to raise errors if the pipeline author fails to provide them. Today there are two competing mechanisms for that: the `required` attribute and an `as` attribute that doesn't allow empty sequence.

If we removed `required`, I think the only thing that you'd lose would be the ability to have an option that was both required and allowed to have the value `()`.

What you'd get in exchange for that is the *in*ability to specify that an attribute is not required but is required to have a value. Which is clearly an error anyway.

**Comment by gimsieke** [comment]
Today I learned that I always used an implicit `@required="no"` with my XSLT template and stylesheet parameters. Since I am one of the few sticklers who always use `@as` attributes in their params and/or with-params, it wasn’t a big deal. When I forgot to supply a param that must not be empty, I received the “A value must be supplied for parameter $x because the default value is not a valid instance of the required type“ error. Which I thought was fair enough. It didn’t ever come to my mind that I could explicitly demand that a parameter be supplied.

Now that I’m in the know, I still think that we can do away with `@required`, also in XProc 3.0.

**Comment by eriksiegel** [comment]
I agree and hadn't realized that there are now mechanisms with which you can do this just as well (and yes, I always try to add `@as` types as well). Thanks for pointing that out. But..

Repeating myself: Being consistent with XSLT was always a strong argument...

**Comment by xml-project** [comment]
> Repeating myself: Being consistent with XSLT was always a strong argument...

I strongly agree with Erik's approach to keep "@required". Being in line with XProc 1.0 is another argument. Actually I do not see any harm if there are two ways of expressing the same.
