### ISSUE TITLE
Static evaluation of attributes and descendants of p:input

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#542]
Currently we [say](http://spec.xproc.org/master/head/xproc/#static-expressions):

> Several kinds of expressions are evaluated during static analysis: [...]
>2. Value templates in the attributes or descendants of p:input [...] and map attributes on those descendants.

Do we want static errors to be raised during analysis of p:input, even if we can not determine by static analysis, if the default binding is actually used.

Options:

1. Yes, the static analysis of attributes, AVT/TVTs and map expression raises statical errors.
2. No, the error is statically detected, but it is raised dynamically, if the default binding is actually used.

What do you think?

**Comment by gimsieke** [comment]
Isn’t this similar to #454, and the solution is 2.?

**Comment by xml-project** [comment]
To my reading #454 is about evaluation of default binding (especially accessing external resources), and there we have a solution. 
My point is broader as it includes evaluation of XPath expressions in attributes:

- p:input/@href 
- p:input/p:document/@href
- p:input/p:document/@document-properties
- p:input/p:document/@parameters
- p:input/p:inline/@document-properties
- Any AVT/TVT as descendant of p:input
- Any AVT/TVT as descendant of p:input/p:inline

AND

- p:output/@href
- p:output/p:document/@href
- p:output/p:document/@document-properties
- p:output/p:document/@parameters
- p:output/p:inline/@document-properties
- Any AVT/TVT as descendant of p:output
- Any AVT/TVT as descendant of p:output/p:inline

But one might argue, that if we answer #454 with (2), we should use this concept here too.

**Comment by eriksiegel** [comment]
IMHO when the possibility exists that the validity of an expression can *not* be determined at static analysis, it should always raise a dynamic error. 

Only when an expression can or should *always* be evaluated totally static (like a @select at a static variable) it should be done at static analysis time.

**Comment by xml-project** [comment]
@eriksiegel It depends on what you call the "expression": This could either mean the XPath expressions enumerated in my last comment or the p:input/p:output as a construct.

If you take the first meaning of "whole expression", then any error is determined statically, because the expression has to be evaluated statically. In the second sense of "whole expression" it is not clear, because from a static analysis I can not know, whether the defective XPath expression is relevant.

**Comment by xml-project** [comment]
An additional problem may come up, if we go for the "dynamic solution" (2).
As the static analysis may discover more than one error to be raised dynamically if the default binding is actually used: Which one is to be raised, so it could be caught?
Currently we do not have a concept of order (or accumulating) dynamic errors, so different processors could take different errors to be raised. This makes the outcome of a defective pipeline running on different processors unpredictable. (Please mind the difference between static errors, which cause the pipeline to fail, and dynamic errors, which may invoke another part of the pipeline to be executed!)
If we go for the dynamic solution (as @gimsieke proposed), we should have an answer to "which error to raise". May be this could be a theme for Thursday's telcon?

**Comment by xml-project** [comment]
We also agreed 20 Sep editor's call that all errors detected during statical analysis of attributes and descendants of p:input are raised statically (possibly using XD-error codes).
Right?
