### ISSUE TITLE
p:with-option for option declared as static

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#543]
Suppose the following pipeline snippet:
````
<p:declare-step>
  <p:declare-step type="inner:inner">
    <p:option name="static_option" static="true" select="5" />
    ...
  </p:declare-step>

  <inner:inner>
    <p:with-option name="static_option" select="xpath-expression" />
  ...
````
If I understand the concept of a static option right, I can not bind a static option using `p:with-option`, because the @select on `p:with-option` is dynamic.

In other words: A static option always has the value given with @select on p:option (unless the processor knows some way to change this called.)

Right? If not, what did I miss?

**Comment by eriksiegel** [comment]
Yes, right, as far as I understand

**Comment by xml-project** [comment]
Proposal:
Change

> err:XS0031: It is a static error to use an option name in p:with-option if the step type being invoked has not declared an option with that name.

to

 err:XS0031: It is a static error to use an option name in p:with-option if the step type being invoked has not declared an option with that name or the option is declared as static.

**Comment by eriksiegel** [comment]
Same error? Seems very different cases to me.

**Comment by xml-project** [comment]
@eriksiegel OK for me!

**Comment by ndw** [comment]
👍

**Comment by ndw** [comment]
On second reading, I concur with Erik that it seems like a different case.
