### ISSUE TITLE
Default connection of input ports

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#544]
As @ndw stated **rightly** in yesterdays discussion on issue #542 , the [specs](http://spec.xproc.org/master/head/xproc/#p.with-input) (last paragraph) say:

> A default connection does not satisfy the requirement that a primary input port is automatically connected by the processor, nor is it used when no default readable port is defined. In other words, a p:declare-step can define defaults for all of its inputs, whether they are primary or not, but defining a default for a primary input usually has no effect. It's never used by an atomic step since the step, when it's called, will always connect the primary input port to the default readable port (or cause a static error). The only case where it has value is on a p:declare-step when that pipeline is invoked directly by the processor. In that case, the processor must use the default connection if no external connection is provided for the port.

This paragraph is taken from the 1.0 specification. I think we can completely remove it and state the new rule

> that a step that has an input port that's unbound, if there is no default readable port, will use the declared default for that port.

With regard to 1.0 compatibility I think this change of concept shouldn't be a problem: A pipeline, that had a static error in 1.0 (unconnected input port) will now run in XProc 3.0 if there is a default binding for the port. A 1.0 pipeline that executed correctly will also do so in 3.0 because it has an actual binding, so the default binding is newer used.

**Comment by ndw** [comment]
I'm ambivalent.

```xml
<p:sink/>
<p:identity/>
```
will always be an error because `p:identity` has an unbound primary input port.
```xml
<p:sink/>
<ex:step/>
```
Will be an error if `ex:step` has an unbound primary input port unless it has a default in which case the default will be used.

I can imagine an author editing a pipeline, replacing `ex:step` with `ex:alternate` and being surprised by the sudden introduction of a static error in the pipeline.

But I'm not going to fight hard against it if that's where consensus falls.

**Comment by eriksiegel** [comment]
Didn't we decide that input ports no longer have to be connected?

**Comment by ndw** [comment]
I don't recall that we said input ports could be unconnected. I assume that an unconnected input would act as if it was connected to p:empty; I think that "empty" inputs are uncommon enough that it would be a usability mistake to silently create them. I think it's more likely that an unconnected input is an error than should be empty.

With respect to @xml-project 's proposal above, I assume that it's an error if the unconnected port has no default.

**Comment by eriksiegel** [comment]
I was mistaken. Yes:

>it's an error if the unconnected port has no default.
