### ISSUE TITLE
Legacy from 1.0: Can maps nest? What's the serialization story? 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#55]
# Can maps nest? What's the serialization story? 

>This is an aggregation of the discussion on "Can maps nest? What's the serialization story?" ([Issue 90 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/90))

**Opened by: ndw on 2014-10-15, 14:30h**

## ndw said on 2014-10-15, 14:30h:

No description provided. 

## ndw said on 2014-10-15, 14:31h:

What kinds of map entry values can be serialized? 

	On 2014-10-16, 19:04h: vojtechtoman referenced this issue.

	On 2015-06-11, 10:57h: ndw added the proposed-resolution label.

## ndw said on 2015-06-11, 11:37h:

We're going to do what XDM 3.1 and XQuery/XSLT Serialization 3.1 say. 

	On 2015-10-07, 14:39h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Yes, maps can nest. Maps cannot be serialized.
