### ISSUE TITLE
I think err:XS0044 is doing too much work

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#556]
At the moment, almost any syntactic error raises XS0044. In particular, an element that occurs where it isn't allowed and a non-whitespace text node that appears where it isn't allowed both raise this error.

I propose that we create a new error for "text isn't allowed here". That's really quite different from "this element isn't allowed here".

**Comment by xml-project** [comment]
Have a look at XS0037:

> It is a static error (err:XS0037) if any user extension step or any element in the XProc namespace other than p:inline directly contains text nodes that do not consist entirely of whitespace.

I think that would do the work in most cases, but I am definitely in favor of more specific static errors which is in my view a big advantage for developers.

**Comment by ndw** [comment]
Perfect. In that case, there are a couple of tests I want to change :-)
