### ISSUE TITLE
Declaring options in XProc's namespace

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#557]
From another discussion: Nothing in the current specs (at least as far as I can see), prevents a pipeline author from doing this:
````
<p:option name="p:my-option"/>
````
I think we should forbid this so we do not run into problems with XProc's standard options.
It is not your namespace, so do not use it.

**Comment by ndw** [comment]
My turn:

> It is a static error (err:XS0028) to declare an option or variable in the XProc namespace.

**Comment by xml-project** [comment]
Thank you, Sir!
