### ISSUE TITLE
Clarifications to p:try/p:catch/p:finally

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#558]
In the course of reviewing a PR (https://github.com/xproc/3.0-test-suite/pull/86), @xml-project and I wound up in a conversation about outputs on `p:finally`. We both recall some discussion of disallowing outputs, but that seems like a bad idea (to me, today). I propose:
1. `p:finally` has arbitrary outputs.
2. The names of the output ports in `p:finally` must be different from the names of all output ports on the `p:try` or any of the `p:catch`es.
2. `p:finally` can read the error port from the `p:catch`

**Comment by xml-project** [comment]
I support @ndw 's proposal. 
After ready issue #128 again, we seem to have decided that last year in Aachen (see my comment from  17 Sep 2017).
Obviously I did not do the whole work, but only a part and closed the issue to soon. Sorry!
