### ISSUE TITLE
p:try is broken

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#559]
When we took `p:group` out of `p:try` we broke it. As currently spec'd, the `p:try` cannot have any outputs!
I assume that we should allow `p:output` in `p:try`. That's going to look a little weird:
```xml
<p:try>
  <p:output port="success"/>
  <p:identity/>
  <p:catch>
    <p:output port="failure"/>
    <p:identity>
  </p:catch>
</p:try>
```
Weird to my eyes at least in that the `success` port is really dependent on the success of the try pipeline whereas its placement directly on `p:try` suggests otherwise. But maybe that's ok. It'll just have no documents on it if the pipeline fails.

**Comment by xml-project** [comment]
@ndw I think your example is right, this is the way it has to be without p:group. I think I have to get used to this too.
