### ISSUE TITLE
Legacy from 1.0: Do we need p:import-schema? 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#56]
# Do we need p:import-schema? 

>This is an aggregation of the discussion on "Do we need p:import-schema?" ([Issue 92 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/92))

**Opened by: ndw on 2014-10-27, 18:59h**

## ndw said on 2014-10-27, 18:59h:

Now that we have XDMs, we don't need "psvi-*" things. But do we need a way to specify that types are required? Would we want to do that by allowing users to import schemas? 

## ndw said on 2015-02-04, 16:02h:

Still exploring, see[http://www.w3.org/XML/XProc/2015/02/04-minutes](http://www.w3.org/XML/XProc/2015/02/04-minutes) 

	On 2015-06-12, 14:20h: ndw assigned alexmilowski and htInEdin and unassigned alexmilowski and htInEdin.

## ndw said on 2015-06-12, 14:22h:

ACTION: Henry and Alex to write up a proposal. 

There's subtlety here with respect to the nature of the set of available schemas; for example, it appears that performing validation may (must?) add the types found in that process to theglobalset of available types. 

	On 2015-06-12, 14:34h: ndw added the awaiting-proposal label.

	On 2015-10-07, 14:39h: ndw added this to the XProc 2.0 LC milestone.

**Comment by eriksiegel** [comment]
Closed because deferred to 4.0
