### ISSUE TITLE
Discussion on pr #547 is not reflected in the specs

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#564]
In comments to pr #547 we agreed on @ndw 's proposal:

>1. If you have a value template or p:with-option or p:variable expression that doesn't refer to the context item (1+2, $foo, etc.) then it doesn't matter what the context is. You'll never have a problem.
>2. If you refer to the context item then you will get an error if the provided context does not consist of exactly one item. It's a quality of implementation issue to make that message meaningful.

I can't find this new approach in the current specs. What did I miss?

**Comment by ndw** [comment]
I think it's an oversight.

**Comment by eriksiegel** [comment]
Its just not written down yet (since it was recently decided)

**Comment by ndw** [comment]
Working on it.
