### ISSUE TITLE
Format returned by p:document-properties-document

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#573]
Now that document properties are `map(xs:QName,item()*)` we need to update the format of the XML document returned. We currently do not cover the case where more than one item is associated with a key.

**Comment by xml-project** [comment]
I am not sure we should reinvent the wheel here. May be we could just use the format generated by [fn:json-to-xml()](https://www.w3.org/TR/xpath-functions-31/#func-json-to-xml).

**Comment by xml-project** [comment]
@ ndw : Good point. What do we do about it?

**Comment by gimsieke** [comment]
For simple (and common?) cases, it is probably still good that the keys are QNames that will naturally map to XML element names and text nodes, maybe with optional type annotations (`as="xs:integer"`). 
For maps and arrays, I’m afraid we need to introduce a custom format that maybe lends its vocabulary from https://www.w3.org/TR/xpath-functions-31/#schema-for-json but allows QNames as keys, making sure that any namespace prefix used in a `@key` attribute is declared. If a map further down in the property contains elements again, then they should be included in the representation as they are.
The namespace of our map and array representations should be different from `http://www.w3.org/2005/xpath-functions`, and maybe we should prefix all element such as `map` and `array`, to make it more evident that this is not the JSON serialization. We could outsource this format specification to a separate spec, making it easier for other people to adopt it.

**Comment by ndw** [comment]
I'd really prefer to have the names be element names not `key` attribute values. My knee-jerk reaction would be to say that we use the key values as the names of elements and if the element value is a sequence, we repeat the element:

`{ p:base-uri: http://example.com, a: 1, cx:b: (a,b,<x/>) }`

becomes

```xml
<c:document-properties>
  <p:base-uri>http://example.com/</p:base-uri>
  <a xsi:type="xs:integer">1</a>
  <cx:b>a</cx:b>
  <cx:b>b</cx:b>
  <cx:b><x/></cx:b>
</c:document-properties>
```

It's a convenience format for pipeline authors to get a bit of XML out of the properties, it's not something that (I feel) needs standardization or widespread interoperability.

**Comment by xml-project** [comment]
@ndw +1

**Comment by gimsieke** [comment]
The document property names are guaranteed to be QNames, they can (and should) be mapped to element names. But if you have an arbitrary map as the value of a document property, you can’t be sure that its keys are QNames.

**Comment by xml-project** [comment]
Sorry, but we agree a while ago, that keys are (or are forced into) QNames. 
p:document-properties return "map(xs:QName,item()*)"

What did I miss?

**Comment by gimsieke** [comment]
`item()*` can be a map

**Comment by xml-project** [comment]
Ah, I see. Your are one level down in the tree.
