### ISSUE TITLE
Order of editors

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#574]
I have to give a class on scientific writing this term. Our topic today was Harvard-style/Chicago-style citation. I stumbled over the rule, that a document with four or more authors/editors **must** be cited using the name of the first author/editor only and then add "et al."

Giving the current order of spec editors, the correct citation would be "Berndzen, A. et al. XProc 3.0..."
I think we all agree that this would be ridiculous. I therefor propose to change to order of editors as following:
Norman Walsh
Achim Berndzen
Gerrit Imsieke
Erik Siegel.

Can we agree on this?

**Comment by ndw** [comment]
I respectfully abstain.

**Comment by gimsieke** [comment]
I don’t have a strong opinion on this.

There are some author list ordering conventions that vary among disciplines: 

- https://wordvice.com/journal-article-author-order/
- http://www.sciencemag.org/careers/2010/04/conventions-scientific-authorship
- https://en.wikipedia.org/wiki/Academic_authorship#Order_of_authors_in_a_list

In our domain, there seem to be different practices, too. Compare the alphabetical [XPath 2.0](https://www.w3.org/TR/xpath20/) with the (probably amount-of-contribution based) [XPath 3.1](https://www.w3.org/TR/xpath-31/) editor list.

Also, I’m not sure how many people will adhere to Chicago style when citing the XProc specification. If they use APA style, they’ll cite everyone involved for up to five authors, at least at the first occurrence.

I suspect that people who cite the XProc spec will probably do so less from scientific papers, or they won’t adhere to a specific citation style. In my conference papers [for example](http://archive.xmlprague.cz/2017/files/xmlprague-2017-proceedings.pdf#page=220), I think I only provide URLs for specs or other collaboratively developed online material most of the time.

If we subscribe to the notion (expressed in some of the linked sources above) that the “supervisor” is often last in list, it is kind of fitting that Erik, who will translate the spec into a book and therefore needs to check that every single statement is understandable and consistent with the others, assumes this role in your proposal (for people who read the list like this), as does Norm in the alphabetical list.

I’m glad that I’m somewhere in the middle either way. If we decided on alphabetical editor order and if I came first, I’d suggest that we put the people who contributed most first instead. You contributed a lot to 3.0, Achim, and therefore I wouldn’t object putting you first. I certainly don’t object putting Norm first. So I’ll abstain, too. If Erik also abstains, you can decide it.

**Comment by xml-project** [comment]
> Also, I’m not sure how many people will adhere to Chicago style when citing the XProc specification. If they use APA style, they’ll cite everyone involved for up to five authors, at least at the first occurrence.

Do not know either. But the class I was referring to was in the Departement of Computer Science. The colleges  from this department ask me to emphasis Harvard and Chicago style citation, because (according to them), all computer science journals require this style of citation.

> I’m glad that I’m somewhere in the middle either way.
Sorry to say, that the current second position is not save. At my university (for mechanical engineering, electrical engineering and also for material sciences, the required order of citation was:
(1) Head of institute (= supervising professor)
(2) Head of group (=supervising post-doc)
(3)-(n) Authors in alphabetical order.

So given our current order, you should be the supervising post-doc. ;-))

**Comment by gimsieke** [comment]
I’m a full professor in dishwasher loading! As such I deserve to be mentioned on the top shelf, 1st row from the left, but still below the flatware drawer.

**Comment by gimsieke** [comment]
He’s a charlatan. It is empirically proven [citation needed] that if the dishes go in ordered, you save up to 21.6% unloading time.

**Comment by eriksiegel** [comment]
Norm should be first, not me!
