### ISSUE TITLE
Mix-up of output/input port

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#575]
The [specs](http://spec.xproc.org/master/head/xproc/#err-vocab) say:

> In order to facilitate some modicum of interoperability among processors, errors that are reported on the error **_output_** port of a p:catch should conform to the format described here.

I think the word "output" is a mistake. Error is an input port.

**Comment by gimsieke** [comment]
Agree

**Comment by xml-project** [comment]
fixed with pr #589
