### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#576]
In the course of revising the spec for #554, I propose to make a couple of changes:

1. I believe that `err:XS0084` incorrectly refers to the `p:expand-text` attribute where it should refer to the `p:inline-expand-text` attribute
2. I propose to remove the constraint that `[p:]use-when` does not apply within `p:inline` elements. I think that's just a mistake. If we leave that, then we'll have the same argument about nesting within inlines that got us both `[p:]expand-text` and `[p:]inline-expand-text`
3. I moved `p:timeout` into the core spec.
4. I added `p:message` to the core spec.

(I'm documenting these here so that we can track them if there's discussion; if no one objects, we can just close this issue.)

**Comment by gimsieke** [comment]
1, agreed.

Because `[p:]use-when` expressions will be evaluated statically, I think they equally work in inlines. So yes, I agree with 2.

3, 4: Ok. Should we move the remainder of [Steps: An Introduction](http://spec.xproc.org/master/head/steps-intro/) to the main spec?

**Comment by xml-project** [comment]
FYI: Just added the xs:anyAtomicType -> QName to "Steps: An Introduction" I do not care to move it to the main specs, but I thought I would be the best plain. Was not aware, @ndw was moving in the opposite direction. Sorry.

**Comment by ndw** [comment]
I'm not sure where the QName section belongs. But I'm going to call that a separate issue and close this one.
