### ISSUE TITLE
What happens with a  [p:]use-when in inline contents?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#584]
I'm happy with the description of the common attributes as its is now. However, reading it one question popped up: What happens when you put a `[p: ]use-when` in inline content? Is it part of the inlined content or processed? The standard does not mention this.

I don't care what happens, as long as it is clear. If we agree on this I suggest adding a sentence about this explicitly to the standard.

**Comment by xml-project** [comment]
Good catch Erik! 
I would be happy with either solution as well.

**Comment by eriksiegel** [comment]
> I’d say, it should be a normal attribute in the inline document, without any processing expectation. Both for @p:use-when and as @use-when.

@xml-project and @ndw : Would that be implementable?

**Comment by ndw** [comment]
I think that's implementable. I think my inclination would have been to go the other way on the basis that pipeline fragments inside inlines are very much an edge case so it doesn't make sense to bias the rules in favor of that case.

But I don't feel strongly about it.

**Comment by xml-project** [comment]
I think that is not much a problem to implement: Doing nothing is easy, if you are able to track the context.

**Comment by eriksiegel** [comment]
All right, I'll add a clarification that inside inline contents `[p:]use-when` has *no* special meaning.
