### ISSUE TITLE
Type "xs:anyAtomicValue" has to be changed to "xs:anyAtomicType"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#594]
In the step library document the type annotation "xs:anyAtomicValue" is used on different occasions, e.g. "p:escape-markup".
I think we need to change this to "xs:anyAtomicType".

What did I miss?

**Comment by gimsieke** [comment]
Yes, I think this is a mistake. There is only `xs:anyAtomicType`.

**Comment by xml-project** [comment]
Will this this, as soon as I know how. Currently the build process rejects xs:anyAtomicType.
