### ISSUE TITLE
p:catch order

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#597]
Currently the specs say:

> Each p:catch pipeline is considered in _document order_.

and

>It is a static error (err:XS0064) if the code attribute is missing from any but the last p:catch or if any error code is repeated.

Because no code can be repeated, I do not see why implementations are restricted to consider p:catch-elements in document order (and how this can be tested).

Proposal: Remove the restriction "document order".

**Comment by gimsieke** [comment]
If the codes can’t repeat on `p:catch` and no more than one error can be thrown at a time, I think this constraint can indeed be dropped.

**Comment by ndw** [comment]
👍

**Comment by xml-project** [comment]
Fixed with pr #621
