### ISSUE TITLE
Legacy from 1.0: Add p:css-formatter 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#60]
# Add p:css-formatter 

>This is an aggregation of the discussion on "Add p:css-formatter" ([Issue 128 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/128))

**Opened by: liamquin on 2014-12-19, 05:58h**

## liamquin said on 2014-12-19, 05:58h:

It seems to be time to add p:css-formatter to the step library; it's already offered as a Calabash extension. 

## ndw said on 2015-03-19, 15:26h:

Added to[https://github.com/xproc/extensions/blob/master/steps/css-formatter.md](https://github.com/xproc/extensions/blob/master/steps/css-formatter.md) 

	On 2015-06-11, 13:02h: xquery added the steps label.

	On 2015-10-07, 14:38h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Moved to the steps repo, https://github.com/xproc/steps/issues/12
