### ISSUE TITLE
Legacy from 1.0: Syntax: add @pipe to make defining connections easier

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#61]
# 2.7.11 Syntax: add @pipe to make defining connections easier 

>This is an aggregation of the discussion on "2.7.11 Syntax: add @pipe to make defining connections easier" ([Issue 133 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/133))

**Opened by: xquery on 2015-01-28, 12:02h**

## xquery said on 2015-01-28, 12:02h:

adding this issue as per action A-260-01, (? do we need to amend current requirements doc ?) 

original proposal [https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0008.html](https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0008.html) 

follow on discussion in meeting minutes Dec 15 2014 [https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0015.html](https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0015.html) 

TBD- synthesis of discussion to date 

## ndw said on 2015-06-12, 10:59h:

Proposal: add a 'from' attribute to steps; the step named in the from attribute identifies the step from which the default readable port should be taken rather than the immediately preceding step. 

	On 2015-06-12, 10:59h: ndw added the proposed-resolution label.

	On 2015-06-24, 14:59h: xquery self-assigned this.

## xquery said on 2015-06-24, 15:41h:

I though we settled on[@pipe](https://github.com/pipe), will need to reconfirm with WG 

	On 2015-10-07, 14:37h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
@pipe on a step binds the primary input port.
@pipe on p:with-input applies to that input

It is an error to have @pipe and p:with-input for the same port.

**Comment by eriksiegel** [comment]
More explicit:

It is an error to have @pipe *on the step* and p:with-input for the same port.
