### ISSUE TITLE
XS0092 and XS0099: What is the difference

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#614]
Sorry, I am confused with XS0099 introduced yesterdays, saying:

> It is a static error to use an option name in p:with-option if the step type being invoked declares that the option is static.

How does this differ from XS0092?

> It is a static error if a p:with-option refers to an option that is declared static.

**Comment by ndw** [comment]
Uhm...lemme get back to you on that :-)

Maybe it's only needed in `p:variable` and not in `p:with-option`. That's most likely.

**Comment by ndw** [comment]
Nope. Just an oversight on my part.
