### ISSUE TITLE
Remove the alternate mechanisms for specifying a QName

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#616]
(This is technically a step issue, but it relates to #612 so I'm creating it here; we can move it if we decide to accept it.)

In XProc 1.0, steps like `p:add-attribute` that expect a QName value allow the pipeline author to specify the `name` or, in separate attributes, the `prefix` and the `namespace`. We did this in 1.0 because it was potentially very difficult to construct a QName if you wanted one. That's just not true anymore in 3.0. (I'm not even sure it was *that* difficult in 1.0, but stipulate that it was).

Instead of using the `prefix` and `namespace` attributes, in 3.0, you could just say:

```xml
  <p:add-attribute attribute-name="{ QName($prefix,$uri) }"/>
```

Given that I think that's (a) not hard and (b) possibly clearer to a reader than

```xml
  <p:add-attribute attribute-prefix="{$prefix}" attribute-namespace="{$uri}"/>
```

I propose that we remove the prefix and namespace attributes. This simplifies the steps, the implementation, and the spec.

**Comment by xml-project** [comment]
Actually I like to keep the old mechanism. You can use either `QName($uri, $local-name-with-prefix}` which is probably easier. 
The old mechanism does not do any harm, does it? And it keeps 1.0 pipelines running.

**Comment by ndw** [comment]
It doesn't do any harm, exactly, but it really complicates the discussion of "QNames as option values". In fact, I simplified it a bit when I moved it from the intro document; I'll go back and complexicate it again :-)
