### ISSUE TITLE
Unclear rule

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#625]
The [specs](http://spec.xproc.org/master/head/xproc/#connections) say:

> Within the context of a compound step, the declared outputs of the compound step must describe their connections.

I current fail to understand what this rule means. Can anybody please enlighten me.

**Comment by ndw** [comment]
When you declare (and even, for that matter, use) an atomic step, you never put a connection in a `p:output`. In declarations, they only describe the properties of the output (primary or secondary, sequence or not, etc.). When you use atomic steps, you never mention them at all.

Things are quite different in compound steps. In compound steps, you must provide a connection (even if it's the default connection to the last step in document order) for the `p:output` ports.

**Comment by xml-project** [comment]
Oh, it is this difference. Thanks @ndw Will look at the context again and think about a more explicit formulation.

**Comment by xml-project** [comment]
Ok, if you know what it is supposed to say, the paragraph is good and I can't easily find a better way to express this. Let's leave it like it is for a while.

**Comment by ndw** [comment]
Ok. Should we close this issue in that case?

**Comment by xml-project** [comment]
Yes, thanks. Forgot this!
