### ISSUE TITLE
Legacy from 1.0: A generalized XML validation step 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#63]
# A generalized XML validation step 

>This is an aggregation of the discussion on "A generalized XML validation step" ([Issue 135 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/135))

**Opened by: ndw on 2015-02-09, 15:06h**

## ndw said on 2015-02-09, 15:06h:

From Gerrit Imsieke: 

Others have already asked for unified report ports for the validationsteps p:validate-with-relax-ng and p:validate-with-xml-schema. Whilewe see that it might not be easy to change the signature of theexisting standard library steps, here’s a fresh approach that alsosaves a lot of verbosity. 

It builds upon the xml-model processing instruction that may beprepended to an XML document ([http://www.w3.org/TR/xml-model/](http://www.w3.org/TR/xml-model/)). 

We could either add a step p:validate-according-to-xml-models thatexecutes each validation and creates a sequence of c:errors andsvrl:schematron-output documents on the report port. 

But as we strive for terseness of expression, we may add an attributeuse-xml-models="assert-valid|report-only|none" to input and outputports. (p:input: both declarations and connections, where theattribute value on connections has precedence). 

If the attribute is on a step’s input port and its value is'report-only', it will add a port 'report' (sequence=true) to thereadable ports within the step. Alternatively, the port could be named'error', to avoid an additional name for ports that magically springinto existence. 

If the attribute value is 'assert-valid' and if the step is within ap:try/p:group, it will add these report documents to the error port ofsubsequent p:catch instructions. 

This will greatly reduce verbosity by eliminating the need to spellout input/output validation steps explicitly. It is syntactic sugarthat may be expanded to long-form explicit validation instructions (bymeans of XSLT transformation, for example). 

If there are no xml-model PIs, no validation will occur. 

xml-model-based validation should support Relax NG, Relax NG compactsyntax, XSD in different versions, ISO Schematron, NVDL, and DTD. 

Because prepending xml-model PIs to documents is a bit cumbersome,there should be an optional step p:prepend-xml-model like this: 

## ndw said on 2015-03-18, 16:22h:

The following declaration is for a generalized validation step. Much of what follows describes how this step applies to XML validation, but the actual validation performed is implementation defined. Validation of JSON data against json-schema would be entirely plausible. 

The semantics of the`p:validate`step are that the`source`document is validated in an implementation defined way. The`schema`and`models`ports exist only to provide suggestions to the implementation. 

There are several possible outputs: 

ISSUE: In the case where this error is caught by`p:catch`(how) can the`validation-attempted`and`report`steps be read? 

The output on the`report`step depends on the validation attempted. For Schematron validation, a report format is defined. For other kinds of validation, the report is implementation-defined. 

Although the step is for generalized validation, it does have a couple of options designed to support a specific XML scenario: the XML Model Processing Instruction. In the absense of other information, implementationsshoulduse the XML Model PI to determine what kind of validation to perform on XML documents. 

The`group`and`phase`options provide the corresponding values as discussed in the XML Model PI spec. 

The`models`input port and the`validation-attempted`output port use XML documents to describe desired validation in the former case and validations attempted in the latter. The following`c:model`element definitionshouldbe supported. 

Additional variations on`c:model`are allowed, as are entirely different vocabulary elements as appropriate. 

When RELAX NG validation is selected, the following parametersshouldbe recognized:`dtd-attribute-values`, and`dtd-id-idref-warnings`. 

When XML Schema validation is selected, the following parametersshouldbe recognized:`use-location-hints`,`try-namespaces`, and`mode`. 

If an NVDL schema appears on the`models`port, NVDL validationshouldbe attempted. 

## ndw said on 2015-03-18, 17:04h:

This was discussed at the 25 Feb 2015 meeting,[http://www.w3.org/XML/XProc/2015/02/25-minutes](http://www.w3.org/XML/XProc/2015/02/25-minutes)(the issue, that is, not the proposal) 

	On 2015-03-19, 11:19h: ndw referenced this issue in xproc/extensions.

## josteinaj said on 2015-04-08, 21:45h:

An output port with basic information about the validation when assert-valid="false" would be useful. Such as the total number of assertions, number of assertions failed, skipped, with warnings and succeeded. Currently a schematron validation succeeds if`count(//svrl:failed-assert) + count(//svrl:successful-report) = 0`, and this XPath is different for other kinds of validations. Some metadata about the validation, when available, might also be useful to include in such a document, such as name (`/sch:schema/sch:title`) and base URI of the source document. Maybe just something like: 

```
<c:result name="Test Name" tests="18" skipped="7" errors="5" warnings="3"/>
```

	On 2015-06-11, 13:02h: xquery added the steps label.

	On 2015-06-12, 14:26h: htInEdin was assigned by ndw.

	On 2015-10-07, 14:36h: ndw added this to the XProc 2.0 LC milestone.

	On 2015-10-07, 15:03h: ndw added the awaiting-proposal label.

**Comment by xml-project** [comment]
Please see 
http://markmail.org/message/vbuhygkwfojvl5rs?q=list:xproc-dev

for a proposal by Matthieu (who surprisingly is not on the list.)

**Comment by ndw** [comment]
12 June 2018 f2f, overtaken by #397
