### ISSUE TITLE
Open questions in p:try

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#639]
I think apart from #632 we should take another look at the section on p:try. 

1. The section states, that the output ports of a p:try are the union of all **declared** output ports of the alternative subpipelines. What are the output ports of a p:try if no alternative **declares** an output port?
2. The example in p:try still has a p:group child.
3. It is not said what happens, if two alternative subpipelines declare an output port with the same name but different values for `@content-types`. I think the answer should be, that the output port on the p:try is a union of these content-types.
4. It is state that " if any subpipeline has a primary output port, even implicitly, every subpipeline must have exactly the same primary output port." I think we need to introduce a static error if this rule is violated.
5. (Related to non-step wrappers): Compound steps like p:group or p:for-each get an implicitly declared (unnamed) output port. The example suggests that this is also true for the initial subpipeline and p:catch, but is said nowhere.

If you find further questions/problems concerning p:try please add them to this issue.

**Comment by xml-project** [comment]
Another point: Suppose there is a dynamic error raised in p:catch. Is the p:finally pipeline executed before the error bubble up? I think it should, so I can clear local resources before the error is caught further up the tree.

**Comment by ndw** [comment]
I think we've resolved your second comment.

I'll look at the other issues asap.

**Comment by xml-project** [comment]
> I think we've resolved your second comment.
+1

>I'll look at the other issues asap.
+1
