### ISSUE TITLE
Legacy from 1.0: default error port 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#64]
# default error port 

>This is an aggregation of the discussion on "default error port" ([Issue 136 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/136))

**Opened by: xquery on 2015-02-14, 06:52h**

## xquery said on 2015-02-14, 06:52h:

in discussions at XProc informal, we discussed how the existence of a default error port would help simplify debugging, error handling and creation of non trivial pipelines. 

## ndw said on 2015-03-18, 15:42h:

Discussed on 25 Feb 2015, action to Jim:[http://www.w3.org/XML/XProc/2015/02/25-minutes](http://www.w3.org/XML/XProc/2015/02/25-minutes) 

	On 2015-06-11, 10:59h: ndw assigned ndw and xquery and unassigned ndw.

## xquery said on 2015-06-13, 14:27h:

Proposal: attempt to scratch out an MVP of error/report ports 

All steps (atomic, compound & custom) expose implicit report and error output ports which contain useful information for debugging and provides a trace of documents processed by the step. 

All atomic and compound steps provided within the XProc step namespace ([http://www.w3.org/ns/xproc-step](http://www.w3.org/ns/xproc-step)) expose an error output port. The error port is the preferred mechanism for reporting standard error output for steps. 

These ports require no explicit declaration and should be considered as secondary (as in not primary) output ports set sequence=false. 

The output port names "errors" and "report" are reserved. It is a static error if an attempt is made to explicitly declare output ports with these names on any step other then p:declare-step. 

If an errors port is explicitly defined on p:declare-step then this explicit definition overrides the built-in error port. 

When an error is thrown by a step, theerroroutput port provides a c:result element with a nested c:errors element containing all dynamic and static errors (as defined in[Section 6](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#errors)) thrown specifically by a step. 

In the event of no error an empty c:result element is supplied as default, which indicates no errors were encountered during step processing. 

It is implementation defined if the step halts on the first error or reports multiple errors. In the event it does report multiple errors, then a c:errors wrapper element must be used. 

The implementator is free to add any foreign namespace elements under c:result. 

Thereportoutput port provides ac:reportelement containing ac:docselement that provide ac:docfor each document processed by the step, detailing the documents[@uri](https://github.com/uri)and@content-type. 

The c:report element is an alias for c:result element and allows the implementator to insert foreign namespaced elements within it as well as within any nested c:doc elements. 

If a report port is explicitly defined on p:declare-step then this explicit definition overrides the built-in report port. 

The report port (and specifically the c:doc element) may also contain errors related to specific documents if the underlying step supports partial failure (TBD- need to discuss partial failure). 

The following exemplifies usage of report port in a pipeline. 

Error and report ports bind automatically to their parent steps. 

When the pipeline is run with a switch instructing an output of the report to be saved to an xml file. 

The report.xml document would contain a c:report containing c:report elements for both steps. 

Open Issues 

* I took the liberty to add an overloaded document-properties() which retrieves the named property of the current doc (used with p:store step) 

* maybe the error report could be written without a try/catch intervening ? 

* we should consider providing top level attribute switch (@report-port=true,@errors-port=true) 

* p:exec already defines an errors output port with c:result, hence the requirement for nested c:errors 

* c:report elements are arbitrary and need discussion to flesh out 

* c:doc could expose a larger subset of the document properties 

## xquery said on 2015-08-05, 13:56h:

All built in steps (atomic and compound) expose an errors output port which contain useful information for debugging and tracing step processing errors. 

All atomic and compound steps provided within the XProc step namespace ([http://www.w3.org/ns/xproc-step](http://www.w3.org/ns/xproc-step)) provide anerrorsoutput port. Theseerrorsport is the preferred mechanism for reporting standard error output for steps similar to unix stderr. 

Error output port declarations will be added to each step declaration as secondary output ports set sequence=false with the output port name"errors"being reserved. 

When an error is thrown by a step, an c:errors element containing a sequence of c:error elements with (as defined in Section 6) thrown specifically by a step is emitted to theerrorsport. I propose that we extend the c:errors element to be able to identify itself (e.g. with[@step](https://github.com/step)and[@type](https://github.com/type)attributes). 

We can debate the finer distinctions of the payload though we have good status quo defined in the spec today. 

In the event of no errors the stepserrorsoutput port obviously returns an empty sequence. 

It is implementation defined if the step halts on the first error or attempts to report multiple errors if possible. 

Theerrorsoutput port automatically bind to its encapsulating steperrorsoutput port. In this manner, the top level errors output port will receive all errors as a sequence of c:errors elements. 

Take the following pipeline; 

To make this concrete, to capture all errors that may have occurred in a pipeline the invoke (using XML Calabash example) would look like. 

Its an open question if errors port behaves as a kind of implicit try/catch 

 

* interrelation with try/catch ... is a bound errors port an implicit try/catch ? 

* any top level switches for enabling/disabling error ports ? sounds like an unneeded feature. 

* error levels or types ? 

## ndw said on 2015-09-23, 14:45h:

ACTION: Jim to turn this into spec prose. 

## ndw said on 2015-09-23, 14:46h:

What do we do about 'tee'ing stderr 

## ndw said on 2015-09-23, 14:46h:

Do we want a shortcut to suppress stderr from a given step. 

	On 2015-10-07, 14:35h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
No magic output ports. We'll declare an appropriate port on the steps that can usefully use it.
