### ISSUE TITLE
Add p:force-qname() function?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#641]
To solve the problem of  `xs:Qname` keys in maps we added a `p:force-qname-keys()` function that is applied by magic to options with maps with `xs:Qname` keys.

Now we do the same kind of magic on `xs:Qname` types options, So it would be consistent to add a `p:force-qname()` function and describe the mechanism in the same way (that this, function is magically applied to options of `xs:QName` type).

**Comment by eriksiegel** [comment]
Sounds like a plan to me. Maybe even:

`p:force-qname(item()*)` so it works on sequences as well (each item in the sequence is treated the same)

**Comment by xml-project** [comment]
Could you please give me a brief hint, in which situations I might like to use `p:force-qname()`?
As far as I understood it, the magic is down by the processor, so I currently fail to see, why a pipeline author might need this function.

**Comment by gimsieke** [comment]
Will pipeline authors invoke `p:force-qname-keys()`? I think this function has been created to make the magic that the processor is supposed to apply a bit more transparent.

**Comment by xml-project** [comment]
> Will pipeline authors invoke p:force-qname-keys()?

If this is to say, no one will ever call it, I propose to remove it from the specs. We could use the prose but free the implementers from additional and unnecessary work.

**Comment by gimsieke** [comment]
I don’t know whether there will be pipeline authors who’d like to call these functions explicitly. Therefore I don’t have a strong argument in favor of exposing it as a function, apart from “it makes the magic more transparent”.
I don’t know how much extra work will go into exposing as a `p:` function a normalization routine that an implementer would have to write anyway.

**Comment by xml-project** [comment]
1.  Since XPath function rely on the underlying XPath implementation they are always at risk, if the XPath vendor changes her API. So if we are sure, it is only for the purpose of the specs, I would strongly argue to remove it.

2. This brings me back to my initial question about a use case for `p:force-name()`.

**Comment by eriksiegel** [comment]
I don't have a use-case at hand either. But since once upon a time we decided to call the `p:force-qname-keys()` to life, it would be consistent to either create a `p:force-qname()`  **or** throw them inexorably on the garbage pile of killed darlings and other once seemingly good ideas...

Both options are fine with me.

**Comment by ndw** [comment]
Consensus at editor's meeting 29 Nov: we don't need to expose `p:force-qname-keys()` to the user. We'll remove it from the `p:` namespace.

**Comment by eriksiegel** [comment]
So, are we there? As far as I understand, what we've decided now is:

- When an option has an explicit datatype `map(xs:QName, ...)` we do QName magic on the QName keys when giving it a value with `p:with-option`
- When an option has an explicit datatype `xs:QName` we do QName magic on the values when giving it a value using ``p:with-option`

Correct? These are the *only* circumstances where we apply QName magic? Not when setting variables with the same datatypes, not when an option is an `array(xs:QName)`. (I'm not advocating to enlarge the scope of the QName magic, just want to be sure).

**Comment by ndw** [comment]
I think that's the effect we want. I started making a front-to-back pass over the document and what I discovered (wrt this item anyway), is that:

1. The section on `map(xs:QName,...)` appeals to the `p:force-qname-keys()` function so it's not going to be a simple matter of removing the function; the description is going to have to be merged in somewhere else.
2. The spec actually describes the transformation of options of type `xs:QName` into QNames explicitly, without appeal to the function.

Somehow those things have to get harmonized. I think it's probably ok to keep them separate, but it would be ok (with me) to merge them if that was the clearer description.

Every time I think I should work on this, I notice that Achim assigned it to himself and I'm off the hook 😄

**Comment by xml-project** [comment]
@ndw Since your english is better than mine: Go on, assign yourself. 😄
No, seriously: If you want to work on something, remove my assignment and go on. On Thursday or Friday I will take a longer time to work on (some of) my assignments.

**On all**
I think that it is fairly odd, that the magic for xs:QName applies for options, but not for variables. So
````
<p:option name="opt" as="xs:QName" select="'name'" />
````
works, but
````
<p:variable name="var" as="xs:Qname" select="'name'" />
````
is an error because it assigns a string to a QName.

Pretty sure, people will hate us for this. I thought we already agreed on this, but obviously not. Do not see, why not. So: **Lets have the map and QName-magic with variables as well!**
