### ISSUE TITLE
Editorial clarification needed on p:with-input

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#642]
Currently the specs say:

> If no connection is provided for a primary input port, the input will be connected to the default readable port. It is a static error (err:XS0032) if no connection is provided and the default readable port is undefined.

It is clear that this means, that if a step type declares a primary input port, and the step's call has no `p:with-input` for this port and there is a DRP, then this DRP provides the binding.

Ok! But if you look at the syntax of `p:with-input`, the following is correct:
````
<p:add-attribute>
  <p:with-input port="source" />
</p:add-attribute>
````
If I look back on the text quoted above, here no binding for primary input port is provided, so the default connection rule is used.

Do we really mean this? From intuition I would argue, that if an author writes `p:with-input`, but provides no binding, she forgot something (the binding) and does not expect the DRP to be used as binding. Following this intuition, I would tend to say, that the example above should be an error.

Any opinion about this?

**Comment by ndw** [comment]
I don’t object to making it an error, but I think the current rules are clear and I don’t find them confusing.

**Comment by xml-project** [comment]
Ok, if this is intentional, I think we should leave it as it is. I was not sure whether this was an unpleasant consequence of the attribute short cuts for binding.
