### ISSUE TITLE
Missing attribute name on p:when, o:otherwise and p:if

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#643]
In the current syntax no attribute 'name' is *not* listed in the syntax box for p:when, p:otherwise and p:if.
I think this is an oversight!

**Comment by gimsieke** [comment]
`p:when` and `p:otherwise` didn’t have a `@name` attribute in 1.0, either, and I don’t think that it has become necessary there. On `p:if`, however, it is needed.

**Comment by xml-project** [comment]
> p:when and p:otherwise didn’t have a @name attribute in 1.0, either, and I don’t think that it has become necessary there.

I do not see why we should forbid naming of p:when and p:otherwise. We did not have it in XProc 1.0 and this made error messages difficult to identity, because the error messages always had to be manufactured according to default step name convention (2.1.1)
Making better error message can't be wrong, so I do not see the point in @gimsieke 's objection.

**Comment by gimsieke** [comment]
I just didn’t see a use case. Improving error messages is a use case.

**Comment by xml-project** [comment]
@gimsieke Sorry for leaving the use-case out. The lack of names on p:when/p:otherwise was one of the most annoying points in XProc 1.0 to me. This is why I took it to be obvious.
Would you mind to approve pr #644 ?

**Comment by xml-project** [comment]
Fixed with pr #644
