### ISSUE TITLE
Legacy from 1.0: Allow access to a sequence output via the default collection of the XPath context

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#65]
# Allow access to a sequence output via the default collection of the XPath context 

>This is an aggregation of the discussion on "Allow access to a sequence output via the default collection of the XPath context" ([Issue 137 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/137))

**Opened by: rdeltour on 2015-02-14, 09:01h**

## rdeltour said on 2015-02-14, 09:01h:

In XProc, it is currently impossible to access a sequence of documents from an output port when evaluating an XPath expression. The [XPath context definition](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#xpath-context) (both for processor- and step-evaluated XPath) says: 

It is a dynamic error (err:XD0008) if a document sequence appears where a document to be used as the context node is expected.Can it be considered that: 

* if a document sequence can be read, the first document in the sequence is set as the context item 
* the whole sequence is set as the default collection 

(in the same manner as what is currently done for initializing the XPath context of the`p:xslt`step). 

In several scenarios it would help simplifying what can currently be achieved only with`p:for-each`or other steps like`p:count`, etc. For instance 

```
<p:count name="count"/>
<p:group>
	<p:variable name="count" select="number(/c:result)"/> 
	<p:choose> 
		<p:when select="$count ge 2"> 
		...
```

could be simplified as 

```
<p:choose>
	<p:when select="count(collection()) ge 2"> ...
```

	On 2015-03-26, 22:42h: rdeltour referenced this issue.

## ndw said on 2015-06-11, 14:36h:

Proposed resolution: in the context where p:input is being used to set the xpath context (p:variable, p:with-option, p:choose, p:when), you may specify collection="true". This establishes the default collection for expressions in that step and makes the context node undefined. 

	On 2015-06-11, 14:36h: ndw added the proposed-resolution label.

	On 2015-10-07, 14:34h: ndw added this to the XProc 2.0 Next PWD milestone.

**Comment by ndw** [comment]
You can specify collection=true anywhere that the input is being collected to be the context for an expression. If collection=true is specified, the context node will be undefined and the default collection will be all of the documents that appeared on that port

**Comment by ndw** [comment]
I fixed this recently. It may need more work, but it's in the spec.
