### ISSUE TITLE
Legacy from 1.0: Reading document properties in a step-evaluated XPath 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#66]
# Reading document properties in a step-evaluated XPath 

>This is an aggregation of the discussion on "Reading document properties in a step-evaluated XPath" ([Issue 138 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/138))

**Opened by: rdeltour on 2015-02-14, 09:58h**

## rdeltour said on 2015-02-14, 09:58h:

XPath [extension functions](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#xpath-extension-functions) are only available in processor-evaluated XPath expressions. This is OK for most functions, but with the introduction of [p:document-properties](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#f.document-properties) –which takes a document node as parameter– it would become useful to be able to use it in step-evaluated expressions. 

Consider the following scenario: I want to be able to filter a sequence of documents based on their content types. I would like to be able to do: 

```
<p:split-sequence 
	test="map:get(document-properties(/),'content-type') eq 
	'application/vnd.foobar+xml'"/>
```

which can only be currently achieved with 

```
<p:for-each>
	<p:choose> 
		<p:when select="map:get(document-properties(/),'content-type') eq 'application/vnd.foobar+xml'"> 
			<p:output port="result" primary="true"/> 
			<p:identity/> 
		</p:when> 
		<p:otherwise> 
			<p:output port="result" primary="true"> 
				<p:empty/> 
			</p:output> 
			<p:sink/> 
		</p:otherwise>
	</p:choose> 
</p:for-each>
```

## ndw said on 2015-03-11, 14:39h:

Discussed here:[http://www.w3.org/XML/XProc/2015/03/11-minutes.html](http://www.w3.org/XML/XProc/2015/03/11-minutes.html) 

Alex to flesh out this issue with more detail. 

## alexmilowski said on 2015-05-26, 17:17h:

The various document properties would be very useful in a variety of contexts: 

* within expressions (e.g., "select" attributes) in pipeline constructs 
* within various steps that use XPath (e.g., XSLT or XQuery) 
* within AVT expressions 

This would allow the same expression to be used in a variety of context just via "cut-n-paste" by the developer. 

Unfortunately, this puts a burden on implementors to modify the XPath implementation used in every step as well as the pipeline processor. Further, if the functions were only optionally available, the pipeline necessary to extract them would radically change depending on whether the values were extracted via the pipeline step expressions or within a transform (e.g., XSLT or XQuery). 

While this sounds like a promising feature, I believe we need more motivating use cases before we place this burden on implementators. 

## rdeltour said on 2015-05-26, 19:16h:

Thanks for the detailed look Alex. 

While this sounds like a promising feature, I believe we need more motivating use cases before we place this burden on implementators.What would you call amotivating use case? (if replacing a 13-line pipeline with a 1-liner isn't compelling enough😉)Also, I would be interested in better understanding the extent of the burden on implementations (my memories of Calabash's internals on that point are too blurry), is it more than e.g. registering a custom function to the Saxon context(s)?I, for one, would obviously prefer a priority of constituencies[à la HTML](http://www.w3.org/TR/html-design-principles/#priority-of-constituencies)("users over authors over implementors over specifiers over theoretical purity"), but of course it's easier said than done when I'm a user and neither an author nor an implementor😛. 

	On 2015-06-12, 14:25h: alexmilowski was assigned by ndw.

	On 2015-10-07, 14:34h: ndw added this to the XProc 2.0 Next PWD milestone.

	On 2015-10-07, 14:34h: ndw referenced this issue.

	On 2015-10-14, 14:16h: ndw modified the milestone: XProc 2.0 LC, XProc 2.0 Next PWD.

## ndw said on 2015-10-14, 14:16h:

Pushing off a little further absent a use case.

**Comment by xml-project** [comment]
See #101

**Comment by ndw** [comment]
Now that the outputs for the branches of p:when don't all have to be the same, you can simply use the when branches to split a sequence. when type=image, output to the image port, when type=xml, output to the xml port, etc.
