### ISSUE TITLE
Nodes in p:inline with non-xml content-type

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#667]
In connection with pr #666 (sorry for the number), the question of how to treat nodes in p:inline with non-xml content-type came up. Suppose the following fragment:
````
<p:with-input>
  <p:inline content-type="text/plain">
    <node>text</node>
  </p:inline>
<p:with-input>
````
Which of the following  happens and where do we say this?

1. The children of p:inline are serialised, so the result is a text node with "<node>text</node>".
2. We take the text value of the children of p:inline, so the result is a text node with "text".
3. It is an error, because when the content-type is non-XML the children of p:inline are required to be text nodes only.

Of course the above fragment is somewhat strange, but it might happen! And it might even happen indirectly with a text value template `{$var}` where $var contains an element node.

Personally I have a slight preference for option (2), but I am not sure you all would agree on this.

**Comment by xml-project** [comment]
Yes, that is confusing because Git somehow ate the markup.  Sorry.
The idea in (1) is to serialize the nodes, so a text node with "\&lt;node\&gt;text\&lt;/node\gt;" is produced.

**Comment by gimsieke** [comment]
I think it should be interpreted like the `@content-type`/`@override-content-type` attributes on `p:load`, `p:document`, or `p:http-request`. And I think if they read such a document from disk, they would return the serialized document as a text node. In your example above, this will be the content that is between the quotes:
```
"
    <node>text</node>
  "
```
This will be variant (1), with escaped XML characters unescaped, I’d say. 
I don’t know though whether there is a use case for reading `p:inline` content as serialized XML. There is certainly one for `p:load` etc.
So I’d say this is the most consistent way to specify it. But as we have experienced, other people may have other perspectives on consistency.

**Comment by xml-project** [comment]
@gimsieke 
1. I do not argue there is a use case for this. I just say it is something, we have to deal with.
2. Not sure what I missed, but I think we have to escape the content between the quotes, if we want it to be the value of a text node.

**Comment by gimsieke** [comment]
1. Yes, this is how I understood your question.
2. Isn’t it that only when the text node is serialized, characters such as `<` need to be escaped?

**Comment by ndw** [comment]
We already say this is an error:

>  It is a dynamic error (err:XD0063) if the p:inline contains any XML markup and has a content type that is not an XML media type.

**Comment by gimsieke** [comment]
Ah Ok, then we can leave it at that. As I said, reading it as a text node would be more in line with `p:load`, but I don’t think there is much need for it.

**Comment by xml-project** [comment]
@ndw Thanks Norm. Overlooked this.
