### ISSUE TITLE
Cardinality of output ports on p:choose and p:try

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#671]
Currently we say: 

> The outputs available from the p:choose are union of all of the outputs declared in any of its alternative subpipelines. 

and

>Each output of the p:choose is declared to produce a sequence if that output is declared to produce a sequence in any of its subpipelines.

On Dec. 13th call we came to the conclusion, that the second rule is wrong and all output ports of a `p:choose` or a `p:try` have to be sequence ports. Consider:

````
<p:choose>
  ....
  <p:when test="false()">
    <p:output port="special" sequence="false" />
   ....
  </p:when>
</p:choose>
````

If no other `p:when` or `p:otherwise` has an output port named `special`,  `p:choose` here will have an output port 'special' that is empty, but has `sequence="false"` because no  subpipeline declared it to be a sequence port. So the processor will raise an error here.

The cited rule works only in the special case that all branches declare output ports with the same names. Therefor all output ports of p:choose (and p:try) must be sequence output ports.

@ndw Have we missed something?

**Comment by ndw** [comment]
Nope, I think you're exactly right.
