### ISSUE TITLE
Define what is a valid c:param element

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#678]
In the context of #677 and the [previous error XD0037/note](https://github.com/xproc/3.0-specification/blob/c03f1afa61e4a411195e2e0d7651719b1aaef671/xproc/src/main/xml/specification.xml#L1989) in `p:make-map()`, we need to specify criteria for validating `c:param`s.

What constitutes a valid `@name` attribute? 

I’d say: It needs to be a string that may contain a namespace prefix and a colon. The namespace binding for the prefix needs to be resolvable in the context of the `c:param` element itself.

Is `c:param` allowed to contain content as an alternative to `@value`?

Is `c:param` allowed to hold an `@as` attribute for the sequence type of its `@value`/content?

Is `c:param` allowed to hold a `@content-type` attribute for its content?

If the `c:param` content is the XPath 3.1 XML representation of JSON and `c:param/@content-type='application/json'`, will it be converted to a map when `p:cast-content-type[@content-type='application/json']` is applied to the `c:param-set` document?

Or can we do without `c:param/@content-type` and `c:param` content will automatically cast to a map if it is the XPath 3.1 XML representation for JSON?

Can we do away with the `c:param/@namespace` attribute?

**Comment by xml-project** [comment]
Sorry, I think the editorial note I copied from the main specs to the steps specs means: "What is it for a `c:param-set` document to be valid?" This is specified in [section 2.34.1 ](http://spec.xproc.org/master/head/steps/#cv.param) I took the text to mean "Where is the best place to specify this?"

So I propose to close this. Or did I miss anything?

**Comment by gimsieke** [comment]
Ah, you’re right, they are specified there. 

Do we need to extend the `c:param` model to try to cover all kinds of values that parameter maps can now hold (typed atomic values, arrays, maps, whole documents, …)? Or do we say, sorry for the loss of information when a map value is not a string?

**Comment by xml-project** [comment]
I think we primarily need c:param-set, so documents constructed to control p:xslt, p:xquery etc. in XProc 1.0 can be used in XProc 3.0 too. So it is mainly for legacy reasons and I would argue to keep it as it is now. We have the XPath representation for JSON for more complex documents.

**Comment by gimsieke** [comment]
Maybe solicit @ndw’s and @eriksiegel’s thoughts about extending or keeping what can be expressed in `c:param-set`s. And then either close or move it.

**Comment by ndw** [comment]
I think `c:param` should be extended to allow inline content instead of a `value` attribute. I'd support adding an `as` attribute as well. But I'm content to move it all into the Steps spec, turn the dynamic errors into step errors, and remove them from the beginning of [§16](http://spec.xproc.org/master/head/xproc/#steps).

**Comment by eriksiegel** [comment]
Moving it to the steps makes sense.
