### ISSUE TITLE
Legacy from 1.0: Clarify variable and option shadowing rules 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#68]
# Clarify variable and option shadowing rules 

>This is an aggregation of the discussion on "Clarify variable and option shadowing rules" ([Issue 142 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/142))

**Opened by: rdeltour on 2015-02-14, 13:43h**

## rdeltour said on 2015-02-14, 13:43h:

Section 2.11 [Variables](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#variables) says: 

Variables and options share the same scope and may shadow each other.while section 3.2 [Scoping of names](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#scoping) says: 

It is a static error (err:XS0004) if an option or variable declaration duplicates the name of any other option or variable in the same environment. That is, no option or variable may lexically shadow another option or variable with the same name.I for one find this confusing, could it be clarified ? For instance: 

Variables and options share the same scope and may shadow each other, in which case it is a static error.## ndw said on 2015-06-12, 10:40h:

This, we believe, is resolved by proposed erratum E13 

[http://www.w3.org/XML/XProc/docs/xproc-proposed-errata.html#e-13](http://www.w3.org/XML/XProc/docs/xproc-proposed-errata.html#e-13) 

See discussion at 

[https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Oct/0003.html](https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Oct/0003.html) 

	On 2015-06-12, 10:40h: ndw added the proposed-resolution label.

## josteinaj said on 2015-06-12, 13:03h:

Does this mean that we won't be able to construct a variable in multiple steps like this, like you can in XSLT? For instance, is this not allowed? 

```
<p:variable name="duration" select="head/meta[@name='duration']/number(@content)"/> 
<p:variable name="duration" 
	select="if (...) then my:fn_1($duration) elseif (...) then my:fn_2($duration) elsemy:fn_3($duration)"/> <p:variable name="duration" select="if (...) then my:fn_4($duration) elsemy:fn_5($duration)"/> 
	...
```

Workarounds if you can't re-use variable names: 

```
<!-- 1: create a new variable for each step of the calculation -->
<p:variable name="duration1" select="head/meta[@name='duration']/number(@content)"/>
<p:variable name="duration2" select="if (...) then my:fn_1($duration1) else
                                     if (...) then my:fn_2($duration1) else
                                                   my:fn_3($duration1)"/>
<p:variable name="duration" select="if (...) then my:fn_4($duration2) else
                                                  my:fn_5($duration2)"/>
...

<!-- 2: wrap each variable in a p:group -->
<p:variable name="duration" select="head/meta[@name='duration']/number(@content)"/>
<p:group>
    <p:variable name="duration" select="if (...) then my:fn_1($duration) else
                                        if (...) then my:fn_2($duration) else
                                                      my:fn_3($duration)"/>
    <p:group>
        <p:variable name="duration" select="if (...) then my:fn_4($duration) else
                                                          my:fn_5($duration)"/>
        ...
    </p:group>
</p:group>

<!-- 3: create one big inefficient/unreadable/unmaintainable xpath expression -->
<p:variable name="duration" select="if (...)
                                        then my:fn_4(
                                            if (...) then my:fn_1(head/meta[@name = 'duration']/number(@content))
                                            else if (...) then my:fn_2(head/meta[@name = 'duration']/number(@content))
                                            else my:fn_3(head/meta[@name = 'duration']/number(@content))
                                        )
                                        else my:fn_5(
                                            if (...) then my:fn_1(head/meta[@name = 'duration']/number(@content))
                                            else if (...) then my:fn_2(head/meta[@name = 'duration']/number(@content))
                                            else my:fn_3(head/meta[@name = 'duration']/number(@content))
                                        )"/>
...
```

	On 2015-10-07, 14:32h: ndw added this to the XProc 2.0 Next PWD milestone.

**Comment by gimsieke** [comment]
see also #87

**Comment by ndw** [comment]
Overtaken by #87
