### ISSUE TITLE
Are all input ports connected automatically, or only primary ones?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#685]
§5 says the primary input ports are special because they'll be automatically connected to the default readable port. I have this vague recollection that we decided all inputs should be automatically connected to the default readable port, even secondary ones. Is the spec wrong, or is my recollection faulty?

**Comment by xml-project** [comment]
I remember we discussed this ones, bit we did not follow it along. If I remember right, I found the rules to confusing. So the specs are right and your recollection is almost right.

**Comment by xml-project** [comment]
Locking up my notes from Prague last year, I found a request of auto-connection non primary ports not to DRP, but connecting input port with number 'n' to the output port number 'n' of the previous step. I think it came from the DAISY people.
I think we `p:with-input pipe="port"` we found a bettet solution.

**Comment by gimsieke** [comment]
I searched old issues and notes in the Wikis.

It seems as if in #447, we rejected the idea that non-primary input ports will connect to the DRP.

The discussion in #446 might also be relevant.

---

Other possibly relevant issues that I found:

In #544, @xml-project proposed the rule (not reflected in the spec yet)

> that a step that has an input port that's unbound, if there is no default readable port, will use the declared default for that port.

This implies that he thought that any step without a declared default will read its input from the DRP. This would have to be reworded in the light of the #447 decision.

---

[In this commtent](https://github.com/xproc/3.0-specification/issues/562#issuecomment-430646002), I stated the assumption that secondary inputs will not read the DRP if there is no explicit or default connection. This assumption was not further discussed.

**Comment by xml-project** [comment]
@gimsieke I am afraid you quoted me wrong: The case we discussed was a default binding on a **primary** input port. So it was not implied, 

> that any step without a declared default will read its input from the DRP.

**Comment by gimsieke** [comment]
I quoted your exact words. Maybe you can clarify this by giving a complete paragraph that would replace 

> A default connection does not satisfy […] if no external connection is provided for the port.

at the end of [p:with-input](http://spec.xproc.org/master/head/xproc/#p.with-input). 

Or maybe it should just be removed there, and we can augment the paragraph 3 paras above that currently reads:

> An input declaration may include a default connection. If no connection is provided for an input port which has a default connection, then the input is treated as if the default connection appeared.

like this:

> An input declaration may include a default connection. If no connection is provided for an input port which has a default connection, then the input is treated as if the default connection appeared. For primary input ports, the default readable port (if present) provides a connection. If there is a default readable port, a primary input for which a default connection is declared will therefore not use its default connection.

**Comment by xml-project** [comment]
> I quoted your exact words.
Context is important, even with quotes. ;-))

**Comment by ndw** [comment]
Executive summary: the spec is correct and my recollection is...hazy. Only the primary input port is automatically connected to the DRP.
