### ISSUE TITLE
Legacy from 1.0: Clarify the concept of "URI appearing in an option value" 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#69]
# Clarify the concept of "URI appearing in an option value" 

>This is an aggregation of the discussion on "Clarify the concept of "URI appearing in an option value"" ([Issue 143 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/143))

**Opened by: rdeltour on 2015-02-14, 13:54h**

## rdeltour said on 2015-02-14, 13:54h:

Section 3.3 [Base URIs and xml:base](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#xml-base-attribute) says: 

When a relative URI appears in an option value, the base URI against which it must be made absolute is ...Does this mean: 

* an option with a value of typemust be resolved as explained ? 
* anyitem used in the expression that is evaluated to compute the option's value must be resolved as explained ? 
* something else ? 

## ndw said on 2015-03-11, 14:39h:

Per [http://www.w3.org/XML/XProc/2015/03/11-minutes.html](http://www.w3.org/XML/XProc/2015/03/11-minutes.html) it means an option with a type of xs:anyURI. Norm to make sure the spec is clear(er). 

	On 2015-10-07, 14:32h: ndw added this to the XProc 2.0 Next PWD milestone.

**Comment by ndw** [comment]
Per http://www.w3.org/XML/XProc/2015/03/11-minutes.html it means an option with a type of xs:anyURI. Norm to make sure the spec is clear(er).

**Comment by ndw** [comment]
Fixed by PR #228
