### ISSUE TITLE
Remove the p:inline exception for [p:]use-when?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#694]
I propose that we remove this paragraph:
```xml
<para>Exception: <tag class="attribute">[p:]use-when</tag> attributes
on descendant <tag>p:inline</tag> elements and in implicit inlines
carry no special meaning and are considered part of the inlined
contents.</para>
```
1. It makes the spec more complicated
2. It strikes me as very unlikely in the real world
3. A pipeline that wanted to create a pipeline containing use-when attributes using `p:inline`
(see what I mean about unlikely?) could use x:use-when attributes in the inline and
rename them in a subsequent step.

**Comment by ndw** [comment]
This is easy to do. Anyone object?

**Comment by eriksiegel** [comment]
So what you mean is to have @[p:]use-when in p:inline-d content processed as normal @[p:]use-when? I'm fine with that.

**Comment by xml-project** [comment]
I have no special opinion on this. Of course @ndw is right that it make things in the specs a lot easier, but I am not sure that people synthesising pipelines would agree. So I would leave this to @gimsieke

**Comment by gimsieke** [comment]
No objection. We can use the workaround that @ndw sketched if we need to.
