### ISSUE TITLE
Legacy from 1.0: shortcut attribute to define document properties 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#70]
# shortcut attribute to define document properties 

>This is an aggregation of the discussion on "shortcut attribute to define document properties" ([Issue 146 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/146))

**Opened by: rdeltour on 2015-02-14, 14:36h**

## rdeltour said on 2015-02-14, 14:36h:

Can it be considered to add a`properties`attribute to document-loader elements and steps (`p:inline`,`p:document`,`p:load`) to set the document's properties as a shortcut of later invoking`p:set-properties`? 

## ndw said on 2015-05-27, 14:27h:

The committee has mixed feelings about doing this now. If it turns out to be very common, then probably. Can you provide some explicit use cases? 

## rdeltour said on 2015-05-27, 15:31h:

I don't remember the specific use case I had in mind, but basically use cases would be exactly the same where you'd use`p:set-properties`, as it's only a shortcut proposal.It seemed like a low-hanging fruit, but I understand you need to prioritize. 

## ndw said on 2015-05-27, 15:37h:

I think the sticking point is that the properties are naturally key/value pairs and having a shortcut attribute to set them would require having to microparse the attribute value. The current standing certainly isn't "no, we're not doing that"; it's more a case of finding out how common the case is whether it's really worth the effort. 

## rdeltour said on 2015-05-27, 15:51h:

Fair enough. But since properties are`map(xs:string,xs:string)`, don't you have the same micro-parsing issue anyway with the shortcut syntax of the`properties`option on`p:set-properties`? 

## ndw said on 2015-05-27, 15:55h:

Oh, indeed. Brain cramp on my part. It would just be a map and we have a constructor syntax for maps. #facepalm 

## rdeltour said on 2015-05-27, 16:05h:

Haha. BTW, I'm not super familiar with XPath 3, but a quick glance shows maps are introduced in XPath3.1, and neither 3.0 nor 3.1 are referenced from XProc 2.0. Should[#30](https://github.com/xproc/1.0-specification/issues/30)be reopened? 

	On 2015-05-27, 16:12h: rdeltour referenced this issue.

	On 2015-10-07, 14:31h: ndw added this to the XProc 2.0 Next PWD milestone.

	On 2015-10-07, 14:31h: ndw referenced this issue.

**Comment by xml-project** [comment]
Currently we have an attribute "override-content-type" on p:load, in the c:request-element of p:http-request and p:document as well as attribute "content-type" on p:inline. So we can set the content-type  as one element of document-properties, but not other. 
To set other properties requires "p:set-properties", so we need at least two, in case of p:inline/p:document probably three steps to archive the goal.

**Proposal:**
Replace attributes "override-content-type" and "content-type" with a new attribute "properties" or "document-properties" which is a map(xs:string,xs:string). For steps p:load, p:http-request and p:document the document properties are added or overwritten (in case the map contains values for 'base-uri' and 'content-type'). For p:inline the attribute just sets the document properties.

**Comment by ndw** [comment]
Proposed: we'll call it `document-properties` and it can override all properties. We can review the name later if necessary, for now it's clearer.

**Comment by xml-project** [comment]
The discussed approach does not work inside the framework of the current specs: "override-content-type" is an attribute in an xml document for p:http-request. Hence we can not assign a map(xs:string, xs:string) here. And p:load is defined with reference to p:http-request and p:document is defined with reference to p:load. So we have a loose end here. The idea only works for p:inline.

**Comment by xml-project** [comment]
https://github.com/xml-project/3.0-specification/issues/9 fixes the problem for p:inline, p:document and p:load, but keeps attribute "override-content-type" on p:http-request.
