### ISSUE TITLE
Missing error for Xpath errors

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#700]
In XProc 1.0 we had XD0023 saying

> It is a dynamic error if an XPath expression is encountered which cannot be evaluated (because it is syntactically incorrect, contains references to unbound variables or unknown functions, or for any other reason).

We kind of lost that error. I would like to see it come back.

**Comment by xml-project** [comment]
Related: Is it really true, that we raise a static error (err:XS0071) for this:

> It is a static error if the XPath expression refers to the name of a variable that is not present in the in-scope bindings.

I would argue that should be a dynamic error, only raised, if the XPath expression is actually evaluated.

**Comment by ndw** [comment]
*shrug*

It could be a dynamic error. My intuition is that 99% of the time `$fooo` is a typo for `$foo` and it would be better to catch it immediately. It's not a case where it could ever work successfully if that expression is ever evaluated.

**Comment by ndw** [comment]
I feel like the question of whether references to functions that are unknown should also be dynamic, but I can't find that now.

Whatever we decide for unknown variables should probably apply to unknown functions.

**Comment by xml-project** [comment]
Currently we have the static error only for missing variables, not for missing functions and not even for syntactically incorrect expressions (missing ')') or something like this.

I agree with you, that we should treat all cases in the same way.

I would definitely be open for having an error equivalent to XD0021 (in XProc 1.0), but make it static.

I am not sure we had this discussion before or if I mix up things.

**Comment by xml-project** [comment]
overtaking by #703
