### ISSUE TITLE
Errors in XPath expressions are reported statically

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#703]
All of the following are static errors:

1. Variables that are not in scope (XS:...)
2. References to unknown functions (XS:...)
3. XPath syntax errors (XP...)

**Comment by eriksiegel** [comment]
? Doesn't Saxon HE has static typing features. Maybe I miss something but that's typing as in @as attributes? I thought that worked in HE also.

**Comment by xml-project** [comment]
@eriksiegel The "Static typing feature" is an optional feature of XPath, defined [here](https://www.w3.org/TR/xpath-31/#id-xpath-static-typing). As far as I know, Saxon HE does not support it.
The "@as"-attribute is dynamic typing = An error raised during evaluation, not during static analysis. They use the terms somewhat different.

**Comment by xml-project** [comment]
Fixed with PR #725
