### ISSUE TITLE
Attribute "content-types" is missing on p:output of p:declare-step that declares a pipeline

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#710]
I think that is an oversight, isn't it?

**Comment by gimsieke** [comment]
Here it’s present:
 * http://spec.xproc.org/master/head/xproc/#p.output
 * http://spec.xproc.org/master/head/xproc/#p.output.6.2

Here it’s missing:
 * http://spec.xproc.org/master/head/xproc/#d2834e0

Yes, that’s a mistake. It should be there, too.

**Comment by xml-project** [comment]
Yes, I was talking about the last one.
