### ISSUE TITLE
What happens when omit-xml-declaration is omitted?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#712]
Currently we have (as it was in 1.0, too):

> The omit-xml-declaration must be supported. If the value is not specified or has the value no, an XML declaration must be produced.

In the 1.0 spec, when there was the `omit-xml-declaration` attribute on a standard step, it would always default to `'true'`. Therefore a processor didn’t have a choice but to omit the XML declaration if the option was missing. 

I think now the situation is different if the sentence above holds: There is no default any more for the `omit-xml-declaration` map entry, therefore a 3.0 processor must now produce an XML declaration if `omit-xml-declaration` is not specified.

Do you agree with this interpretation? If so, do we want to have this default behavior (XML declaration will be produced for the `xml` and `xhtml` methods if nothing is specified for `omit-xml-declaration`) that deviates from 1.0?

Another random observation: In the steps spec, we still occasionally refer to XSLT 2.0 and XQuery 1.0 serialization (for ex. in [`p:escape-markup`](http://spec.xproc.org/master/head/steps/#c.escape-markup)). It should probably link to [XSLT and XQuery Serialization 3.1](https://www.w3.org/TR/xslt-xquery-serialization-3/) or to [§ 16.3.1](http://spec.xproc.org/master/head/xproc/#serialization) where we link to the current 3.1 serialization spec. We can fix this while handling the other question raised above.

**Comment by xml-project** [comment]
Related: [fn:serialize()](https://www.w3.org/TR/xpath-functions-31/#func-serialize) defines "yes" as default value for " omit-xml-declaration".

**Comment by gimsieke** [comment]
Maybe we should just say that the `fn:serialize()` defaults apply. This will also answer #713.
