### ISSUE TITLE
Contradiction concerning p:output/serialization?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#716]
In the section about attribute [serialization](http://spec.xproc.org/master/head/xproc/#serialization) on p:output we say:

> If the processor is not serializing (if, for example, the pipeline has been called from another pipeline), then the serialization must be ignored.

But in the section on [static analysis](http://spec.xproc.org/master/head/xproc/#static-expressions) we say:

> Value templates in the attributes or descendants of p:input and p:output and map attributes on those descendants.

Now suppose the value for "serialization" is not syntactically valid or uses undeclared variables/functions. According to the "static-analysis" section, this is a static error regardless of the actual serialization. So the attribute is _not_ "ignored" as said in the section on "serialization".

I think what we want is that a static error is raised, if the expression is invalid, but the _values_  in the map are ignored unless they are actually used.

Did I miss something?

**Comment by ndw** [comment]
No, that sounds right. I think the former statement is just worded too strongly.
