### ISSUE TITLE
Legacy from 1.0: Make the test suite license explicit

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#72]
# Make the test suite license explicit 

>This is an aggregation of the discussion on "Make the test suite license explicit" ([Issue 150 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/150))

**Opened by: ndw on 2015-03-06, 01:22h**

## ndw said on 2015-03-06, 01:22h:

No description provided. 

	On 2015-10-07, 14:30h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Done.
