### ISSUE TITLE
Is XS0071 overtaken by events?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#728]
XS0071 is raised if the XPath expression refers to the name of a variable that is not present in the in-scope bindings. But only for the select-attribute on p:variable, p:option and p:with-option.

I think this special case is now overtaken by XS107:

> It is a static error if any static XPath error is encountered during the static analysis of an expression, e.g. because the expression is not syntactically valid, contains reference to unknown variables, or makes use of undeclared functions.

Proposal: Remove XS0071.

**Comment by ndw** [comment]
👍

**Comment by xml-project** [comment]
Fixed with pr #730
