### ISSUE TITLE
Legacy from 1.0: Ability to ignore DTD referenced from doctype declaration when loading documents 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#73]
# Ability to ignore DTD referenced from doctype declaration when loading documents 

>This is an aggregation of the discussion on "Ability to ignore DTD referenced from doctype declaration when loading documents" ([Issue 151 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/151))

**Opened by: josteinaj on 2015-03-18, 18:22h**

## josteinaj said on 2015-03-18, 18:22h:

It would be useful to be able to ignore the DTD referenced in the doctype declaration when loading documents. If I remember right, the XML spec requires that XML parsers check for the existence of the referenced DTD, even when the DTD is not parsed, which typically results in a HTTP GET request or similar to whatever URL is given in the doctype. 

I have all my XML catalogs configured now so I haven't had this problem lately, but this would be a nice feature that would avoid workarounds like loading the XML file as text, stripping away the doctype with a regex, storing the file and loading it again as XML. 

Setting`dtd-validate="false"`on`p:load`does not help because the DTD is still pinged. 

	On 2015-10-07, 14:30h: ndw added this to the XProc 2.0 LC milestone.

**Comment by gimsieke** [comment]
Related: A more straightforward and standardized way to parse HTML-serialized HTML5 documents is also desirable. Currently it works (in Calabash) by having validator.nu in the classpath, issuing a p:http-request also for local files and then apply p:unescape-markup.

In #58, @ndw mentioned a step `p:xml-parse`. Should we have such a distinct step for common yet non-XML-standard parsing requirements, or should each `p:document` be able to apply different parsing methods, either specified by the user or as a fallback cascade?

Maybe `p:document` (and `p:load`) can get an optional `@parse` attribute that can assume the values 'xml' (default), 'ignore-doctype-and-entities', 'html5' and maybe also 'json'. 

The behaviour of 'ignore-doctype-and-entities' can be specified in line with what the BaseX internal XML parser does if instructed to ignore DOCTYPE and named entities. It will still parse the [named entities](https://www.w3.org/TR/html5/syntax.html#named-character-references) that are defined in HTML5.

A non-solution would be to tell the user to configure a different XML parser such as LexEv globally.

If `p:document` and `p:load` should be equipped with the capability to read files with arbitrary content types, HTML5 and JSON and other file types can probably be detected by MIME sniffing as suggested by @alexmilowski in #82. But still, content that purports to be XML needs an override option for ignoring DOCTYPE and named entities as mentioned above.

**Comment by ndw** [comment]
12 June 2018 f2f, consensus to close this issue without action.
