### ISSUE TITLE
Legacy from 1.0: Consider adding URI/prefix alternatives for p:xslt’s initial-mode and template-name options

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#74]
# Consider adding URI/prefix alternatives for p:xslt’s initial-mode and template-name options 

>This is an aggregation of the discussion on "Consider adding URI/prefix alternatives for p:xslt’s initial-mode and template-name options" ([Issue 155 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/155))

**Opened by: gimsieke on 2015-03-30, 09:04h**

## gimsieke said on 2015-03-30, 09:04h:

Elements, such as p:add-attribute or p:wrap-sequence, that potentially create new namespace bindings provide two alternative ways for providing an element, attribute, … name: 

We use a step,[letex:xslt-mode](https://subversion.le-tex.de/common/xproc-util/xslt-mode/xslt-mode.xpl), that accepts the initial mode dynamically. The mode names in our XSLT stylesheets are often prefixed. Right now, we have to declare the mode name bindings for every stylesheet that may be supplied to the in letex:xslt-mode’s step declaration. This makes it less versatile and universal than we would wish. 

A solution may be if p:xslt accepted the additional non-required options`template-name-prefix`,`template-name-uri`,`initial-mode-prefix`, and`initial-mode-uri`. 

Another solution may be to look into the provided stylesheet’s top-level element and to use the namespace bindings that are declared there (with precedence for bindings declared in the XProc document). I don’t know whether this approach is in line with the general concepts for namespace handling. It feels a bit ad-hoc. 

## ndw said on 2015-06-11, 08:34h:

We think that this problem can be addressed by changing the type of initial-mode (and other QName-typed attributes) to EQName, then the literal "Q{[http://example.com/}name](http://example.com/%7Dname)" can be used. That can be constructed dynamically without an in-scope namespace binding. 

	On 2015-06-11, 08:35h: ndw added the resolved label.

## gimsieke said on 2015-06-11, 08:45h:

perfect 

	On 2015-10-07, 14:30h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Proposal: Anywhere a QName value is allowed, an EQName value should be allowed.
