### ISSUE TITLE
Refactor the specs into separate repositories?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#750]
There's value in keeping the specs in a single repository because they share a bunch of common prose and link to each other. But there would be value in putting the steps specification into the steps repository because that's where step issues are raised.

I suppose with a little more build magic, we could have the steps specification in a different repository, but still pull them all together in the build for the language spec.

Thoughts?

**Comment by gimsieke** [comment]
A drawback could also be that whenever we reorganize the specs, we’ll have to move the issues, too (and also update references to issues). I wouldn’t oppose though. 

When the subspecs reside in separate repos, we can use Git submodules to tie them together. This requires less magic. Note that submodules are fixed to a certain commit; you’ll have to get used to updating them to the latest commit and commit the containing overarching spec.

**Comment by ndw** [comment]
I'm not proposing a separate repo for *each* step spec, just moving all the step specs to the steps repo. *Because* that's where the issues are.

And yes, submodules is one way forward. I'll investigate what the build process would be like.

**Comment by xml-project** [comment]
This sounds like a good idea to me. Currently I have to switch repo between reading the issue and looking at the actual text. This is (somewhat) annoying.

**Comment by xml-project** [comment]
@ndw I think this is done. Close?

**Comment by ndw** [comment]
Yup
