### ISSUE TITLE
Should p:if have an impllicit else that does p:identity instead of p:sink

### ISSUE THREAD

**Issue by pmasereeuw** [xproc/3.0-specification#751]
After hearing Erik's information about p:if, and before really reading the specs, I would like to remark that my use case for an if-then-else in xproc 1.0 was a p:choose with a p:when changing something and a p:otherwise just doing a p:identify. My feeling is that the new p:if should be defined along these lines instead of just giving an empty result/p:sink in the implied else-part.

**Comment by ndw** [comment]
Feb 21 editor's meeting: we concur. There's a little bit of subtlety in spec'ing it wrt default readable ports and such.

**Comment by ndw** [comment]
It is an error if the p:if does not have a primary output port.
