### ISSUE TITLE
Document for JSON steps

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#755]
@ndw Currently we have no document for JSON steps, have we? Would you mind creating a template for these steps, so I can make some editing there.
I think if I will do this, at best it will not work with your build process, at worst it will crash the process.

**Comment by ndw** [comment]
Sure. Are you happy if I do major violence to the repositories today to move the step specs into the steps repo? If you are, I'll simply make sure there's a JSON specification in there.

**Comment by xml-project** [comment]
@ndw No, please go on. I am on trains (mostly no wifi) til late afternoon.

**Comment by xml-project** [comment]
Fixed.
