### ISSUE TITLE
Legacy from 1.0: consider making the match attribute default to '/*' for p:add-attribute etc.

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#76]
# consider making the match attribute default to '/*' for p:add-attribute etc. 

>This is an aggregation of the discussion on "consider making the match attribute default to '/*' for p:add-attribute etc." ([Issue 160 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/160))

**Opened by: gimsieke on 2015-05-26, 15:05h**

## gimsieke said on 2015-05-26, 15:05h:

In 1.0, only p:insert has a default of '/' for the match attribute, and p:label-elements defaults to . For most other steps with a match option, this option is required and does not have a default value. I find myself using match="/" most of the time, at least with p:add-attribute. Will it harm to make match default to '/' for p:add-attribute and several other steps listed below? The reason is: it reduces verbosity (a bit) without introducing too much arcane magic. 

step| currently has default? | proposed default
----|------------------------|-----------------
**p:add-attribute**	| no	| '/*'
p:delete	| no	| probably none
**p:hash**	| no	| '/*' (unless p:hash gets a select option that allows hashing string values calculated from the select expression)
p:insert	| yes | '/*'
p:label-elements | 	yes	| '*'
p:make-absolute-uris |	no | probably none
**p:rename** |	no	| '/*' (not sure about this)
p:replace	| no	| probably none
**p:set-attributes**	| no	| '/*'
**p:string-replace**	|no	| '/*'
**p:unwrap**	| no	| '/*'
**p:uuid**	| no| 	'/*'
**p:wrap**	| no	| / (not sure about this)
p:www-form-urlencode |no | 	probably none

Proposed changes are **boldface**.

## josteinaj said on 2015-05-27, 10:45h:

Would be great to have more defaults. Definitely`/*`for`p:add-attribute`,`p:rename`and`p:unwrap`(as you suggest). 

For`p:string-replace`though`/*`will basically always result in a`XD0001`error. Something like`/*/text()`would be more useful for the simple cases. 

	On 2015-10-07, 14:29h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Proposal: make "/*" the default for the ones where that makes sense (and it doesn't for string-replace), and leave the rest without a default. Don't make users remember that the defaults are different.
