### ISSUE TITLE
Values for attribute "xpath-version"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#766]
On [p:declare-step](http://spec.xproc.org/master/head/xproc/#p.declare-step) we say:

> The requested xpath-version must be used to evaluate XPath expressions subject to the constraints outlined in Section 7.2.2, “XPath in XProc”. If the attribute is not specified, the value “3.1” is assumed.

and in section 7.2.2 we say:

> XProc uses XPath 3.1 as an expression language.

As it does not make much sense requesting `@xpath-version="2.0"`, I propose to change the text on p:declare-step saying that the requested version must be "3.1" (or higher) and that it is an error to request any version < 3.0.

Thoughts?

**Comment by xml-project** [comment]
@eriksiegel Yes, may be that work, but I am not sure. 
Our definition is very interwoven with maps and arrays, which are not *declared* for XPath 2.0. Making an XProc 3.0 processor running with XPath 2.0 seems to me very complicated because it needs to be based on two different XDM models. I don't think it's worth it, but as you said correctly, that is implementation dependent. But I am not sure that we can (consistently) say, that an XProc 3.0 processor may use XPath 2.0 as expression language.
Anyway, we should fix the contradiction in the specs I quoted.

**Comment by gimsieke** [comment]
Yes, let’s make anything below 3.1 an error. Is that what you intended, @xml-project? Because you said it must be at least **3.1** and “it is an error to request any version **< 3.0**.” Then 3.0 is in a limbo: On the one hand it must not be used and on the other hand its use need not throw an error. Maybe it should read “it is an error to request any version < 3.1.”

See also a related discussion in #408

**Comment by xml-project** [comment]
@gimsieke Yes, you are right. It should read "<3.1", not "<3.0".

**Comment by eriksiegel** [comment]
I hadn't considered this map usage *inside* XProc, so yes, agree.

**Comment by xml-project** [comment]
Per 19-02-21 we decided that a version < 3.1 is an error.
