### ISSUE TITLE
Treatment of @visibility when the element is not child of p:library

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#767]
For `p:option` and `p:variable` we say that it is an error, to declare `visibility='private'`when the `p:option` or `p:variable` is not a child of a p:library. ([XS:0093](http://spec.xproc.org/master/head/xproc/#err.S0093))

But for the same attribute on `p:declare-step` we [say](http://spec.xproc.org/master/head/xproc/#p.declare-step):

> If the p:declare-step is not a child of a p:library the attribute has no effect and is ignored.

I think this different treatment is confusing and we should find a uniform way to deal with this problem: Either error in all cases or ignored in all cases.

Did I miss something?

**Comment by eriksiegel** [comment]
No preference for how to deal with this

**Comment by ndw** [comment]
Per 21 Feb editor's meeting, just ignore it.

**Comment by xml-project** [comment]
Fixed with pr #781
