### ISSUE TITLE
Obsolete reference?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#768]
Currently in [p:declare-step](http://spec.xproc.org/master/head/xproc/#p.declare-step) (in section on attribute `type`) we say:

> Except as described in Section 13, “Versioning Considerations”, the XProc namespace must not be used in the type of steps.

But in [Section 13](http://spec.xproc.org/master/head/xproc/#versioning-considerations) there is no related text. Having checked this with the 1.0 prose, I think this reference is related to backward-compatibility and backward-compatibility. But the paragraphs were remove in Prague. So imho the quoted sentence is obsolete.
Right?

**Comment by gimsieke** [comment]
Yes, this exception needs to be dropped

**Comment by ndw** [comment]
Norm will update the schema to decimal and make sure the syntax box is formatted correctly.
