### ISSUE TITLE
Missing error code for p:option/p:variable as children of p:library

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#779]
In section [11.3](http://spec.xproc.org/master/head/xproc/#statics) we say:

> Options and variables that are the direct children of p:library must be declared static.

But I can not find the error code to raise in the specs. I do not think that err:XS0100 (general syntax error) should be used here. So it seems we need another error. Right?

**Comment by gimsieke** [comment]
I cannot find a static error for this, either. I agree that we need a specific one.

**Comment by xml-project** [comment]
fixed with pr #780
