### ISSUE TITLE
Legacy from 1.0: Consider adding @timeout to control potentially long-running steps

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#78]
# Consider adding @timeout to control potentially long-running steps 

>This is an aggregation of the discussion on "Consider adding @timeout to control potentially long-running steps" ([Issue 162 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/162))

**Opened by: Conal-Tuohy on 2015-06-04, 03:52h**

## Conal-Tuohy said on 2015-06-04, 03:52h:

Steps like`p:http-request`,`p:xslt`, and`p:xquery`can take a long time to run, and might usefully have an option to put some constraint on that time. e.g. by setting a timeout in milliseconds. 

`<p:http-request timeout="1000"/>` 

If the step failed to terminate in time, it would generate a dynamic error. 

It's common for HTTP Client APIs to offer an explicit timeout, and XProc implementations could easily delegate a timeout to their underlying HTTP API. For instance: [https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/params/HttpConnectionParams.html#setConnectionTimeout%28int%29](https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/params/HttpConnectionParams.html#setConnectionTimeout%28int%29) 

The runtime of a`p:xslt`,`p:xquery`, or`p:exec` step is also potentially unbounded. Especially in the framework of a multi-user application it could be useful to be able to kill off a pathological stylesheet or query which has been running too long. 

	On 2015-06-04, 04:07h: Conal-Tuohy referenced this issue.

## ndw said on 2015-06-11, 13:10h:

This seems like an interesting idea. It's not specific to p:xslt, but applies equally to all steps. 

We'd like to get implementor experience about what kinds of security annotations would be most useful/interoperable. 

	On 2015-06-11, 13:10h: ndw added the defer label.

	On 2015-06-11, 13:11h: ndw added this to the XProc 3.0 milestone.

**Comment by ndw** [comment]
Allow @timeout on steps with a maximum duration specified as an xs:duration; if the value is just a number it's a number seconds. It's a dynamic error.

**Comment by xml-project** [comment]
Addressed with PR #243
