### ISSUE TITLE
Value for p:declare type?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#789]
Details. details: I wonder if this is allowed: 

```xml
<p:declare-step xmlns="my-namespace-for-steps" type="mystep">
```

Is the default namespace used in determining step types?

**Comment by xml-project** [comment]
Yes, we need to say more about this. `type` is marked as an EQName and XPath 3.1 says about EQNames without prefix:

> A name written in this form has no prefix, and the rules for determining the namespace depend on the context in which the name appears.

Any preferences?

**Comment by eriksiegel** [comment]
I would prefer that a namespace prefix is mandatory (or Q{...}  notation, maybe). Like the QName magic. Then its always clear that this type thing is in a namespace.

But I'm not sure whether that would be "unnaturally" or un-XML-sh.

**Comment by ndw** [comment]
Names without colons are in no namespace, step types are forbidden from being in no namespace.

**Comment by ndw** [comment]
The current spec says:

>The type attribute provides a type for the step. The value of the type can be from any namespace provided that the expanded-QName of the value has a non-null namespace URI. It is a static error (err:XS0025) if the expanded-QName value of the type attribute is in no namespace or in the XProc namespace. Neither users nor implementers may define additional steps in the XProc namespace. 

I don't see any ambiguity. You cannot specify a step type in no namespace.

If you agree, please close this issue.
