### ISSUE TITLE
Legacy from 1.0: Consider adding an option to the p:xslt step to filter the stylesheet's access to URIs 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#79]
# Consider adding an option to the p:xslt step to filter the stylesheet's access to URIs 

>This is an aggregation of the discussion on "Consider adding an option to the p:xslt step to filter the stylesheet's access to URIs" ([Issue 163 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/163))

**Opened by: Conal-Tuohy on 2015-06-04, 04:07h**

## Conal-Tuohy said on 2015-06-04, 04:07h:

If the`p:xslt`step can be configured to restrict access to particular data sources, such as the file system, then it can more safely be used to run user-supplied XSLT stylesheets in a multi-user environment. e.g. 

```
<p:xslt uri-filter="^(http:|https:).*$"><!--no access to file: URIs-->
	... 
</p:xslt>
```

Unlike in other environments, XSLT 2's`<xsl:result-document>`does not write directly to a file system, so it doesn't pose a risk. However, a stylesheet could gain read access to local data sources using e.g. a`file:`URI, e.g. 

```
<xsl:stylesheet version="2.0" xmlns : xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:template match="/"> 
		<xsl:copy-of 
			select="document('file:///var/lib/tomcat7/conf/tomcat-users.xml')"/> 	</xsl:template> 
</xsl:stylesheet>
```

A custom URI resolver for the XSLT step could filter all requested URIs and prevent access to any which didn't match the specified filter. 

When combined with [#162](https://github.com/xproc/1.0-specification/issues/162) this feature would provide a "safe mode" for XSLT. 

	On 2015-10-07, 14:28h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Why is this specific to XSLT? Shouldn't this apply to all steps?

Is there any reason that this has to vary by step type? Shouldn't this be a global setting: pipelines may (or may not) access these URIs...

I'm tempted to say that this should be outside the scope of the actual pipeline. Like our recent work on an "injection" spec for debugging, maybe there should be a "document management" spec for runtime control of the pipeline.

**Comment by xml-project** [comment]
I do not see the connection to p:xslt either. And it is definitely no feature of the language, but of the processor / implementation. MorganaXProc has such a protecting system as Calumet has, but I do not see any reason to put it into XProc's specs.
Actually it is dangerous to do it, because with p:eval the uri-filter would be created on the fly. Having a mechanism inside the implementation is much more secure.

Proposal: Close!

**Comment by ndw** [comment]
Right. I'm going to close this. If it's something that the community would value seeing standardized, I propose that we make a separate spec for it, as I mentioned above.
