### ISSUE TITLE
Extension of JSON-related steps in the standard library

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#795]
Many JSON related step, like merging maps, insert into a map, an array, etc. could be done with XPath, so we should discuss if the want this steps as build in XProc steps, as a recommend (non)-standard library written in XProc or leave it to the pipeline authors to build this steps if they want it.

Last week I proposed a `p:json-join` which is supposed to take a sequence of JSON documents on the source port and joins them together in an array appearing on the step's output port. This steps can't be done in XPath (as far as I can see), because the array on the output port should reflect the order of documents on the source port. (Remember that fn:collection() in XPath is not ordered)
The second mandatory step I could think of is some kind of `p:json-validate`, validating some JSON against JSON-schema.

But what about the others? We shortly discussed this problem in Prague, but the question which selection language (XPath or a JSON-language) we should use could not be solved. So we postponed the question. If we want to have a last-call for the step library in London, I think we should make a decision soon.

Any suggestions, comments, preferences?

**Comment by Conal-Tuohy** [comment]
I agree about the two mandatory steps and don't personally feel a need for JSON steps that could be done with a `p:identity` with a `select` attribute.

**Comment by Conal-Tuohy** [comment]
Some time ago I investigated other JSON query languages analogous to XPath, and I'm sorry to say I found them quite disappointing; my opinion is that XPath 3.1 is much better. Is there a problem with just using XPath?

**Comment by eriksiegel** [comment]
Given the XML background of XProc, its not very probable that it will be used intensively for JSON stuff. 

This may sound cynical, but from some personal prejudiced experience: JSON users are, well, JSON users, everything from the old-fashioned XML side is looked at with a lot of suspicion and usually not even taken into consideration. Its not hip-and-happening enough.

My guess is that all the JSON support we add will be used mostly by *XML* people that now and then have to do some JSON processing (whether they like it or not...). So if we can get away with just a few JSON steps and doing mostly XPath, I think we'll be fine. I don't feel much like putting a lot of effort in something that will rarely be used and can be done with existing means as well.

But again, that's the old-geezer cynical and prejudiced me speaking...

**Comment by xml-project** [comment]
We keep it simple for now.
