### ISSUE TITLE
Legacy from 1.0: Consider removing p:group from p:try 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#80]
# Consider removing p:group from p:try 

>This is an aggregation of the discussion on "Consider removing p:group from p:try" ([Issue 164 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/164))

**Opened by: ndw on 2015-06-06, 10:00h**

## ndw said on 2015-06-06, 10:00h:

XSLT has added xsl:try: 

I wonder if we should consider removing the`p:group`in`p:try` 

## xquery said on 2015-06-06, 10:10h:

remove or make implicit e.g. syntactic nicety 

	On 2015-10-07, 14:27h: ndw added this to the XProc 2.0 LC milestone.

**Comment by xml-project** [comment]
Proposal: Keep p:group in p:try. Makes xproc more readable than the alternative.

**Comment by ndw** [comment]
I don't think anyone was in favor.
