### ISSUE TITLE
Move the RELAX NG Schema generation to a different repository

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#800]
I'm creating this issue to make sure everyone has visibility on it.

Today, the RELAX NG schemas are composed from the language schema and the step schema when the core specification is built. This means that when a step signature changes, we have to rebuild the core spec just to get the updated schema.

I don't think that's sustainable. I propose that we create a repository for building specs that composes the schema fragments from both the specification repo and the steps repo.

**Comment by xml-project** [comment]
@ndw Does that mean we shouldn't change anything in the step library currently?

**Comment by ndw** [comment]
No, not at all. This is just a heads up that I'm going to work on it. It won't have any impact on either spec.

**Comment by ndw** [comment]
Oh, I suppose it's also a chance to object, if you have an objection :-)

**Comment by xml-project** [comment]
No, not at all. Please go on. As you are the architect of our infrastructure (did I say "Thank you!" for this enough?), I totally rely on your opinion.

**Comment by ndw** [comment]
Done. There's a new 3.0-grammar repo.
