### ISSUE TITLE
Additional cleanup necessary after yesterdays merge

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#801]
Yesterday @ndw introduced our new context of content-types for documents to the working draft.

After reading it again in context, I think some additional cleanup is necessary:

1. To my reading the newly introduced section 3.3 makes the following section 3.4 almost completely obsolete. Only the error condition at the end of 3.4 seems to be relevant now.

2. Section 3.4 (1) says, that "image/svg+xml" is an XML mediatype, but 3.3 says it is not. I would argue to add image/svg+xml to the standard list of content types, XML expands to.

3. Section 3.3 starts with

> In some contexts (step inputs, step outputs, and inline elements, for example) ...

I think that the reference to "inline elements" is misleading here. To my understanding `p:inline/@content-type` _specifies the actual media type_ of the document, so there is no list here, no asterisk is allowed and no expansion will take place. 

Of you give me a go, I would try to make these changes. Otherwise, could you please tell me where I am wrong.

**Comment by ndw** [comment]
1. Yes, you're probably right.
2. Yes, I think xml should expand to: `application/xml text/xml */*+xml -application/xhtml+xml`
3. Yes, that's just a brain cramp on my part.
