### ISSUE TITLE
Replace "XML media type" with "XML or HTML media type" in some places

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#803]
I think I found some more places to change (some as a consequence of pr #799) :

1. XD0063 says it is an error if any inline content contains XML markup but has not an XML media type. I think here we need to add HTML media type as well.

2. In XD0054 we must add HTML media type

3. Section 16.10.1 should be renamed to "Inline XML and HTML content". In the first line we should add "HTML media type" additional to XML media type.

4. In section 10.2 under 1. we should add HTML media type. As a consequence we have to mention it in 2. too.

Can I have a go (or non-go) for this changes please.

**Comment by ndw** [comment]
👍
