### ISSUE TITLE
Join Adjacent Text Nodes in the XDM of Step Results?

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#807]
@xml-project [tried to specify an error for a `p:hash` result](https://github.com/xproc/3.0-steps/pull/81) that replaces the “document element” with a text node. Now that we allow multiple top-level elements below a document node, `p:hash` might create multiple adjacent text nodes. Admittedly, this is a pathological case, but we need to specify more accurately what’s supposed to come out of a step.
When these adjacent text nodes are serialized, they are merged (see #722) according to _S<sub>6</sub>_ in [sequence normalization](https://www.w3.org/XML/Group/qtspecs/specifications/xslt-xquery-serialization-31/html/#serdm).
But how does the XDM look after it has emerged from a step? I don’t think a full sequence normalization is in order here since for some serialization methods, sequence normalization must not be performed, and some normalization steps only make sense if the document is immediately going to be serialized. 
The main issue here seem to be adjacent text nodes. Should we say that adjacent text nodes a) must be merged or b) may be merged before they emerge from a step?

**Comment by ndw** [comment]
Adjacent text nodes in a single document must be merged per 6.7 in the XDM spec.
