### ISSUE TITLE
Legacy from 1.0: What is the default content-type of the result of loading a file: URI 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#82]
# What is the default content-type of the result of loading a file: URI 

>This is an aggregation of the discussion on "What is the default content-type of the result of loading a file: URI" ([Issue 172 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/172))

**Opened by: ndw on 2015-06-10, 11:00h**

## ndw said on 2015-06-10, 11:00h:

Now that we have non-XML documents, we should take advantage of the OS "registry" of content types by extension. Should that be overridable? 

## xquery said on 2015-06-10, 11:15h:

Is 'application/octet-stream' the right answer or do we provide some kind of heuristic, with no default ? 

## alexmilowski said on 2015-06-10, 11:19h:

We should look at the MIME Sniffing Standard:[https://mimesniff.spec.whatwg.org](https://mimesniff.spec.whatwg.org) 

	On 2015-10-07, 14:27h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
I think the most critical question is: are we going to require implementations to sniff content for content types in an interoperable way?

If not, I think the answer is "it's implementation defined."

**Comment by gimsieke** [comment]
I’d say “implementation-defined”. Maybe the spec can recommend that implementations _should_ at least support a mapping that is based on file extensions in the approximate scope that [Apache](https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types) or [Nginx](https://github.com/nginx/nginx/blob/master/conf/mime.types) Web servers support, but are free to apply other or additional methods such as content sniffing.

**Comment by ndw** [comment]
12 June 2018 f2f, "implementation defined."
