### ISSUE TITLE
p:option @values error can't be a static error

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#823]
Currently, the description of `p:option` says:

> values
>
>    A list of acceptable values may be specified in the values attribute. If specified, the value of  the values attribute must be a list of atomic values expressed as an XPath sequence, for example: ('one', 'two', 'three'). It is a static error (err:XS0101) if the values list is not an XPath sequence of atomic values. 

I don't believe that can be a static error in the general case.

**Comment by xml-project** [comment]
Hhm, thinking of a situation, where a option declaration is not parsed statically. Could you give us an example, where @values is not analysed statically?

**Comment by ndw** [comment]
Nevermind. I completely misread that as the error to raise if the supplied value wasn't a member of the list. #braincramp
