### ISSUE TITLE
p:choose and p:if are inconsistent

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#825]
In `p:choose`, we say that if no `p:when` is selected and there's no `p:otherwise`, nothing is written to any output port.

In `p:if`, we say that if the test expression is false, the step acts like an identity step on the default readable port.

That's inconsistent; I think we said that `p:if` is syntactic sugar for a `p:choose` with no `p:otherwise`.

I think `p:choose` should behave like `p:if` if there's no `p:otherwise`.

**Comment by xml-project** [comment]
:+1

**Comment by gimsieke** [comment]
Where do we say that about `p:choose`? In the current draft, as a consequence of issue #785 and PR #792, the behavior for `p:choose` with no `p:when` selected and no `p:output` is identity.

**Comment by xml-project** [comment]
I think there is an internal inconsistency too in  [p:choose](http://spec.xproc.org/master/head/xproc/#p.choose) because at the beginning it says:

>  If there are no subpipelines for which the expression evaluates to true then, if a default subpipeline was specified, it is selected, otherwise, no subpipeline runs and an empty sequence appears on all of the outputs.

At the end there is another rule, cited by @gimsieke

**Comment by ndw** [comment]
Right. So it's explicitly inconsistent in the spec and it's just an editorial oversight. I believe there's consensus on what we want the behavior to be.

**Comment by xml-project** [comment]
👍
