### ISSUE TITLE
Do sequences have to be tested?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#828]
Is this an error?

```
<p:variable name="test" select="3+5">
  <p:inline><doc1/></p:inline>
  <p:inline><doc2/></p:inline>
  <p:inline><doc3/></p:inline>
</p:variable>
```

If it is, what error should be raised?

**Comment by eriksiegel** [comment]
It doesn't look like an error to me. You set the stage for the `p:variable` by adding all those `p:inline`-s and the never use them. Not an error, just dumb.

**Comment by ndw** [comment]
I'm fine with that. It *would* be an error if my expression referred to the context, but since it doesn't, it's harmless.

**Comment by xml-project** [comment]
So: No action required. Close?

**Comment by eriksiegel** [comment]
Since there were no more comments on @xml-project 's close proposal, I close it. One down...
