### ISSUE TITLE
Proposal: p:finally cannot have a primary output port

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#829]
We have two constraints:
1. All of the subpipelines of `p:try` must have a consistent primary output port.
2. All of the output ports of `p:finally` must be distinct from any other subpipline's output ports.

It follows that if any (and therefore all) of the (non-final) branches of the `p:try` have a primary output port, the `p:finally` can't because 1 and 2 above. And if none of the non-final subpipelines have a primary output port, `p:finally` can't either because of 1.

I think we should say that explicitly somewhere.

(Alternatively, I think we could imagine a universe in which constraint 1 and 2 only apply jointly; if none of the non-final subpipelines have a primary output port, the `p:finally` is allowed to as long as it has distinct name. But I don't think we should imagine that universe.)

**Comment by ndw** [comment]
If there's agreement on the point above, a subsidiary question arises. Consider:

```
<p:try>
  <p:output port="main"/>
  ...subpipeline...
  <p:catch>
    <p:output port="main"/>
    ...subpipeline...
  </p:catch>
  <p:finally>
    <p:output port="finally"/>
    ...subpipelinee...
  </p:finally>
</p:try>
```

According to the rules, the "finally" output port is primary because it doesn't say that it's not and it's the only output port from that subpipeline.

We could force users to put `primary="false"` on the port, or we could special case the rule that makes the output port primary.

**Comment by ndw** [comment]
On further reflection, I think we should require `primary="false"`. If we make it implicitly not-primary, then it won't connect to the last step by default and that's going to be confusing since it will look like it should.

**Comment by ndw** [comment]
No one's commented, can I assume that means my proposal is non-controversial? The `p:finally` must not have a primary output port?

**Comment by xml-project** [comment]
👍
