### ISSUE TITLE
Legacy from 1.0: Does directory-listing provide the content-type in the resulting c:file elements?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#83]
# Does directory-listing provide the content-type in the resulting c:file elements? 

>This is an aggregation of the discussion on "Does directory-listing provide the content-type in the resulting c:file elements?" ([Issue 173 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/173))

**Opened by: ndw on 2015-06-10, 11:01h**

## ndw said on 2015-06-10, 11:01h:

Does p:directory-listing provide a content-type matching option? 

## ndw said on 2015-06-10, 11:07h:

For example, include-content-type and exclude-content-type parallel to include/exclude regex. 

	On 2015-10-07, 14:26h: ndw added this to the XProc 2.0 LC milestone.

**Comment by ndw** [comment]
Overtaken by #405.
