### ISSUE TITLE
Do we need to say more on p:with-input/@select

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#832]
In [p:with-input](http://spec.xproc.org/master/head/xproc/#p.with-input) for attribute "select" we say in the last paragraph:

> If a document constructed by selection consists exclusively of text nodes, then it has a content type of text/plain, otherwise it has a content type of application/xml. If the selection result is a map or an array, it is a JSON document. It is a dynamic error (err:XD0016) if the select expression on a p:input or p:with-input returns attribute nodes or function items.

Atomic values are not mentioned here. One can imply that a text document is created from the rest, but I am wondering whether we should say this explicitly.

**Comment by Conal-Tuohy** [comment]
I think the part
> If the selection result is a map or an array ...

should instead say
> If the selection result is a map, an array or an atomic value ...

**Comment by xml-project** [comment]
Yes, may be. But we decided otherwise. My question is purely editorial whether the specs are clear enough in this point.

**Comment by Conal-Tuohy** [comment]
I would say the spec as it stands is _not_ sufficiently clear. If the selection is a sequence of atomic values then it's not at all clear (to me, at least) what kind of document I should expect.

**Comment by xml-project** [comment]
Thanks. Will try to improve this.

**Comment by ndw** [comment]
If maps and arrays produce JSON documents, I think the consistent result for atomic values is also JSON documents. How is a result of type xs:integer different from a result of type map(*)? We've already agreed that integers, floats, booleans, etc. are all valid JSON documents.

**Comment by xml-project** [comment]
If I remember right we wanted xs:string (as result of function calls on selected text nodes) and text nodes to be aligned: Both should be text documents here. 
This was the reason we decided that **all** atomic values become text documents.
I have a reservation about treating xs:string different from the other atomic types. But I wouldn't object to make all atomic results JSON documents here.

**Comment by ndw** [comment]
Yes, I initially wrote "agreed that are integers, floats, strings, etc." but then I realized we already say that strings become text documents. :-)

**Comment by ndw** [comment]
Consensus: atomic values (including string) are passed along as atomic values as "JSON documents"

**Comment by xml-project** [comment]
Fixed with pr #837
