### ISSUE TITLE
p:system-properties() must behave normal during static analysis

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#839]
Currently we say on [p:system-properties](http://spec.xproc.org/master/head/xproc/#f.system-property):

> The value of the p:system-property function during static analysis is implementation-defined.

I think this is to general because a processor would be free not to expose any value during static analysis. But since these values are needed for `use-when`, interoperable pipelines need this function.
Proposal: 

1. The function behaves normal during static analysis. (Like p:version-available())
2. As an implementation may expose additional values (in a separate namespace): It is implementation defined which of these additional values are visible during static analysis. If a value is known, but not visible, an empty sequence has to be returned.

Did I miss something?

**Comment by gimsieke** [comment]
Sounds very reasonable to me
