### ISSUE TITLE
Markup in p:inline when the content type is not XML or HTML

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#845]
We have [a conflict](https://github.com/xproc/3.0-test-suite/issues/217) in the spec with respect to markup in p:inline when the content type is not XML or HTML.

The TVT prose says, use the string values. Inline says it's an error.

I propose that we remove `err:XD0063`.

**Comment by ndw** [comment]
On further discussion with Achim, I simply got it wrong. Nevermind.

**Comment by xml-project** [comment]
Close?

**Comment by ndw** [comment]
Yep.
