### ISSUE TITLE
Evaluation of attribute "as"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#846]
The [XPath specs](https://www.w3.org/TR/xpath-31/#dt-sequence-type) say:

> The in-scope schema types in the static context are initialized with a set of predefined schema types that is determined by the host language. This set may include some or all of the schema types in the namespace http://www.w3.org/2001/XMLSchema, represented in this document by the namespace prefix xs. 

I think we should state that is predefined, so I do not have to declare this namespace every time I want to type an option/variable.

**Comment by ndw** [comment]
No.

That is simply not how XML works. The set of namespace prefixes that are bound is precisely, explicitly, exactly, and only the set that have in-scope namespace declarations.

The prose quoted is clear: schema types in that namespace are in the static context and that namespace is represented *in this document* by the prefix `xs:`.

**Comment by xml-project** [comment]
I am pretty sure you are right, but I do not understand why. To my reading in
````
<p:variable name="anything" as="xs:integer*" />
````
the attribute contains a string (not a QName). And WE say, that an XProc processor has to interpret this string as an XPath sequence type. 

XPath says, the host language (=XProc) may define predefined schema types. So we are free to say that all schema types of "http://www.w3.org/2001/XMLSchema" are defined.

I do not understand the difference you make here and the use of any XPath expression in XProc where I write `$a instance of xs:integer` without declaring the namespace because it is predeclared according to the [specs](http://spec.xproc.org/master/head/xproc/#xproc-and-step-xpath-context).

**Comment by ndw** [comment]
The prose about the host language says that it may predefine schema *types*. That is a completely separate issue from the question of namespace bindings in XPath expressions. I understand that prose to mean that a processor could predefine the schema type `my:hatsize` and then this would be a valid expression: `$a as instance of Q{http://my/namespace}hatsize`.

And yes, you're right that the value of the `as` attribute is a string, not parsed by the XML parser, and we could, in principle, say that the "xs:" namespace was bound magically in that context. But it would be wrong. That's not how any other XML-based language works. Even Schematron, which doesn't use the standard `xmlns:` binding mechanism requires **a** binding mechanism.

In XML languages, you have to declare the namespaces you use. All of them. Even if you only use them in QNames in attribute values that are technically strings.

**Comment by xml-project** [comment]
Thanks. I see your point.

Why is XPath (and XQuery) different?

**Comment by ndw** [comment]
XPath is different because it doesn't really stand on its own. It's expected to be embedded in a host language. The host language makes up the rules.

XQuery is different because it's not an XML language. I think the decision to allow pre-declared namespaces in XQuery is a mistake, but that wasn't a fight I was going to win in that working group.

XML languages (Schematron, XSLT, XProc, etc.) all have to play by the XML rules.

**Comment by xml-project** [comment]
As XProc is the host language for XPath, wouldn't it be more in line with your approach to say, that
````
select="$a instance of xs:string"
````
is an error in XProc unless the namespace is declared?
