### ISSUE TITLE
Proposal: make the error port the default readable port in p:catch/p:finally

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#847]
Observations (unless I’ve overlooked something, of course):

1. If you want to read the `error` port in a `p:catch`, you have to both name the catch and fully qualify the `p:pipe` (or `@pipe`) that reads from it.
```
...
<p:catch name=“catch”>
   <p:identity>
      <p:with-input pipe=“error@catch”/>
   </p:identity>
...
```
2. The default readable port, if there is one, comes from the step that precedes the `p:try`. That doesn’t seem like a very useful default.
3. Authors can always write pipes that point back to the preceding step if they want. And that will probably feel (relatively) natural as they’re reaching outside the confines of the container that they’re in.

It’s a little odd, I admit, but I still think it might be an improvement.

**Comment by ndw** [comment]
I guess this proposal also proposes that the `error` port should be primary in `p:catch` though I suppose that’s not strictly *necessary*.

**Comment by xml-project** [comment]
👍 If I remember right, we talked about this on one of our face to face meetings, but we have never put it into the specs.
