### ISSUE TITLE
Open questions on p:viewport

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#849]
I think [`p:viewport`](http://spec.xproc.org/master/head/xproc/#p.viewport) needs to be updated to recent development:

> It is a compound step that processes a single **XML** document ....

I think we need to allow HTML documents also. And (if I am right with the next point) also Text documents.

> It is a dynamic error (err:XD0010) if the match expression on p:viewport does not match an element or document.

I think this is a leftover from XProc 1.0. Since we now use XDM i think `match` should be able to match anything except an attribute and a namespace.

> and the result that appears on the output port replaces the matched element.

I think we need to say more about what happens relative to the result's content-type.
Proposal:

1.  For an XML document and a HTML document, the matched element is replaced with all children of the result's document node.
2. For a Text document the matched element is replaced by the child of the result's document node. (This is the same as (1), but I listed it separately so can vote against it.
3. If it is a JSON document, it is an error.
4. If it is another document, it is an error.

**Comment by ndw** [comment]
I agree that we should allow HTML.

How is it useful to allow text documents? Adjacent text nodes are combined, so the document will consist of a single text node. The smallest select expression you can make on that is the whole node, so you'll replace the whole thing. (Or nothing.)

I'm still thinking about the JSON case. Does it makes sense to select a portion of the map or array? It might, but I haven't worked out if that's implementable or not. I'm certainly happy to make it an error in the short term.

I guess we should clarify that if you select the whole XML or HTML document and replace it with a text node, you get a text/plain document out.

**Comment by xml-project** [comment]
> How is it useful to allow text documents?

I did not claim, it is very useful. But I see no reason to make it an error.

> I'm still thinking about the JSON case. Does it makes sense to select a portion of the map or array? It might, but I haven't worked out if that's implementable or not. I'm certainly happy to make it an error in the short term.

I think it would be useful, e.g. updating all values in a map with a certain key. But as far as I can see, we do not have an expression language to match portions of maps/arrays, have we?

**Comment by xml-project** [comment]
In the prose of p:viewport the first line says:

> It is a compound step that processes a **single** XML document

But then the second paragraph after the syntax box reads:

>  If the p:viewport input is a sequence, **each document** in the sequence is processed

This might be confusing and I think we should fix this saying that a sequence is processed, but that every document is processed in turn (independent of the others).
