### ISSUE TITLE
Missing error code in 16.2.1

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#851]
In [16.2.1](http://spec.xproc.org/master/head/xproc/#conn-prec) we say twice:

> It will be a static error if there is no default connection.

I think we need to say, which error code has to be raised here.

**Comment by ndw** [comment]
Seems like it could be `err:XS0032` or we could make up a new error code for this case.

**Comment by xml-project** [comment]
Thanks, I was still searching: I think XS0032 is ok.
