### ISSUE TITLE
Preceding or trailing whitespace in p:inline 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#853]
In the [specs](http://spec.xproc.org/master/head/xproc/#inline-xml-content) for `p:inline` we say:

> Any preceding or following whitespace-only text nodes will be discarded.

I think the reference (preceding or following **what**) is ambiguous: Do we mean preceding/following the first none text node or do we mean before and after an element node (analogues to XML)?

**Comment by ndw** [comment]
I think we meant only leading or trailing whitespace. But I also think this is a mistake. I think that we should say all content in `p:inline` is significant.

I think we should say that leading and trailing whitespace in an *implicit* inline is discarded.

So:

```xml
<p:with-input>
  <doc> text </doc>
</p:with-input>
```

creates an input document with a single node, `doc` containing ` text `. But

```
<p:with-input>
  <p:inline>
    <doc> text </doc>
  </p:inline>
</p:with-input>
```

creates a document with three top-level nodes, initial whitespace, a `doc` element (containing ` text `), and trailing whitespace.

If we strip whitespace out of `p:inline`, then there's no way to create a document that *has* leading whitespace.

**Comment by xml-project** [comment]
👍
