### ISSUE TITLE
Does err:XD0038 apply to outputs as well?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-specification#854]
Today, `err:XD0038` reads:

> It is a dynamic error if an input document arrives on a port and it does not match the allowed content types.

Should this apply to steps that produce outputs that don't match their declared content types? Or do we need/want a different error for that?

**Comment by xml-project** [comment]
I thought this is XD0042:

> It is a dynamic error (err:XD0042) if a document arrives on an output port whose content type is not accepted by the output port specification.

Did I miss a difference?

**Comment by ndw** [comment]
No, I searched for "does not match" and that error message says "is not accepted". Thank you.
