### ISSUE TITLE
Legacy from 1.0: Deal with proposed errata 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#86]
# Deal with proposed errata 

>This is an aggregation of the discussion on "Deal with proposed errata" ([Issue 181 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/181))

**Opened by: ndw on 2015-06-12, 10:40h**

## ndw said on 2015-06-12, 10:40h:

No description provided. 

	On 2015-06-12, 10:40h: ndw self-assigned this.

	On 2015-10-07, 14:25h: ndw added this to the XProc 2.0 LC milestone.

**Comment by gimsieke** [comment]
What’s this about? Can we haz better descriptions?

**Comment by ndw** [comment]
I propose to close this as "overtaken by events"
