### ISSUE TITLE
Wording of XS0091 still needs to be changed

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#865]
After reading yesterdays PR in context, I think XS0091 needs a small update. Currently it reads:

> It is a static error if a p:option declared before the subpipeline begins shadows another option declared within the same p:declare-step.

The phrase "declared before the subpipeline begins" is a relict from static variables because afaik every option (static or not) is declared before the subpipeline begins. So the phrase is not wrong but may be misleading.

**Comment by gimsieke** [comment]
Agree, simply delete “declared before the subpipeline begins”

**Comment by xml-project** [comment]
Already did with pr #867 What did I miss?

**Comment by gimsieke** [comment]
I thought this one referred to another place that XS0091 was mentioned in. Maybe I should have looked at the notifications in chronological order…

**Comment by xml-project** [comment]
Ok, thanks. I thought I overlooked another appearance of the phrase.
