### ISSUE TITLE
Handling of attribute nodes output conversion?

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#869]
In section http://spec.xproc.org/master/head/xproc/#documents.6 we write:

> If the item is any other node (except for a document node), a document node is wrapped around the node and the document's content-type is application/xml.

What happens with attribute nodes? AFAIK you cannot have an attribute node as a child of a document node.

**Comment by xml-project** [comment]
Right. But the sections starts:

>  Some steps like p:xslt, p:xquery etc. create a sequence of new XDM instances. 

As you can not return an attribute for p:xslt etc. the passage seems right to me.

But if you feel we need to say, that an attribute can not be returned from p:xslt etc. it would be fine for me.

**Comment by eriksiegel** [comment]
You're right, you cannot output an attribute node (I just tried). I'll try to make this more clear in the prose.
