### ISSUE TITLE
Legacy from 1.0: Sibling shadowing for variables should be allowed. 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#87]
# Sibling shadowing for variables should be allowed. 

>This is an aggregation of the discussion on "Sibling shadowing for variables should be allowed." ([Issue 182 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/182))

**Opened by: alexmilowski on 2015-06-12, 13:28h**

## alexmilowski said on 2015-06-12, 13:28h:

In the current proposed XProc 1.0 errata (E.13), we clarified that variables can shadow up but not "left" (preceding siblings). We should remove this restriction in 2.0 to make XProc more like XQuery and XSLT. Variables can be redefined in both of those languages by following sibling elements. 

## josteinaj said on 2015-06-12, 13:45h:

Also, I don't know if it's been discussed in the WG but (like in XSLT) it would be useful if `p:variable` was not restricted to the beginning of a subpipeline: 

[https://github.com/xproc/specification/blob/50c0ed0fe6437bb8e52315eabc41fe6d6b3a8a35/langspec/xproc20/xproc20.xml#L340](https://github.com/xproc/specification/blob/50c0ed0fe6437bb8e52315eabc41fe6d6b3a8a35/langspec/xproc20/xproc20.xml#L340) 

I would prefer not having to wrap stuff in a `p:group` just because I want to define a variable: 

```
<p:pipeline>
	<p:xslt>...</p:xslt> 
	<p:group> 
		<p:variable name="number-of-chapters" select="..."/> 
		... 
	</p:group> 
</p:pipeline>
```

(Having to wrap it in a `p:group` also makes it more difficult to connect steps sometimes.) 

## vojtechtoman said on 2015-06-12, 13:53h:

Does redefining of variables introduce new links to the dependency graph? I have to think about it some more, but there may arise ordering paradoxes if it doesn't. Or... maybe not - just recording the paranoiac voices whispering into my ear. 

## ndw said on 2015-06-14, 17:57h:

[@vojtechtoman](https://github.com/vojtechtoman) yes, it introduces new links because variable bindings that used to be an error are now simply shadowings of previous siblings. But I don't think there's any danger of paradox. 

```
	<p:variable name="foo" select="3"/>
	<p:variable name="bar" select="$foo + 1"/>
	<p:variable name="foo" select="4"/>
	<p:variable name="baz" select="$foo + $bar"/>
```

is entirely equivalent to 

```
	<p:variable name="foo.1" select="3"/>
	<p:variable name="bar" select="$foo.1 + 1"/>
 	<p:variable name="foo.2" select="4"/>
  	<p:variable name="baz" select="$foo.2 + $bar"/>
```

In both cases, I've left out the connections but they already exist in the language. Being able to shadow preceding siblings is just fiddling with the scope of variables. 

[@josteinaj](https://github.com/josteinaj) everytime the "variables at the top of compound steps" rule comes up, we've tried to remove that restriction. We've always failed. I'll try to write something up about it. 

## ndw said on 2015-06-14, 19:05h:

See also: [https://github.com/xproc/notes/blob/master/vargroup/index.adoc](https://github.com/xproc/notes/blob/master/vargroup/index.adoc) 
Document is now [here.](https://github.com/ndw/xproc-notes/blob/master/vargroup/README.adoc)

## josteinaj said on 2015-06-15, 07:41h:

[@ndw](https://github.com/ndw) Interesting read. 

However, can't you can cause the same problem in v1.0 by just wrapping the variables with`p:group`s like this?: 

```
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns : p="http://www.w3.org/ns/xproc" xmlns : c="http://www.w3.org/ns/xproc-step" version="1.0">

	<p:load name="loader">
		<p:with-option name="href" select="static-base-uri()"/> 
	</p:load> 
	<p:group name="mine1"> 
		<p:output port="result"/> 
		<p:variable name="foo" select="5"> 
			<p:pipe step="loader" port="result"/> 
		</p:variable> 
		
		<p:add-attribute match="/*" attribute-name="foo"> 
			<p:with-option name="attribute-value" select="$foo"> 
				<p:pipe step="mine2" port="result"/> 
			</p:with-option> 
		</p:add-attribute> 
	</p:group> 
	
	<p:group name="mine2"> 
		<p:output port="result"/> 
		<p:variable name="bar" select="6"> 
			<p:pipe step="mine1" port="result"/> 
		</p:variable> 
		
		<p:add-attribute match="/*" attribute-name="bar"> 
			<p:with-option name="attribute-value" select="$bar">
				<p:pipe step="loader" port="result"/> 
			</p:with-option> 
		</p:add-attribute> 
	</p:group> 
	
	<p:store href="file:/tmp/out.xml"> 
		<p:input port="source"> 
			<p:pipe step="mine1" port="result"/> 
		</p:input> 
	</p:store> 
</p:declare-step>
```

(edit: updated with working v1.0 example) 

Or maybe I'm missing something. In any case, this seems to be yet another "simple for authors" vs "simple for implementers" issue. 

## ndw said on 2015-06-15, 17:05h:

Yes, that pipeline does seem to cause an undetected loop in XML Calabash.blush 

And yes, even before that discovery :-), I was pretty much convinced that we should fix this in 2.0. 

	On 2015-10-07, 14:25h: ndw added this to the XProc 2.0 Next PWD milestone.

**Comment by ndw** [comment]
I'm pretty sure I posted a proposal to fix this.

**Comment by xml-project** [comment]
I think we should separate this into two issues:

1. Sibling shadowing for variables (Opened by: alexmilowski on 2015-06-12, 13:28h)

1. Variables everywhere  (@josteinaj said on 2015-06-12, 13:45h:)

Two very different problems. I am in favour of both, but (1) seems to me easy to solve, while (2) raises some interesting questions about XPath context for att "select".

**Comment by xml-project** [comment]
See also #68

**Comment by ndw** [comment]
I think this is resolved in the current spec? Anyone disagree?

**Comment by ndw** [comment]
I'm saying "nope".
