### ISSUE TITLE
Final editorial changes

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#873]
Let's use this issue to gather things we need to do to finalize things. Add a comment if you think of something.

**Comment by eriksiegel** [comment]
Change all straight single (and double, are there any?) quotes in the text with the right typographical ones

**Comment by xatapult** [comment]
Shouldn't we change the status of the thing after this is finished? It now reads "Editor's draft"?

I'm not sure what the status should become but Editor's draft doesn't sound right to me. Any suggestions?
