### ISSUE TITLE
Different behavior of p:output on p:for-each / p:viewport

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#878]
Is there a reason for the different rulings for p:output on these two steps? If so, please enlighten me, because I always fail to explain, why these two steps behave so differently.

If not: Do we want to harmonize them, so they behave in the same way? Or do you think its too late for this?

**Comment by ndw** [comment]
A for-each can produce any number of outputs; if you don't specify any outputs, then you get an anonymous primary output if the last step in the subpipeline has a primary output port, just like other compound steps.

A viewport can produces one output: the input document as modified by the viewport subpipeline. If you don't specify any outputs, then you get an anonymous primary output if the last step has a primary output. It should be an error if the last step doesn't have one and there isn't an output specified.

Does that help explain the difference?

**Comment by xml-project** [comment]
@ndw That is super helpful, thanks Norm. I will quote you on this if you do not mind.
