### ISSUE TITLE
Legacy from 1.0: define doc metadata properties

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#88]
# define doc metadata properties 

>This is an aggregation of the discussion on "define doc metadata properties" ([Issue 183 of the xproc/1.0-specification](https://github.com/xproc/1.0-specification/issues/183))

**Opened by: xquery on 2015-06-12, 13:36h**

## xquery said on 2015-06-12, 13:36h:

We could provide a list of document metadata properties that every xproc processor must support. Maybe useful to have a normative section (very small) eg. 

* name/uri 
* content-type 

and non normative list. 

## vojtechtoman said on 2015-06-12, 13:58h:

Just thinking out loud: some info about the origin/history of the document? Like the name of a step that produced the document or maybe even an accumulated list of steps that the document passed through; timestamps; ... 

	On 2015-10-07, 14:24h: ndw modified the milestone: XProc 2.0 Next PWD, XProc 2.0 LC.

## ndw said on 2015-10-07, 14:31h:

See also: issue #146 in the XProc 1.1. legacy[#146](https://github.com/xproc/1.0-specification/issues/146): **now**: issue[#70](https://github.com/xproc/3.0-specification/issues/70). See Gerrit's comment below.

## ndw said on 2015-10-07, 14:34h:

See also: issue #138 in the XProc 1.1. legacy[#138](https://github.com/xproc/1.0-specification/issues/138): **now**: issue[#66](https://github.com/xproc/3.0-specification/issues/66).

**Comment by gimsieke** [comment]
see also #70
