### ISSUE TITLE
Attribute @document-properties on p:inline / p:document

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#881]
Unless I overlooked something, I think we need to say more about the XPath expression in this attribute if it appears on p:with-input.
We say, that the XPath expression is evaluated statically if the p:inline, p:document is a child of p:input / p:output. This means only static options and no context item.

But I found nothing on p:with-input/p:inline/@document-properties and p:with-input/p:inline/@document-properties. 
1. Since the expression is not on the "static evaluation" list, I assume it is evaluated dynamically, right?
2. Therefor all inscope variables/options are visible, right?
3. It the default readable port the context-item of the XPath expression? I assume it is.

Does I make sense to say so explicitly in the specs? What did I miss?

**Comment by ndw** [comment]
That all sounds right to me, and yes, probably worth making explicit in the spec.

**Comment by eriksiegel** [comment]
@xml-project: In an attempt to pick up this issue I was trying to find the spot in the spec where:

>We say, that the XPath expression is evaluated statically if the p:inline, p:document is a child of p:input / p:output. This means only static options and no context item.

I looked all over but couldn't find it... Do you remember  what you were referring to?

**Comment by xml-project** [comment]
It is a consequence of [this](http://spec.xproc.org/master/head/xproc/#static-expressions), isn't it?

**Comment by eriksiegel** [comment]
Yes... but that states it quite clearly and doesn't specifically mention document properties. II don't really think making things more explicit is necessary.

**Comment by xml-project** [comment]
> Yes... but that states it quite clearly and doesn't specifically mention document properties. II don't really think making things more explicit is necessary.

Yes, it's about p:input/p:output, but my original problem (first post) was p:with-input!

**Comment by ndw** [comment]
We should say that the default readable port provides the context items for all expressions, just as we already say it for syntactic shortcut options in AVTs.
