### ISSUE TITLE
Map 'serialization' and p:document-properties-document()

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#884]
in the [specs](http://spec.xproc.org/master/head/xproc/#f.document-properties-document) we say:

> If a map appears as a value, the property element will have an attribute named map with the value “true”. It is implementation-defined how or if a processor attempts to serialize maps that appear in document properties. If the implementation does not serialize maps, the property element will be empty.

Can we still get away with this after we introduced map as value for 'serialization' ourselves?

**Comment by xml-project** [comment]
Editors call on 2019-10-03: We should specify some interoperable xml representation for maps in document properties.

**Comment by eriksiegel** [comment]
20191109: Achim has a solution for this and will propose this shortly.

**Comment by xml-project** [comment]
See #909
