### ISSUE TITLE
Be more explicit about syncing base-uri document properties with base URIs

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#889]
In the [Document Properties](http://spec.xproc.org/master/head/xproc/#document-properties) section we say:

> The processor is responsible for assuring that the `base-uri` property matches the base URI of each document produced on every output port.

I think it is obvious that this implies: If, for example, `p:xslt` produces documents with base URIs on its secondary output port, the processor needs to equip these documents with a corresponding `base-uri` property.

But is it also implied that if a property is set using [`p:set-properties`](http://spec.xproc.org/master/head/steps/#c.set-properties) or a `document-properties` option (for example on `p:inline`), what is then returned by `base-uri(/)` should reflect the new value?

I think it is implied since otherwise the document property and the base URI wouldn’t match. Or if the base URI weren’t affected but property and base URI were still supposed to match, `p:set-properties` couldn’t be used to alter the base URI.

Therefore I think also setting the property needs to manipulate the base URI, and I think we should make this explicit. 

And we probably need to say which has precedence for `p:inline`, `p:load`, `p:document` and maybe some more: 
* The `base-uri` property that comes from the `properties`/`document-properties` map 
* or the base URI of the `p:inline` / the loaded document?

I’d say the map needs to have precedence because otherwise you cannot override a base URI of a document node.

**Comment by xml-project** [comment]
I agree with the general line of your thoughts. However I have two remarks

- Just before the phrase you quoted, the specs say: "If no such key is present, the document has no base URI." Unless I am totally missunderstanding this phrase, this rules out the p:xslt case you made, unless pipeline authors explicitly use set-property. Here the two sentences obviously contradict each other. I think we should remove the sentence I quoted, which is inline with your approach.
- My second point results from the divergence of base uri (as defined in the [XDM specs](https://www.w3.org/TR/xpath-datamodel-31/#dm-base-uri)) and xs:anyURI (as defined in [XMLSchema](https://www.w3.org/TR/xmlschema11-2/#anyURI)) A base uri is defined with refence to "URI reference" (RFC 3986). So we have either to invent a mechanism converting the base-uri property (xs:anyURI) to the document's base uri (URI). Or we have to say, that the base-uri property has to be a URI. Do you see any other, hopefully easier and less intrusive, solution?

**Comment by xml-project** [comment]
In another line of thought: Do we realy need the distinction between the base-uri-property and the base-uri of the represented document for XML, HTML and text documents? Couldn't we just say, that for this document types, the base-uri property _is_ the base uri of the represented document? There would be no need to synchronize any more, would it?
For JSON and binary documents the represented document does not have a base uri, so there is no need for synchronization either. The basi-uri property for those documents does not have any further meaning or use. Its just a label to recognize these documents.
Wouldn't this solve the synching problem by simply remove its cause?

**Comment by gimsieke** [comment]
I recently wanted to set, in XProc 1.0, the base URI of an XML document. The base URI of `/`, not of `/*`. The latter I could have changed by adding an `@xml:base` attribute.
I didn’t see a simple solution. The only way I came up with was by using `p:xslt` and `xsl:result-document`. 
The scenario was a bit like in [`pxp:zip`](http://exproc.org/proposed/steps/other.html#zip): You have a sequence of documents on the input port and a sequence of URIs (from manifest entries or, in my case, an option with space-separated URIs). The task is to use documents with matching base URIs from the source port and, if there is no such document on the source port, load it from this URI from disk. The documents obtained either way will be passed to the result port. A key requirement is that they retain their base URIs.
I can do this with XSLT, but unfortunately, in a single `p:xslt` step I cannot write to an URI that I have just read from, due to [XTDE1500](https://www.w3.org/TR/xslt-30/#err-XTDE1500). Thus I needed to append another `p:xslt` step just to restore the base URIs to their original values. The [resulting step](https://github.com/transpect/xproc-util/blob/master/load/xpl/load-sources.xpl) (including a bit of documentation) is 78 lines long.

I’d say that the task sounds quite simple and I expect that there should be a simple XProc solution, at least in 3.0. But the only two methods that let me manipulate a document node’s base URI is via XSLT as sketched above or by document property overrides. Because the XSLT solution is bonkers, I want to be able to use `p:set-properties` et al. in order to influence what `base-uri(/)` will report as the base URI.

**Comment by xml-project** [comment]
I am not sure how this contributes to the point under discussion or my previous statements on this point. Isn't the switch from XML to XDM a game changer, so that observations on XProc 1.0 are not longer relevant?

**Comment by gimsieke** [comment]
The original point was (with my use case in mind): How do we synchronize the base URI and the `base-uri` document property. You proposed: We synchronize them by declaring that the base URI is always in the lead and that the document property is a read-only view of this base URI. Upon which I asked: How, if not by manipulating the `base-uri` document property, can I change the base URI of a document node?

**Comment by xml-project** [comment]
> You proposed: We synchronize them by declaring that the base URI is always in the lead and that the document property is a read-only view of this base URI. Upon which I asked: How, if not by manipulating the base-uri document property, can I change the base URI of a document node?

OK, so I was not able to make my point. I never ment to propose a read-only view. As I said above, I agree with your line of thought.

**Comment by gimsieke** [comment]
Ah, I see. Sometimes it is better to speak with each other in person… Then these misunderstandings can be avoided more quickly, or one can use their fists to reinforce an argument ;)

But even if we say that both are identical, still two people can have different opinions about whether it must be possible to change the base URI by altering the document property. Or whether it is possible to override the base URI of a `p:inline` document using the `@document-properties` attribute.

**Comment by xml-project** [comment]
> Or whether it is possible to override the base URI of a p:inline document using the @document-properties attribute.

May be this is a stupid question and I overlook something, but: How do you set the documents base uri (= the base uri property of the document node) with p:inline? To my reading you can't, you can just set the base uri of the root element.
This is why I always thought (and implemented) that the base-uri property in `document-properties()` sets this.
What did I miss?

**Comment by gimsieke** [comment]
Yes, of course, you can use, in a pipeline that has an entirely different base URI,
```xml
<p:inline xml:base="http://acme.com/foo.bar"><doc/></p:inline>
```
in order to set the base URI of the inline `doc/>` document to `http://acme.com/foo.bar`. So for `p:inline`, there is indeed an existing (also 1.0) method to set the base URI of the inlined document’s document node.

Still we need to specify for `p:inline` which has precedence: The base URI of `p:inline` or the map entry of the `document-properties` map attribute. Or whether the `document-properties` attribute has an effect at all on the base URI.

And still the question remains how to change the base URI of an XML document that does not originate from `p:inline` (but `p:load`, `p:xslt`, etc.).

**Comment by xml-project** [comment]
Thanks. I think you are right that we need to say more about this in the specs. I understood  @document-properties to take precedence, but reading the specs on this, I can not give any prove for this reading.

**Comment by gimsieke** [comment]
What about the sentence I proposed to add in https://github.com/xproc/3.0-specification/pull/890#pullrequestreview-304252528?

The proposal was:

And I suggest that we add a sentence to [§ 14.3 Base URIs and xml:base](http://spec.xproc.org/master/head/xproc/#xml-base-attribute), for example:

> The base URI of a document node may be manipulated by changing the `base-uri` document property.

**Comment by xml-project** [comment]
Don't rush me please. The PR I filed is against the step repo. The main specs (where you sentence goes) is next. I do not know a way to address two repos with one PR. Do you?

**Comment by xml-project** [comment]
I think this is basically fixed apart from Gerrits request.

**Comment by xml-project** [comment]
Consensus on editorials call 2019-10-31:
1. On p:inline, p:document, p:load and with p:set-properties the base uri property of the underlying XML, HTML, or text document is changed. For JSON documents and other documents the processor keeps track of the property.
2. The value for key "base-uri" has to be an xs:anyURI.
3. The processor calls p:urify() on this value (to be extended by @gimsieke to cover non ascii characters and not allowed ascii characters in URI according to RFC 3986)
4. If the result of calling p:urify() is not an absolute URI according to RFC 3986, a dynamic error is raised.

**Comment by eriksiegel** [comment]
Number 3 and 4 above no longer apply

**Comment by eriksiegel** [comment]
New 3: The resulting URI must be absolute and must be valid according to RFC3986, otherwise an error code is raised.

Spec needs to be updated to reflect these decisions. Only the new 3 needs to be added.

And: if you specify any document properties they overwrite any existing document properties , for example on p:document.

**Comment by xml-project** [comment]
set-property still needs a change.

**Comment by xml-project** [comment]
try to fix the last point with PR in [steps](https://github.com/xproc/3.0-steps/compare/master...xml-project:fix-889?expand=1)

**Comment by xml-project** [comment]
Fixed with pr 889 (steps).
