### ISSUE TITLE
Revert PR #89 and steps #250

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#894]
I propose to revert
https://github.com/xproc/3.0-specification/pull/890
https://github.com/xproc/3.0-steps/pull/250

and thereby solve
https://github.com/xproc/3.0-specification/issues/892
https://github.com/xproc/3.0-steps/issues/251

I think the discussion has shown, that these PRs were premature because we have to agree on a concept of base URI and its valid values first.

**Comment by gimsieke** [comment]
It wasn’t specified that the base URI is read-only. 
This was specified:
> The processor is responsible for assuring that the base-uri property matches the base URI of each document produced on every output port. 
If you want to prevent `p:set-properties` from changing the `base-uri` property, you need to say that an attempt to change it must be ignored by the processor or an error must be raised.
