### ISSUE TITLE
Another aspect of synchronizing XProc's document property 'base-uri' and documents base uri property

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#897]
This is related to #889 , but as I do not want to interfere with @gimsieke's work on this, I raised an new issue:

Currently (to my understanding) we [say](http://spec.xproc.org/master/head/xproc/#document-properties), that if a document has no base-uri, the 'base-uri' key in the document properties document is not present. I think we should change that, saying that the 'base-uri' property is always present, but associated with the empty sequence for documents without a base uri.

This approach is more in line with XPath's approach to the document URI property.

**Comment by gimsieke** [comment]
No objection

**Comment by eriksiegel** [comment]
Main reason: `p:document-property()` function usage.

We decide against it. If a document does *not* have base-uri the document-properties does map does not have base-uri entry.

**Comment by eriksiegel** [comment]
Still have to clarify what the word optional means for the base-uri property.

**Comment by ndw** [comment]
Fixed by #903
