### ISSUE TITLE
How to handle errors in URIs

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-specification#899]
Related to the discussion going on in https://github.com/xproc/3.0-steps/pull/255

How are we going to handle normalization and errors in URIs, for instance in the URIs pased to the archive related steps?

We could have them handled by `p:urify` (if we decide to run every URIs through this function before use). It should raise an error for relative URIs then.

**Comment by xml-project** [comment]
See minutes of cologne workshop

**Comment by eriksiegel** [comment]
See also https://github.com/xproc/3.0-steps/issues/248
