### ISSUE TITLE
content-type attribute on p:output

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#93]
For step documentation and (some) static type checking it would be useful to have a content-type attribute also on the declaration of output ports.

**Comment by ndw** [comment]
What is the consequence if the step output doesn't match (any of) the specified content type(s)?

**Comment by gimsieke** [comment]
Similar to what happens when you declare a variable in XSLT or XQuery and the variable’s assigned content doesn’t match the declaration?

**Comment by ndw** [comment]
Ok. It seems less useful to me because for the vast majority of steps you know what the output type is going to be. But there's no reason not to provide it for completeness and uniformity if nothing else.

**Comment by xml-project** [comment]
Think of a pipeline you wrote (or a colleague) two years ago: If you want to call this pipeline from another pipeline now, it seems to be useful, if the pipeline states that it will produce results of a specific content type and you do not have to look up the flow. I agree that is is ness useful for steps in the standard library.

**Comment by ndw** [comment]
Yes, I'm in favor of the idea.

**Comment by ndw** [comment]
Yes, we should do this. It's a dynamic error if the step produces a content type that doesn't "match" the content type.

**Comment by gioele** [comment]
The definition of what does it mean that "two content type strings match" is discussed in issue #139.

**Comment by xml-project** [comment]
Solved by @ndw in #143 143

**Comment by xml-project** [comment]
@ndw I think we can close this. We have to add the attribute in the main section etc., but that is issue #152.

**Comment by ndw** [comment]
I concur.
