### ISSUE TITLE
Examples in https://spec.xproc.org/master/head/xproc/#parallelism seem to be incomplete

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-specification#938]
When reading https://spec.xproc.org/master/head/xproc/#parallelism I am a bit puzzled, it says "consider the following pipeline" and shows the snippet

```
<p:xslt name="generate-stylesheet">
    <p:with-input port="source" href="someURI"/>
    <p:with-input port="stylesheet" href="someOtherURI"/>
  </p:xslt>

  <p:store name="save-xslt" href="gen-style.xsl"/>
```

Later on it seems to show the exact same snippet but says "Now the result is independent of the implementation strategy".

I have tried to look at the source and it seems it uses XInclude in https://github.com/xproc/3.0-specification/blob/master/xproc/src/main/xml/parallel.xml with two different files but somehow the section in the complete spec cuts off the last part of the two examples so that they both end up looking the same.

**Comment by xml-project** [comment]
Right, the examples are broken because a third step (which makes the difference) is missing. The original example comes from the 1.0 specs: https://www.w3.org/TR/xproc/#parallelism
I will fix this. Thanks for finding.

**Comment by xml-project** [comment]
Here are my findings: As far as I understand the build process, the files 

- "../../../build/examples/par1.txt"

- ../../../build/examples/par1b.txt"

are created from

- "3.0-specification/xproc/src/main/examples/par1.xml"
- "3.0-specification/xproc/src/main/examples/par1b.xml"

The later seems to be correct, so something in the build process is broken causing the last steps in the "xml"-documents not to be copied in the "txt"-documents.
As I am not completly familar with the whole build process, this is someting @ndw has to look in.

**Comment by ndw** [comment]
Fixed. (Or "fixing" as I expect the update is still building at the moment.) Thank you!
