### ISSUE TITLE
p:for-each example uses pipe="chapters@current"

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-specification#943]
The section 15.2.2 in https://spec.xproc.org/master/head/xproc/#p.for-each has an example 5 "A Sample For-Each" which declares `<p:for-each name="chapters">` and then inside uses `<p:with-input port="source" pipe="chapters@current"/>`.

Isn't that supposed to be `<p:with-input port="source" pipe="current@chapters"/>`, as the syntax wants the port name first and then the step name after the `@` sign?

**Comment by xml-project** [comment]
Right. We had it the other way around before, so this is a legacy error.

**Comment by gimsieke** [comment]
That’s quite possible since we reversed the shorthand syntax at some point.
