### ISSUE TITLE
Should XProc 3 rnc or rng schema work with oXygen 22?

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-specification#945]
I have download the XProc 3.0 rng and rnc schemas linked from the spec in https://spec.xproc.org/master/head/xproc/#ancillary-files to use them inside oXygen 22 to have content completion and validation when trying to write my first XProc 3 attempts.

But for some reason oXygen throws up four errors inside the schema

```
System ID: C:\SomePath\XProc3\xproc30.rnc
Main validation file: C:\SomePath\XProc3\some-file.xml
Engine name: Jing
Severity: error
Description: an "element" pattern containing an "attribute" pattern with a non-null ID-type must have a name class that contains only "choice" and "name" elements
Start location: 483:3

System ID: C:\SomePath\XProc3\xproc30.rnc
Main validation file: C:\SomePath\XProc3\some-file.xml
Engine name: Jing
Severity: error
Description: an "element" pattern containing an "attribute" pattern with a non-null ID-type must have a name class that contains only "choice" and "name" elements
Start location: 473:3

System ID: C:\SomePath\XProc3\xproc30.rnc
Main validation file: C:\SomePath\XProc3\some-file.xml
Engine name: Jing
Severity: error
Description: conflicting ID-types for attribute "id" from namespace "http://www.w3.org/XML/1998/namespace" of element "load" from namespace "http://www.w3.org/ns/xproc"
Start location: 514:3

System ID: C:\SomePath\XProc3\xproc30.rnc
Main validation file: C:\SomePath\XProc3\some-file.xml
Engine name: Jing
Severity: error
Description: conflicting ID-types for attribute "id" from namespace "http://www.w3.org/XML/1998/namespace" of element "load" from namespace "http://www.w3.org/ns/xproc"
Start location: 508:14
```

The file references the schema with `<?xml-model href="xproc30.rnc" type="application/relax-ng-compact-syntax"?>`.

Is anyone using those schemas with oXygen successfully?

**Comment by xatapult** [comment]
I'm using: `xproc-3/3.0-grammar/build/xproc30.rng`, successfully. I haven't used the compact syntax version.

I think (@ndw, can you help us out?) that you need to use the build version of the schemas, but I'm not sure.

**Comment by martin-honnen** [comment]
@xatapult, thanks, with the help of the oXygen support I got the schema from the XProc 3 spec to work, the errors I got can be prevented by disabling id/idref checks in the oXygen/RelaxNG parser settings.

**Comment by ndw** [comment]
Right. That's what you have to do. It's a consequence of the design of id/idref checks in RNG. The compact and XML forms should be the same, @xatapult
