### ISSUE TITLE
Inconsistency in spec of select attribute of p:input and p:with-input?

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-specification#946]
When I read in https://spec.xproc.org/master/head/xproc/#p.input about the `select` attribute

> It is a dynamic error (err:XD0016) if the select expression on a p:input or p:with-input returns anything other than document nodes, element nodes, processing instruction nodes, comment nodes, text nodes or an empty sequence.

and then in https://spec.xproc.org/master/head/xproc/#p.with-input 

> If a document constructed by selection consists exclusively of text nodes, then it has a content type of text/plain, otherwise it has a content type of application/xml. If the selection result is a map or an array or an atomic value, it is a JSON document. It is a dynamic error (err:XD0016) if the select expression on a p:input or p:with-input returns attribute nodes or function items.

then it seems to me that the first quote prescribes an error (for any `select`ion on `p:with-input` being not of the node types in the quote) while the second quote specifies that non-node values like map, array or atomic values are selectable, only attribute nodes or function items are not selectable.

Those two quotes seem to contradict each other in terms of the possible allowed types of selected values.

**Comment by gimsieke** [comment]
As one can imagine, the `p:input` wording predates the `p:with-input` wording. The latter has been amended when @xml-project addressed #702 and #832. We need to rephrase `XD0016` for `p:input/@select` accordingly.

**Comment by ndw** [comment]
👍
