### ISSUE TITLE
Validate option attributes or not?

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#948]
When I validate an XProc 3.0 pipeline it says my pipeline is invalid when I write something like this:

```xml
<p:directory-list detailed="{$detailed}"> ...
```

The message is: `value of attribute "detailed" is invalid; must be a boolean`

Well... yes and no. 

Given that very complex things can happen using AVTs in option attributes, maybe we should not validate their contents at all?

Opinions please.

**Comment by gimsieke** [comment]
Let’s get rid of AVTs. I didn’t like the idea in the first place, anyway.

**Comment by xatapult** [comment]
LOL

The resolution is I suppose simple: Make sure that in the schema all option attributes have the type `xs:string` or something like that.

**Comment by gimsieke** [comment]
Seriously, one option is not to specify the type as boolean but as a regex like `'(\{.+\}|true|false)'` (in RNG, patterns are automatically anchored), but then `<p:directory-list detailed="{$t}rue">` will be flagged as invalid. Or we can accept any string.

We might leave the current RNC or RNG as it is and generate these more liberal patterns.

**Comment by ndw** [comment]
Sounds like a schema bug, one way or another. 

I created https://github.com/xproc/3.0-grammar/issues/5 to track this.

**Comment by xatapult** [comment]
Ok, then we can close this one.
