### ISSUE TITLE
p:variable @visibility is superfluous?

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#949]
We still specify a `@visibility` attribute on a `p:variable`. But we no longer allow global variables in libraries (superseded by global static options). Therefore I think `p:variable/@visibility` must be removed.

**Comment by xml-project** [comment]
👍 Ups.

**Comment by xatapult** [comment]
I'll create a PR for this

**Comment by xatapult** [comment]
I changed the text in #950. Don't know how to change the schema. Can somebody else do this?

**Comment by gimsieke** [comment]
I changed it in the online editor

**Comment by xml-project** [comment]
@xatapult @gimsieke Can we close this issue?
