### ISSUE TITLE
Typo in  example 7.1. Evaluating expressions during static analysis

### ISSUE THREAD

**Issue by daliboris** [xproc/3.0-specification#951]
In the example
```
<p:option name="B" static="true" select="$A + count(//*)">
    <p:document href="doc.xml"/>
</p:variable>
```

Opening tag should be `<p:variable>`.

**Comment by xatapult** [comment]
Hi @daliboris . That's not the case. There are no static variables in XProc 3.0 (anymore). That's all superseded now by static *options*.

**Comment by gimsieke** [comment]
When fixing the example, we need to remove the one remaining reference to static variables in [`p:option/@select`](https://spec.xproc.org/master/head/xproc/#err.inline.D0001.4). This could be considered as a substantive fix that needs to be recorded in the change log.

**Comment by daliboris** [comment]
OK, thanks. I'm beginner and waiting for the announced book.

But there is still problem with no corresponding opening (**<p:option>**) and closing (**</p:variable>**) tag in the example. Or am I wrong?

**Comment by xml-project** [comment]
> But there is still problem with no corresponding opening (<p:option>) and closing (</p:variable>) tag in the example. Or am I wrong?
No, of course you are right. We have to fix this too.
