### ISSUE TITLE
@select on p:with-input (and related constructs)

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#965]
I think there is (a) a contradiction in the current specs and (b) the case of a *sequence* with atomic values is not correctly covered.

ad a): On [select](https://spec.xproc.org/master/head/xproc/#p.with-input) we say:

> If the result from applying the select expression to the document(s) is an atomic value, a text node with the corresponding string value is created.

But then (in the last paragraph on `@select`):

> If the selection result is a map or an array or an atomic value, it is a JSON document. 

So what is it: A text node (= a text document) or a JSON.

I think what we want to say is: If the result is an xs:string, a text node is created. Otherwise (for any other atomic value, array or map) it a JSON document. Right?

ad b): As far as I understand the prose we do not cover the case where the result of `@select` is a mixed sequence of nodes, atomic values etc. Consider: `p:with-input select="(1,2)"` I think the result should a sequence of two JSON documents, but I do not think this is clearly stated in the section.
What did I miss?

**Comment by xatapult** [comment]
I agree with @xml-project . 

What we decide here should IMHO be consistent with what we say in [Creating documents from XDM step results](https://spec.xproc.org/master/head/xproc/#documents.6).

**Comment by xatapult** [comment]
Consensus, yes, like stated above.
