### ISSUE TITLE
base-uri inside p:viewport

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#966]
During the testing of Morgana an issue came up: https://github.com/xml-project/MorganaXProc-IIIse/issues/34

What is the base-uri of the current document inside a `p:viewport`?

**Comment by gimsieke** [comment]
The spec says: 

> The base URI of the resulting document that is passed to the subpipeline is the base URI of the matched element or document.

So if you have matched `div` in the source document, the document node that wraps each `div` on the `current` port has the same base URI as the `div` element when it was part of the source document.

(The quote above implies that you can only match elements or document nodes, but you should at least also be able to match text nodes. The surrounding document node will have the text node’s base URI. What else can we match? PIs? Is the issue that we can match something that results in a JSON document?)

I don’t have access to https://github.com/xml-project/MorganaXProc-IIIse/issues/34

**Comment by xml-project** [comment]
>  I don’t have access to https://github.com/xml-project/MorganaXProc-IIIse/issues/34

No, you haven't. Sorry.

But what is the base uri of the document inside the p:viewport is from a matched pi ,text or comment. We do not say anything about this, so I conclude, it does not have a base uri. 
RIght?

**Comment by xatapult** [comment]
Maybe. But in the case of the issue I raised for Morgana (that @ndw and @gimsieke can't access) the match was an element and it had still no base-uri. So is this a bug or do we interpret the spec differently?

For non-element we might look at the parent for a base-uri? Or indeed provide an empty one.

**Comment by gimsieke** [comment]
At least this seems to be clearly specified: If the element _had_ a base URI in the source document, the document on `current` must have the same base URI.

**Comment by xml-project** [comment]
@xatapult Fixed the bug with yesterdays release.

**Comment by ndw** [comment]
Conclusion: in `p:viewport`, the sentence
>The base URI of the resulting document that is passed to the subpipeline is the base URI of the matched element or document.

should read:

>The base URI of the resulting document that is passed to the subpipeline is the base URI of the matched node.
