### ISSUE TITLE
Does section on PSVIs in XProc need an update?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#968]
Could someone who is more familiar with PSVI than me please have a look on the section
[PSVIs in XProc](https://spec.xproc.org/master/head/xproc/#psvi-support), especially point (5) near the end of the section.
I think it is evident that we have to say "XSLT 2.0 or higher" there, but I am worried about the phrase

> implementations must not include PSVI properties in the outputs of steps defined by this specification. 

I think this is a verbatim copy of the 1.0 specification where all atomic steps we defined in the same document containing this sentence. If I am not mistaken we need to add a reference to the standard step library, the validation library etc.

**Comment by xatapult** [comment]
Consensus. We think that the only one knowledgeable enough is @ndw ... So, sorry, we assigned you...
