### ISSUE TITLE
Can use of position() or last() raise err:XD0001?

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-specification#971]
The test case https://test-suite.xproc.org/tests/nw-collection-002.html raises the error `err:XD0001` because "a sequence of documents is the context for an XPath expression on a p:variable".

As far as I understand it, this is due to https://spec.xproc.org/master/head/xproc/#xproc-xpath-context-31 specifying "If the explicit connection or the default readable port provides no or more than one document then the context item is undefined. It is a dynamic error (err:XD0001) if the XPath expression makes use of the context item, but the context item is undefined."

I wonder why the section following about "context position and context size" saying 'The context position and context size are both “1”' does not have a similar requirement to raise an error if a sequence of documents is the context and then the context item is undefined.

Or asking the other way, if the test case used `<p:variable name="a" select="position()"/>` or `<p:variable name="a" select="last()"/>`, should the variable have the value `1` or should an error be raised?

**Comment by ndw** [comment]
I think they should raise errors.

**Comment by xatapult** [comment]
Consensus
