### ISSUE TITLE
Define anonymous input ports, add p:if to the list 

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#972]
As raised my @martin-honnen on xproc-dev:

The spec needs to a) explicitly define what it means by “anonymous input port“, and it needs to b) say that p:with-input must not have a port attribute when used in p:viewport, p:for-each, p:choose, p:when, or p:if (which might just be done by saying that their input ports are anonymous and pointing to the definition). 
Thirdly unless the list was updated when fixing b), the spec needs to add p:if to the list in the bullet point “In a p:choose or p:when, it is a binding for the context item for the test expression(s).” of https://spec.xproc.org/master/head/xproc/#p.with-input

**Comment by ndw** [comment]
Yes, I think that's what "anonymous" means. And yes, I think`p:if` needs to be added.

**Comment by xatapult** [comment]
Consensus
