### ISSUE TITLE
Check 5.1.2 Input connections

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#98]
Reference to p:pipe is missing in syntax box of [5.1.2. Input connections](spec.xproc.org/master/head/xproc11/#input-connections), isn't it?

**Comment by ndw** [comment]
Yes, it looks that way.

**Comment by xml-project** [comment]
@ndw Help needed: Even though this seems easy, I failed to fix it. The syntax declaration is imported from some other file, but I could not find the right one. (Also I was afraid of causing some major trouble because there is a RNC and a RNG file. I guess they are connected in some way?)

**Comment by xml-project** [comment]
Fixed!
