### ISSUE TITLE
Allow @xml:space on <p:inline>?

### ISSUE THREAD

**Issue by xatapult** [xproc/3.0-specification#983]
Maybe too late (feature freeze) but I dearly miss the ability to specify `xml:space="preserve"` on `p:inline` to prevent pretty printing of the contents by an editor.

Any chance we might still add this or is it really too late? I think it would just be a schema update, no changes to processors required.

**Comment by xatapult** [comment]
Or add as a general attribute, just like `xml:id`?

**Comment by gimsieke** [comment]
`@xml:space`, `@xml:lang`, `@xml:base`, and `@xml:space` should be permitted on (almost?) every element IMHO.

**Comment by ndw** [comment]
Yes, absolutely.

**Comment by xml-project** [comment]
FEATURE FREEZE!

**Comment by xatapult** [comment]
Ah, clash of opinions. Let's discuss Wednesday.

**Comment by xatapult** [comment]
I'm not sure that allowing `xml:base` is *just* a schema change. That has semantics attached.

**Comment by gimsieke** [comment]
It’s already allowed where `@xml:id` is allowed.
https://github.com/xproc/3.0-grammar/blob/master/src/main/schema/core30.rnc#L177

**Comment by xml-project** [comment]
> Let's discuss Wednesday.

But it is not Wednesday, but the 8th, isn't it.

Just another delay! With this strategy I am not sure we will finish the core specs before the end of this millenium!

**Comment by xml-project** [comment]
> I'm not sure that allowing xml:base is just a schema change. 

xml:id and xml:base are allowed on any element says the [spec](https://spec.xproc.org/master/head/xproc/#common-attr).

**Comment by xml-project** [comment]
@gimsieke Sorry, overlapping answers.

**Comment by xatapult** [comment]
Sorry *next* week Wednesday, July 8th, 17:00.

**Comment by xml-project** [comment]
Proposal: Defer to XProc 3.1

**Comment by xml-project** [comment]
@gimsieke 
> It’s not a feature that creates new work items for any implementor I guess

Of course that is a big change for the implementors, because current those attribute are forbidden, therefor an error is raised.

**Comment by xml-project** [comment]
Fixed with #985 and fix in grammar repo.
