### ISSUE TITLE
Error for unexpected content-type on p:input missing

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-specification#99]
Where do we say what happens, when a document with a content-type appears on a port and that content-type is NOT expected.
An error should be raised (I guess), but I can find nothing about this and no error code for this case.

See for p:output see also #93

**Comment by xml-project** [comment]
See declaration of dynamic error [XD1003](http://spec.xproc.org/master/head/xproc11/#err.inline.D1003):
If an input port provides a set of acceptable content types, it is a dynamic error if an input document that arrives on the port has a content type that does not match any content type in that set.

This error is only mentioned in the last paragraph of [2.3 Input and Outputs](http://spec.xproc.org/master/head/xproc11/#input-output), but not in [5.1.1. Input declarations](http://spec.xproc.org/master/head/xproc11/#input-declarations).

**Proposal:**
Add the following text after the list of examples of content types in 5.1.1.:
"It is a dynamic error (err:XD1003) in an input port provides a set of acceptable content types and an input document arrives on that port with a content type that does not match any content type in that set."

Additionally we may add something like the following text, to make explain what happens, if no attribute content-types is present (e.g. in pipelines from XProc 1.0): 
"If the input port declaration has no content-types attribute, only documents with content type "application/xml" are accepted."

**Comment by Conal-Tuohy** [comment]
Why only `application/xml`? Shouldn't pipelines which don't declare a required content type accept _any_ XML media type?

**Comment by xml-project** [comment]
Yes, you are of course right. My point was to define a default value at all. Will fix it this afternoon.

**Comment by xml-project** [comment]
Change the last sentence to:
"If the input port declaration has no content-types attribute, only documents with an XML media type ("application/xml text/xml */*+xml") are accepted."

**Comment by ndw** [comment]
I think we have a section in the doc that says there are three kinds of documents: XML, text, and binary. It's probably sufficient to say "any XML document' with a link back to that common section.

**Comment by xml-project** [comment]
Fixed with pr #107.
