### ISSUE TITLE
Allow Java implementations to represent UNC paths with 4 slashes

### ISSUE THREAD

**Issue by gimsieke** [xproc/3.0-specification#998]
See [this discussion on Slack](https://xmlcom.slack.com/archives/C011NLXE4DU/p1607439842435300?thread_ts=1607410964.419800&cid=C011NLXE4DU) if you are subscribed to the xml.com slack.

On some “official” page that has been moved in the meantime (probably the one linked from [this StackOverflow answer](https://stackoverflow.com/questions/1878024/file-uris-and-slashes#answer-1878071)), Microsoft said that the leading two backslashes in UNC paths translate to nothing after the `file://` protocol part, that is, `\\host\path` becomes `file://host/path`.

While I was able to read (using Saxon) from a UNC path URI with only two slashes after `file:`, I wasn’t able to write to a similar URI (“URI has an authority component”). However, the four-slash variant `file:////host/path` works in `xsl:result-document`, as @arithmeticus pointed out on Slack. This four-slash variant also works (in Saxon) when reading a resource.

I don’t know how non-Saxon based Java tools behave. If it turns out that they all can read from and write to four-slash UNC URIs, I propose that we say in the `p:urify()` spec that XProc processors implemented in Java may (or should) represent UNC paths with four slashes instead of two after `file:`, as long as Java shows this behavior.

**Comment by ndw** [comment]
Fine by me. Dealing with filesystems and URIs on Windows is a [nightmare](https://github.com/xmlresolver/xmlresolvercs/issues/2).

**Comment by ndw** [comment]
@gimsieke , can you clarify what you'd like to change for this bug? Are you simply saying that on a Windows system, you'd like `p:urify` to preserve four slashes after `file:`? Or is there more to it?

**Comment by gimsieke** [comment]
My request referred to the 2020-08 last call draft. Item 5. of the decision step list in the [p:urify()](https://spec.xproc.org/lastcall-2020-08/head/xproc/#f.urify) section gave an instruction how to identity UNC paths. The request would then be: If a path has been identified as a UNC path, implementations are free to start the p:urified version with `file:////` instead of `file://`.

The new prose doesn’t speak of UNC paths any more. I suggest that we add something like the following paragraph to item 3. in the [URI construction](https://spec.xproc.org/master/head/xproc/#urify-uri-construction) subsection:

On Windows, if `$filepath` matches the regular expression given in item 7. of the decision list in § 8.9 and if the scheme has been determined to be `file` implicitly (that is, for UNC paths), an implementation **MAY** append another two slashes before the authority so that the resulting URI starts with "`file:////`". This is allowed in order to avoid known issues when writing to such a URI that represents a UNC path.

**Comment by gimsieke** [comment]
On 2nd thought, this 2→4-slash fixup should also be allowed for _explicit_ file URIs with an authority part.

**Comment by xatapult** [comment]
@gimsieke I was going over the issues in an attempt to fix them as requested in the XML Prague meetup, but I don't feel comfortable about fixing this one. I'm fine with text you propose in https://github.com/xproc/3.0-specification/issues/998#issuecomment-1051987861, but not sure what would be needed for your comment in https://github.com/xproc/3.0-specification/issues/998#issuecomment-1051991611.

Since you already proposed the textual changes for this it doesn't seem much work to me to finish this one...
